### ISSUE TITLE
as_quosure() does not separate expr and env from lazy object

### ISSUE THREAD

**Issue by julianstanley** [r-lib/rlang#1009]
Minimal example:
```R
my_lazy <- lazyeval::as.lazy("test")
rlang::as_quosure(my_lazy)
```

This example returns:

```R
<quosure>
expr: ^<S3: lazy>
env:  empty
```

Here's the behavior I expected:

```R
> my_lazy <- lazyeval::as.lazy("test")
> rlang::as_quosure(my_lazy$expr, my_lazy$env)
<quosure>
expr: ^test
env:  package:base
```

@cpsievert recommended I post this issue, after we were working on [issue 1783 in plotly](https://github.com/ropensci/plotly/issues/1783).

**Comment by lionel-** [comment]
You need `compat_lazy()` from https://github.com/r-lib/rlang/blob/master/R/compat-lazyeval.R.
The functions in this file are not exported so you must copy it in your package.
