### ISSUE TITLE
expected behaviour of sym / enexpr

### ISSUE THREAD

**Issue by mpatey** [r-lib/rlang#1014]
Maybe this is not how these functions are supposed to be used, but is this behaviour as expected? `sym` seems to have a side effect such that subsequent calls on the same parameter are affected.

``` r
library(rlang)

test_enexpr_sym <- function(s1) {
  list(enexpr(s1),
       sym(s1))
}

test_sym_enexpr <- function(s1) {
  list(sym(s1),
       enexpr(s1))
}

one <- "two"
test_enexpr_sym(one)
#> [[1]]
#> one
#> 
#> [[2]]
#> two
test_sym_enexpr(one)
#> [[1]]
#> two
#> 
#> [[2]]
#> [1] "two"
```

<sup>Created on 2020-06-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Yes this is expected for technical reasons. Defusing must happen first.
