### ISSUE TITLE
How to obtain the 0.4.6 version on my local PC

### ISSUE THREAD

**Issue by JulianGaviriaL** [r-lib/rlang#1017]
I apologize in advance in case this is a silly question.

I need to download the latest version  (0.4.6) of the rlang package, since further packages require it (e.g. "see" package). Unfortunately the command the following command lines still provide the version 0.4.5 :
# install.packages("remotes")
remotes::install_github("r-lib/rlang")

I am migrating from matlab to R... and it seems there is still a long way to walk through

Many thanks in advance.

**Comment by lionel-** [comment]
0.4.6 is the latest version so just use `install.packages("rlang")`.

**Comment by JulianGaviriaL** [comment]
Hi Lionel, 
Thanks for replying. Yes indeed` install.packages("rlang")` worked the third time I tried . The reason it did not work before, was because it was necessary to uninstall the older version (0.4.5) manually, as first step. Such as it was requested in the R-studio forum,
https://community.rstudio.com/t/how-to-download-the-0-4-6-version-of-rlang-package-on-my-local-pc/71671

Thanks again , and have a nice day.
