### ISSUE TITLE
cnd_muffle should always work

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#1022]
i.e. I think the terminal abort should be removed. I think muffling a condition that doesn't need to be muffled can be silent.

**Comment by lionel-** [comment]
Should it return `FALSE` in that case? Then:

```r
error = function(cnd) {
  if (!cnd_muffle(cnd)) {
    otherwise
  }
}
```

Unsure if it's better than

```r
error = function(cnd) {
  cnd_muffle(cnd))
  otherwise
}
```

The former style makes me think of `if (!setjmp(buf))` in C, which may or may not be a good thing.

**Comment by hadley** [comment]
Yeah, that seems like a good idea.
