### ISSUE TITLE
Can't install rlang 0.4.7 on windows 10 x64

### ISSUE THREAD

**Issue by Andrzej-Andrzej** [r-lib/rlang#1024]
Hi ,
I can't install rlang 0.4.7 on windows 10 x64. Version 0.4.6 is OK.
What should I do ? 
R 4.0.2, 
When I try to install it I receive an errors about "permission denied", I can't even install dev version of rlang.

**Comment by lionel-** [comment]
I don't think I can help you with permission errors. Maybe post in a help forum like Community or StackOverflow? I would try to include more information in your question.

**Comment by lionel-** [comment]
Maybe the permission error only occurs when compiling, so if you wait for the binaries to come out, it might resolve itself. You can see on https://cran.r-project.org/web/packages/rlang/index.html that Windows binaries are still not ther.

**Comment by Andrzej-Andrzej** [comment]
Yes, that problem occurs when compiling, but why rlang can't compile properly whilst other packages can ?
When rlang windows  binaries will be available on Cran ?

**Comment by lionel-** [comment]
Sorry I don't know the answer to these questions.

**Comment by lionel-** [comment]
oh hmmm, this is interesting:

> Error: Unknown lifecycle stage superseded

**Comment by lionel-** [comment]
I think it's using the old `rlang:::lifecycle()` function from your previous install to create the doc files, instead of the new version.

Can you try reinstalling with a completely fresh session? Double-check in `sessionInfo()` that rlang is not already loaded before installing.

**Comment by dnadle** [comment]
I get a 404. rlang_0.4.7.zip is not present in https://cran.rstudio.com/bin/windows/contrib/4.0/

**Comment by lionel-** [comment]
Maybe the binary didn't propagate to that mirror yet. Try https://cran.r-project.org/bin/windows/contrib/4.0/rlang_0.4.7.zip instead.

**Comment by Shicheng-Guo** [comment]
Same here, \R\R-4.0.2\library\rlang\libs\x64\rlang.dll: Permission denied

_install.packages("rlang_0.4.7.tar.gz", repos = NULL, type = "source")
* installing *source* package 'rlang' ...
** package 'rlang' successfully unpacked and MD5 sums checked
ERROR: cannot remove earlier installation, is it in use?
* removing 'C:/Users/sguo2/OneDrive - JNJ/Documents/R/R-4.0.2/library/rlang'
* restoring previous '/R/R-4.0.2/library/rlang'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying R\R-4.0.2\library\00LOCK-rlang\rlang\libs\x64\rlang.dll to R\R-4.0.2\library\rlang\libs\x64\rlang.dll: Permission denied
Warning in install.packages :
  installation of package ‘rlang_0.4.7.tar.gz’ had non-zero exit status_

**Comment by lionel-** [comment]
@Shicheng-Guo I think this is the relevant part:

> ERROR: cannot remove earlier installation, is it in use?

See https://github.com/rstats-wtf/what-they-forgot/issues/62#issuecomment-545038970
