### ISSUE TITLE
Unable to install rlang on Mac OS X

### ISSUE THREAD

**Issue by eviert** [r-lib/rlang#1026]
When attempting to install rlang on the new version of R 4.0 the following error occurs when attempting to rknit (requires installing rlang)

```
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘rlang’
Calls: :: ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

The downloaded source packages are in
	‘/private/var/folders/xv/9bd8ngq17f31t9b9b2rgsldr0000gp/T/RtmpG7tW8a/downloaded_packages’
also installing the dependency ‘rlang’

  There is a binary version available but the source version is later:
      binary source needs_compilation
rlang  0.4.6  0.4.7              TRUE
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/htmltools_0.5.0.tgz'
Content type 'application/x-gzip' length 219435 bytes (214 KB)
==================================================
downloaded 214 KB

The downloaded binary packages are in
	/var/folders/xv/9bd8ngq17f31t9b9b2rgsldr0000gp/T//RtmpG7tW8a/downloaded_packages
installing the source package ‘rlang’

trying URL 'https://cran.rstudio.com/src/contrib/rlang_0.4.7.tar.gz'
Content type 'application/x-gzip' length 847308 bytes (827 KB)
==================================================
downloaded 827 KB

* installing *source* package ‘rlang’ ...
** package ‘rlang’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘rlang’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rlang’
```

It appears this might be an issue with rlang and version 4 of R as this was working fine prior to upgrading to 4.0 from 3.6

**Comment by lionel-** [comment]
This doesn't appear to be an rlang issue?

**Comment by eviert** [comment]
to be honest, it is unclear. The issue was resolved as soon as I downgraded back to 3.6.3. The issue occurs when attempting to knit an R markdown document. R wants to upgrade all the packages including rlang. All other packages install as expected. rlang is the only one that returns the exit with unexpected zero. I thought I had captured that output.

While in 3.6.3 I am able to upgrade rlang to .0.4.7.

**Comment by lionel-** [comment]
When there are compilation issues on your machine, you can specify `type = "binary"` so it doesn't try to install from source.

**Comment by lionel-** [comment]
If you want to compile packages that don't have binaries yet, it seems you'll have to solve the `xcrun` issue.

**Comment by eviert** [comment]
I will give that a Try.

Thank you!
