### ISSUE TITLE
Should warn and friends reclass condition objects?

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#1027]
``` r
x <- rlang::catch_cnd(
  tryCatch(stop("foo"), error = function(e) rlang::warn(e))
)
class(x)
#> [1] "simpleError" "error"       "condition"
```

<sup>Created on 2020-07-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
`warn()` does not take a condition object. Maybe it should be `cnd_signal(as_warning(cnd))`?

**Comment by lionel-** [comment]
Instead of `as_warning()`, maybe it's better to wrap the condition in a new warning object with a special class that forwards `conditionMessage()` etc?

**Comment by hadley** [comment]
Yeah, I don't have any strong feelings here, but it seems like we could make this interface a little less confusing.

**Comment by lionel-** [comment]
How about:

```r
f <- function() stop("foo")
try_catch(f(), error = function(cnd) warn(parent = cnd))
```

Then our `conditionMessage()` methods would delegate to `cnd$parent` when the message is empty, i.e. this would not be displayed as a chained error but as a wrapped error where the parent takes the place of the child.

**Comment by hadley** [comment]
Looking at this again, I think maybe all that I actually want is a bit more error checking on the first argument:

``` r
rlang::warn(simpleError("Hi"))
#> Error in format_error_bullets(x[-1]): nms %in% c("i", "x", "") is not TRUE
```

<sup>Created on 2021-09-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

That would at least force you to consider what to do.

**Comment by lionel-** [comment]
oh I thought you wanted to synchronise the base class of the condition with the type of signal being emitted.
