### ISSUE TITLE
Implications of is_interactive() consulting the option "rstudio.notebook.executing"

### ISSUE THREAD

**Issue by jennybc** [r-lib/rlang#1031]
I use `rlang::is_interactive()` in gargle (and many other places). gargle may need to interact with the user, for example, initially it will ask the user for permission to create a token cache. Or, in regular usage, gargle may offer the user a menu of different emails to select from when auth-ing with a specific API.

If a user likes to work in R Notebooks or in regular Rmd's with the "Chunk output inline" behaviour, this interacts very poorly with `rlang::is_interactive()`, which reports `FALSE` for them, even though they are in an interactive session. Or, at least, the user certainly _thinks_ they are in an interactive session.

<img width="403" alt="Screen Shot 2020-07-21 at 1 30 08 PM" src="https://user-images.githubusercontent.com/599454/88104210-f702c000-cb56-11ea-8ef0-ea71324ed838.png">

Is something you've run up against / thought about before?

I am thinking I might just have to counsel people to NOT use "Chunk output inline" with gargle-using packages. Or they have to code their script as if they are in a non-interactive session.

**Comment by lionel-** [comment]
I think this is from https://github.com/r-lib/rlang/pull/705#issuecomment-449035164

Maybe we should add an `ignore_notebook = FALSE` argument?

**Comment by lionel-** [comment]
or `ignore = NULL` with possible values from `c("knitting", "notebook", "testing")`.

**Comment by hadley** [comment]
Or maybe we should just remove the notebook check altogether?

**Comment by hadley** [comment]
Yeah, I think we should remove it all together — `readLines()` doesn't work in the notebook, but `menu()` does. And menu is the primary way which we solicit interaction from the user, so I think we should be ok.

**Comment by jennybc** [comment]
I've done some historical research.

readxl copied this from `readr:::show_progress()`:

https://github.com/tidyverse/readr/blob/2b9ec3302a30a57e7ecc3b71c7f0fa6dba74c884/R/utils.R#L24

And readr added this check in response to:

https://github.com/tidyverse/readr/issues/793

I am coming to the conclusion that it may still be relevant when deciding to display progress bars. But I don't think it belongs in `rlang::is_interactive()`.
