### ISSUE TITLE
capture.output(inform()) behaves differently in interactive sessions

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/rlang#1037]
This is the same issue as https://github.com/r-lib/cli/issues/160, essentially. 

Non-interactive session:

```r
❯ R -q -e 'capture.output(rlang::inform("boo"))'
> capture.output(rlang::inform("boo"))
boo
character(0)
>
>
```

Interactive session:

```r
❯ R -q
> capture.output(rlang::inform("boo"))
[1] "boo"
```

**Comment by TylerGrantSmith** [comment]
This seems like an unavoidable consequence of how `capture.ouput` works.  In the default mode (`type = output`) it only captures messages sent to `stdout`.  Since no   The behavior of `inform` using `stderr` non-interactively is intentional based on the description:

```
#'   By default, `inform()` prints to standard output in interactive
#'   sessions and standard error otherwise. This way IDEs can treat
#'   messages distinctly from warnings and errors, and R scripts can
#'   still filter out the messages easily by redirecting `stderr`.
```

**Comment by gaborcsardi** [comment]
I think whenever there is an active sink on either stdout or stderr, it should print to stderr.

**Comment by TylerGrantSmith** [comment]
So you think instead `inform` should use 
```
    .file <- .file %||% if (is_interactive() && 
                            sink.number("output")  == 0 && 
                            sink.number("message") == 2) 
      stdout()
    else stderr()
```

**Comment by lionel-** [comment]
@TylerGrantSmith The goal of this change is to make `inform()` behave consistently interactively and non-interactively. The red output in RStudio is secondary to behaviour consistency.
