### ISSUE TITLE
dplyr error: Input must be a vector, not a `data.frame` object.

### ISSUE THREAD

**Issue by Mihiretukebede** [r-lib/rlang#1038]
![image](https://user-images.githubusercontent.com/44161975/89283784-0a7d5300-d64e-11ea-9535-100a49efc0a3.png)

**Comment by lionel-** [comment]
If you update rlang `install.packages("rlang")` you shouldn't see this "Trace data is not square" internal error anymore as it has been fixed.

I have a sent a pull request to the author of bibliometrix to fix the "must be a vector" bug.

**Comment by Mihiretukebede** [comment]
Thank you very much @lionel-. I will try that.

**Comment by lionel-** [comment]
Fixed in https://github.com/massimoaria/bibliometrix/pull/131.
