### ISSUE TITLE
Dependency on "lmerTest" package

### ISSUE THREAD

**Issue by brunolopesbr** [r-lib/rlang#1041]
I could not update rlang, an issue that can be found here:

https://community.rstudio.com/t/rstudio-freaked-out-on-me-today-cant-update-rlang-package/50349/4

After instaling the "lmerTest" package I could update rlang, as it is described on the post - it seems that "lmerTest" is a dependency, but was not installed on the system.

To reproduce it, onde should do a fresh R instalation and then install a deprecated version of rlang. Next, try to update rlang - and when it dows not work, install "lmerTest".

**Comment by lionel-** [comment]
rlang does not depend on lmerTest. What probably happened is that you restarted your R session and then it worked. See https://github.com/rstats-wtf/what-they-forgot/issues/62#issuecomment-545038970 for how to poperly update packages on Windows platforms.
