### ISSUE TITLE
vectorize as_name over quosures?

### ISSUE THREAD

**Issue by MatthieuStigler** [r-lib/rlang#1043]
It seems it is not possible to use `as_name` over  a list of quosures, only over single separate quosures? Is this intended behavior, or something that could bre made vectorized?

case use is for example capturing the names of ..., I end up using `map_chr(enquos(...), rlang::as_name)`, it would be great if one could do instead ` rlang::as_name(enquos(...))`?

Thanks!

**Comment by lionel-** [comment]
This is intended behaviour. The results of `as_name()` and `as_label()` are size stable.
