### ISSUE TITLE
exec() fails to splice length zero argument if named, otherwise not

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/rlang#1045]
With rlang 0.4.7. I am not sure but I feel `exec()` behavior here should not depend on whether the argument of length zero is named or not.

``` r
# context
c()
#> NULL

# works 
x <- c(a = 3)
sub <- unname(x[character()])
rlang::exec(c, !!!sub)
#> NULL

# fails
x <- c(a = 3)
sub <- x[character()]
rlang::exec(c, !!!sub)
#> Error in rlang::exec(c, !!!sub): attempt to set an attribute on NULL
```

<sup>Created on 2020-08-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Looks like a bug in the C function `Rf_coerceVector()` from the R API:

```r
x <- set_names(dbl())
rlang:::vec_coerce(x, "pairlist")
#> Error in rlang:::vec_coerce(x, "pairlist"):
#>   attempt to set an attribute on NULL
```

I'll work around.
