### ISSUE TITLE
Preserving single string quote in quosures

### ISSUE THREAD

**Issue by vspinu** [r-lib/rlang#1047]
Would it be possible to preserve the string quotation when quoting and substituting:

```
> quo(a > 'b')
<quosure>
expr: ^a > "b"
env:  global
```
I guess this is R parser substitution and little could be done on rlang side. I need it in the context of automatic mapping of R expressions to SQL statements, where single quote and double quote have different meaning.

**Comment by lionel-** [comment]
Unfortunately `'` and `"` are purely parser syntax. In the AST there's only `STRSXP` objects in both cases.
