### ISSUE TITLE
Tests for visibility of as_function()

### ISSUE THREAD

**Issue by wch** [r-lib/rlang#1055]
I just spent a few hours trying to figure out why my tests were passing locally but failing in CI. It turns out the dev version of `as_function()` preserves visibility, but the CRAN version does not.

This is good, but to ensure it stays good, I suggest adding tests like these:

```R
f <- as_function(quo(invisible(1)))
expect_invisible(f())

f <- as_function(quo(1))
expect_visible(f())

f <- as_function(~ invisible(1))
expect_invisible(f())

f <- as_function(~ 1)
expect_visible(f())
```

These fail on the CRAN version, but pass on the dev version.

The original problem is probably related to #961.

**Comment by lionel-** [comment]
Done, thanks!
