### ISSUE TITLE
trace_back() prints nothing in lldb debugger

### ISSUE THREAD

**Issue by kevinushey** [r-lib/rlang#1059]
To reproduce, try something like the following in an R session:

```
debugonce(data.frame)
as.data.frame(list(x = 1))
```

This will activate the R debugger and pause the REPL. Then, in a separate terminal try attaching to that R session with a debugger; e.g. on macOS:

```
sudo lldb -n R
```

Then, in that session try using `rlang` to print a stack trace:

```
expr (SEXP) R_ParseEvalString("print(rlang::trace_back())", R_GlobalEnv)
```

Unfortunately, nothing is printed. "It would be nice" if this worked, to make it easier to see what the R call stack looks like when attached to an R session.

FWIW, `sys.calls()` and `sys.frames()` also return `NULL` here, whereas `sys.status()` does give the set of calls on the stack.

**Comment by lionel-** [comment]
You might need to evaluate in the current environment.

See the difference:

```r
lobstr::cst()
#>     █
#>  1. ├─base::as.data.frame(list(x = 1))
#>  2. └─base::as.data.frame.list(list(x = 1))
#>  3.   ├─base::do.call(data.frame, c(x, alis))
#>  4.   └─(function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE, ...
#>  5.     └─lobstr::cst()

evalq(lobstr::cst(), globalenv())
#>     █
#>  1. └─lobstr::cst()
```

Unfortunately `R_GetCurrentEnv()` is currently buggy and the fix hasn't been merged yet: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17839

It's possible to evaluate `sys.frame(-1)` in the empty env to get it, though it might be a bit tricky. I have this helper in vctrs:

```c
  SEXP current_frame_body = PROTECT(r_parse_eval("as.call(list(sys.frame, -1))", R_BaseEnv));
  SEXP current_frame_fn = PROTECT(r_new_function(R_NilValue, current_frame_body, R_EmptyEnv));

  // Then this can be evaluated in the empty env
  peek_frame_call = PROTECT(Rf_lcons(current_frame_fn, R_NilValue));
```

We could export a C callable from rlang to get the current backtrace.

**Comment by kevinushey** [comment]
> We could export a C callable from rlang to get the current backtrace.

This would make me happy. :-)

**Comment by lionel-** [comment]
Here you go:

```c
(lldb) expr R_GetCCallable("rlang", "rlang_print_backtrace")(true)
#>     █
#>  1. └─global::f()
#>  2.   ├─base::tryCatch(g())
#>  3.   │ └─base:::tryCatchList(expr, classes, parentenv, handlers)
#>  4.   └─global::g()
#>  5.     ├─base::evalq(h())
#>  6.     │ └─base::evalq(h())
#>  7.     └─global::h()
#> (void *) $0 = 0x000000010054e3f0

(lldb) expr R_GetCCallable("rlang", "rlang_print_backtrace")(false)
#>  1. global::f()
#>  4. global::g()
#>  7. global::h()
#> (void *) $1 = 0x000000010054e3f0
```

**Comment by kevinushey** [comment]
Thank you!
