### ISSUE TITLE
Re-licensing rlang

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#1063]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/r-lib/rlang/graphs/contributors). @akbertram, @AliciaSchep, @brodieG, @egnha, @jonocarroll, @jrnold, @kalibera, @karldw, @mikmart, @rcannood, @richierocks, @salim-b, @smingerson, @TylerGrantSmith, @yutannihilation, would you permit us to re-license rlang with the MIT license? If so, please comment "I agree" below.
​
* [x] [@akbertram](https://github.com/r-lib/rlang/commits?author=akbertram)  
* [x] [@AliciaSchep](https://github.com/r-lib/rlang/commits?author=AliciaSchep)  
* [x] [@brodieG](https://github.com/r-lib/rlang/commits?author=brodieG)  
* [x] [@egnha](https://github.com/r-lib/rlang/commits?author=egnha)  
* [x] [@jonocarroll](https://github.com/r-lib/rlang/commits?author=jonocarroll)  
* [x] [@jrnold](https://github.com/r-lib/rlang/commits?author=jrnold)  
* [x] [@kalibera](https://github.com/r-lib/rlang/commits?author=kalibera)  
* [x] [@karldw](https://github.com/r-lib/rlang/commits?author=karldw)  
* [x] [@mikmart](https://github.com/r-lib/rlang/commits?author=mikmart)  
* [x] [@rcannood](https://github.com/r-lib/rlang/commits?author=rcannood)  
* [ ] [@richierocks](https://github.com/r-lib/rlang/commits?author=richierocks)  
* [x] [@salim-b](https://github.com/r-lib/rlang/commits?author=salim-b)  
* [x] [@smingerson](https://github.com/r-lib/rlang/commits?author=smingerson)  
* [x] [@TylerGrantSmith](https://github.com/r-lib/rlang/commits?author=TylerGrantSmith)  
* [x] [@yutannihilation](https://github.com/r-lib/rlang/commits?author=yutannihilation)

**Comment by salim-b** [comment]
I agree

**Comment by rcannood** [comment]
I agree below.

**Comment by brodieG** [comment]
My contributions had to be [reverted](https://github.com/r-lib/rlang/pull/951) due to conflicts with dbplyr, so you do not need my acquiescence for relicensing.

Should you resurrect the contributions I grant you the right to re-license them MIT although wish you were keeping it GPL (for those wondering why see the discussion [under ggplot2](https://github.com/tidyverse/ggplot2/issues/4236)).

**Comment by kalibera** [comment]
I am ok with that as my contributions to rlang are minor.

**Comment by karldw** [comment]
I agree.

And @brodieG, thanks for linking to the background.

**Comment by AliciaSchep** [comment]
I agree

**Comment by smingerson** [comment]
I agree

**Comment by TylerGrantSmith** [comment]
I agree

**Comment by jonocarroll** [comment]
I agree

**Comment by egnha** [comment]
I agree

**Comment by yutannihilation** [comment]
I agree.

**Comment by akbertram** [comment]
I agree.

**Comment by jrnold** [comment]
I agree

**Comment by mikmart** [comment]
I agree

**Comment by hadley** [comment]
We have made a good-faith attempt to get consent from all contributor to the package under the previous license. This has included reviewing contributions to the package for non-trivial changes, seeking agreement to re-license with GitHub issues, sending a reminding after two weeks, and reaching out by e-mail (where possible).

Unfortunately, we have not received a response from @richierocks . We have carefully reviewed their contributions. Given that the contributions are relatively small, and no one has objected to re-licensing across all tidyverse and r-lib repos, we are going to move ahead with the re-licensing. Of course, if we later discover that contributors are not happy with the re-licensing, we'll re-implement their changes.

**Comment by richierocks** [comment]
Apologies; I missed this. I agree.
