### ISSUE TITLE
Check packages installed

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#1075]
Takes character vector of functions, and if any not installed and interact, offers to install for you (using install.packages, or pak if its installed). e.g.

```R
#> check_installed("foo", "for reason")
foo is needed for reason.
1. Install with install.packages()
2. Install with pak
3. Stop so you can install yourself
```

I think @jimhester has some existing code for this (sans pak support).

rlang isn't the perfect place for this, but it's something we need for many packages, so we have a standard user facing dialog when suggested packages aren't installed. Currently we have a lot of variations of this in `utils.R`.

**Comment by jimhester** [comment]
The code I have used for this is at https://github.com/r-lib/cpp11/blob/597b6fb2593b34cae090cd3a5f6c5850e9c4f0ec/R/utils.R#L23-L45

**Comment by lionel-** [comment]
Thanks @jimhester that was helpful!
