### ISSUE TITLE
eval_tidy() assigns into shadow environment

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#1077]
This seems by design and inevitable (or not). I wonder if we should document this behavior more prominently?

``` r
library(rlang)

x <- 1

quo <- quo(x <- 3)
eval_tidy(quo)

x
#> [1] 1

eval_bare(quo_get_expr(quo), quo_get_env(quo))

x
#> [1] 3
```

<sup>Created on 2020-12-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Maybe it should be documented that `eval_tidy()` and quosures should generally be avoided unless you're working with a data mask. When there is no data mask, you can generally use promises to mesh environments, unless you need repeated evaluations as in Shiny.

**Comment by krlmlr** [comment]
Thanks for looking into it!
