### ISSUE TITLE
Add support for sentinel values

### ISSUE THREAD

**Issue by schloerke** [r-lib/rlang#1079]
`ggplot2` has built in sentinel value support using the `waiver()` function: https://github.com/tidyverse/ggplot2/blob/9741da5050f81b7b5c012c56d02f45fc93d68f89/R/utilities.r#L177-L188

```r
#' A waiver object.
#'
#' A waiver is a "flag" object, similar to `NULL`, that indicates the
#' calling function should just use the default value.  It is used in certain
#' functions to distinguish between displaying nothing (`NULL`) and
#' displaying a default value calculated elsewhere (`waiver()`)
#'
#' @export
#' @keywords internal
waiver <- function() structure(list(), class = "waiver")

is.waive <- function(x) inherits(x, "waiver")
```

I've run into a situation a few times where I can **not** use `NULL` as a placeholder value for an argument as `NULL` could be supplied by a user and should be used. 
Using `missing(arg)` does not allow for other functions to build on top of my function as the arguments might be directly supplied, which makes `missing()` not very useful.

`ggplot2` resolved this situation by supplying a `waiver()` function which allows for users to supply `NULL` values and can be distinguished from default behavior.

------------------------

I think it would be great if there was a "sentinel" value that can be validated it is a sentinel value.

I am opening this issue for discussion and would be happy to make a PR. Thank you!

**Comment by lionel-** [comment]
One way is to use `is_missing(arg)` instead of `missing()`. Then users can also supply `missing_arg()` (or equivalently `quote(expr = )`).

You can alias `missing_arg()` to some more descriptive name. This is what the `lifecycle::deprecated()` sentinel does.

**Comment by schloerke** [comment]
🤦‍♂ so many functions.

`missing_arg()` Covers my use case!

Thank you. Closing

**Comment by schloerke** [comment]
Implemented: https://github.com/rstudio/shiny/pull/3174/commits/d24406e4eeb60b81ee0160315fa0f172c7a09f5b
🎊🎊
