### ISSUE TITLE
rlang still calls deprecated as_character internally (eg. in as_utf8_character)

### ISSUE THREAD

**Issue by aryoda** [r-lib/rlang#1082]
**Observation:**

`rlang` has deprecated the function `as_character`

https://github.com/r-lib/rlang/blob/51f5cbde84797eeb6064a13d72eef1d7ed752502/R/lifecycle-retired.R#L322

but does still call it internally eg. in a frequently called function like `as_utf8_character`

https://github.com/r-lib/rlang/blob/e7500d4c5ca38c07607855a726961d8cf635bb9c/R/utils-encoding.R#L41

**Impact:**

If I call an `rlang` function it throws a warning for another internally called `rlang` function
even though the client never calls the deprecated function directly:

```
library(rlang)
options(lifecycle_disable_warnings = FALSE, lifecycle_verbose_soft_deprecation = TRUE)
rlang::as_utf8_character("abc")
```

shows

```
[1] "abc"
Warning message:
`as_character()` is deprecated as of rlang 0.4.0
Please use `vctrs::vec_cast()` instead.
This warning is displayed once per session. 
```

**Expected behaviour:**

Do not throw deprecation warnings when `rlang` package functions call other deprecated `rlang` functions.

Mainly: Replace all internal `as_character` calls with `vctrs::vec_cast` calls (as proposed by the deprecation message).

**Comment by lionel-** [comment]
Just a heads up that the UTF-8 tools in rlang are likely about to be deprecated for the 1.0 version.

**Comment by lionel-** [comment]
Thanks for the report!
