### ISSUE TITLE
"missing" doc topic (ironically?) missing from docs

### ISSUE THREAD

**Issue by mmuurr** [r-lib/rlang#1083]
The doc topic "missing", created in [`vec-na.R`](https://github.com/r-lib/rlang/blob/master/R/vec-na.R) is absent in [`_pkgdown.yml`](https://github.com/r-lib/rlang/blob/master/_pkgdown.yml), and this does appear on the `rlang.r-lib.org` site. Purposeful? (If so, I appreciate the irony.)

Guessing the best place for this (if not purposeful) is in the "Create vectors" section?

**Comment by lionel-** [comment]
These aliases have been purposely removed from the documentation index (they are marked with `@keyword internal`) because) because their fate is a bit uncertain.
