### ISSUE TITLE
interaction with withr::defer()

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/rlang#1085]
This gives a segfault: 

```r
library(rlang)

f3 <- function() {
  withr::defer(2)
  dots <- quos(integer(1))
  quo <- quo(c(!!!dots))
}

f3()
```

originally from https://github.com/tidyverse/dplyr/issues/5667

**Comment by lionel-** [comment]
Not sure what was going on but this seems to be fixed in the dev version. I added a unit test.
