### ISSUE TITLE
Don't interpret `{{ } { }}` as curly curly

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#1087]
This will help with:

```r
expect_snapshot({
  {
    "foo"
    foo()
  }

  {
    "bar"
    bar()
  }
})

**Comment by assignUser** [comment]
First of all, thank you for this amazing package @lionel- ! I post in this closed issue as this is the issue causing the error as far as I can see. I would be happy to open another issue though.

I ran into this issue within nested functions, outside functions and even only `inner` works fine.
I tried this with both the current cran version and dev version of rlang.

```
library(rlang)
seed <- 42

setup <- expr({
    library(rlang)
    set.seed(!!seed)
})

# no probelm
expr({
    !!setup
    runif(10)
})

# in nested functions though:
outer <- function(a) {
    a <- rlang::enexpr(a)
    some_condition <- TRUE

    if(some_condition){
      eval(a)
    }
}

inner <- function(b){
    b <- rlang::enexpr(b)
    eval(b)
}

outer(inner(b = {
    !!setup
    runif(10)
}))
```
