### ISSUE TITLE
should 'rlang_fake_data_pronoun' report a numeric length?

### ISSUE THREAD

**Issue by kevinushey** [r-lib/rlang#1108]
Originally from here:

https://github.com/rstudio/rstudio/issues/8711

RStudio's autocompletion system got into a spot where `length(object)` reported `NULL`, as the data `<pronoun>` object was then being used for completions. Could we instead just return `0` here?

https://github.com/r-lib/rlang/blob/8ceabce82913060b5ca04427538cbbd1b3a7234b/R/eval-tidy.R#L172-L173

**Comment by lionel-** [comment]
oh yeah, that makes sense. I guess a vector class must always have consistent behaviour even when it's not meant to be used.
