### ISSUE TITLE
object 'testthat_print' not found

### ISSUE THREAD

**Issue by r2evans** [r-lib/rlang#1112]
```lang-r
devtools::document(...) # some local package
# Error in get(genname, envir = envir) : object 'testthat_print' not found
```

There is no code change required for this issue, just awareness of the source of the problem and its fix. Whether you blog it or tweet it or just keep this issue open and pinned for a while is up to you.

## The Fix

Update `testthat` to 3.0.0 or newer.

If you haven't upgraded to `rlang-0.4.10` yet, when you do, make sure you include `"Suggests"` in the `dependencies=` argument, as in

```lang-r
install.packages("rlang", dependencies = c("Depends", "Imports", "LinkingTo", "Suggests"))
```

(That includes 14 packages, it's possible one or more will be new to you.)

## Background

Stemming from https://github.com/r-lib/devtools/issues/2309, the issue arises because `rlang` can be updated while ignoring some of its dependencies.

Specifically, `testthat::testthat_print` was added (https://github.com/r-lib/testthat/commit/07b19c87e2a3465ceb155570bd86ae68c75a2350) before testthat3 was released. `rlang` started using it around the same time (https://github.com/r-lib/rlang/commit/bfb1d4130a811a99ca190cc88077eab08ea2a5d8), before it released rlang-0.4.10. So far, so good.

Unfortunately, `testthat` is in rlang's `Suggests:`, and the default for `install.packages` is `dependencies=NA` which only considers `c("Depends", "Imports", "LinkingTo")`.

**Comment by lionel-** [comment]
Thanks for the heads up. I should probably have conditioned the registration on the testthat version.

**Comment by daattali** [comment]
Thanks for catching this @r2evans ! I've also noticed all the "Error in get(genname, envir = envir) : object 'testthat_print' not found" messages lately and had no idea where they're coming from, finally decided to google it and found your info :)

**Comment by dapritchard** [comment]
It can probably be inferred from @r2evans fantastic synopsis (thank you!), but for those who are in a situation where it is inconvenient or difficult to upgrade testthat, rlang 0.4.9 does not have this issue when used with previous versions of testthat.

**Comment by chasemc** [comment]
Confirming that `install.packages("rlang", dependencies = c("Depends", "Imports", "LinkingTo", "Suggests"))` fixed it for me

**Comment by lionel-** [comment]
Thanks for documenting the issue and the solution @r2evans! Judging from the emojis this is a commonly googled annoyance.

Conditioning the registration on the testthat version is tricky because loading rlang should not load testthat. Maybe we should just ignore the registration request in `s3_register()` when the generic doesn't exist.

**Comment by tttongwang** [comment]
Same issue! I just reinstalled the "testthat" pkg again and then the problem has gone. 

remove.packages("testthat)
install.packages("testthat")
