### ISSUE TITLE
`is_bare_formula()` example docs are confusing

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/rlang#1115]
In `?is_bare_formula` we have the following example. Note that the docs imply that the first call to `is_bare_formula(f)` should be returning `TRUE`?

This may be a bug in `is_bare_formula()`? 🤷‍♂️ 

```r
library(rlang)

# the below rlang docs are incorrect. the first call to `is_bare_formula()`
# returns `FALSE`?

# Note that unevaluated formulas are treated as bare formulas even
# though they don't inherit from "formula":
f <- quote(~foo)
is_bare_formula(f)
#> [1] FALSE

# However you can specify `scoped` if you need the predicate to
# return FALSE for these unevaluated formulas:
is_bare_formula(f, scoped = TRUE)
#> [1] FALSE
is_bare_formula(eval(f), scoped = TRUE)
#> [1] TRUE
```

**Comment by lionel-** [comment]
The return value is correct. The remark about the class is confusing though. Does it mean that an unclassed `~` call with an environment will return `TRUE`? Even if that's the case that does not seem very useful.

**Comment by lionel-** [comment]
Probably not worth changing this, but nowadays I would just consider that unevaluated tilde calls are never formulae.

**Comment by lionel-** [comment]
You were right Davis, there is a bug in `is_bare_formula()`. I will fix the bug and change the default of `scoped` to `TRUE` to reflect the historical behaviour.
