### ISSUE TITLE
quos_auto_name() generates duplicate names for inlined vectors

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#1116]
``` r
rlang::quos_auto_name(list(1:3, 2:4, 3:5))
#> $`<int>`
#> [1] 1 2 3
#> 
#> $`<int>`
#> [1] 2 3 4
#> 
#> $`<int>`
#> [1] 3 4 5
```

<sup>Created on 2021-02-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

I wonder if it would be better to use the `...1`, `...2`, etc convention since that actually generates syntactically valid names that are consistent with our other naming principles. Maybe it would need to take `names_prefix` as an argument in order to control in cases where you wanted to match base R behaviour or otherwise override?

See discussion at https://github.com/tidyverse/tidyr/issues/1092.

**Comment by DavisVaughan** [comment]
Duplicate names are also possible from truncation to `...`, i.e. https://github.com/tidyverse/tidyr/issues/1116

```r
library(rlang)

quos_auto_name(quos(
  dplyr::tibble(
    fruit = c("Apple", "Banana"),
    fruit_id = c("a", "b")
  ),
  dplyr::tibble(
    status_id = c("c", "d"),
    status = c("cut_neatly", "devoured"),
  )
))
#> <list_of<quosure>>
#> 
#> $`dplyr::tibble(...)`
#> <quosure>
#> expr: ^dplyr::tibble(fruit = c("Apple", "Banana"), fruit_id = c("a", "b"))
#> env:  global
#> 
#> $`dplyr::tibble(...)`
#> <quosure>
#> expr: ^dplyr::tibble(status_id = c("c", "d"), status = c("cut_neatly",
#>           "devoured"), )
#> env:  global
```

**Comment by lionel-** [comment]
Good point @DavisVaughan, that's a pretty common case. I guess `c("foo(...)...1", "foo(...)...2")` is a bit confusing. Not sure how we can do better besides breaking the convention and using a simple number suffix?

**Comment by lionel-** [comment]
cc @jennybc

**Comment by jennybc** [comment]
>  I guess `c("foo(...)...1", "foo(...)...2")` is a bit confusing

I don't have a good grasp of how often this comes up and how often a human is required to actually use these names. But my guess is not often? Is there much foreseeable harm by using the existing approach and just letting them be ugly?

**Comment by lionel-** [comment]
I would say it's uncommon but not extremely rare. It's true that when this happens the resulting names are not useful anyway, so making them more ugly is one more incentive to supply names for these inputs.

**Comment by jennybc** [comment]
This is an explicit design goal of our name uniquification strategy 😂

> 3.5.4 Ugly, with a purpose
>
> You might say that names like `x...5` are ugly and you would be right. We’re calling this a feature, not a bug! Names that have been automatically unique-ified by the tidyverse should catch the eye and give the user strong encouragement to take charge of the situation.

https://design.tidyverse.org/names-attribute.html#unique-names
