### ISSUE TITLE
[Feature request] Checking character vectors agains a set of valid values 

### ISSUE THREAD

**Issue by tzakharko** [r-lib/rlang#1119]
Something we use quite often is validating a character vector agains a table of valid values, i.e.:

```
is_character(x) && all(x %in% values)
```

 I think this could be a useful addition to `rlang`'s family of fast `is_*` predicates, either as an additional argument to `is_character*()` family or maybe as an entirely new `is_factorish()` function. 

If the authors of `rlang` are interested in this functionality, I can provide an initial C implementation.

**Comment by lionel-** [comment]
I think it's not so clear what's happening from:

```r
is_character(x, values = vals)
```

compared to the explicit operations:

```r
is_character(x) && all(x %in% vals)
is_character(x) && setequal(x, vals)
```
