### ISSUE TITLE
%|% is too strict about type for a length 1 input

### ISSUE THREAD

**Issue by jennybc** [r-lib/rlang#1122]
I just tried to use `%|%` for a scalar and got an error because the incoming `NA` is logical (as most are) and the scalar replacement value is character. It feels like our general policy is not to take the logical-ness of `NA` too literally in these situations.

It feels like this should work without me specifically ensuring `NA_character_`, which is often out of one's control.

``` r
library(rlang)

possibly_missing_scalar <- NA

possibly_missing_scalar %|% "fallback"
#> Error: Replacement values must have type logical, not type character

possibly_missing_scalar <- NA_character_

possibly_missing_scalar %|% "fallback"
#> [1] "fallback"
```

<sup>Created on 2021-02-25 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9002)</sup>

**Comment by lionel-** [comment]
rlang is not equiped to deal with this, which is why `%|%` will be removed from the package. This should be either a vctrs or a funs function.
