### ISSUE TITLE
`enquo()` does not play well with magrittr pipe

### ISSUE THREAD

**Issue by astamm** [r-lib/rlang#1128]
The following function takes the unquoted name of a package and returns the package name as a string:
```
get_pkg_name_v1 <- function(pkg) {
  pkg <- rlang::enquo(pkg)
  rlang::quo_name(pkg)
}
get_pkg_name_v1(rlang)
# [1] "rlang"
```
and this works smoothly.

However if I try rewriting the same function using **magrittr**'s pipe operator, things go sideways:
```
get_pkg_name_v2 <- function(pkg) {
  pkg %>% 
    rlang::enquo() %>% 
    rlang::quo_name()
}
get_pkg_name_v2(rlang)
# [1] "pkg"
```

It seems that it is `enquo()` that does not play well with the pipe because the following version works well:
```
get_pkg_name_v3 <- function(pkg) {
  pkg <- rlang::enquo(pkg)
  pkg %>% 
    rlang::quo_name()
}
get_pkg_name_v3(rlang)
# [1] "rlang"
```

**Comment by lionel-** [comment]
There should be no expectation that it works that way.

However this will work with the base pipe `|>` because it rewrites the expression before it is ever evaluated. magrittr has a different evaluation model because it has placeholders.

By the way `quo_name()` is superseded by `as_name()` and `as_label()`.

**Comment by astamm** [comment]
Thanks for getting back at me so quickly on this. I thought that the pipe was passing the result obtain from previous pipe calls in the left-hand side of the current pipe as the first argument of the function in the right hand side of the pipe. Following this logic, that would make the second version of the function that I proposed correct. So I understand that the pipe is working differently from what I thought. However, it could be good that this behavior be documented somewhere. But then again it might already be the case and I am just not aware of it. Anyway, thank you for your comment and thank you for pointing out the deprecation of some functions.
