### ISSUE TITLE
Explicit call to rang::.data in mutate fails

### ISSUE THREAD

**Issue by tjebo** [r-lib/rlang#1133]
I am likely doing sth terribly wrong, but I am very confused by the following: 

``` r
library(tidyverse)
df <- data.frame(x = letters[1:6], y = tail(letters, 6))
foo_implicit <- function(df){
dplyr::mutate(df, pv = paste(.data$x, .data$y))
}

foo_explicit <- function(df){
dplyr::mutate(df, pv = paste(rlang::.data$x, rlang::.data$y))
}

foo_implicit(df)
#>   x y  pv
#> 1 a u a u
#> 2 b v b v
#> 3 c w c w
#> 4 d x d x
#> 5 e y e y
#> 6 f z f z
foo_explicit(df)
#> Error: Problem with `mutate()` input `pv`.
#> x Input `pv` can't be recycled to size 6.
#> ℹ Input `pv` is `paste(rlang::.data$x, rlang::.data$y)`.
#> ℹ Input `pv` must be size 6 or 1, not 0.
```

<sup>Created on 2021-03-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by lionel-** [comment]
The `.data` binding is a fake empty object which exists for convenience (to be imported in a package, to provide a help page `?.data`, ...). `.data` should be used without any qualifier, just like you refer to columns without any qualifiers.

**Comment by lionel-** [comment]
I think `rlang::.data$foo` should give a clear error message instead of returning `NULL`. Thanks for the heads up.

**Comment by tjebo** [comment]
Thanks, this is very useful. Makes total sense
