### ISSUE TITLE
`hash_file()`

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#1134]

**Comment by lionel-** [comment]
Feel free to take this one if you'd like to @DavisVaughan :)

**Comment by DavisVaughan** [comment]
Potentially look at how openssl hashes connections in batches, to avoid pulling the entire file into memory (also works with urls) https://github.com/jeroen/openssl/blob/94f67ebd4e1036e6f20f887523f35d1cbd121c86/R/hash.R#L167-L188

**Comment by hadley** [comment]
Would be good to pair with `hash_character()` so that `hash_file(path) == hash_character(readLines(path))` (module the trailing newline problem).

**Comment by DavisVaughan** [comment]
Also worth considering if `hash_file()` is just a convenience layer over the more general set of:

```
hash_initialize()
hash_feed()
hash_finalize()
```

`hash_initialize()` could return an external pointer with a C finalizer attached that destroys it (this is what openssl does)
https://github.com/jeroen/openssl/blob/8f54c6b9667c5eddd52b6cb6140055f57e0f2ffc/src/stream.c#L22-L23

**Comment by hadley** [comment]
That's starting to feel a bit too general for what we want here, which is just a fast cache for common operations (file and object)

**Comment by hadley** [comment]
I changed my mind; I now think exposing combining hashes is worthwhile because I needed it in two different places 😄

**Comment by lionel-** [comment]
What would be the advantage of `hash_combine(hash(foo), hash(bar))` over `hash(list(hash(foo), hash(bar))`?
