### ISSUE TITLE
Why is `env_unlock()` dangerous?

### ISSUE THREAD

**Issue by jchrom** [r-lib/rlang#1139]
Motivation: In some languages, objects can be extended by way of adding methods. In R6, you can do this with unlocked objects. But, there is no way to restrict this: Once you have an unlocked object, you can just keep adding.

My idea is to use locked objects, extensible only by a limited set of decorators. These would have the ability to unlock the objects temporarily, add methods, re-assign their environments to make self/private work, lock the new bindings, and finally lock the environment. Using `rlang::env_unlock()` seems like a perfect solution here, given there is no base counterpart to `lockEnvironment()`.

But I see the docs are warning against this function ("should only be used in development tools or interactively") and [Lionel commented](https://github.com/r-lib/rlang/issues/423#issuecomment-369006924) the function might get removed from rlang altogether. I can implement it without rlang, but I am interested to hear your opinion on the approach I described above. Do you think unlocking object environments could be dangerous? And do you see this function ever being promoted to stable?

Any comments much appreciated, and many thanks for your continued work for the R community!

**Comment by lionel-** [comment]
I don't think we're going to make a danger package in the end so feel free to use it at your own risk. Its usage is unsafe because it's circumventing the public R API and might break at any time. We only use it for development tools.

**Comment by jchrom** [comment]
Ok, so the usage as such is not dangerous but the fact it is not public API means it could change without warning, which is dangerous in itself. Thanks!

**Comment by lionel-** [comment]
As long as you unlock environments that you have yourself locked, I think the usage is hygienic and makes sense.

**Comment by lionel-** [comment]
Note that you can achieve most of the locking via S3 methods e.g. for `$<-`. I'd probably go that route instead of using an internal R API.

**Comment by jchrom** [comment]
Ok, interesting. Am I on the right track here?

```
e = new.env()
e$x = 0

# Lock the env:
class(e) = "locked"

`$<-.locked` = function(...) {
  stop("the env is locked!", call. = FALSE)
}

`$.locked` = function(env, name) {
  .subset2(env, name)
}

e$y = 1 #Error
e$x     #Returns 0

# Unlock env:
class(e) = NULL

e$y = 1 #Works
e$y     #Returns 0
```

**Comment by lionel-** [comment]
You could also encode the information in an attribute rather than in the class.

> This would not work with R6 though because it calls lockEnvironment(public_bind_env) to lock self.

Right but unlocking the environments locked by R6 would not be hygienic because you aren't the one that locked it.

**Comment by jchrom** [comment]
My example was a bit lazy, an attribute check would have been much better. As for the actual env unlocking, I guess it will be safer to abandon that idea. Thanks for the pointers!
