### ISSUE TITLE
Attributes persist across calls to `rlang::quos`

### ISSUE THREAD

**Issue by dgkf** [r-lib/rlang#1142]
I'm developing a package that uses `rlang::quos` to provide some core functionality. 

When testing that package on R devel, I found that `rlang::quos` will create `<list_of<quosure>>` with attributes from the last `<list_of<quosure>>` object that was modified. 

### R (devel; using `rocker/tidyverse:devel`)

```r
> R.version.string
[1] "R Under development (unstable) (2021-02-19 r80028)"
> packageVersion("rlang")
[1] ‘0.4.10’
> x <- rlang::quos(a)
> attr(x, "test") <- "test attribute for object 'x'"
> y <- rlang::quos(b)
> y
<list_of<quosure>>

[[1]]
<quosure>
expr: ^b
env:  global

attr(,"test")
[1] "test attribute for object 'x'"
```

### R (4.0.3; using `rocker/tidyverse:latest`)

```r
> R.version.string
[1] "R version 4.0.3 (2020-10-10)"
> packageVersion("rlang")
[1] ‘0.4.10’
> x <- rlang::quos(a)
> attr(x, "test") <- "test attribute for object 'x'"
> y <- rlang::quos(b)
> y
<list_of<quosure>>

[[1]]
<quosure>
expr: ^b
env:  global
```

I don't expect experimental and developing packages to have completely stable APIs, but I felt like this might be of interest while working toward the next R release. It would help, though, to know whether this is functionality that `rlang` aims to provide or whether I should find another way of capturing this data that doesn't rely on attributes.

**Comment by lionel-** [comment]
> It would help, though, to know whether this is functionality that rlang aims to provide or whether I should find another way of capturing this data that doesn't rely on attributes.

In general it's best not to modify attributes of classes that are not explicitly subclassable via an exported constructor. In this case it looks like `new_quosures()` doesn't support subclassing.
