### ISSUE TITLE
Integrate `beepr::beep` into `rlang::entrace`?

### ISSUE THREAD

**Issue by jooyoungseo** [r-lib/rlang#1149]
I have used [`beepr::beep()`](https://statisticsglobe.com/play-sound-at-end-of-script-in-r) as an auditory error signal for myself like below:

``` r
options(error = beepr::beep)

stop("foo")
```

However, I would love to integrate `rlang::entrace` into this beeping sound. What would be the best workaround? I thought the following would work, but this did not work as I expected.

``` r
options(rlang_backtrace_on_error = "branch", error = function() {rlang::entrace(); beepr::beep()})
```

Any advice would be greatly appreciated.

**Comment by lionel-** [comment]
Maybe look into `globalCallingHandlers()`. It will add noise to the backtrace though but I plan to (try to) fix that in the short term. Sorry I don't have any great solution for this :(

**Comment by lionel-** [comment]
oh actually there is an easy way, you can instrument `entrace()` with `base::trace()`:

```r
trace(rlang::entrace, beepr::beep, print = FALSE)
```

**Comment by jooyoungseo** [comment]
Thanks! But, I don't hear any beep sound:

``` r
options(error = trace(rlang::entrace, beepr::beep, print = FALSE))
stop("foo")
```

**Comment by lionel-** [comment]
The `trace()` call must be outside the `options()`call. It works by side effect.

```r
options(error = rlang::entrace)
trace(rlang::entrace, beepr::beep, print = FALSE)
```

**Comment by jooyoungseo** [comment]
Sorry for pinging you again, @lionel-

``` r
options(error = rlang::entrace)
trace(rlang::entrace, beepr::beep, print = FALSE)

# The following does not beep.
stop("foo")
```

Do you have any ideas?

**Comment by lionel-** [comment]
Sorry I don't know.
