### ISSUE TITLE
Better support for `pak::handle_package_not_found()` in `check_installed()`

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/rlang#1150]
To support `pak::handle_package_not_found()` better, would it make sense to signal a packageNotFoundError` condition from `rlang::check_installed()`? And also define a 
 `retry_loadNamespace` or other restart that pak can invoke after the installation?

Then people using the pak global handler would get that UI and a restart, and for people not using the global handler nothing changes, they'll get the menu from rlang?

Ideally there would be one condition for all missing packages, so maybe we should define a different error, because `packageNotFoundError` always has a single package.

**Comment by lionel-** [comment]
If multiple packages are needed then I agree it would be better to create a more flexible error condition `"rlib_error_package_not_found"`.

Using the `retry_loadNamespace` restart seems a bit strange. Maybe we should use a more general name, like `"rlib_restart_package_not_found"`?
