### ISSUE TITLE
Feature request: enhance typo detection in `arg_match()`

### ISSUE THREAD

**Issue by echasnovski** [r-lib/rlang#1152]
Couple of suggestions how `arg_match()` and `arg_match0()` can be even more useful when detecting typos:

- Offer an appropriate suggestion when typo is base on characters with different cases:

``` r
# This should suggest "ABC"
rlang::arg_match0("abc", "ABC")
#> Error: `"abc"` must be one of "ABC".

# This should suggest "A"
rlang::arg_match0("a", c("A", "B"))
#> Error: `"a"` must be one of "A" or "B".
```

- Always offer suggestion. For example, remove `if` clause [here](https://github.com/r-lib/rlang/blob/160d371e0c6b59c0685d928f82caba84628701e5/R/arg.R#L88-L90) or add `else` which suggested first element in `set`. I understand this might be questionable, but I can see people prefer this.

- If execution speed is a concern here, maybe add argument `suggest = TRUE` to `arg_match()` and `arg_match0()`?

**Comment by hadley** [comment]
We should definitely do case-insensitive matching, but I think it's a bad idea to always make a suggestion because you might suggest something completely different to what the user type, and that would be confusing.

**Comment by echasnovski** [comment]
Maybe I actually meant something a little bit different. I find it very useful to have some sort of helpful pointer in case of en error. Having "Did you mean ...?" in case of a small typo is great, but having nothing in case of a big typo is not so great.

Maybe it is better to have some default value suggestion (via first argument of `set` or some extra argument `default_suggestion`) or some sort of other suggestion ("Supply one of them." after listing possible values).

**Comment by hadley** [comment]
@echasnovski that's fine, but I think it's out of scope for rlang.
