### ISSUE TITLE
feature request: signalers' message argument to auto-extract conditionMessage

### ISSUE THREAD

**Issue by mmuurr** [r-lib/rlang#1158]
I find every now and then I use this 're-throw' condition pattern, typically from inside some specialized handler or class:
```r
tryCatch({
  some_code_here()
}, error = function(e) {
  # perhaps log an error here, e.g. to stderr
  rlang::abort(conditionMessage(e), class = "special_error_subclass") ## or warn, inform, signal, etc.
})
```
... where the external caller then is equipped to handle different unique error subclasses, and each time for the condition message I have to `conditionMessage(original_condition_obj)`.

I'm curious to hear your thoughts on this feature request: let rlang's condition signalers' `message` argument auto-extract `conditionMessage(message)` if `message` is already a condition object?
So, in the above code, the re-throw line would look like `rlang::abort(e, class = "special_error_subclass")`.

Current behavior errs:
```r
rlang::abort(errorCondition("my msg"))
# Error in format_error_bullets(x[-1]) :
#   nms %in% c("i", "x", "") is not TRUE
```

**Comment by lionel-** [comment]
There is no plan to support conditions in the message argument.

By the way it is recommended to rethrow from a calling handler (rather than exiting), perhaps using `parent = `. This way you keep the full backtrace.
