### ISSUE TITLE
`as_function()` should take `global_env()` default for `env`

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#1170]
Looking up function names supplied as string requires starting from an environment, which currently defaults to the caller of `as_function()`. This is rarely the correct env to look in. Yet it's hard to remember to pass the user env and it's sometimes tricky to keep track of that env.

I think we should decide that passing a function name as string is strictly for user convenience, not for package authors. Then it makes sense to start the lookup from the global env by default. What do you think @hadley?

**Comment by hadley** [comment]
Yeah, I think that makes sense. A package author will quickly discover the issue if they use a string and the env isn't correct.
