### ISSUE TITLE
rlang fails tests because of missing suggested packages

### ISSUE THREAD

**Issue by dmurdoch** [r-lib/rlang#1178]
`rlang` is currently failing CRAN tests on the winUCRT platform with these test failures:

```
> f("{nm}" := "value")
Error: Can't use `{` symbols in LHS of `:=` if glue is not installed.
```

and 

```
  > library("testthat")
  Error in library("testthat") : there is no package called 'testthat'
  Execution halted
```

Both `glue` and `testthat` are suggested packages.

These tests should be made conditional on the presence of the suggested packages so that `rlang` reverse dependencies can still be built and tested on CRAN.  If I can get a test platform set up, I'll submit a PR.

**Comment by dmurdoch** [comment]
PR #1179 fixes the issue with glue. 

The issue with testthat is harder:  there doesn't seem to be a way to warn users that testthat is missing other than failing the test, which gives an ERROR and makes all downstream packages from rlang fail:  including testthat.  Ignoring the missing testthat means that other possible errors in rlang will not be detected.

**Comment by lionel-** [comment]
Closing this now until we can figure out a general solution for the hard dependencies of scripts in `tests/`. Happy to revisit once we have one. In the meantime I have fixed another issue when rmarkdown isn't installed (see https://github.com/r-lib/rlang/commit/48fa63a3). Thanks for looking into this @dmurdoch!
