### ISSUE TITLE
Should arg_match() pass NULL through?

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#1182]
```R
arg_match0(NULL, letters)
```

Should this return `NULL` rather than erroring?

**Comment by lionel-** [comment]
I think the contract of `arg_match()` is that it returns a string, then you can safely do things like `if (arg == "foo")`.

It could gain a `null = ` argument? Could be set to a position e.g. `null = 1` so it always selects the default choice even after changes in the possible values.

**Comment by hadley** [comment]
Yeah that's true. Probably better to just handle individually.
