### ISSUE TITLE
Possible typo in abort documentation: 'withCallinghandlers'

### ISSUE THREAD

**Issue by dapritchard** [r-lib/rlang#1185]
There are two instances of `withCallinghandlers` in the documentation of `abort` which I believe are meant to be `withCallingHandlers`? (Note the capitalized 'H'.)

It's also very likely that I'm not fully understanding the desired effect of the example, but would we want to remove the outer `try` call in order for an error to be thrown without being caught in this example?
```r
try(withCallinghandlers(
  download(file),
  error = function(err) {
    msg <- sprintf("Can't download `%s`", file)
    abort(msg, parent = err)
}))
```

**Comment by lionel-** [comment]
Thanks for the heads up!

Examples are used as basic unit tests by CMD check. We use `try()` in examples that throw errors because it prints the error and catches it right away. This way the error doesn't reach R CMD check, which would cause a failure.
