### ISSUE TITLE
Consider adding `switch2` with dynamic dots

### ISSUE THREAD

**Issue by GiuseppeTT** [r-lib/rlang#1190]
What do you think about adding a dynamic dots implementation of the built-in `switch`?

Below is a simple implementation with some examples.
``` r
switch2 <- function(
    expression_,
    ...
) {
    expression_ <- list(expression_)
    dots <- rlang::list2(...)

    do.call(switch, c(expression_, dots))
}

a <- "a"
b <- "b"

switch2(
    "a",
    !! a := "You selected a",
    !! b := "You selected b"
)
#> [1] "You selected a"

first <- 1
second <- 2

switch2(
    2,
    "{first}" := "You selected first",
    "{second}" := "You selected second"
)
#> [1] "You selected second"

honda_civic_aspects <- as.list(mtcars["Honda Civic", ])

switch2(
    "mpg",
    !!! honda_civic_aspects
)
#> [1] 30.4
```

<sup>Created on 2021-05-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by lionel-** [comment]
Thanks for the suggestion, unfortunately I think this is out of scope for rlang. Also a `switch2()` operator would raise a lot of design issues such as value matching.
