### ISSUE TITLE
update rlang on CRAN

### ISSUE THREAD

**Issue by Athanasiamo** [r-lib/rlang#1202]
Hi.

I've discovered that rmarkdown on CRAN depends on the current dev version of rlang (0.4.11.9000), while rlang version on CRAN is 0.4.11. This is wrecking all sorts of havocs for new installs, where rmarkdown will fail to install because the correct rlang version is not available on CRAN. And rmarkdown being a pivotal package, this quite difficult to resolve neatly. 

It's mentioned in this ticket on the remotes package: https://github.com/r-lib/remotes/issues/610

Jim says it'll be resolved once the binaries are in place, and I'm assuming he's right. But I thought I'd make a note of it here that there is a dependency mismatch on CRAN for these two packages.

**Comment by lionel-** [comment]
> rmarkdown on CRAN depends on the current dev version of rlang

I don't think it is possible for a CRAN package to depend on a dev version.

Looking at your log and tracking down a bit, it looks like you're using dev gradethis which uses dev hmtltools which uses dev rlang (https://github.com/rstudio/htmltools/blob/master/DESCRIPTION). Sorry that this is causing issues. I don't think we can do something here though.

**Comment by Athanasiamo** [comment]
thanks, and sorry for misleading you. I went down the wrong rabbithole it seems!
