### ISSUE TITLE
Possible export `env_as_list()`?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/rlang#1204]
Since `rlang::as_list()` is deprecated, which used `rlang:::env_as_list()`

```r
> rlang:::env_as_list
function (x) 
{
    names_x <- names(x)
    x <- as_base_type(x, as.list)
    set_names(x, .Call(rlang_unescape_character, names_x))
}
```

Implicitly requested by:
https://twitter.com/sakrejda/status/1392808155009191937

A current alternative is:

```r
env %>% env_get_list(env_names(.))
```

**Comment by lionel-** [comment]
This is probably not needed but let's keep thinking about it if use cases surface.
