### ISSUE TITLE
Find a way to display non-existing and fake srcrefs in backtraces

### ISSUE THREAD

**Issue by vspinu** [r-lib/rlang#1206]
The location of the temporary sources and fake sources works just fine with ESS. If a package is located in user's project directories (`ess-r-package-library-paths`) ESS will find locations even from the tmp srcref locations. 

More severely, ESS uses fake paths to track ad-hoc evaluation of functions. Things work as expected in normal stacktraces, but not with rlang's entrace. 

More generally, I believe that even for non-ESS use case hiding refs from trace might be harmful as they convey useful information about the issue (dir nesting, file-name, package name).

 #628

**Comment by vspinu** [comment]
There is an issue with relative paths as well. Source some files `setwd` => locations not displayed. 

```
> source("tmp.R")
> test2()
Error in test() : failed
Backtrace:
    █
 1. └─global::test2()
 2.   └─global::test() tmp.R:10:2
> setwd("..")
> test2()
Error in test() : failed
Backtrace:
    █
 1. └─global::test2()
 2.   └─global::test()
> traceback()
3: stop("failed") at tmp.R#6
2: test() at tmp.R#10
1: test2()
> 
```

Plus the consistency issue, R's traceback() does display the locations no matter what, so for a user switching from plain traceback to entrace it's a bit of a surprise.

**Comment by lionel-** [comment]
> There is an issue with relative paths as well. Source some files setwd => locations not displayed.

I don't see that. Please post a reprex.

**Comment by lionel-** [comment]
The problem with dangling files is that the full absolute location is distracting:

```r
options(
  "rlang:::trace_force_dangling_srcrefs" = TRUE,
  rlang_backtrace_on_error = "full"
)

attributes(attributes(rlang::eval_bare)$srcref)$srcfile
#> /private/tmp/RtmplkdUvG/R.INSTALLf67d666be756/rlang/R/eval.R

f <- function() { g() }
g <- function() { rlang::eval_bare(quote(h())) }
h <- function() { i() }
i <- function() { rlang::abort("foo") }

f()
#> Error: foo
#> Backtrace:
#>     ▆
#>  1. └─global::f()
#>  2.   └─global::g()
#>  3.     ├─rlang::eval_bare(quote(h()))
#>  4.     └─global::h()
#> /private/tmp/RtmplkdUvG/R.INSTALLf67d666be756/rlang/R/eval.R:99:2
#>  5.       └─global::i()
```

What we could do is to detect a `R/*.R` pattern in file names and elide when the file doesn't exist:

```r
f()
#> Error: foo
#> Backtrace:
#>     ▆
#>  1. └─global::f()
#>  2.   └─global::g()
#>  3.     ├─rlang::eval_bare(quote(h()))
#>  4.     └─global::h() .../rlang/R/eval.R:99:2
#>  5.       └─global::i()
```

Are there some interactions with RStudio to be aware of @hadley?

**Comment by lionel-** [comment]
Regarding the ESS srcrefs, it'd be distracting as well to have this sort of paths in backtraces:

```
/var/folders/cr/whn38wbj72zd8h7wwwtnch500000gn/T/srcrefs5.r!KPcbvQ:1:1
```

I think we could provide a hook in rlang that ESS could use to transform fake source paths to actual locations. Then rlang could abbreviate the actual path as appropriate depending on current location.

**Comment by hadley** [comment]
@hadley I don't know of anything off the top of my head

**Comment by vspinu** [comment]
> I don't see that. Please post a reprex.

Place the following code in `tmp.R`
```
options(error = rlang::entrace,
        rlang_backtrace_on_error = "full")

test <- function() {
  stop("failed")
}

test2 <- function() {
  test()
}
```
Then
```
> source("tmp.R"); test2()
Error in test() : failed
Backtrace:
    █
 1. └─global::test2()
 2.   └─global::test() tmp.R:10:2
> setwd(".."); test2()
Error in test() : failed
Backtrace:
    █
 1. └─global::test2()
 2.   └─global::test()
```

> The problem with dangling files is that the full absolute location is distracting:

I wasn't bothered by it before you mentioned it :)

Those /tmp path could be abreviated. From ESS prospective we don't care, as long as the path contains package name we should be able to reconstruct it. Adhoc evaluation references use the token at the end of the file name, so it's fine as well.

**Comment by vspinu** [comment]
Could we please add an option to disable this behavior for now, until we have a solution for this?

**Comment by lionel-** [comment]
There is already a private option that you can use until a definitive fix:

```r
options(
  "rlang:::trace_force_dangling_srcrefs" = TRUE
)
```

**Comment by lionel-** [comment]
Let's try this. Dangling srcrefs are printed but we only keep the last 3 components of the path.
