### ISSUE TITLE
`is_named()` change breaks dplyr edge case

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/rlang#1219]
``` r
library(rlang)

# New behavior
is_named(list())
#> [1] TRUE

# Previously
is_named(list())
#> [1] FALSE
```

From https://github.com/r-lib/rlang/issues/191

This change breaks a test in dplyr:
https://github.com/tidyverse/dplyr/blob/99896e05cd51d3e8ce859efa100feb23f31c2f66/tests/testthat/test-bind.R#L160-L162

`bind_rows()` uses this predicate function to determine if the input is flattenable or not, and the change to `is_named()` changes the behavior:

```
is_flattenable <- function(x) vec_is_list(x) && !is_named(x)
dots <- flatten_if(dots, is_flattenable)
```

**Comment by lionel-** [comment]
Let's just add a new util `is_named2()` and keep the behaviour of `is_named()` unchanged. This makes the API more complicated but it makes sense when you think about `names()` vs `names2()`.
