### ISSUE TITLE
interrupt() errors if interrupts are not processes immediately

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/rlang#1224]
Which does not seem correct, as they are sometimes not processes immediately. E.g.

```r
globalCallingHandlers(interrupt = function(int) print("Unhandled interrupt!"))
tryCatch(
  suspendInterrupts(rlang::interrupt()),
  interrupt = function(x) print("interrupt!")
)
```

```r
#> Error: Internal error: Simulated interrupt not processed
#> Run `rlang::last_error()` to see where the error occurred.
#> [1] "Unhandled interrupt!"
```

So I would think that throwing an error there is not necessary.

**Comment by gaborcsardi** [comment]
I am not sure what the purpose of `interrupt()` is, but https://github.com/r-lib/rlang/commit/00d71b10013eb500c4abc91793ce511349079ec7 does not seem right to me.

Is `interrupt()` supposed to mimic a real interrupt, i.e. a SIGINT on Unix?

**Comment by lionel-** [comment]
yeah but it's not used anywhere AFAIK. I planned to switch to a pure R `invokeRestart()` approach.

>  00d71b1 does not seem right to me.

Could you elaborate?

**Comment by gaborcsardi** [comment]
If a real SIGINT comes in while the interrupts are suspended, then it is "delivered" once they are allowed again.

**Comment by lionel-** [comment]
ah that makes sense. Does this look better? https://github.com/r-lib/rlang/commit/1855862e

Are you going to depend on the behaviour of interrupt simulation?

**Comment by gaborcsardi** [comment]
Yeah, that looks good.

> Are you going to depend on the behaviour of interrupt simulation?

Hmmm, I am not sure what you mean, sry.

**Comment by lionel-** [comment]
I've been considering implementing `interrupt()` with something simpler like `signalCondition(int); invokeRestart("abort")`. So I was wondering if the hard interrupt simulation was something you would expect from this function?

**Comment by gaborcsardi** [comment]
Got it. I don't know, it is hard to decide which one is more useful, they are both quite niche. Plus sometimes neither will do, and you need an actual signal. 

So I would leave it as is. If you just want the condition, you can always signal that yourself.
