### ISSUE TITLE
Unquoting language objects with `!!!` warning alternative

### ISSUE THREAD

**Issue by laresbernardo** [r-lib/rlang#1233]
Hi! This is more of a question rather than an issue with `rlang`. I started getting these warnings (once per session) some time ago for some old functions that actually don't break the code but are annoying (I guess that's the idea):

```
Warning message:
Unquoting language objects with `!!!` is deprecated as of rlang 0.4.0.
Please use `!!` instead.

  # Bad:
  dplyr::select(data, !!!enquo(x))

  # Good:
  dplyr::select(data, !!enquo(x))    # Unquote single quosure
  dplyr::select(data, !!!enquos(x))  # Splice list of quosures
```

What happens is that depending on how many inputs are passed to `...`, the function plots A or B (here's the actual function: [distr](https://laresbernardo.github.io/lares/reference/distr.html)). To do so, the code manually picks the first one or the second one with `!!!enquos(...)[[n]]`. Here is a reproducible example:

```
options(lifecycle_repeat_warnings = TRUE) # So we can check if any alternative solution works
library(dplyr)
data("starwars")
foo <- function(x, ...) {
  temp <- enquos(...)
  group_by(x, !!!temp[[1]]) %>% tally()
}
foo(starwars, sex, gender) # Will ignore gender in this case
```

What would be the correct way of doing this? Thanks!

**Comment by markfairbanks** [comment]
One easy way to your issue is to use single brackets like this `!!!enquos(...)[n]`.

One way to think about it - `!!!` splices lists. If you use `[[n]]` it returns a single quosure because it extracts the individual element of the list. If you use `[n]` it returns a list (of length 1), with the single element being your target quosure.

So now this works without warnings:

``` r
options(lifecycle_repeat_warnings = TRUE) # So we can check if any alternative solution works
library(dplyr)
data("starwars")
foo <- function(x, ...) {
  temp <- enquos(...)
  group_by(x, !!!temp[1]) %>% tally()
}

foo(starwars, sex, gender) # Will ignore gender in this case
#> # A tibble: 5 x 2
#>   sex                n
#>   <chr>          <int>
#> 1 female            16
#> 2 hermaphroditic     1
#> 3 male              60
#> 4 none               6
#> 5 <NA>               4
```

**Comment by laresbernardo** [comment]
That's exactly it @markfairbanks  Thanks a lot! can't believe it was this easy!  😂
