### ISSUE TITLE
Empty quosures can not be turned into callable functions

### ISSUE THREAD

**Issue by schloerke** [r-lib/rlang#1244]
Reprex:

``` r
fn <- rlang::as_function(rlang::quo())
fn()
#> Error in fn(): object '' not found
```

<sup>Created on 2021-07-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I'm expecting the body of the function to not throw an error, such as `function(){}` to be returned from `rlang::as_function(quo())`.

----------------

I have a workaround using `quo_is_missing()`.

```r
fun <- rlang::as_function(q)
if (rlang::quo_is_missing(q)) {
  rlang::fn_body(fun) <- quote({})
}
```

**Comment by lionel-** [comment]
The thing is that `quo()` really represents the missing argument so I'm not sure special-casing it in `as_function()` is to be expected. I think I prefer keeping things simple and mecanical here.
