### ISSUE TITLE
Build system prepends DESTDIR on mkdir calls during the make phase

### ISSUE THREAD

**Issue by mmatongo** [r-lib/rlang#1246]
First noticed here https://github.com/kisslinux/kiss/issues/258

The build system assumes that `DESTDIR` is only set during the `install` phase (which is an incorrect assumption to make).
This behaviour is unexpected, the result of this is that it prepends `DESTDIR` to the `mkdir` calls that lead to breaking builds.

A workaround for this is by adding `DESTDIR=""` in the make phase.

**Comment by lionel-** [comment]
rlang is an R package. Are you looking for https://bugs.r-project.org/?

**Comment by mmatongo** [comment]
> rlang is an R package. Are you looking for https://bugs.r-project.org/?

My mistake, sorry. 😄
