### ISSUE TITLE
check_dots_used() and nonstandard evaluation

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#1251]
Could `enquo()` and friends mark an argument as "used"?

``` r
library(rlang)

generic <- function(x, ...) {
  check_dots_used(action = warn)
  method(x, ...)
}

method <- function(x, ..., foo = NULL) {
  enquo(foo)
}

generic("x", foo = bar)
#> Warning: 1 components of `...` were not used.
#> 
#> We detected these problematic arguments:
#> * `foo`
#> 
#> Did you misspecify an argument?
#> <quosure>
#> expr: ^bar
#> env:  global
```

<sup>Created on 2021-08-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

CC @mgirlich.

**Comment by lionel-** [comment]
This is difficult because we can't force its argument as it couldn't be captured again. We could use auxiliary data stored in the environment to determine if a variable is used though.

**Comment by lionel-** [comment]
Can you `force()` the argument after `enquo()`?

**Comment by mgirlich** [comment]
We cannot force it directly as this might produce an error, e.g. when `foo` is used with `tidyselect::eval_select()` this won't work. Wrapping it in `try()` still produces the warning :-/

**Comment by lionel-** [comment]
I mean after all NSE has been performed, is there a time where you could force the argument?

**Comment by lionel-** [comment]
Perhaps in `on.exit()`.

**Comment by mgirlich** [comment]
Basically yes. But I'm not sure if it works. `foo` is used with tidyselect, so we will likely get an error when we force it, e.g. if we force `foo = everything()` or `foo = a:b` (where `a` and `b` are columns) then we get an error. Is there a way we can force it without an error? Or can we catch the error and it is still evaluated?

**Comment by lionel-** [comment]
Can you send a reprex please so I can understand the setup?

**Comment by mgirlich** [comment]
Here is the reprex that hopefully makes it clearer.

Without `enquo()` I cannot use expressions like `c(mpg, cyl)`

``` r
library(rlang)
library(ellipsis)

generic <- function(x, ...) {
  check_dots_used(action = warn)
  method(x, ...)
}

method <- function(x, ..., foo = NULL) {
  tidyselect::eval_select(foo, mtcars)
}

# `everything()` works without `enquo(foo)`
generic("x", foo = dplyr::everything())
#>  mpg  cyl disp   hp drat   wt qsec   vs   am gear carb 
#>    1    2    3    4    5    6    7    8    9   10   11

# but `c(mpg, cyl)` doesn't
generic("x", foo = c(mpg, cyl))
#> Error: object 'mpg' not found
#> Warning: 1 components of `...` were not used.
#> 
#> We detected these problematic arguments:
#> * `foo`
#> 
#> Did you misspecify an argument?
```

<sup>Created on 2021-08-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

With `enquo()` I get the warning about unused arguments

``` r
method <- function(x, ..., foo = NULL) {
  tidyselect::eval_select(enquo(foo), mtcars)
}

generic("x", foo = everything())
#> Warning: 1 components of `...` were not used.
#> 
#> We detected these problematic arguments:
#> * `foo`
#> 
#> Did you misspecify an argument?
#>  mpg  cyl disp   hp drat   wt qsec   vs   am gear carb 
#>    1    2    3    4    5    6    7    8    9   10   11
generic("x", foo = c(mpg, cyl))
#> Warning: 1 components of `...` were not used.
#> 
#> We detected these problematic arguments:
#> * `foo`
#> 
#> Did you misspecify an argument?
#> mpg cyl 
#>   1   2
```

<sup>Created on 2021-08-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

And forcing `foo` produces an error

``` r
method <- function(x, ..., foo = NULL) {
  tidyselect::eval_select(enquo(foo), mtcars)
  force(foo)
}

generic("x", foo = everything())
#> Error in everything(): could not find function "everything"
#> Warning: 1 components of `...` were not used.
#> 
#> We detected these problematic arguments:
#> * `foo`
#> 
#> Did you misspecify an argument?
generic("x", foo = c(mpg, cyl))
#> Error in force(foo): object 'mpg' not found
#> Warning: 1 components of `...` were not used.
#> 
#> We detected these problematic arguments:
#> * `foo`
#> 
#> Did you misspecify an argument?
```

<sup>Created on 2021-08-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lionel-** [comment]
oh yeah of course. I'm not sure we want to support that though, it would make both ellipsis and tidy eval more complex for little payoff.

**Comment by lionel-** [comment]
Sorry that we can’t fix that.
