### ISSUE TITLE
Can't force display of full backtrace in Rmd

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#1269]
````
```{r}
library(rlang)
options(rlang_backtrace_on_error = "full")

f <- function() {g()}
g <- function() {h()}
h <- function() {i()}
i <- function() {abort("Hi!")}
```

```{r}
f()
```

````

I see:

```
Quitting from lines 14-16 (test.Rmd) 

Error in `i()`: Hi!
Backtrace:
 1. global::f()
 2. global::g()
 3. global::h()
 4. global::i()
Execution halted
```

And why don't I see a srcref here?

**Comment by hadley** [comment]
And if I change the code block to `error = TRUE`:

````
```{r, error = TRUE}
i()
```
````

I don't get a full backtrace either, despite what https://rlang.r-lib.org/reference/rlang_backtrace_on_error.html#expected-errors-in-rmarkdown-documents suggests.

**Comment by lionel-** [comment]
You should see the same behaviour w/o markdown. Backtraces of size 1 are
not displayed since they are not informative. They only happen with
interactive commands.

**Comment by hadley** [comment]
I messed up my initial example by typing `i()` instead of `f()`. But if you update it to use `f()` I still see the same problems:

* When `error = FALSE`, I see the simplified traceback, not the full traceback
* When `error = TRUE`, I don't see any traceback.

**Comment by lionel-** [comment]
> And why don't I see a srcref here?

That's because `attr(srcref, "srcfile")$filename` is set to `"<text>"`. I don't know what causes that.

**Comment by lionel-** [comment]
I think the problem with `error = TRUE` is more general. With the new display of error messages where we control the full message, including the `"Error: "` prefix, we probably want a customisation point in knitr to let rlang format the full error message. By the same token we'll be able to insert a backtrace below the error message.

cc @cderv

**Comment by hadley** [comment]
In the interim, we should fix the rlang docs to make it clear that we can't currently control the display of errors in knitr. Then I think we can close this issue, but continue to work with the knitr team on better tracebacks for expected errors.

**Comment by lionel-** [comment]
Actually the `sew()` method for rlang errors takes `rlang_backtrace_on_error_report` into account so you should see a backtrace @hadley.

The remaining things to fix are:

- Support for calling handlers in evaluate and knitr so that we can save `last_error()` within-chunk instead of across chunks through the `sew()` methods.
- A customisation point for formatting whole error messages including the prefix. Once we have that we can remove the `sew()` method and include the backtrace from there.

**Comment by hadley** [comment]
Oh yeah, that looks fine to me. I thought you were saying that didn't work.
