### ISSUE TITLE
duplicate() does not properly clone rvest objects

### ISSUE THREAD

**Issue by geotheory** [r-lib/rlang#1270]
Not sure if this is a {rlang} or {rvest}.  `duplicate()` seems unable to clone {rvest} objects.  The following example is from this [SO question](https://stackoverflow.com/questions/69038406/rvest-object-cloned-with-rlangduplicate-is-not-properly-cloned).

```
require(rvest)
h = '<ul>
<li id="target">
text to extract
<ul><li>text to ignore</li><li>this too</li></ul>
</li>
</ul>'

doc = xml2::read_html(h)
x = html_node(doc, '#target')

html_text(x)
#> [1] "\ntext to extract\ntext to ignorethis too"

x2 = rlang::duplicate(x, shallow = FALSE)
children = html_children(x2)
xml2::xml_remove(children)
html_text(x2)
#> [1] "\ntext to extract\n"

# That works as intended, however x has also been mutated:
html_text(x)
#> [1] "\ntext to extract\n"
```

**Comment by lionel-** [comment]
I have changed the doc to make it clear that `duplicate()` is for R experts only.

Probably these rvest objects have mutable state like an environments in their structure (or are themselves environments?). So rvest should provide this functionality itself (if it makes sense).

**Comment by geotheory** [comment]
Cheers I'll report to rvest. 

I'd think if a function is published then it should be assumed that _anyone_ will use it, so the priority _should_ be for documentation to help all users understand its mecahnism and limitations.  Otherwise maybe give an idea what you mean by expert, because lots of R people who consider themselves pretty expert might lack something you consider important in the context.

**Comment by lionel-** [comment]
Functions that are marked with `@keywords internal` are not meant to be used by everyone. For this reason they don't appear in the package's documentation index. I have mentioned in the documentation what is meant by experts in this case, i.e. users of the C API of R.

**Comment by lionel-** [comment]
I have replaced "experts" by "users of the C API" in https://github.com/r-lib/rlang/commit/ab788c712a2132d0ee9b12f09f22584d3fbe76e3
