### ISSUE TITLE
rlang related sefault on tidyverse installs

### ISSUE THREAD

**Issue by wallingTACC** [r-lib/rlang#1280]
There is a segfault that occurs during installs of many of the tidyverse related packages that appears to be related to rlang.  Installing directly from git seems to resolve the issues, so please consider pushing a new rlang version to cran.  More details can be found here.

https://github.com/tidyverse/ggplot2/issues/4499

I'm afraid I can't offer too much more insight into what the actual core issue is, but to summarize, running the following before installing, for example, tidyverse seems to resolve the issue.

pak::pkg_install("r-lib/rlang")

**Comment by lionel-** [comment]
It's much more likely to be an issue in your installation.

What happens if you reinstall the CRAN version from source? What happens if you reinstall all your packages from binary?

**Comment by lionel-** [comment]
Closing this but let me know if you run into more issues or find anything weird.
