### ISSUE TITLE
Should `names2()` return column names of a matrix/array?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/rlang#1285]
Currently `names2()` returns 1 `""` for each element in the array, which also feels odd.

Really I wanted a type stable `colnames()` that returns `character()` even in the zero col case:

``` r
library(rlang)

x <- matrix(1:4, nrow = 2, ncol = 2, dimnames = list(c("r1", "r2"), c("c1", "c2")))
x
#>    c1 c2
#> r1  1  3
#> r2  2  4

names(x)
#> NULL
names2(x) # 1 "" for each element
#> [1] "" "" "" ""

# I wanted a type stable colnames()
colnames(x)
#> [1] "c1" "c2"
colnames(x[,integer()]) # i.e. wanted `character()` here
#> NULL
```

`names()` seems to return `NULL`, so `names2()` could possibly return `character()`, but that also doesn't feel great.

**Comment by lionel-** [comment]
I'm not sure this is the right level of abstraction for an rlang function. Also, technically, matrices and arrays may have names (i.e. element-wise metadata).

**Comment by DavisVaughan** [comment]
I would also be happy to accept that this just isn't what `names2()` should be used for.

It's also a little bit arbitrary to decide that the names of the 2nd dimension should be returned here for an N dimensional array

**Comment by DavisVaughan** [comment]
I actually didn't know you could do this. In light of this, I think `names2()` is being consistent with `names()` here and that no changes are needed

``` r
x <- matrix(1:4, nrow = 2, ncol = 2, dimnames = list(c("r1", "r2"), c("c1", "c2")))
names(x) <- letters[1:4] 

x
#>    c1 c2
#> r1  1  3
#> r2  2  4
#> attr(,"names")
#> [1] "a" "b" "c" "d"

names(x)
#> [1] "a" "b" "c" "d"

rlang::names2(x)
#> [1] "a" "b" "c" "d"
```

<sup>Created on 2021-09-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

**Comment by lionel-** [comment]
I'd be happy to add `colnames2()` if you find it useful.

**Comment by DavisVaughan** [comment]
I think this is rare enough that I'm okay without it, but thanks.

I did just discover that `colnames()` has `do.NULL=` which you can set to `FALSE` to force names to be generated

```r
> colnames(x[, integer()], do.NULL = F)
character(0)
> colnames(x[, integer()], do.NULL = T)
NULL
```
