### ISSUE TITLE
Should trace API interact with `.__error_call__.`?

### ISSUE THREAD

**Issue by tzakharko** [r-lib/rlang#1317]
`rlang`recently added an extremely useful feature of overriding the error call in a local environment (in form of `.__error_call__.` and `local_error_call()`). This is great for auxiliary checking functions that have to perform checks on behalf of other functions for example. 

I was wondering whether it would be a good idea if `trace_back()` inferred `bottom` from `.__error_call__ .` in case the latter is an environment. This could potentially produce cleaner traces that omit the auxiliary functions entirely. E.g.

```r
library(rlang)

check <- function(x) {
  .__error_call__. <- caller_env()
  (x>0) || abort("must be positive")
}

f <- function(x) {
  check(x)
  x*2
}

f(-1)
```

currently produces 

```
Error in `f()`: must be positive
Backtrace:
    ▆
 1. └─global f(-1)
 2.   └─global check(x)
```

If trace would use the information in `  .__error_call__.`, the error produced instead would state:

```
Error in `f()`: must be positive
Backtrace:
    ▆
 1. └─global f(-1)
```

**Comment by lionel-** [comment]
Probably not because you generally want to get the full story from a backtrace, since they are for debugging.
