### ISSUE TITLE
Consider making `as_label()` generic

### ISSUE THREAD

**Issue by tzakharko** [r-lib/rlang#1318]
`as_label()` is an extremely useful function for generating a concise, single-line text representation of an arbitrary object. Sometimes I do find myself wanting more customizability however. It currently dispatches to `pillar::type_sum()` which does not work well for all cases, as it can be useful for a generated label to be different from the column summary label.

Proposed change:  make `as_label()` generic and move the current implementation to `as_label.default()`

**Comment by lionel-** [comment]
Thanks for the suggestion. I've mentioned it in #1173 to keep track.
