### ISSUE TITLE
print names of .onLoad functions in traceback?

### ISSUE THREAD

**Issue by kevinushey** [r-lib/rlang#1321]
For example:

```
> trace(dyn.load, quote(print(rlang::trace_back())))
Tracing function "dyn.load" in package "base"
[1] "dyn.load"
> library(RcppParallel)
Tracing dyn.load(path, local = FALSE, now = TRUE) on entry 
     ▆
  1. └─base::library(RcppParallel)
  2.   ├─base::tryCatch(...)
  3.   │ └─base tryCatchList(expr, classes, parentenv, handlers)
  4.   │   └─base tryCatchOne(expr, names, parentenv, handlers[[1L]])
  5.   │     └─base doTryCatch(return(expr), name, parentenv, handler)
  6.   └─base::loadNamespace(package, lib.loc)
  7.     └─base runHook(".onLoad", env, package.lib, package)
  8.       ├─base::tryCatch(fun(libname, pkgname), error = identity)
  9.       │ └─base tryCatchList(expr, classes, parentenv, handlers)
 10.       │   └─base tryCatchOne(expr, names, parentenv, handlers[[1L]])
 11.       │     └─base doTryCatch(return(expr), name, parentenv, handler)
 12.       └─RcppParallel fun(libname, pkgname)
 13.         └─RcppParallel:::loadTbbLibrary("tbb")
 14.           └─base::dyn.load(path, local = FALSE, now = TRUE)
 ```

Note that the traceback reports RcppParallel's `.onLoad()` function as `RcppParallel fun(libname, pkgname)`. I would've expected to see `RcppParallel:::.onLoad(libname, pkgname)` instead.

My best guess is that this happens because the function is assigned to a variable `fun` and called here, when loaded via `loadNamespace()`:

https://github.com/wch/r-source/blob/d3c735e8b5d4a4ac527958b24ede3699fcd0f4b3/src/library/base/R/namespace.R#L241-L244

This issue is pretty minor since the traceback already makes it clear from `runHook(".onLoad", ...)` that we'll be running the `.onLoad()` hook, though.

**Comment by lionel-** [comment]
hmm, unfortunately it's the responsibility of the failing code to make sure backtraces are legible. It's probably not worth the effort to go around it here, especially since namespace loading has other debugging tools available, such as tracing.

**Comment by kevinushey** [comment]
Maybe I'm misunderstanding, but there's no failure or error here; it's just the symbol name reported in `rlang`'s backtrace is less useful within a `.onLoad()`.

**Comment by lionel-** [comment]
Sorry if I wasn't clear, I meant it's the responsibility of internal code to make sure it's legible in a backtrace. For instance using `map(x, \(x) foo(x))` instead of `map(x, foo)`, to avoid `foo` being bound to a foreign symbol.

If I understand correctly, you would like to detect this sort of cases at trace capture time and patch the backtrace to be more informative? If yes, I think that this is out of scope for `trace_back()`.

**Comment by kevinushey** [comment]
Thanks for clarifying! That's indeed what I meant, but I agree this is perhaps ultimately out-of-scope.
