### ISSUE TITLE
Question regarding modification of compiler constants

### ISSUE THREAD

**Issue by asardaes** [r-lib/rlang#1324]
Hello, I'm trying to understand an [`rcnst` issue](https://github.com/kalibera/cran-checks/blob/981f1d3d294ccf3046bd7f5915d29ca265941c6e/rcnst/results/table.express/00check.log) that was flagged in one of my packages by CRAN. The package makes extensive use of `rlang` to build expressions that `data.table` understands, and since the latter does a lot of operations by reference, I was told that things like `MARK_NOT_MUTABLE` could cause conflicts. Are there functions in `rlang` that could return objects that should never be modified in place?

The error from the check references the body of a function [created with `rlang::expr`](https://github.com/asardaes/table.express/blob/c7d4768d35cf811a7cdcd9a6f4509dc7917bbda0/tests/testthat/unit/test-right_join.R#L158) and then evaluated with `base::eval`, and I can't imagine a scenario in which somehow the body of the function was modified by the code it executes when evaluated.

**Comment by lionel-** [comment]
IIRC injected values are marked as not mutable. There was a bytecode bug where an index injected in a `for` loop would be mutated otherwise.

**Comment by asardaes** [comment]
So it's indeed possible that a call like `data.table::as.data.table(!!lhs)` marks the object bound to `lhs` as not mutable? That would explain why `rcnst` complains after `data.table` modifies `lhs` in place.

**Comment by lionel-** [comment]
Closing since there doesn't seem to be a bug in rlang here.

**Comment by asardaes** [comment]
Well, it's not a bug per se, but is it a feature? I imagine there are reasons for that logic, and I imagine most scenarios don't involve modification by reference, but it certainly caught me off guard.

**Comment by lionel-** [comment]
rlang is following R semantics here. It gets a foreign object and injects it in a new container (language object). This foreign object might have been owned by a given context where mutation was safe (e.g. for loop with a freshly initialised `i`), but as soon as the object is injected, it becomes shared, and should no longer be mutated.

See the tests in https://github.com/r-lib/rlang/commit/b2a814ef1220907e37acd1f1d6eb4975ee40b189
