### ISSUE TITLE
`error_cnd()` and bullets

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/rlang#1329]
``` r
library(rlang)
error_cnd(message = c(
  "bla", 
  i = "bla", 
  x = "bla"
))
#> <error/rlang_error>
#> Error: bla
#> bla
#> bla
```

<sup>Created on 2021-12-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by lionel-** [comment]
For now you need to pass `use_cli_format = TRUE`.

But we should probably look up the flag in the caller env?

**Comment by romainfrancois** [comment]
Yeah maybe. FTR, I found out about this with something like this: 

``` r
library(rlang)
local_use_cli()
#> Setting deferred event(s) on global environment.
#>   * Execute (and clear) with `withr::deferred_run()`.
#>   * Clear (without executing) with `withr::deferred_clear()`.

abort(c("hello", i = "World"), parent = error_cnd(message = c(x = "error")))
#> Error:
#>   hello
#>   ℹ World
#> Caused by error:
#>   error
```

<sup>Created on 2021-12-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
