### ISSUE TITLE
Installation of rlang fails on R 4.0.2 / SUSE Linux Enterprise Server 15 SP1

### ISSUE THREAD

**Issue by tillandlauer** [r-lib/rlang#1339]
Hello and happy new year!

On our HPC (SUSE Linux Enterprise Server 15 SP1), the newest R version available is 4.0.2. 
Here, installing rlang via install.packages("rlang") leads to a compilation error:

```
In file included from ./lib/rlang.h:81,
from export/exported.c:1,
from export.c:1:
./lib/c-utils.h: In function 'r_ssize_as_double':
./lib/c-utils.h:81:11: error: 'DBL_MAX' undeclared (first use in this function); did you mean 'TMP_MAX'?
if (x > DBL_MAX || x < -DBL_MAX) {
^~~~~~~
TMP_MAX
```

Could you please help me resolve this issue? According to CRAN, rlang should support R ≥ 3.3.0. Is this a problem with our HPC system or of rlang?

Thank you and best regards,
Till

**Comment by lionel-** [comment]
Hello,

This is strange, `DBL_MAX` should be defined in `<float.h>` according to https://en.cppreference.com/w/c/types/limits, and that header is properly included: https://github.com/cran/rlang/blob/c166e385ecb66d02c244106bd83277bf3bca0084/src/lib/c-utils.h#L4 (this is the current CRAN version).

Also when I search for that error on the web, it is generally recommended to fix it by including `<float.h>`, e.g. https://stackoverflow.com/questions/28427495/error-c2065-dbl-max-undeclared-identifier-in-vs2008-but-not-in-vs2010

Perhaps there is an issue with your gcc or clang install?

We do require C99, but I'd be surprised if your Linux server did not support it.

**Comment by tillandlauer** [comment]
Hi Lionel,

After inquiring with our HPC support, this turned out to be a local gcc configuration issue - it's not a bug of rlang after all. Thanks for your prompt help and sorry for bothering you!

Best regards,
Till
