### ISSUE TITLE
Replacement for `with_abort()`

### ISSUE THREAD

**Issue by pat-s** [r-lib/rlang#1351]
`with_abort()` got removed in v1.0.0 released yesterday but I could not find a NEWS entry for this which possibly suggests a replacement.

Also I checked in `rlang` v0.4.12 for a deprecation notice but could not find one.

What is the advise regarding the replacement of `with_abort()`?

**Comment by lionel-** [comment]
oh I didn't catch your package in revdep checks. Note that using `with_abort()` within `tryCatch()` does not create complete backtraces. Instead you could have used `withCallingHandlers()` (or the new `try_fetch()`).

The replacement for `with_abort()` is `global_handle()` on the user side. If you need to do this on the package side, try something like this: https://github.com/r-lib/tidyselect/blob/b17977d1c8aad254b51e778272d12b965e523c7a/R/conditions.R#L13-L24.

Note that with rlang 1.0.1 (things are still in flux), you'll need to add `parent = NA` to let rlang know that you are rethrowing an error (this enables better backtrace handling). The `NA` means the rethrow is unchained. More documentation to come.

**Comment by lionel-** [comment]
I guess I shouldn't just remove functions without deprecation even if CRAN checks look good, these might still be used in internal organisations.

**Comment by pat-s** [comment]
> oh I didn't catch your package in revdep checks.

It's not on CRAN (for various reasons) so no worries therefore ;)

> Note that using with_abort() within tryCatch() does not create complete backtraces. Instead you could have used withCallingHandlers() (or the new try_fetch()).

Thanks! I did not implement this part of the package myself, hence I was not aware of possibly more safe approaches :)

> The replacement for with_abort() is global_handle() on the user side. If you need to do this on the package side, try something like this: r-lib/tidyselect@b17977d/R/conditions.R#L13-L24.
> Note that with rlang 1.0.1 (things are still in flux), you'll need to add parent = NA to let rlang know that you are rethrowing an error (this enables better backtrace handling). The NA means the rethrow is unchained. More documentation to come.

Sounds helpful, thanks! Will tryout later throughout the day hopefully.

> I guess I shouldn't just remove functions without deprecation even if CRAN checks look good, these might still be used in internal organisations.

I guess this is mainly a problem for pkgs which are used so heavily by others like `rlang` - and then it becomes complicated to catch pkgs not on CRAN. Not pushing a pkg to CRAN is something which increases judging from my stomach feeling, especially with projects like R-universe.

**Comment by pat-s** [comment]
Thanks, the suggested replacement worked 🎉
