### ISSUE TITLE
as_label converting to `list(...)`

### ISSUE THREAD

**Issue by xiaodaigh** [r-lib/rlang#1355]
I am getting this weird error

```rlang::as_label(quote(list(length_df.chunk_agg.disk.frame(Sepal.Width/Sepal.Width + 2))))```

gives

`list(...)`

![image](https://user-images.githubusercontent.com/4497189/151790261-57fc7604-c881-4476-a6ed-6b505733c4e5.png)

where if i get "list(...)" as the result of running rlang::as_label

Contained in the zip is the .rds file. It's not easy creating a MWE since I'ved tried but it doesn't work. But I've screenshotted it and showed where it happens.

[tmp.zip](https://github.com/r-lib/rlang/files/7970485/tmp.zip)

**Comment by lionel-** [comment]
What output are you expecting?

**Comment by xiaodaigh** [comment]
I checked the source, it might be the intended behaviour, but I was expected "list(length_df.chunk_agg.disk.frame(Sepal.Width/Sepal.Width + 2))"
