### ISSUE TITLE
cli snapshots need update again

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/rlang#1365]
cli 3.2.0 on CRAN breaks the snapshot tests here, e.g.

```
 [9] "  <ansi_string>"           - "  <cli_ansi_string>"       [9]   
```

`ansi_string` class is now `cli_ansi_string`:

https://github.com/r-lib/cli/blob/e02b8e995561d405f467bbcfe62b03e2d4a1a98b/R/ansiex.R#L5

**Comment by lionel-** [comment]
How did you discover this? Are running continuous integration on rlang with the `CI` or `NOT_CRAN` envvar set?

Workflow-wise, it doesn't seem like snapshot breakages on a dev version warrant opening issues, or even fixing until the developer looks at the package again.

**Comment by MichaelChirico** [comment]
the breakage is on the CRAN version. we are trying out NOT_CRAN in our tests yes.

**Comment by lionel-** [comment]
Is it necessary to set `NOT_CRAN`? The thing is that snapshot failures are not breakages per se. Snapshots are merely meant to monitor the evolution of output over time. I wasn't expecting another organisation to set `NOT_CRAN`.

**Comment by MichaelChirico** [comment]
Realizing that the `cli` update came after the `rlang` update (I think when I filed I thought `rlang`'s snapshots were already broken when pushed to CRAN, but not so).

Are snapshot updates part of your regular CRAN release flow?

(closing for now, Q is for curiosity/edification)

**Comment by lionel-** [comment]
They are part of the development workflow rather than the release workflow. When I come back to a package (perhaps only for a quick change) and see snapshot failures, I inspect the diffs in case there is any unwanted changes. If everything is in order, I update, commit, and push.

**Comment by lionel-** [comment]
Fixed in https://github.com/r-lib/rlang/commit/7b0d33c82ad8e7c1981423dc9754a3372d88d386
