### ISSUE TITLE
recent update cli  breaks shiny app on R 4.0.3

### ISSUE THREAD

**Issue by hugokoopmans** [r-lib/rlang#1367]
Hi Guys, not sure if this is appropriate but I have an issue on my Rshiny server  that still runs R 4.0.3 when updating to a recent version of cli.

    Error : 'format_warning' is not an exported object from 'namespace:cli'

Details on SO https://stackoverflow.com/questions/71179648/r-shiny-app-deployed-on-r-4-0-3-fails-but-works-on-4-1-2-package-dependencies

Please advise.

**Comment by lionel-** [comment]
hmm no that's the correct version for `format_warning()`, 2.5.0. The error probably comes from somewhere in rlang anyway, I'll take a closer look. See also https://github.com/tidyverse/dplyr/issues/6189
