### ISSUE TITLE
Suggested enhancement to `rlang_backtrace_on_error`

### ISSUE THREAD

**Issue by OfekShilon** [r-lib/rlang#1375]
(1) Thank you for (another) great library!
(2) I'm currently used to working with `options(error=recover)`, and `browser()` my way interactively into some function on the stack (==tree). Maybe it is possible to enjoy `rlang_backtrace_on_error=branch` with this workflow, and have a "Selection:" menu pop up which would select an environment to browse into, from this culled function tree?

**Comment by lionel-** [comment]
Hello, thanks for the suggestion.

We may offer this feature in the future but there is no plan to implement it in the short term.
