### ISSUE TITLE
dots-ellipsis.R functions showing as deprecated

### ISSUE THREAD

**Issue by TimTaylor** [r-lib/rlang#1380]
The check functions showing in [dots-ellipsis](https://github.com/r-lib/rlang/blob/main/R/dots-ellipsis.R) currently show as deprecated. Is this a mistake?

**Comment by lionel-** [comment]
I don't think that is the case? Can you show me please?

**Comment by TimTaylor** [comment]
https://github.com/r-lib/rlang/blob/22fe9e9d729d562fcfd580c7a350f56d7a864639/R/dots-ellipsis.R#L10

**Comment by TimTaylor** [comment]
I'm so sorry.  Need more coffee
