### ISSUE TITLE
Incorrect work caller_call in pipelines

### ISSUE THREAD

**Issue by avraam-inside** [r-lib/rlang#1383]
Case 1:
```r
test_function_2 <- function(val_any) {rlang::caller_call() %>% as.character() %>% .[1] %>% return()}

test_function_1_frame <- function() {
    
    val_any <- '/home/admin'
    
    val_ret_1 <- val_any %>% test_function_2()
    val_ret_2 <- test_function_2(val_any)
    
    list(
        val_ret_1 = val_any %>% test_function_2(),
        val_ret_2 = test_function_2(val_any)
    ) %>% 
    return()
}
```

From the code above we get this answer:
![image](https://user-images.githubusercontent.com/52919010/160206251-84c75e38-43db-458b-8b93-a35f6604df40.png)

Case 2: But at the same time, caller_env works correctly:
```r
test_function_2_cal <- function() {rlang::caller_env() %>% rlang::env_label() %>% return()}

test_function_1_cur <- function() {
    
    list(
        val_ret_cur = rlang::current_env() %>% rlang::env_label(),
        val_ret_cal = test_function_2_cal()
    ) %>% 
    return()
}
```
![image](https://user-images.githubusercontent.com/52919010/160206476-dd723331-3fce-4449-bc58-2b35adcb0338.png)

Please fix caller_call, thanks

**Comment by lionel-** [comment]
There should be no expectation that stack inspection tools like `caller_call()` will work the same way in unpiped code than within `%>%` pipes. Also `return()` does not really work within `%>%` pipelines, only a trailing return is allowed by special-casing, for backward compatibility.

In general, we don't use much pipes in low level code (see the internals of our packages) and reserve it for data analysis.
