### ISSUE TITLE
Question: how to evaluate expressions that can be evaluated and leave unevaluated those that can't?

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/rlang#1384]
Is it possible to automatically evaluate those defused expressions that contain symbols that can be resolved, and leave as defused those that can't?

Here's an example of what I am trying to achieve:

```R
library(rlang)
  
`%/.%` <- substitute
{x + x^2 + a + b} %/.% exprs(x = 3)
```

which returns:

```R
{
    3 + 3^2 + a + b
}
```

I would like a way to make it return `12 + a +  b`, so resolving the `x` to `3` and `x^2` to `3^2`, and then to `9`, and finally add `3 + 9`, i.e. `12`, but leave `a` and `b` unevaluated because they can't be looked up in the current environment.

Is this possible?

I am drawing inspiration from the first example from Mathematica documentation here: https://reference.wolfram.com/language/ref/Rule.html.

BTW: I couldn't run reprex on this example: https://github.com/tidyverse/reprex/issues/412.

The motivation for my question is really just to learn NSE with `{rlang}` at this point.

EDIT: Now that I am thinking, I am guessing this is not possible... The notion of what can and can't be evaluated cannot be determined without actually attempting to evaluate the expressions, right?

**Comment by lionel-** [comment]
You basically need to write your own interpreter of R code, descending the AST and evaluating expressions as you go. There is no rlang-specific tools for this. See also tidyselect for an example of a custom interpreter. This is not a trivial project though.

**Comment by ramiromagno** [comment]
Okay @lionel- , thanks for your comment.
