### ISSUE TITLE
Extract data-mask data as list

### ISSUE THREAD

**Issue by anthonynorth** [r-lib/rlang#1385]
Is there support for extracting data from a data-mask as an object / list? As if  a `<pronoun>` supported `as.list()`. How I'm currently handling this is via `rlang::env_parent(mask)` -- I don't need to walk the environment tree in my use-case.

If this isn't supported, are you open to adding a utility for it? Something like the following (as a concept):
```r
as.list.rlang_data_pronoun <- function(x, ...) {
  mask <- .subset2(x, 1)

  Reduce(
    function(env, lst) utils::modifyList(lst, as.list(env)),
    env_parents(mask, mask$.top_env),
    init = list(),
    right = TRUE
  )
}
```

Edit: stop env search at `top_env`

**Comment by lionel-** [comment]
There is no support for keeping track of variables in a mask as that is application-specific. For instance dplyr keeps track of the list of variables in another data structure. If you need this functionality, you'll have to implement yourself currently and for the foreseeable future.

Note that there are subtleties to be aware of, e.g. the user may create variables in the mask through `<-`. Also `env_parents()` is not appropriate here, it'll overreach if the top of the mask inherit from something else than the global env.
