### ISSUE TITLE
Parent of warning doesn't get warning style

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#1387]
<img width="387" alt="Screen Shot 2022-04-05 at 08 15 02" src="https://user-images.githubusercontent.com/4196/161762089-60a959a6-6571-460a-8cbe-a2b3fd06dbac.png">

**Comment by lionel-** [comment]
What do you mean by warning style?

**Comment by hadley** [comment]
i.e. the error is in bold, which looks weird.
