### ISSUE TITLE
`enexprs()`/`enquos()` doesn't treat `:=` as an `=` when nested inside another function

### ISSUE THREAD

**Issue by markfairbanks** [r-lib/rlang#1389]
I'm trying to build a pipeable data.table call that supports tidy evaluation and ran into this. To be honest I'm not sure if this is supposed to work.

``` r
library(rlang)

datatable_dots <- function(...) {
  dots <- enexprs(...)
  dots
}

col <- expr(x)
datatable_dots(.(!!col := mean(!!col)))
#> [[1]]
#> .(`:=`(x, mean(x)))

# Expected
exprs(.(x = mean(x)))
#> [[1]]
#> .(x = mean(x))
```

**Comment by lionel-** [comment]
`:=` is currently only a feature of dynamic dots. It's possible we'll make it a feature of injection, but not in the short term.

**Comment by lionel-** [comment]
I forgot to mention that you can work around this by splicing a named list:

```
expr(foo(!!!set_names(list(arg), nm)))
```
