### ISSUE TITLE
Should the second argument of `set_names()` be vectorised?

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#1391]
I found this a little surprising:

``` r
library(rlang)

x <- c(a = 1, b = 2, c = 3)
x |> set_names("x")
#> x x x 
#> 1 2 3
```

<sup>Created on 2022-04-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lionel-** [comment]
We discussed and implemented this a little while ago. This is handy to label groups of vectors, or to specify a bullet name.
