### ISSUE TITLE
could trace_back() better annotate functions "hidden" in closures?

### ISSUE THREAD

**Issue by kevinushey** [r-lib/rlang#1399]
For example, consider the following:

```
library(rlang)
trace(getOption, quote(print(rlang::trace_back())))
local({ rlang:::defer(42) })
```

I see:

```
Tracing getOption("knitr.in.progress") on entry 
     ▆
  1. ├─base::local(...)
  2. │ └─base::eval.parent(substitute(eval(quote(expr), envir)))
  3. │   └─base::eval(expr, p)
  4. │     └─base::eval(expr, p)
  5. └─base::eval(...)
  6.   └─base::eval(...)
  7.     └─rlang:::defer(42)
  8.       └─rlang add_handler(...)
  9.         └─rlang exit_frame(envir, frames, calls)
 10.           └─rlang in_knitr(envir)
 11.             └─rlang knitr_in_progress()
 12.               ├─base::isTRUE(getOption("knitr.in.progress"))
 13.               └─base::getOption("knitr.in.progress")
```

The "internal" functions like `in_knitr` and `knitr_in_progress` are marked as part of the `rlang` namespace, but IMHO it could be made more explicit that those are part of a separate internal closure somehow.

For what it's worth, this was prompted by me reading that output and thinking I would've been able to reference those functions via `rlang:::in_knitr`, but that failed since they're really in `defer()`, e.g. you could find them in `environment(rlang:::defer)$in_knitr`)

(feel free to close if you feel this is too narrow, since this pattern shouldn't be especially common)

**Comment by lionel-** [comment]
The current display is a compromise between indicating the package to which a local function belongs (which is very useful) and terseness to avoid distracting too much from the actual function call. I'd be happy to improve it. Do you have suggestions?

**Comment by kevinushey** [comment]
Throwing out some potential options...

```
# special delimiter
rlang^add_handler(...)
rlang#add_handler(...)

# annotate package name in some way
(rlang) add_handler(...)
(^rlang) add_handler(...)

# or, if we wanted to mention the parent function name
# (use `$$` since `rlang::defer$add_handler()` wouldn't actually be valid R code here)
rlang::defer$$add_handler()
```

I gravitate towards `^` as `rlang` is the environment "above" the environment hosting the function, but I'm not sure if that will be apparent or meaningful for others.

**Comment by lionel-** [comment]
I think delimiters like `^`, `#` and `$$` have two problems. First as you said the meaning will not be obvious to users. And second because they are heavy on the typography, they don't create enough separation between the package and the function call, making it harder to skim through the backtrace.

I'm not sure the parentheses are much of an improvement. I think that will make the package much more conspicuous in the case of local functions, which will unnecessarily divert the eye.

We had `::::` before but we changed it to a blank space as this is not a real operator and we didn't want people to think they can run the code to inspect the function. I think I'd still prefer that option if we have to use a fake operator.

Sorry that's a complex issue :)

**Comment by lionel-** [comment]
How about this:

```
     ▆
  1. ├─base::local(...)
  2. │ └─base::eval.parent(substitute(eval(quote(expr), envir)))
  3. │   └─base::eval(expr, p)
  4. │     └─base::eval(expr, p)
  5. └─base::eval(...)
  6.   └─base::eval(...)
  7.     └─rlang:::defer(42)
  8.       └─rlang (local) add_handler(...)
  9.         └─rlang (local) exit_frame(envir, frames, calls)
 10.           └─rlang (local) in_knitr(envir)
 11.             └─rlang (local) knitr_in_progress()
 12.               ├─base::isTRUE(getOption("knitr.in.progress"))
 13.               └─base::getOption("knitr.in.progress")
```

**Comment by kevinushey** [comment]
Belatedly here to say I like this treatment. Thanks!
