### ISSUE TITLE
Can check_installed() be used inside tryCatch()?

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/rlang#1402]
I hoped the following code ignores all errors yet asks users to install `noSuchPackage` if it's not installed. Are there anyway to make this work? I guess the answer is probably no because `check_installed()` somehow uses the mechanism of `tryCatch()` behind the scene, but want to confirm (I read the code, but I couldn't understand what's happening).

``` r
tryCatch(
  rlang::check_installed("noSuchPackage"),
  error = \(e) invisible(NULL)
)
```

The context is we see this problem in ggplot2:

https://github.com/tidyverse/ggplot2/pull/4845

**Comment by lionel-** [comment]
We could add a `fallback` argument to complement `action`.

**Comment by lionel-** [comment]
As discussed in the ggplot2 issue, we should not signal `"error"` condition in the restart mechanism of `check_installed()`. This way it will work in `tryCatch()` as expected.
