### ISSUE TITLE
Error chaining errors

### ISSUE THREAD

**Issue by epruesse** [r-lib/rlang#1405]
```R
    tryCatch({
        message("before")
        rlang::abort("test")
    }, error = function(err) {
        message("in handler")
        rlang::abort("bla", parent = err)
    })
```

leads to 

```R
before
in handler
Error in frames[[parents[[setup_loc]]]] : 
  attempt to select less than one element in integerOneIndex
```

Setting `parent = NA` gives me the same error. Am I missing something here?

**Comment by lionel-** [comment]
This looks like a bug in rlang.

By the way `tryCatch()` has serious shortcomings for rethrowing errors, you should use `withCallingHandlers()` or `try_fetch()`.

**Comment by lionel-** [comment]
It looks like this is a bug that only happens during backtrace creation when chaining an error directly in the console.

So you can wrap in a function to solve this (here using `try_fetch()`):

```r
f <- function() {
  try_fetch({
    message("before")
    rlang::abort("test")
  }, error = function(err) {
    message("in handler")
    rlang::abort("bla", parent = err)
  })
}

f()
```

**Comment by epruesse** [comment]
Ah, thank you. I'll switch to `try_fetch()`. In my initial reading, it looked like `try_fetch()` was meant for calling external C API, not as a replacement for `tryCatch()`. If I read it right, I'd have `zap()` as the equivalent to Python `raise` and `abort(msg, type, parent=err)` as equivalent to Python `raise type(msg) from err`.

W.r.t. bug, I suppose documenting that `abort(parent=...)` requires being below top level frame would suffice if fixing adds complexity useless outside of simply testing. (Plenty of tidyverse things don't seem to work at top level)
