### ISSUE TITLE
`check_installed()` doesn't recognize a `load_all()`'d package as installed

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/rlang#1413]
```r
> rlang::check_installed("hardhat")
> devtools::load_all(".")
ℹ Loading hardhat
> rlang::check_installed("hardhat")
ℹ The package `hardhat` is required.
✖ Would you like to install it?

1: Yes
2: No
```

This comes up in a test for hardhat. I have a `create_modeling_package()` function that is modeled after usethis, it creates a new package and calls `use_package("hardhat", type = "Imports")` to set up the description file of that package. `use_package()` eventually calls `check_installed("hardhat")` and this is failing in my test for `create_modeling_package()` now.

**Comment by DavisVaughan** [comment]
Oh it is this new commit to fix #1378 

https://github.com/r-lib/rlang/commit/5fcde82f783e7618a0504ba81fb0655911e16d81

The `env_is_locked()` bit is problematic here (hardhat's env isn't locked while running tests?)

**Comment by DavisVaughan** [comment]
Ah ok so I was surprised that `load_all()` wasn't sealing the namespace, but it seems like this recent commit in dev pkgload _does_ seal the namespace. https://github.com/r-lib/pkgload/commit/29cc79a4fc40dbc6f32c44d8ff655d9a146857c1

So I think we'd need a pkgload release before the next rlang release for this to be compatible with previous behavior.

```r
# pak::pak(c("r-lib/pkgload", "r-lib/rlang"))

> rlang::is_installed("hardhat")
[1] TRUE
> devtools::load_all(".")
ℹ Loading hardhat
> rlang::is_installed("hardhat")
[1] TRUE
```

**Comment by lionel-** [comment]
I've started the release process of pkgload.
