### ISSUE TITLE
Find the OO system used for an object

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#1426]
Something like this:

```R
obj_oo_type <- function(x) {
  if (is.object(x)) {
    if (inherits(x, "R7_object")) {
      "R7"
    } else if (inherits(x, "R6")) {
      "R6"
    } else if (isS4(x)) {
      "S4"
    } else {
      "S3"
    }
  } else {
    "base"
  }
}
```

This might possibly live in shim file, but that partly depends on the result of https://github.com/r-lib/cli/issues/463 and https://github.com/r-lib/vctrs/issues/139 — I think we need to host a consistent way of describing types somewhere centrally (either in rlang or maybe in a new package).

**Comment by lionel-** [comment]
Maybe we should add this to `compat-friendly-type.R`?

**Comment by hadley** [comment]
Yeah, that's probably a reasonable place for now. 

I can't quite figure if there's enough here for a separate package or not. When you consider the full scope of abbreviated vs full vs user facing type names, there is potentially a lot of code that we'd want to use in a lot of places.
