### ISSUE TITLE
Require rlang 1.0.3 but am stuck with windows binary rlang 1.0.2

### ISSUE THREAD

**Issue by DWJ27** [r-lib/rlang#1431]
Hi,

I'm currently setting up a new computer (windows) and downloading the required packages.

To download some of the required packages I'm being told rlang 1.0.3 is required, but I only have access to rlang 1.0.2.

Not a 100% how this works, but I see rlang has just been updated recently. Is there a certain amount of time before a binary version of an update becomes available?

**Comment by lionel-** [comment]
Yes it takes a few days before a binary version is available. You could install Rtools and build from source if you need it right away.

But there is nothing that should "require" rlang 1.0.3. Maybe try `install.packages("rlang", type = "binary")` to install the older version from source.

**Comment by DavisVaughan** [comment]
> there is nothing that should "require" rlang 1.0.3

The new pkgload release does, right?

**Comment by lionel-** [comment]
yes this is discussed in the other thread.

**Comment by lionel-** [comment]
rlang is now built for Windows
