### ISSUE TITLE
`srcref = TRUE` arg for `new_function()`

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/rlang#1436]
It would be nice if `new_function()` could provide some control on the srcref, e.g. `srcref = TRUE` would be the default and keep current behaviour (consistent with `as.function()` too), `srcref = FALSE` would recursively remove the srcref related attributes.

With the current implementation I cannot easily reproduce the code to create an existing function without a srcref : 

Here's an attempt to recreate `stats::ave()`

``` r
args_ <- alist(x =, ... =, FUN = mean)
body_ <- quote({
  if (missing(...)) 
    x[] <- FUN(x)
  else {
    g <- interaction(...)
    split(x, g) <- lapply(split(x, g), FUN)
  }
  x
})
env_ <- asNamespace("stats")

waldo::compare(
  rlang::new_function(args_, body_, env_),
  ave,
  ignore_srcref = FALSE
)
#> `attr(body(old), 'srcfile')` is an S3 object of class <srcfilecopy/srcfile>, an environment
#> `attr(body(new), 'srcfile')` is absent
#> 
#> `attr(body(old), 'srcref')` is a list
#> `attr(body(new), 'srcref')` is absent
#> 
#> `attr(body(old), 'wholeSrcref')` is an S3 object of class <srcref>, an integer vector
#> `attr(body(new), 'wholeSrcref')` is absent
#> 
#> `attr(body(old)[[2]][[4]], 'srcfile')` is an S3 object of class <srcfilecopy/srcfile>, an environment
#> `attr(body(new)[[2]][[4]], 'srcfile')` is absent
#> 
#> `attr(body(old)[[2]][[4]], 'srcref')` is a list
#> `attr(body(new)[[2]][[4]], 'srcref')` is absent
#> 
#> `attr(body(old)[[2]][[4]], 'wholeSrcref')` is an S3 object of class <srcref>, an integer vector
#> `attr(body(new)[[2]][[4]], 'wholeSrcref')` is absent
```

<sup>Created on 2022-07-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Note that  `identical(rlang::new_function(args_, body_, env_), ave)` is `FALSE`, I believe the default `ignore.srcref = TRUE` probably applies only on the outer layer.

**Comment by lionel-** [comment]
You can call `zap_srcref()` to recursively remove the srcrefs.
