### ISSUE TITLE
has_crayon checks consume up to 20% of run time on a script running for 2.5min

### ISSUE THREAD

**Issue by smarr** [r-lib/rlang#1444]
Dear rlang maintainers:

In search for optimization potential in my R reporting scripts, I noticed that `has_crayon` and corresponding checks are really high in the profiles.

After basically removing the check (with the following hack https://github.com/smarr/rlang/commit/394cb8869e037951481f1bf8ecd6404925dab540), run-time of the scripts reduces anywhere between 10-20%.

These scripts do not benefit from crayon, since they just generate some files, but don't actually report anything on the console.

I suspect a key culprit is using `has_crayon()` as default value here:

https://github.com/r-lib/rlang/blob/main/R/quo.R#L572-L574

Would it make sense to cache the result of `has_crayon()` and use the cached value subsequently?

Thanks!

**Comment by hadley** [comment]
Would you mind providing a simple reprex that illustrates that?

**Comment by smarr** [comment]
Sorry, I am not quite following. What's reprex, and what does "that" refer to exactly? The performance overhead?

I haven't gone through the motions of creating a reproducible isolated example, but the following should demonstrate the performance gains:

```bash
git clone https://github.com/smarr/ReBenchDB
cd ReBenchDB
wget https://rebench.stefan-marr.de/static/exp-data/TruffleSOM-1907.qs
wget https://rebench.stefan-marr.de/static/exp-data/TruffleSOM-1908.qs
./render-report.sh TruffleSOM-1907.qs TruffleSOM-1908.qs
```

Testing that on my local machine with the baseline, unmodified rlang version:

```
~/tmp/ReBenchDB$ ./render-report.sh TruffleSOM-1907.qs TruffleSOM-1908.qs
Opening  test.html
Run time of Report: 1.62 mins
(took 0h:01m:39s)
~/tmp/ReBenchDB$ ./render-report.sh TruffleSOM-1907.qs TruffleSOM-1908.qs
Opening  test.html
Run time of Report: 1.64 mins
(took 0h:01m:41s)
~/tmp/ReBenchDB$ ./render-report.sh TruffleSOM-1907.qs TruffleSOM-1908.qs
Opening  test.html
Run time of Report: 1.63 mins
(took 0h:01m:40s)
```

After completely removing the check, as in the mentioned hack:

```
~/tmp/ReBenchDB$ ./render-report.sh TruffleSOM-1907.qs TruffleSOM-1908.qs
Opening  test.html
Run time of Report: 1.40 mins
(took 0h:01m:26s)
~/tmp/ReBenchDB$ ./render-report.sh TruffleSOM-1907.qs TruffleSOM-1908.qs
Opening  test.html
Run time of Report: 1.40 mins
(took 0h:01m:26s)
~/tmp/ReBenchDB$ ./render-report.sh TruffleSOM-1907.qs TruffleSOM-1908.qs
Opening  test.html
Run time of Report: 1.40 mins
(took 0h:01m:26s)
```

And, just for completeness, caching the result using an environment: https://github.com/smarr/rlang/commit/466fe7d87a47428cee45e9e346922b3a2bc374ba
[I tried evaluating it on package load, but that change failed to install]


```
!> ~/tmp/ReBenchDB$ ./render-report.sh TruffleSOM-1907.qs TruffleSOM-1908.qs
Opening  test.html
Run time of Report: 1.46 mins
(took 0h:01m:29s)
!> ~/tmp/ReBenchDB$ ./render-report.sh TruffleSOM-1907.qs TruffleSOM-1908.qs
Opening  test.html
Run time of Report: 1.45 mins
(took 0h:01m:29s)
!> ~/tmp/ReBenchDB$ ./render-report.sh TruffleSOM-1907.qs TruffleSOM-1908.qs
Opening  test.html
Run time of Report: 1.40 mins
(took 0h:01m:26s)
```

I don't really know, but naive me finds such performance cost for a feature that's not even used (colorful printing to a terminal), a bit surprising.
Would there be a way to check this perhaps on package load, and ideally just have different versions of the `red`, `blue`, ... functions depending on whether `has_crayon` is true?

**Comment by hadley** [comment]
Yes, that performance hit is undesirable and we'll certainly do something about it. But we can work on it faster if you can provide a small self contained reproducible example ([reprex](http://reprex.tidyverse.org/) for short) that allows us to see exactly where the problem is. You mentioned that you did profiling, so I was hoping you could supply a small example that showed `has_crayon()` taking up an inordinate amount of time.

**Comment by smarr** [comment]
The following profile might give you the necessary insights, [data.Rprof.zip](https://github.com/r-lib/rlang/files/9169643/data.Rprof.zip), though, I failed in my attempt to produce a smaller self-contained test case for the moment.

**Comment by lionel-** [comment]
This should now be better, but without a reprex I can't be sure i'll solve your problem.

**Comment by smarr** [comment]
I can confirm it's better, using the code from [above](https://github.com/r-lib/rlang/issues/1444#issuecomment-1191983206).

With rlang from before the change, i.e., at 330dfaf044966238e3acab8b3929ec6777e1770e, I get:

```
./render-report.sh tmp/TruffleSOM-1907.qs tmp/TruffleSOM-1908.qs;./render-report.sh tmp/TruffleSOM-1907.qs tmp/TruffleSOM-1908.qs; ./render-report.sh tmp/TruffleSOM-1907.qs tmp/TruffleSOM-1908.qs
Opening  test.html
Run time of Report: 1.37 mins
Opening  test.html
Run time of Report: 1.38 mins
Opening  test.html
Run time of Report: 1.36 mins
(took 0h:04m:11s)
```

After the change, i.e. at version bed63f3f715061483e6df4541306b7961814bbfe, I get:

```
./render-report.sh tmp/TruffleSOM-1907.qs tmp/TruffleSOM-1908.qs;./render-report.sh tmp/TruffleSOM-1907.qs tmp/TruffleSOM-1908.qs; ./render-report.sh tmp/TruffleSOM-1907.qs tmp/TruffleSOM-1908.qs
Opening  test.html
Run time of Report: 1.31 mins
Opening  test.html
Run time of Report: 1.31 mins
Opening  test.html
Run time of Report: 1.31 mins
(took 0h:04m:00s)
```

Though, that's still quite a bit of a difference compared to completely removing the option (as per https://github.com/smarr/rlang/commit/394cb8869e037951481f1bf8ecd6404925dab540):

```
./render-report.sh tmp/TruffleSOM-1907.qs tmp/TruffleSOM-1908.qs;./render-report.sh tmp/TruffleSOM-1907.qs tmp/TruffleSOM-1908.qs; ./render-report.sh tmp/TruffleSOM-1907.qs tmp/TruffleSOM-1908.qs
Opening  test.html
Run time of Report: 1.24 mins
Opening  test.html
Run time of Report: 1.24 mins
Opening  test.html
Run time of Report: 1.24 mins
(took 0h:03m:48s)
```
