### ISSUE TITLE
Concatenation of a quosure and a list of quosure is not interchangeable

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/rlang#1446]
Hi,

This is probably a quibbling corner case of minor importance but it seems that the concatenation of `quo()` and `quos()` depends on the order of the operation:

``` r
cols = rlang::quo(c(mpg, gear))
dots = rlang::quos(cyl, am)

class(cols)
#> [1] "quosure" "formula"
class(dots)
#> [1] "quosures" "list"
class(c(dots, cols))
#> [1] "quosures" "list"
class(c(cols, dots))
#> [1] "list"
```

<sup>Created on 2022-07-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

In the latter case, the `quosures` class is lost but I'm not sure that this class is important or if this can cause any trouble at all.

This is obviously caused by the absence of `rlang:::c.quosure()` but the result is a bit unexpected. Maybe `c.quosures()` could be aliased to `c.quosure()`?

**Comment by lionel-** [comment]
I'm pretty sure this should be an error in all cases so can you please use `c(list(quo), quos)` instead?
