### ISSUE TITLE
Should `arg_match()` handle `NULL`?

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#1451]
``` r
f <- function(x = NULL) (
  rlang::arg_match(x, letters)
)
f()
#> Error in `f()`:
#> ! `x` must be a character vector, not NULL.
```

<sup>Created on 2022-07-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

i.e. should this instead return `"a"`?

**Comment by lionel-** [comment]
Maybe it should take `allow_null = FALSE` as in the type checkers in the standalone file?

**Comment by hadley** [comment]
Why would it ever allow `NULL` though? Don't you expect it to always return a single string? 

...

Oh now I'm arguing with past Hadley, so maybe this isn't a good idea?

**Comment by lionel-** [comment]
I _think_ past Hadley's idea was that `NULL` represents the default, and so it should match the first value of the enum?

**Comment by hadley** [comment]
Maybe? Still seems a bit weird to present-me.

**Comment by lionel-** [comment]
ok let's close until future us have better ideas :)
