### ISSUE TITLE
last_error() sometimes fails with its own internal error

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/rlang#1456]
Hi,

Sometimes, `last_error()` fails with this error instead of outputting the real last error:

``` r
f = function(x){
  purrr::map(substitute(x), deparse)
}
# f(c(foo, bar))
f(foo)
#> Error in `purrr:::stop_bad_type()`:
#> ! `.x` must be a vector, not a symbol
#> Run `rlang::last_error()` to see where the error occurred.
rlang::last_error()
#> Error in `$<-.data.frame`(`*tmp*`, "call_text", value = c("global f(foo)",  : 
#> replacement has 3 rows, data has 2
```

This `purrr` call is the last code I tried that triggered this behavior, I'm not sure why this syntax is problematic while others are OK.

**Comment by lionel-** [comment]
ooh this is a bug we've tried to track down in the past, thanks for the reprex!
