### ISSUE TITLE
`arg_options()` for getting the possible values of an argument?

### ISSUE THREAD

**Issue by jameslairdsmith** [r-lib/rlang#1465]
It seems that it would sometimes be useful to capture the set of acceptable values for an argument. This would save you having to duplicate them in the function body. `match.arg()` provides us the value(s) actually selected, but not those that are available. Below is my attempt at an implementation. It felt a bit hack-y; there is probably a better way.

``` r
library(rlang)

arg_options <- function(x){
  eval(fn_fmls(caller_fn())[[englue("{{ x }}")]])
}

test_fun <- function(x = c("A", "B", "C"), y = c("X", "Y")){
  arg_options(x)
}

test_fun()
#> [1] "A" "B" "C"

test_fun2 <- function(x = c("A", "B", "C"), y = c("X", "Y")){
  arg_options(y)
}

test_fun2()
#> [1] "X" "Y"
```

<sup>Created on 2022-08-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lionel-** [comment]
Thanks for the suggestion. We don't plan to add something like that in rlang at the moment but I'll keep this in mind.
