### ISSUE TITLE
New tags on tidyverse/rlang repo

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#147]
I have removed the confusing lazyeval tags from the tidyverse/rlang repo. Also I have renamed `v0.1` to `v0.1.0`.

Could you please run `git pull --prune --tags` @hadley @krlmlr @jimhester 

To make sure the old tags don't get pushed accidentally. Also if you don't prune I don't know what will happen once we reach `v0.2.0` since that was an existing lazyeval tag.

**Comment by krlmlr** [comment]
I'm seeing:

```
> git tag | xargs git tag -d
Deleted tag 'v0.1.0' (was 38a9faf)
Deleted tag 'v0.1.1' (was 684221a)
Deleted tag 'v0.1.10' (was 0672321)
Deleted tag 'v0.1.9' (was 6dcbee9)
Deleted tag 'v0.2.0' (was 4aaadb3)
> git fetch --all --prune
Fetching origin
From git://github.com/hadley/rlang
 * [new tag]         v0.1.0     -> v0.1.0
 * [new tag]         v0.1.1     -> v0.1.1
Fetching lionel-
From git://github.com/lionel-/rlang
 * [new tag]         v0.1.10    -> v0.1.10
 * [new tag]         v0.1.9     -> v0.1.9
 * [new tag]         v0.2.0     -> v0.2.0
Fetching krlmlr
```

**Comment by lionel-** [comment]
oops, I have now remove the faulty tags from my remote.
