### ISSUE TITLE
is_expression() doesn't look at attributes of calls

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/rlang#1475]
From `?rlang::is_expression`:

> In rlang, an expression is the return type of parse_expr(), the set of objects 
> that can be obtained from parsing R code

``` r
x <- quote(a(1)(2))
attr(x[[1]], "foo") <- "bar"

# I'm ok with this
rlang::expr_deparse(x)
#> [1] "a(1)(2)"

# But then doesn't this mean this should be FALSE ?
rlang::is_expression(x)
#> [1] TRUE
```

<sup>Created on 2022-09-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

For context in S4 objects we can find calls with attributes.

**Comment by lionel-** [comment]
That makes sense. But this might be a bit tricky, need to be careful about srcref attributes created by the parser on some language objects, e.g. `{`.

**Comment by moodymudskipper** [comment]
Ah indeed good catch, I believe this implies that using current definition `quote({a})` is not an expression either. 
Maybe we could have `is_expression(x, ignore_attr = TRUE, ignore_srcref = TRUE)` , these are attributes we find in `Waldo::compare()`.
