### ISSUE TITLE
Calling `abort()` from an assignment operator or function

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#1478]
Is there a way to get a nice error call just like with the non-assignment version?

``` r
`[.foo` <- function(x, i, ...) {
  rlang::abort("Single bracket.")
}

`[<-.foo` <- function(x, i, value, ...) {
  rlang::abort("Single bracket assign.")
}

foo <- structure(1, class = "foo")

foo[1]
#> Error in `foo[1]`:
#> ! Single bracket.
foo[1] <- 2
#> Error in `[<-`:
#> ! Single bracket assign.
```

<sup>Created on 2022-09-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Perhaps something like:

```r
foo[1] <- 2
#> Error in `foo[1] <- 2`:
#> ! Single bracket assign.
```

This might improve error messages for tibble.

**Comment by lionel-** [comment]
I think the problem is: https://github.com/r-lib/rlang/issues/1369#issuecomment-1137418527

**Comment by lionel-** [comment]
It's true you can assume that the caller env will have the object bound to at least one binding, since that's the requirement for sub assignment. But you can't assume that it's bound to only a single binding, there might be multiple.

(By the way there is `rlang::obj_address()`)

**Comment by lionel-** [comment]
Also this won't support complex subassignments like `foo[[1]][[2]] <- bar` correctly.
