### ISSUE TITLE
Add ability to pass anonymous function to `check_installed(action = )`

### ISSUE THREAD

**Issue by olivroy** [r-lib/rlang#1480]
Hi,

would it be possible to support anonymous functiions in `check_installed()`

The ... in check_installed() must be empty, so it is not possible to pass additional parameters to the function

Some of my packages are hosted on private GitLab, which doesn't seem to be supported by pak. (the default install option)

```r
check_installed(
 "package",
  action = ~ remotes::install_gitlab(pkg, host = "mygitlab.com")
)
#> Error in `rlang::check_installed()`:
#> ! `action` must be `NULL` or a function, not a <formula> object.
``` 

In the doc, it is written that ... are used by `action`, but they must be empty.

This doesn't work either
```r
check_installed(
 "package",
  action = remotes::install_gitlab(pkg),
  host = "mygitlab.com"
)
#> Error in `rlang::check_installed()`:
#> ! `...` must be empty.
#> x Problematic argument:
#> * host = "mygitlab.com"
```

**Comment by lionel-** [comment]
We could do `as_function(action)`. However since purrr-style lambdas are superseded in favour of R lambdas, I'm not sure we'll want to add this functionality where it didn't exist.

So you can do either of these:

```r
# Requires R 4.0
action = \(pkg) remotes::install_gitlab(pkg, host = "mygitlab.com")

# No requirements
action = function(pkg) remotes::install_gitlab(pkg, host = "mygitlab.com")
```

**Comment by olivroy** [comment]
Thanks for the explanation 
This didn't work. I had to add 
```r
\(pkg, ...) remotes::install_gitlab(pkg, host = "mygitlab.com")
```
to make it work.

The error message was 
```r
Error in `rlang::check_installed()`:
! `action` must take a `...` argument.
```
Maybe saying 
```r
! The `action` function must take a `...` argument 
```
would be a clearer error message.
