### ISSUE TITLE
Consider `check_` functions

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#1481]
```R
library(rlang)

# Context:
# * user created scalars
# * normally typed directly in the function call
# * complementary to vctrs style checks
# * lives in rlang compat file

check_number <- function(x, 
                         min = NULL,
                         max = NULL,
                         allow_decimal = FALSE,
                         allow_missing = FALSE,
                         allow_infinite = FALSE,
                         allow_null = FALSE
                         )
  
  # Should this be inclusive or exclusive?
  if (!is.null(min) && x < min) {
    abort("`x` must be greater than {min}, not {x}")
  }
}

check_bool <- function(x, allow_missing = FALSE, allow_null = FALSE) {
}

check_string <- function(x, 
                         allow_empty = FALSE,
                         allow_missing = FALSE,
                         allow_null = FALSE,
                         ) {
  
}

check_enum <- function(x, values = NULL) {
  
}
```

**Comment by jennybc** [comment]
I just pulled `compat-types-check.R` and `combat-obj-type.R` into a gargle branch and this spurred 1 question and 1 suggestion.

Question: gargle already imports rlang and, indeed, imports the entire rlang namespace. I don't understand why I need to bring in a compat file to get rlang's checkers, for example. Why wouldn't these just be exported for other packages to use? I associate compat files with the desire to avoid a dependency.

Observation: Consider the definition of `check_string()` at the time I'm writing this:

``` r
check_string <- function(x,
                         ...,
                         what = "a single string",
                         arg = caller_arg(x),
                         call = caller_env()) {
  if (!is_string(x)) {
    stop_input_type(x, what, ..., arg = arg, call = call)
  }
}
```

If used like so:

``` r
gargle_oauth_client <- function(
    id,
    ...
) {
  check_string(id)
  ...
}
```

I see

``` r
gargle_oauth_client()
#> Error in is_string(x): argument "id" is missing, with no default
```

I.e. the error comes from the `is_string()` call in `check_string()` and we never make it to the intended call to `stop_input_type()` and as a result we also don't report the user-facing caller (`gargle_oauth_client()`).

I think I expected `check_string()` to effectively act like `if (missing(x) || !is_string(x)) { ... }`, which is presumably equivalent to @hadley's suggestion re: `allow_missing = FALSE` and yields:

``` r
gargle_oauth_client()
#> Error in `gargle_oauth_client()`:
#> ! `id` must be a single string, not absent.

#> Backtrace:
#>     ▆
#>  1. └─gargle::gargle_oauth_client(id = <empty>)
#>  2.   └─gargle:::check_string(id) at gargle/R/gargle-oauth-client.R:53:2
#>  3.     └─gargle:::stop_input_type(x, what, ..., arg = arg, call = call) at gargle/R/compat-types-check.R:36:4
#>  4.       └─rlang::abort(message, ..., call = call, arg = arg) at gargle/R/compat-obj-type.R:230:2
```

**Comment by lionel-** [comment]
> Question: gargle already imports rlang and, indeed, imports the entire rlang namespace. I don't understand why I need to bring in a compat file to get rlang's checkers, for example. Why wouldn't these just be exported for other packages to use? I associate compat files with the desire to avoid a dependency.

Compat files are also for experimental APIs. These checking functions might even end up in another package eventually.

Regarding the absent argument error, I still hope that my patch to fix the error call will make it in the next version of R. In the meantime you can us `check_required()` before calling `check_string()`.

The `allow_missing` argument is about allowing `NA` values. We could add another argument to essentially ask the checker to call `check_required()`, but I'm not sure we want to do that.

**Comment by hadley** [comment]
For now, what's the downside of adding `missing()` to the check?



``` r
library(rlang)
check_string <- function(x,
                         ...,
                         what = "a single string",
                         arg = caller_arg(x),
                         call = caller_env()) {
  if (missing(x) || !is_string(x)) {
    rlang:::stop_input_type(x, what, ..., arg = arg, call = call)
  }
}

f <- function(x) {
  check_string(x)  
}

f()
#> Error in `f()`:
#> ! `x` must be a single string, not absent.
```

<sup>Created on 2022-09-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jennybc** [comment]
> Compat files are also for experimental APIs. These checking functions might even end up in another package eventually.

I see. I do really like the idea of having shared checkers like this, so I hope they end up being exported somewhere and rlang feels natural to me.

**Comment by lionel-** [comment]
> For now, what's the downside of adding missing() to the check

Good idea, I didn't know `stop_input_type()` handled missing arguments.

**Comment by lionel-** [comment]
@jennybc We now handle missing arguments in the checker functions.
