### ISSUE TITLE
DLL version does not correspond to the package version

### ISSUE THREAD

**Issue by stephanJG** [r-lib/rlang#1483]
I newly installed Rstudio and R on windows, but can not install the rlang package.
`Error: package or namespace load failed for ‘rlang’:
 .onLoad failed in loadNamespace() for 'rlang', details:
  call: NULL
  error: The rlang package is not properly installed.
The DLL version does not correspond to the package version.
Please update rlang to the latest version.
Updating packages on Windows requires precautions:
  <https://github.com/jennybc/what-they-forgot/issues/62>`

I have tried installing from source/binary, removed everything, my .libPath is correct, shut down pc after remove.packages(), updated R/Rstudio/packages, .... tried all I could find in forums. I also checked the DLL version via 

```
if(.Platform$OS.type == "windows") withAutoprint({
+     DLL.version(file.path(R.home("bin"), "R.dll"))
+     DLL.version(file.path(R.home(), "library/stats/libs", .Platform$r_arch, "stats.dll"))
+ })
> DLL.version(file.path(R.home("bin"), "R.dll"))
[1] "4.2.1  (2022-06-23)" "4.2.1  (2022-06-23)"
> DLL.version(file.path(R.home(), "library/stats/libs", .Platform$r_arch, "stats.dll"))
[1] "4.2.1  (2022-06-23)" "4.2.1  (2022-06-23)"

```
```
> sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_Europe.1252  LC_CTYPE=English_Europe.1252   
[3] LC_MONETARY=English_Europe.1252 LC_NUMERIC=C                   
[5] LC_TIME=English_Europe.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.1 tools_4.2.1   
```
RStudio 2021.09.1 Build 372

Any help would be highly appreciated.

**Comment by lionel-** [comment]
Can you try installing with `pak::pak()` to see if it fixes the problem please.

**Comment by stephanJG** [comment]
That gives
```
Error in pkg_env$.onLoad(dirname(pkg_dir), package) : 
  object 'clic_start_thread' not found
```

**Comment by lionel-** [comment]
Have you seen this before @gaborcsardi?

**Comment by gaborcsardi** [comment]
That looks like a broken pak installation, try reinstalling the binary from CRAN, in a clean session, or from here: https://github.com/r-lib/pak#arrow_down-installation

As for the original problem, do you have another R session open with rlang loaded? Do you load rlang or another package in your `.Rprofile`?

**Comment by stephanJG** [comment]
I had checked my `.Rprofile`, I now checked again. Its only the usual silenced stuff. I am not pre-loading via the profile anymore.

I dont think that is relevant but the installation was approved by my company and I had to install it as admin. But all is on the pc I am working on and looks normal (R, Rstudio installed in C:\R\R-4.2.1; C:\rtools42).

**Comment by stephanJG** [comment]
`install.packages("pak",source="binary")`
`install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s", .Platform$pkgType, R.Version()$os, R.Version()$arch))`

both same error for pak

**Comment by gaborcsardi** [comment]
So what's the full output of `install.packages("rlang")`? 

Can you install an older version of rlang? E.g. with 
```
install.packages(
  "https://cran.r-project.org/src/contrib/Archive/rlang/rlang_1.0.4.tar.gz",
  repos = NULL, 
  type = "source"
) 
```

**Comment by stephanJG** [comment]
```
> install.packages(
Warning message:
R graphics engine version 15 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed. 
+     "https://cran.r-project.org/src/contrib/Archive/rlang/rlang_1.0.4.tar.gz",
+     repos = NULL, 
+     type = "source"
+ )
Warning in install.packages :
  the 'wininet' method is deprecated for http:// and https:// URLs
trying URL 'https://cran.r-project.org/src/contrib/Archive/rlang/rlang_1.0.4.tar.gz'
Content type 'application/x-gzip' length 740971 bytes (723 KB)
downloaded 723 KB

* installing *source* package 'rlang' ...
** package 'rlang' successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc  -I"C:/R/R-42~1.1/include" -DNDEBUG -I./rlang/    -I"C:/R/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c capture.c -o capture.o
gcc  -I"C:/R/R-42~1.1/include" -DNDEBUG -I./rlang/    -I"C:/R/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c internal.c -o internal.o
g++  -std=gnu++11 -I"C:/R/R-42~1.1/include" -DNDEBUG -I./rlang/    -I"C:/R/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c rlang-rcc.cpp -o rlang-rcc.o
gcc  -I"C:/R/R-42~1.1/include" -DNDEBUG -I./rlang/    -I"C:/R/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c rlang.c -o rlang.o
gcc  -I"C:/R/R-42~1.1/include" -DNDEBUG -I./rlang/    -I"C:/R/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c version.c -o version.o
g++ -shared -s -static-libgcc -o rlang.dll tmp.def capture.o internal.o rlang-rcc.o rlang.o version.o -LC:/R/rtools42/x86_64-w64-mingw32.static.posix/lib/x64 -LC:/R/rtools42/x86_64-w64-mingw32.static.posix/lib -LC:/R/R-42~1.1/bin/x64 -lR
installing to C:/R/R-4.2.1/library/00LOCK-rlang/00new/rlang/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'rlang':
 .onLoad failed in loadNamespace() for 'rlang', details:
  call: NULL
  error: The rlang package is not properly installed.
The DLL version does not correspond to the package version.
Please update rlang to the latest version.
Updating packages on Windows requires precautions:
  <https://github.com/jennybc/what-they-forgot/issues/62>
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/R/R-4.2.1/library/rlang'
Warning in install.packages :
  installation of package ‘C:/Users/skbstjo/AppData/Local/Temp/RtmpKURPBb/downloaded_packages/rlang_1.0.4.tar.gz’ had non-zero exit status
```

**Comment by stephanJG** [comment]
Installing rlang_1.0.5.zip with Rstudio did not work either

**Comment by gaborcsardi** [comment]
Are you sure that no other R process is running? Can you look at task manager to see? 

Can you see if there is an rlang installation already in a library? Can you run `find.package("rlang")` and if rlang is installed, then can you remove it with `remove.packages("rlang")` first? After that can you check that indeed all rlang files are removed?

**Comment by stephanJG** [comment]
installing from RGui still gives `The DLL version does not correspond to the package version.`

**Comment by gaborcsardi** [comment]
So what is the full output of this, after restarting the R session?

```
loadedNamespaces()
install.packages("rlang", type = "binary")
```

**Comment by stephanJG** [comment]
```
> loadedNamespaces()
[1] "compiler"  "graphics"  "tools"     "utils"     "grDevices" "stats"     "datasets"  "methods"   "base"     
Warning message:
R graphics engine version 15 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed. 
> install.packages("rlang",type = "binary")
Warning in install.packages :
  the 'wininet' method is deprecated for http:// and https:// URLs
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/rlang_1.0.5.zip'
Content type 'application/zip' length 1572108 bytes (1.5 MB)
downloaded 1.5 MB

package ‘rlang’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\skbstjo\AppData\Local\Temp\RtmpqOo97p\downloaded_packages
```

**Comment by gaborcsardi** [comment]
That looks good, but I guess when you load the package it still fails?

To make totally sure that no frozen R process locks the DLL, you can run 
```
ps::ps_shared_lib_users(file.path(find.package("rlang"), "libs", "x64", "rlang"), "libs", "x64", "rlang.dll"))
```
and this should return an empty table.

The other possibility is that you are doing this as a regular user and only admin can remove the DLL file, so try installing rlang as admin, or cleanup the library as admin.

**Comment by stephanJG** [comment]
```
> ps::ps_shared_lib_users(file.path(find.package("rlang"), "libs", "x64", "rlang"), "libs", "x64", "rlang.dll")
Error: .onLoad failed in loadNamespace() for 'ps', details:
  call: fun(libname, pkgname)
  error: object 'ps__init' not found
```
I think it all has to do with the fact that I am not having admin right for my pc. I will do as you recommend and re-install with the admin.

**Comment by gaborcsardi** [comment]
It seems that your user is locked down and not allowed to load unsigned (?) DLLs. You can run R, so the R DLLs are allowed.

In any case this does not look like an issue with rlang.

**Comment by stephanJG** [comment]
The solution to this problem

Within my windows account the IT run Rstudio/R as administrator. I could install rlang. The lib path was to the within the admin account, however if I opened Rstudio/R normally under my account rlang was also installed and working. :-))))))
