### ISSUE TITLE
Export `rlang_abort()` from C

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#1484]
And possibly a variant where you can set the error call?

**Comment by lionel-** [comment]
We have `r_abort()`, `r_abort_call()`, and `r_abort_lazy_call()`. This all goes through an R-level call.

To get them, call `rlang:::use_rlang_c_library()` in your package and follow instructions (hopefully we haven't missed any). You can use functions from that library without switching your style (cf vctrs where old files still use the base API style).

**Comment by lionel-** [comment]
I recommend looking into `struct r_lazy` as well to flexibly represent calls as frame objects: `{ .x = frame, .env = r_null }` or symbols to evaluate in a frame: `{ .x = r_sym(".call"), .env = frame }`.

**Comment by hadley** [comment]
Why are these `r_*()` and not `rlang_*()`?

And I didn't get very far with `use_rlang_c_library()`:

```
> rlang:::use_rlang_c_library()
trying URL 'https://github.com/r-lib/rlang/archive/main.zip'
downloaded 990 KB

Error in `if (!fs::dir_exists(lib_path)) ...`:
! argument is of length zero
```

**Comment by lionel-** [comment]
I think just because `r_` is the prefix of the rlang library. We could make these `rlang_` since they wrap rlang features though.

**Comment by lionel-** [comment]
Closing this since we already export `abort()` as a C callable. We just don't have headers for it in `inst/` since the rlang lib is currently vendored.
