### ISSUE TITLE
`expr_text()` converting without inserting "\n"

### ISSUE THREAD

**Issue by Sciurus365** [r-lib/rlang#1489]
I would like to request a feature that let users choose if they want to have linebreaks when using `expr_text()`. I think it's helpful if there's a function that just turns expressions into strings without adding anything. These linebreaks are mainly for formatting the displayed output, but it's not a part of the class conversion itself and may lead to problems in some cases. 
Thanks for considering!

**Comment by lionel-** [comment]
You can use `as_label()` if you don't want linebreaks.

**Comment by Sciurus365** [comment]
> You can use `as_label()` if you don't want linebreaks.

Thanks @lionel- , but this also uncontrollably abbreviates the expression.
Maybe it's better to illustrate with the following example.

```r
rlang::expr(aaaa_bbbbbbb[t - 1] * aaaa_bbbbbbb[t - 2] * aaaa_bbbbbbb[t - 3]) %>% rlang::expr_text()
#> [1] "aaaa_bbbbbbb[t - 1] * aaaa_bbbbbbb[t - 2] * aaaa_bbbbbbb[t - \n    3]"
rlang::expr(aaaa_bbbbbbb[t - 1] * aaaa_bbbbbbb[t - 2] * aaaa_bbbbbbb[t - 3]) %>% rlang::as_label()
#> [1] "aaaa_bbbbbbb[t - 1] * aaaa_bbbbbbb[t - 2] * ..."

# desired:
#> [1] "aaaa_bbbbbbb[t - 1] * aaaa_bbbbbbb[t - 2] * aaaa_bbbbbbb[t - 3]"
```

**Comment by lionel-** [comment]
Sorry about these limitations. Unfortunately we are not planning to do more work on deparsing features in rlang, at least not in the short or medium term.

**Comment by Sciurus365** [comment]
> Sorry about these limitations. Unfortunately we are not planning to do more work on deparsing features in rlang, at least not in the short or medium term.

Oh okay, thanks for letting me know!

>
