### ISSUE TITLE
eval tidy error

### ISSUE THREAD

**Issue by madmonarch09** [r-lib/rlang#1498]
I keep getting the error 'Data' must be uniquely named but does not have names.
I am currently trying to run spaceNtime using a small subset of my data (about 10 lines). At the 4th step, I started getting the error about my data not having names/unique names but all data columns have a unique name. I tried inputting <make.unique>
 as well and it doesn't seem to do anything. 

> colnames(COUNT) <- make.unique(c("row", "cam", "datetime", "count", "cam_area"))
> colnames(EFFORT) <- make.unique(c("rows", "cam_ID", "start_datetime", "end_datetime", "area"))

I would appreciate any help/input on this in the simplest terms possible (I am a complete novice in this).
Here is the code output I was getting:

> ste_eh <- ste_build_eh(df, deploy, occ)
Error:
! `data` must be uniquely named but does not have
  names
Run `rlang::last_error()` to see where the error occurred.
rlang::last_error()
<error/rlang_error>
Error:
! `data` must be uniquely named but does not have
  names
---
Backtrace:
  1. spaceNtime::ste_build_eh(df, deploy, occ)
 12. rlang::abort(message = message)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/rlang_error>
Error:
! `data` must be uniquely named but does not have
  names
---
Backtrace:
     x
  1. +-spaceNtime::ste_build_eh(df, deploy, occ)
  2. | \-spaceNtime:::validate_df(df)
  3. |   \-... %>% verify(count >= 0)
  4. +-assertr::verify(., count >= 0)
  5. | \-base::isTRUE(attr(data, "assertr_data_defective"))
  6. +-assertr::verify(., is.numeric(count))
  7. | \-base::isTRUE(attr(data, "assertr_data_defective"))
  8. +-assertr::verify(., lubridate::is.POSIXct(datetime))
  9. | \-base::isTRUE(attr(data, "assertr_data_defective"))
 10. +-assertr::verify(., has_all_names("cam", "datetime", "count"))
 11. | \-rlang::eval_tidy(expr, data, parent.frame())
 12. \-rlang::abort(message = message)

**Comment by lionel-** [comment]
Hello. This error is unlikely to be caused by rlang. It's probably an issue in spaceNtime. You'll need to post a full (and minimal if possible) reprex if you'd like help, see https://www.tidyverse.org/help/.

**Comment by madmonarch09** [comment]
@lionel- Thank you for your reply, I will look into reprex.
