### ISSUE TITLE
`quo_squash()` doesn't always squash all quosures

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/rlang#1509]
``` r
library(rlang)

eq <- quo(`==`)
quo <- expr((!!eq)(1,2))
quo
#> (~`==`)(1, 2)

quo_squash(quo)
#> (~`==`)(1, 2)
```

I'm not sure, but I think there is some branch missing here about `node_car()`?
https://github.com/r-lib/rlang/blob/bed63f3f715061483e6df4541306b7961814bbfe/R/quo.R#L478

**Comment by lionel-** [comment]
yup it looks like it
