### ISSUE TITLE
Reimplement `zap_srcref()` in C

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#1513]
It's causing a bottleneck in large shiny apps.

**Comment by wch** [comment]
Just to add some data, here's a profvis flame graph showing how much time is spent in `zap_srcref` when a user connects to a large Shiny app. In this app, it's 640ms, and each user has to pay this price.

<img width="1255" alt="image (18)" src="https://user-images.githubusercontent.com/86978/213029910-171e329a-37f3-4233-82c0-5ca1dd3f305e.png">
