### ISSUE TITLE
Issues updating rlang in RStudio

### ISSUE THREAD

**Issue by seandres11** [r-lib/rlang#1515]
Hello! 

I have been having a hard time loading many packages that require rlang in R version 1.4.1 

When I load packages which depend on rlang (such at dplyr), the console tells me the following error:

Error: package or namespace load failed for ‘dplyr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘rlang’ 1.0.5 is already loaded, but >= 1.0.6 is required 

I have tried installing with 'dependencies=T' and restarting R, however the problem still persists. 

Please let me know if you know of any work arounds for this.

Cheers,
Sam

**Comment by lionel-** [comment]
What happens when you reinstall rlang?

Usually these problems occur on Windows because R can't replace DLLs of loaded packages on that OS. So whenever you update packages, you need to make sure:

- That there isn't any other opened sessions of R (RStudio, RGUI, R in the console, etc)
- That your RProfile doesn't load any packages automatically.

Then, start R and update the desired packages in the very first command.

**Comment by lionel-** [comment]
Try updating with https://github.com/r-lib/pak

**Comment by blueja5** [comment]
I am having the same problem going from 1.02 to 1.06. It seems that the binaries aren't available - is this right? I haven't used compilation tools and would ideally not start doing but not being able to update rlang is causing me a lot of problems with other packages? I am on a mac using 4.0.2

**Comment by blueja5** [comment]
I have also tried pak: 
pak::pkg_install("rlang")
✓ Loading metadata database ... done
                                                                           
→ Will update 1 package.
→ The package (742.51 kB) is cached.
+ rlang 1.0.2 → 1.0.6 👷🏻‍♂️🔧
? Do you want to continue (Y/n) y
ℹ No downloads are needed, 1 pkg (742.51 kB) is cached
ℹ Building rlang 1.0.6
Error: Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
Type .Last.error.trace to see where the error occurred

**Comment by lionel-** [comment]
I can see on the CRAN page that binaries have been built for all OSes: https://cran.r-project.org/web/packages/rlang/index.html

What repo are you using? Does your setup have any sort of restrictions?
