### ISSUE TITLE
How to use convert `check_dots_empty(action = signal)` to `check_dots_empty(error = ...)` ?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#1517]
The documentation and NEWS are suggesting that `action` is deprecated as of 1.0.0, but I haven't found a usage example with a coarse search. What did I miss?

**Comment by lionel-** [comment]
You just pass an error handler as `error` argument. It is passed to `try_fetch()` so just follow the link there for information and examples.

```r
check_dots_empty(error = function(cnd) {
  warning("foo")
  zap()
})
```

**Comment by krlmlr** [comment]
Thanks! I'll leave this open in case we want to improve the documentation.
