### ISSUE TITLE
Export `check_` functions?

### ISSUE THREAD

**Issue by arnaudgallou** [r-lib/rlang#1520]
Any chance to export the `check_` functions?

I'm working on a project and would like to perform argument checks. I'm ending up making similar functions and feel like reinventing the wheel. These functions are useful in my opinion.

**Comment by lionel-** [comment]
At some point they will be exported from here or elsewhere but not in the short term.

These functions are in a file that you can copy them in your project. This way we can make changes to the API or semantics without causing breakages in your package.

**Comment by arnaudgallou** [comment]
Sounds good, will make a copy of the functions in the meantime. Thanks.
