### ISSUE TITLE
should `{{ }}`work in `inject()` ? or fail elegantly ?

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/rlang#1524]
If I understand correctly the use cases, and I might not, `inject()` is meant to be used exclusively on functions that don't support  injection/defusion.

In that case `{{ }}` is useless in those if it inlines a quosure, since these functions cannot handle those.

``` r
fun <-function(x) {
  rlang::inject({{ x }} ~ a)
}

fun(y)
#> ~y ~ a
#> <environment: 0x11a132280>
```

The above might return `y ~ a` if we make `{{ }}` equivalent to `!!enexpr()`. This would be convenient but users might miss that environments are not considered and this would be problematic in cases where it matters, e.g. if we used `data.frame({{ x }})` in `fun()` and a local `y` was defined.

Another solution might be to fail explicitly and invite the user to use `!!exexpr(x)` if they need the expression, and that they might need `eval_tidy(enquo(x))` if they want the value.

**Comment by lionel-** [comment]
It's also used for functions that don't support implicit injection but that do support quosures. We have a use case in Shiny.
