### ISSUE TITLE
Behaviour of `list2()` contradicts the docs

### ISSUE THREAD

**Issue by jennybc** [r-lib/rlang#1525]
~I'm finding a few places where~ the behaviour of `list2()` contradicts what the documentation says.

---

This comes from one of the examples.

``` r
library(rlang)

fn <- function(data, ...) {
  list2(...)
}

# Empty arguments trigger an error by default OR DO THEY?
fn(, )
#> list()
```

---

I didn't find another contradiction.

But I guess I assumed that `list2()` is like calling `dots_list()` with all of its defaults. And that is not true, which is sort of confusing, since the finer details of what `list2()` does are not documented. So the only way to learn how `dots2()` behaves with respect to names, etc. is to conduct experiments or consult the source.

``` r
library(rlang)

fn_list2 <- function(...) {
  list2(...)
}

# acts like dots_list(.named = NULL), which is not the default
fn_list2(1, 2)
#> [[1]]
#> [1] 1
#> 
#> [[2]]
#> [1] 2
names(fn_list2(1, 2))
#> NULL

fn_dots_list <- function(...) {
  dots_list(...)
}

# we get default behaviour, which is dots_list(.named = FALSE)
fn_dots_list(1, 2)
#> [[1]]
#> [1] 1
#> 
#> [[2]]
#> [1] 2
names(fn_dots_list(1, 2))
#> [1] "" ""
```

I think it would be helpful to say that `list2()` is like calling `dots_list()` but with a non-default choice for `.named`.

``` r
# list2(...) is equivalent to
dots_list(
  ...,
  .named = NULL # !!! not the default !!!
  # default for everything else
)
```

**Comment by lionel-** [comment]
`list2()` and `dots_list()` behave the same by default. `fn(, )` didn't fail because the first empty argument was passed to `data` instead of `...`, and then there was only one missing argument in `...` which got trimmed out because of `.ignore_empty = "trailing"`.

I tweaked the documentation to make this part a little clearer.
