### ISSUE TITLE
More informative error in dynamic dots when LHS of `:=` is correct type but wrong size?

### ISSUE THREAD

**Issue by yjunechoe** [r-lib/rlang#1526]
Somewhat related to #1492, although I see that specific case will get resolved in `{glue}`.

Inside dynamic dots, if the LHS of `:=` is the correct type (string or symbol) but has size > 1, it currently errors with ``The LHS of `:=` must be a string or a symbol``:

```
library(rlang)

len1 <- "A"
len2 <- c("A", "B")

list2(!!len1 := 1)
#> $A
#> [1] 1
list2(!!len2 := 1)
#> Error in `list2()`:
#> ! The LHS of `:=` must be a string or a symbol
```

In cases where the user gets the type right but the length wrong, the intended takeaway here is the number mismatch ("**a** string or **a** symbol") but I wonder if that's too subtle and gets lost on users reading this error. Critically, I think the issue is compounded by the fact that there's no formal distinction between "string (scalar)" vs. "character (vector)" in R, so users who use "string" and "character" interchangeably might read the error as "LHS needs to be a character (vector)" which would be confusing.

Tidyverse is generally very helpful at pointing out size mismatches in error messages, and I wonder whether the error in these cases can be ``The LHS of `:=` must have size 1, not size 2``. Or if it's too complicated to do this without forcing the promise, maybe the generic error message can be augmented to emphasize the length-1 constraint a bit better, something like ``The LHS of `:=` must be a string or a symbol of size 1`` or ``The LHS of `:=` must have size 1 and be of type string or symbol``?

I feel that the error could use this extra emphasis on size because users could get stuck interpreting the error as signaling that the LHS is of incorrect type, like a function, since those cases also share the same error message (where the intended emphasis here is "a **string** or a **symbol**"):

```
list2(!!mean := 1)
#> Error in `list2()`:
#> ! The LHS of `:=` must be a string or a symbol
```

Just to add my personal experience with this: I thought `:=` could take a multi-length vector in the LHS like in data.table's `dt[, (len2) := 1]`, which doesn't work for `dplyr::mutate(df, len2 := 1)` . It took a while for me to parse the error message with emphasis on "a".

```
library(dplyr, warn.conflicts = FALSE)
df <- tibble(x = 1:3)
new_cols <- c("y", "z")

df |> 
  mutate(!!new_cols := 0)
#> Error in `quos()`:
#> ! The LHS of `:=` must be a string or a symbol
```

Thanks!

**Comment by lionel-** [comment]
Thanks this is now:

```r
list2(!!c("A", "b") := 1)
#> Error in `list2()`:
#> ! The LHS of `:=` must be a string, not a character vector.
```
