### ISSUE TITLE
Improvements to `check_dots_used()` error message

### ISSUE THREAD

**Issue by krivit** [r-lib/rlang#1532]
I would like to use this function in my packages. Thank you for providing it!

However, it looks like it reexports the version in `rlang` (that's marked as deprecated in its own documentation). Is this the intended behaviour? In particular, I much prefer the error message in the `ellipsis` version, since it directs the end-user's attention to the possibility that they had misspelled an argument name. (And, there doesn't appear a way to meaningfully customise it short of capturing the message string and rewriting the hard-coded parts.)

I've tried installing both `rlang` and `ellipsis` from GitHub, and I get the following, which doesn't match the repository README:
``` r
  safe_mean <- function(x, ..., trim = 0, na.rm = FALSE) {
  ellipsis::check_dots_used()
  mean(x, ..., trim = trim, na.rm = na.rm)
}

safe_mean(1, 2, 3, 4)
#> Error in `safe_mean()`:
#> ! Arguments in `...` must be used.
#> ✖ Problematic arguments:
#> • ..1 = 2
#> • ..2 = 3
#> • ..3 = 4
```

<sup>Created on 2023-01-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by lionel-** [comment]
Could you please post both the actual error message and what you'd expect/prefer?

**Comment by krivit** [comment]
Thanks for looking into this!

The actual error message is in the original post's reprex:
```
#> ! Arguments in `...` must be used.
#> ✖ Problematic arguments:
#> • ..1 = 2
#> • ..2 = 3
#> • ..3 = 4
```

I think the one in `r-lib/ellipsis` README (https://github.com/r-lib/ellipsis#readme) is better. It's currently:
```
#> Error: 3 components of `...` were not used.
#> 
#> We detected these problematic arguments:
#> * `..1`
#> * `..2`
#> * `..3`
#> 
#> Did you misspecify an argument?
```

I don't think it's perfect either, because my goal would be to provide a warning, guiding the end-user towards locating and fixing what was most probably a typo. I would therefore prefer something less technical-sounding, along the lines "Arguments, a, b, and c were not recognised or used. Did you misspell an argument name?"

Also, in light of this ticket being moved to `r-lib/rlang`, would it be possible to clarify which package's version I *should* use, since `r-lib`'s is tagged deprecated?

**Comment by krivit** [comment]
More generally, perhaps instead of hard-coding the message, perhaps it could be an argument, either a string giving an alternative to "Arguments in `...` must be used." or a function taking an `alist`? It looks like, at least in principle, it's possible to extract the relevant information from the condition, e.g.,
``` r
library(rlang)
f <- function(...) check_dots_used(error=function(cnd){
  a <- cnd$body[names(cnd$body)=="*"]
  warn(sprintf("Arguments %s were not recognised or used. Did you misspell an argument name?",
               paste0(sQuote(a), collapse=", ")))
})
f(a=1,b=2)
#> Warning: Arguments 'a = 1', 'b = 2' were not recognised or used. Did you
#> misspell an argument name?
```
However, this is more cumbersome than it has to be, and it also relies on the `cnd` data structure for this particular condition never changing. Also, there is no rigorous way to obtain just the argument names short of parsing those expressions.

> `rlang::check_dots_used()` is not deprecated. Perhaps you've been confused by the deprecation label for the `action` argument? I.e. only one argument is deprecated, not the whole function. Or am I missing something?

Indeed. My bad.

**Comment by krivit** [comment]
> If needed we could add more structured conditions to allow customisation, but the work to do this and the increase to the API surface would have to be worth it.

The existing API already takes a function that customises the action taken. Its limitation is that the function is given the information about the condition in an inconvenient format.

That having been said, it's possible to work around that (by parsing the strings), if the condition's format can be relied on to be stable:

``` r
library(rlang)
library(purrr)
f <- function(...) check_dots_used(error=function(e){
  v <- parse(text=e$body[names(e$body)=="*"]) |> as.list() |> map(as.list) |> map(2)
  warn(sprintf("Arguments %s were not recognised or used. Did you misspell an argument name?",
               paste0(sQuote(v), collapse=", ")))
})
f(a=1,b=2)
#> Warning: Arguments 'a', 'b' were not recognised or used. Did you misspell an
#> argument name?
```
