### ISSUE TITLE
FR: Type predicate to check if something is a "simple" atomic vector

### ISSUE THREAD

**Issue by markfairbanks** [r-lib/rlang#1538]
I'm basically trying to check if something is an atomic vector and not a matrix.

``` r
library(rlang)

is_simple_atomic <- function(x) {
  is_atomic(x) && !is.matrix(x)
}

is_simple_atomic(1)
#> [1] TRUE
is_simple_atomic("a")
#> [1] TRUE
is_simple_atomic(list(1))
#> [1] FALSE
is_simple_atomic(matrix(1))
#> [1] FALSE
```

**Comment by lionel-** [comment]
Unfortunately I think we're not looking to add any more predicates to the already complex set. Also it isn't clear what should happen with 1d array etc. This predicate looks sufficiently specialised for it to be better maintained in local utils.R file.
