### ISSUE TITLE
Embrase does not work

### ISSUE THREAD

**Issue by alexander-pastukhov** [r-lib/rlang#1539]
I am confused, because I don't know whether it is me or specific setup but embrace `{{}}` does not work for me. 

Taking the example from documentation 

`my_mean <- function(data, var) {
  dplyr::summarise(data, mean = mean({{ var }}))
}`

and using it as 
`data <- ggplot2::mpg`
`var <- "cyl"`
`dplyr::summarise(data, mean = mean({{ var }}))`

produces an NA as mean and the following warning message:

> In mean.default(~"cyl") : argument is not numeric or logical: returning NA

Same if I use "Under the hood" code snippet: `dplyr::summarise(data, mean = mean(!!enquo(var)))`

But it does work via `dplyr::summarise(data, mean = mean(!!sym(var)))`

Tested on three installations (all windows) with only dplyr and rlang libraries loaded: 
* R 4.2.2, dplyr 1.0.10, rlang 1.0.6
* R 4.1.3, dplyr 1.0.8, rlang 1.0.2
* R 4.1.1, dplyr 1.0.10, rlang 1.0.6

I suspect there is some trivial explanation but I am completely at loss and any help is highly appreciated!

**Comment by hadley** [comment]
I'd recommend reading https://r4ds.hadley.nz/functions.html#data-frame-functions.

**Comment by alexander-pastukhov** [comment]
@hadley, thank you for the tip (and for all the fantastic work you do for the R community)! With regard to the issue: Perhaps small edits of documentation for embrace are in order, with the actual example of calling the function (once I saw _how_ the variable name is passed, I immediately realized why it was not working for me but it is _not_ obvious from the docs because the function is never called) and, ideally, exactly the link you supplied as "see also"? And, perhaps, a brief explanation on how you can get the same functionality but with variable name as a string or a reference in "see also"? Because I am not quite sure what `mean_var` is. I think it is a potential reference to an object but I need to re-read "Advanced R" to figure this out. For a more typical R user (who did not read advanced R), passing variable name to _their own_ function without quotes is probably very unintuitive and the fact that the whole thing does not work without being wrapped into a function is totally not obvious (documentation hints at that but does not explicitly say that). Sorry if I sound negative and picky, but this is a brilliant functionality, which I fell is underused because of these small important details, which are hard to figure out and are not present in the documentation.
