### ISSUE TITLE
Inconsistency between `is_call()` + `call_name()` vs `is_call(name = ...)` on quosure

### ISSUE THREAD

**Issue by mgirlich** [r-lib/rlang#1549]
I incorrectly used `is_call()` on a quosure and found this confusing inconsistency:

``` r
library(rlang)

x <- quo(desc(x))
is_call(x)
#> [1] TRUE
call_name(x)
#> [1] "desc"
is_call(x, "desc")
#> [1] FALSE
```

<sup>Created on 2023-02-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by lionel-** [comment]
I've been meaning to make `is_call()` return `FALSE` on quosures but it's been difficult a few years ago and is probably even more difficult now, regarding backwards compatibility.

In general though, `is_call()` is lower level than `call_name()` and the invariant you are looking for is not guaranteed. We do have invariants in terms of `is_call_simple()` though.
