### ISSUE TITLE
`global_entrace()` should invisibly return previous value

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#1552]
I can see this would be straightforward, but we need it for code like https://github.com/yihui/knitr/pull/2218/files#diff-555f06595df0f4008b82d676f7d0d0bdaa01bfa4b51952abb052a50ba450c0e6R300

**Comment by lionel-** [comment]
I think this means we need to simplify the interface of `global_entrace()` to be "all or nothing". Because currently you can selectively enable or disable entracing for different condition classes.
