### ISSUE TITLE
`check_whole_number()` closed interval messaging

### ISSUE THREAD

**Issue by teunbrand** [r-lib/rlang#1591]
Hi rlang team,

I think it would be great if during a check for nonzero positive integers, the output of `check_number_whole(0, min = 1)` would not be:

```r
! `0` must be a number larger than 1, not the number 0.
```

and instead could read: 

```r
`0` must be a whole number larger than or equal to 1, not the number 0
```

In particular, I'd like to confer that 1 is included in the interval. It would also be nice to message that these should be integers/whole numbers.

Please let me know if you'd welcome a PR for this.

**Comment by lionel-** [comment]
A PR would be nice but this might be a bit tricky.
