### ISSUE TITLE
Add `substitute_q()` in `rlang`?

### ISSUE THREAD

**Issue by Sciurus365** [r-lib/rlang#1617]
Hi, I found the `pryr::substitute_q()` function very helpful in substituting some variables of an expression, but the `pyry` is superseded and the same functionality is not provided in `rlang`. Would you consider adding it to `rlang`, or is another approach recommended now? Thanks.

**Comment by lionel-** [comment]
Unfortunately the style of metaprogramming implemented in `substitute_q()` is currently out of scope for rlang. You can keep using the pryr function though.
