### ISSUE TITLE
Fail to install in R4.1.0(win11)

### ISSUE THREAD

**Issue by awtexcv** [r-lib/rlang#1624]
I downloaded rlang1.1.1 from https://cran.r-project.org/web/packages/rlang/index.html, but i can't install it even i removed the old package.
> install.packages("G:/RStudio/rlang_1.1.1.tar.gz", repos = NULL, type = "source")

Warning in file.rename(instdir, final_instdir) :
  cannot rename file 'G:/RStudio/library/00LOCK-rlang/00new/rlang' to 'G:/RStudio/library/rlang', reason 'permission denied.'
ERROR:    moving to final location failed
* removing 'G:/RStudio/library/rlang'
Warning in install.packages :
  installation of package ‘G:/RStudio/rlang_1.1.1.tar.gz’ had non-zero exit status

**Comment by lionel-** [comment]
I would try to solve this:

>  cannot rename file 'G:/RStudio/library/00LOCK-rlang/00new/rlang' to 'G:/RStudio/library/rlang', reason 'permission denied.'

Maybe try installing with `pak::pak()` and since you're on Windows double check you've closed all active R and RStudio sessions before installing.

**Comment by awtexcv** [comment]
thank you, i solved it.
