### ISSUE TITLE
Missing map_vec() in R/standalone-purrr.R

### ISSUE THREAD

**Issue by Layalchristine24** [r-lib/rlang#1636]
The new `map_vec()` (see https://purrr.tidyverse.org/reference/map.html) appears to be missing from the file  R/standalone-purrr.R. Is it already planned to add it?

**Comment by hadley** [comment]
Unfortunately not, because that requires vctrs to correctly combine the various possible types of output.

**Comment by Layalchristine24** [comment]
All right. Thank you!
