### ISSUE TITLE
rlang::qq_show return code is not same with excution

### ISSUE THREAD

**Issue by djhbs** [r-lib/rlang#1640]
Hi, thank you very much for help.

In the below example, the `rlang::qq_show` show the right code:

`tibble::tibble(a = character(0), b = integer(), c = double())`

but the execution does not return right variable names, only the right type.

For first variable, the right name should be `a` not `a = character(0)`

```r
var <- c("a = character(0)", "b = integer()", "c = double()")
rlang::qq_show(tibble::tibble(!!!rlang::parse_exprs(var)))
#> tibble::tibble(a = character(0), b = integer(), c = double())

tibble::tibble(a = character(0), b = integer(), c = double())
#> # A tibble: 0 × 3
#> # ℹ 3 variables: a <chr>, b <int>, c <dbl>

df <- tibble::tibble(!!!rlang::parse_exprs(var))
df
#> # A tibble: 0 × 3
#> # ℹ 3 variables: a = character(0) <chr>, b = integer() <int>,
#> #   c = double() <dbl>
```
 I am not sure I use the function wrongly, but the result is  strange.

**Comment by lionel-** [comment]
That's because `a = character(0)` is an assignment expression just like `a <- character(0)`. And you are injecting this whole assignment as individual argument.

If you want to pass names, do it via the names of the list of expressions, e.g.

```r
exprs <- c(a = "character(0)", b = "integer()", c = "double()")

# Or equivalently:
exprs <- list(a = quote(character(0)), b = quote(integer()), c = quote(double()))
```
