### ISSUE TITLE
`global_entrace()` cannot be used with other CallingHandlers

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/rlang#1644]
Hi,

It seems that the very useful `global_entrace()` forbid the use of other handlers in some contexts.

``` r
callr::r(\(){
  library(tidyverse) |> 
    suppressPackageStartupMessages()
})
#>  [1] "lubridate" "forcats"   "stringr"   "dplyr"     "purrr"     "readr"    
#>  [7] "tidyr"     "tibble"    "ggplot2"   "tidyverse" "stats"     "graphics" 
#> [13] "grDevices" "utils"     "datasets"  "methods"   "base"

callr::r(\(){
  rlang::global_entrace()
  library(tidyverse) |> 
    suppressPackageStartupMessages()
}) 
#> Error: ! in callr subprocess.
#> Caused by error in `globalCallingHandlers(error = function (cnd) ...`:
#> ! should not be called with handlers on the stack
```

<sup>Created on 2023-07-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

However, this reprex is not 100% reproducible in the console (i.e outside `callr`), so here is a step list to reproduce the error:

 - create a file "init.R" containing these lines (in any order):
```r
rlang::global_entrace() 
library(tidyverse)
```
 - run `source("init.R") |> suppressPackageStartupMessages()`
 - you should get the error

This is actually the steps that got me the error.
I'm using `rlang` v1.1.0 with R 4.1.3.

**Comment by lionel-** [comment]
Unfortunately this is a limitation of `base::globalCallingHandlers()` that rlang can't work around.
