### ISSUE TITLE
Should abort() add pkg name as outermost S3 class?

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#167]
so `abort(msg, c("foo", "bar"))` would create a typed error of class `c("foo", "bar", "error", "pkg_name")`, and the class for `abort(msg)` would simply be `c("error", "pkg_name")`.

cc @jimhester @gaborcsardi @jennybc

**Comment by Hong-Revo** [comment]
I think it would be cleaner to have a separate attribute if you want to return this information.

**Comment by lionel-** [comment]
hmm you're right, package names might conflict with classes in some situations.

**Comment by lionel-** [comment]
This would be problematic with abort wrappers, would need to carry the environment or the package name through arguments.
