### ISSUE TITLE
Feature request: add function to modify an atomic vector in place

### ISSUE THREAD

**Issue by Yunuuuu** [r-lib/rlang#1673]
Feature request: Kindly evaluate the possibility of implementing a function that enables direct modification of an atomic vector, similar to the functionality provided by data.table's `set` function. The objective is to seamlessly and efficiently alter the atomic vector within its current storage space.

**Comment by lionel-** [comment]
Hello, unfortunately this is out of scope for rlang. See `vec_poke_n()` and `vec_poke_range()` though but these are experimental functions that may get removed from rlang.
