### ISSUE TITLE
Allow keeping names with squash, similar to unlist.

### ISSUE THREAD

**Issue by NGaffney** [r-lib/rlang#168]
Currently when squashing a nested list it only maintains the innermost names, discarding information which can be important and potentially causing name collision errors.

``` r
library(purrr)
library(rlang)

pets <- list(
  pet = list(
    name = "Fluffy"
  ),
  coat = list(
    colour = "blue",
    pattern = "mearle"
  ),
  eyes = list(
    colour = "blue"
  )
)

squash(pets)
```

    ## $name
    ## [1] "Fluffy"
    ## 
    ## $colour
    ## [1] "blue"
    ## 
    ## $pattern
    ## [1] "mearle"
    ## 
    ## $colour
    ## [1] "blue"

On the other hand `unlist` has the `use.names` argument which keeps names by concatenating the names of each level.

``` r
pets %>% 
  unlist %>% 
  as.list
```

    ## $pet.name
    ## [1] "Fluffy"
    ## 
    ## $coat.colour
    ## [1] "blue"
    ## 
    ## $coat.pattern
    ## [1] "mearle"
    ## 
    ## $eyes.colour
    ## [1] "blue"

It would be nice to have an equivalent option for `squash` rather than having to collect and then manually set the names after squashing, like below.

``` r
recursive_names <- function(x, parent_name = NULL) {
  if (is.list(x)) {
    if (!is.null(parent_name)) {
      x_names <- paste(parent_name, names(x), sep = "_")
    } else {
      x_names <- names(x)
    }
    
    map2(
      x,
      x_names,
      recursive_names
    ) %>% 
      reduce(c)
  } else {
    return(parent_name)
  }
}

squash_named <- function(x) {
  setNames(
    squash(x),
    recursive_names(x)
  ) 
}

pets %>% 
  squash_named()
```

    ## $pet_name
    ## [1] "Fluffy"
    ## 
    ## $coat_colour
    ## [1] "blue"
    ## 
    ## $coat_pattern
    ## [1] "mearle"
    ## 
    ## $eyes_colour
    ## [1] "blue"

**Comment by lionel-** [comment]
I think you'd use this (once implemented): https://github.com/tidyverse/purrr/issues/525
