### ISSUE TITLE
Missing error in `vec_recycle_common()` shim

### ISSUE THREAD

**Issue by teunbrand** [r-lib/rlang#1700]
I believe the following is supposed to throw an error, as the output is not a list where every element is of length 1.
``` r
rlang:::vec_recycle_common(list(a = 1, b = 1:2), size = 1)
#> $a
#> [1] 1
#> 
#> $b
#> [1] 1 2
```

<sup>Created on 2024-04-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

The function has a specific branch to throw an appropriate error in the part below.

https://github.com/r-lib/rlang/blob/65018f9d6212610a518f6e38d87a427d98422824/R/standalone-vctrs.R#L121-L123

I think `ns != size` should be `n != size` for the error to trigger correctly.
I'd be happy to prepare a PR if welcome.

**Comment by lionel-** [comment]
A PR would be welcome ☺️
