### ISSUE TITLE
The main branch was force pushed by accident

### ISSUE THREAD

**Issue by eitsupi** [r-lib/rlang#1759]
@lionel- Some changes seem to have been removed, I recommend protecting the main branch in GitHub settings and not allowing force push.
https://github.com/r-lib/rlang/compare/55453da3665bf51af8560bf84214e77c61d3d458..fb2f3b7d311493fab65b1f5ee5872f47b52ffd65

I assumed this was an accident, but if this change was intentional, I think it should be changed with revert, not force push.

**Comment by lionel-** [comment]
Thanks for the heads up!! I got myself into a very strange git state where I could not pull, fetch, or push. I force-pushed to get myself out of this situation after a quick peek at the repo, but I must have missed something. I should have double checked.

In general I don't mind force-pushing to main for quick corrections though.

**Comment by lionel-** [comment]
Alright should be fixed! - via a force push ;-)

Thanks again! I was so confused yesterday...
