### ISSUE TITLE
Implementation of defer

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#180]
```R
defer <- function(expr, scope = parent.frame()) {
  expr <- enquo(expr)

  call <- expr(on.exit(rlang::eval_tidy(!!expr), add = TRUE))
  eval_bare(call, scope)
}
```

Not sure what it should be called. Maybe `ctxt_on_exit()`?

Could also implement `env_on_exit()`  as wrapper around `reg.finalizer()`.

**Comment by hadley** [comment]
Might also be useful to have some way to check if an environment is in the context stack so we can give an error if you try to call `defer()` with an environment that's not on the stack.

**Comment by lionel-** [comment]
it would be nice to have a consistent prefix for installing stuff on the stack. We'd use it e.g. for `tidyselect::set_current_vars()`.

IIRC other packages use `local_`. It's not great but maybe we should use it for consistency? E.g. `local_unwind()`, `local_vars()`?

**Comment by lionel-** [comment]
`defer()` is now implemented as a compat file in withr: https://github.com/r-lib/withr/blob/master/R/defer.R
