### ISSUE TITLE
lang_modify with list object and unnamed NULL hangs R

### ISSUE THREAD

**Issue by Hong-Revo** [r-lib/rlang#187]
```
library(rlang)
lang_modify(list(a=1), NULL)
```
Leaves R unresponsive; the only fix is to shut it down from the OS. This is on Windows 10 Pro 64-bit.

This is an edge case, but hanging R seems a bit unfriendly. It should probably throw an error.

**Comment by egnha** [comment]
@Hong-Revo Good catch. On Mac OS (El Capitan) and R 3.4.0, this segfaults.
