### ISSUE TITLE
`@` accessor for attributes from non-S4 objects

### ISSUE THREAD

**Issue by jimhester** [r-lib/rlang#207]
It would be nice to provide the `@` accessor for non-S4 objects, like you can with S4 slots (which are implemented as attributes anyway). A simple R implementation

``` r
`@` <- function(x, which) {
  if (isS4(x)) {
    base::`@`(x, which)
  } else {
    attr(x, deparse(substitute(which)), exact = TRUE)
  }
}

`@<-` <- function(x, which, value) {
  if (isS4(x)) {
    base::`@<-`(x, which, value)
  } else {
    `attr<-`(x, deparse(substitute(which)), value)
  }
}

x <- 1
x@a <- 2
x@a
#> [1] 2
x@b
#> NULL
```

Some thoughts on this

1. Currently rlang does not mask any functions from base R. We could define this on-load to avoid the warning about masking `@` if we wanted.
2. The real implementation might be better off in C.
3. I think using `exact = TRUE` is probably best, but it is a departure to how `$` works in base R.
4. Do we want to return `NULL` for missing attributes, or an error?

I think it would be nice to have this in rlang so we could start using it today, but alternatively we could propose the change to R-devel instead.

cc/ @hadley

**Comment by hadley** [comment]
Ideally, we should propose to R-devel, and provide a backport in rlang.  

I agree that `exact = TRUE` is the desired behaviour.

**Comment by lionel-** [comment]
In the meantime I have added a replacement variant of `%@%`.

**Comment by hadley** [comment]
It feels a bit weird that `%@%<-` doesn't require quotes, but `%@%` does

**Comment by lionel-** [comment]
oh I hadn't realised that that `%@%` wasn't a quoting function. It feels like it should be?

**Comment by lionel-** [comment]
Maybe I should also add Jim's S4 handling, then it's easy to override `@` in the globalenv or in a namespace with

```r
`@` <- `%@%`
`@<-` <- `%@%<-`
```
