### ISSUE TITLE
expr_text should call deparse with backtick=TRUE

### ISSUE THREAD

**Issue by DarwinAwardWinner** [r-lib/rlang#211]
When calling `expr_text` on a name that requires backticks, it does not include the backticks:

```r
> expr_text(f_rhs(quo(`symbol_that_needs_backquotes!@#$%`)))
[1] "symbol_that_needs_backquotes!@#$%"
```

To fix this, `expr_text` should use `backtick=TRUE` when calling `deparse`.

**Comment by lionel-** [comment]
Thanks. I had to use a different solution in order to support `<U+xxx>` unicode tags.

**Comment by krlmlr** [comment]
This now breaks a test in _dplyr_: https://travis-ci.org/tidyverse/dplyr/jobs/434982204#L1277

``quo_text(quo(`~`))`` used to return just a tilde. We can work around in the development version, but the CRAN version will break when we release an _rlang_ update.

**Comment by DarwinAwardWinner** [comment]
Is this actually a bug that breaks some functionality, or just a test that's failing because the error message doesn't match exactly?

**Comment by krlmlr** [comment]
The latter. I have submitted a fix for _dplyr_, but I'm not sure.
