### ISSUE TITLE
as_dictionary.data.frame can return invalid dictionaries

### ISSUE THREAD

**Issue by davharris** [r-lib/rlang#213]
Currently, `rlang::as_dictionary(cbind(iris, iris), read_only = TRUE)` returns a "dictionary" with repeated columns, which is invalid.  I noticed this problem via a call like `select(cbind(iris, iris), Species)` in dplyr that returned a cryptic error about dictionaries.

I think `rlang::as_dictionary.data.frame` should probably throw an error about repeated column names instead of returning an invalid object.  Another option would be changing the column names as happens in `as_dictionary.default`.

**Comment by lionel-** [comment]
The error is now

```
Error: `data` must be uniquely named but has duplicate elements
```
