### ISSUE TITLE
Error message in as_dictionary.default should name repeated columns

### ISSUE THREAD

**Issue by davharris** [r-lib/rlang#214]
Currently, a call like `dplyr::select(cbind(iris, iris), Species)` tells the user `Error: Data source must be a dictionary`, which isn't very clear to non-experts. (The underlying reason for this error is addressed in #213.)

[Based on the code surrounding the error message](https://github.com/tidyverse/rlang/blob/master/R/dictionary.R#L39), it looks like this error will only be thrown when there are repeated columns. The error message would be more helpful if it told the user which columns were duplicated, like `tibble::as_tibble(cbind(iris, iris))`.

**Comment by mcallaghan** [comment]
I tried to gather a dataframe, and got the error  

`Error: is_dictionaryish(x) is not TRUE`

It took me quite a while to realise that this meant that I had duplicated column names, more info would definitely be helpful!

**Comment by lionel-** [comment]
Agreed.

**Comment by lionel-** [comment]
The error is now

```
Error: `data` must be uniquely named but has duplicate elements
```

**Comment by handibles** [comment]
I received this beaut (`Error: `data` must be uniquely named but has duplicate elements`) through a call to ggplot2's geom_point, and spent a while combing through each item, looking for duplicated rownames. Took a while to figure out that elements referred to columns - is this an issue with my own learning curve (i.e. I should have known that columns, not rownames, are the elements in question), or can the language be re-repointed for true novices?..

**Comment by lionel-** [comment]
Good point this is now "`data`must be uniquely named but has duplicate columns" in the development version.
