### ISSUE TITLE
cnd_resignal()

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#224]
Throws an error if inherits from error, or warns if a warning, or signals if simple condition.

**Comment by hadley** [comment]
Should we just call this `cnd_signal()`? 

The we could eliminate `cnd_inform()`, `cnd_warn()`, and `cnd_abort()` - I think it's reasonable to say that the signalling is always determined by the class of the condition. (This would deviate from our general philosophy of avoiding S3 dispatch, but I think we'd implement with `inherits`, and I don't see how we can avoid it)

**Comment by hadley** [comment]
i.e.

```R
cnd_signal <- function(cnd, .muffable = FALSE) {
  if (inherits(cnd, "error")) {
    invisible(.Call(rlang_cnd_abort, cnd, .mufflable))  
  } else if (inhertis(cnd, "warning")) {
    invisible(.Call(rlang_cnd_warn, cnd, .mufflable))  
  } else if (inherits(cnd, "message")) {
    invisible(.Call(rlang_cnd_inform, cnd, .mufflable))
  } else {
    invisible(.Call(rlang_cnd_signal, cnd, .mufflable))
  }
}
```
