### ISSUE TITLE
Theory section of tidyeval article not a header

### ISSUE THREAD

**Issue by batpigandme** [r-lib/rlang#233]
It's fine in the Rmd, but in the [tidy-evaluation.html, line 131](https://github.com/tidyverse/rlang/blob/master/docs/articles/tidy-evaluation.html#L131), you can see it's being rendered as a citation (possibly due to the colon, which, again, is not in the Rmd)
`<p><span class="citation">@section</span> Theory:</p>`

**Comment by lionel-** [comment]
This vignette is no longer part of the package.
