### ISSUE TITLE
pattern-matching / 'map_when' helper?

### ISSUE THREAD

**Issue by kevinushey** [r-lib/rlang#246]
This would be something similar to `case_when()`, but for mapping conditions to operations -- something like a generalized switch.

As an example, the following code:

```R
mtcars %>% map_when(
  starts_with("d") ~ prod(.),
  contains("a")    ~ sum(.),
  c("mpg", "cyl")  ~ cor(.)
)
```

would evaluate to something like:

```R
> mtcars %>% map_when(
+   starts_with("d") ~ prod(.),
+   contains("a")    ~ sum(.),
+   c("mpg", "cyl")  ~ cor(.)
+ )
[[1]]
[1] 1.218225e+91

[[2]]
[1] 336.09

[[3]]
          mpg       cyl
mpg  1.000000 -0.852162
cyl -0.852162  1.000000
```

Would this be worth adding to `rlang` (or somewhere similar)? Or does this already exist as some function I'm not aware of?

**Comment by lionel-** [comment]
That might fit in the vctrs package, which will probably be the home of `case_when()` in the future.

**Comment by lionel-** [comment]
and nothing happens :p where are you move bot?
