### ISSUE TITLE
Add a `with_connection` function

### ISSUE THREAD

**Issue by jrnold** [r-lib/rlang#252]
Evaluate an expression with a connection, and then close it.  I want to avoid the the `unused connection closed` messages. I think it would simply look like this, where `conn` becomes a pronoun for the expression.
```
with_conn <- function(conn, expr) {
  on.exit(close(conn))
  eval_tidy(enquo(expr), env = env_parent(), data = list(conn = conn))
}
```
This is inspired by Python's `with` statement: http://effbot.org/zone/python-with-statement.htm.

**Comment by jrnold** [comment]
An example of how this would be used is:
```
with_conn(gzfile('foo.csv', 'r'), read_csv(conn))
```

**Comment by lionel-** [comment]
Note that thanks to lazy evaluation you don't need to capture the argument:

```r
with_conn <- function(conn, expr) {
  on.exit(close(conn))
  expr
}
```

**Comment by lionel-** [comment]
Interesting idea. The next rlang version will feature a bunch of `with_` and `scoped_` functions. The scoped version would look like:

```r
local({
  scoped_connection(file("path"))
  read_csv(.conn)
})
```

**Comment by jrnold** [comment]
awesome! That's the functionality I'm looking for. Thanks!

**Comment by lionel-** [comment]
Connections will be tackled in another package. cc @gaborcsardi

**Comment by gaborcsardi** [comment]
withr already has this I think

**Comment by gaborcsardi** [comment]
`withr::local_connection`

It has a bunch of other `local_` functions as well.
