### ISSUE TITLE
Search through closure ancestry in ns_env_name()

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#272]
So it's robust to closures created with function operators. cc @jennybc

**Comment by jennybc** [comment]
I (think) I understand what you mean now, but I also can't create a scenario where this actually comes up. Could you say a few more words about the scenario?

**Comment by lionel-** [comment]
It comes up when functions are created with function operators:

```r
my_fn <- purrr::partial(fn, foo = "foo")
```

This is probably a fairly rare case.

**Comment by jennybc** [comment]
I experimented like so:

  * An inner function that is defined in a package.
  * An outer function that is defined ?somewhere? via a function operator and that wraps the inner function. I contemplated ?somewhere? being same package as inner function or the global workspace.
  * Usage of `ns_env_name()`, either in the inner function or the wrapper function.

I couldn't think up a combination of the latter two where you'd expect `ns_env_name()` to work but it doesn't and it should.  Am I on the right track? I'm not trying to address this issue, just understand it.

**Comment by lionel-** [comment]
I think a more common use case would be a closure that maintains some state in a closure environment rather than the namespace:

```r
make_fn <- function() {
  state <- 0
  function(arg = optionally(10)) {
    arg <- arg_option(arg)
    state <<- state + arg
    state
  }
}

my_fn <- make_fn()
```

Sorry for the contrived example ;)

**Comment by lionel-** [comment]
We just need to add that functionality in `ns_env()` to have it in the other functions. Would it make sense to search through the ancestry no matter what? Or should it be an argument, e.g. `inherit`? In that case what should be the default? I'm leaning towards making that behaviour unconditional.

**Comment by hadley** [comment]
I don't understand this issue, but I'm generally in favour of making the inputs to `env_` functions less flexible, so I think the problem with functions would then go away.

**Comment by lionel-** [comment]
Let's think more about this.
