### ISSUE TITLE
`are_numeric`, `all_numeric`, and friends

### ISSUE THREAD

**Issue by njtierney** [r-lib/rlang#274]
Not sure if this should go in [`vctrs`](https://github.com/hadley/vctrs), please feel free to let me know if this should move.

It can be handy to test whether all or things are numeric, and just like there is a `rlang::are_na`, I'm wondering if there should be this for other types?

For example

``` r
are_numeric <- function(x, ...){
  any(as.logical(lapply(x, is.numeric)))
}

all_numeric <- function(x, ...){
  all(as.logical(lapply(x, is.numeric)))
}

are_numeric(iris)
#> [1] TRUE
are_numeric(letters)
#> [1] FALSE
are_numeric(1:10)
#> [1] TRUE
all_numeric(iris)
#> [1] FALSE
all_numeric(letters)
#> [1] FALSE
all_numeric(1:10)
#> [1] TRUE
```

**Comment by lionel-** [comment]
The `numeric` concept is not defined in rlang so maybe vctrs is the place?

For consistency the `are_numeric()` would be a vectorised functions that returns a logical vector as long as the input. The version you're suggesting should probably be called `any_numeric()`.
