### ISSUE TITLE
Do quosures need subset and subset-assignment methods?

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#292]
E.g. https://community.rstudio.com/t/tutorial-on-quosures/2611/12?u=lionel

**Comment by hadley** [comment]
Hmmmm, I'm not sure. I think it'll be a lot of work to create a completely parallel set of operators. It might be better to tell people to extract with `get_expr()`, modify that, and then update?

**Comment by lionel-** [comment]
How about something like this:

```r
`[[.quosure` <- function(x, ...) {
  unclass(x)[[2]][[...]]
}
`[[<-.quosure` <- function(x, i, value) {
  attrs <- attributes(x)
  x <- unclass(x)
  x[[2]][[i]] <- value
  attributes(x) <- attrs
  x
}
```

**Comment by hadley** [comment]
You'll also need to define `length()` and `names()` methods, and then I think that will break `str()`, so you'll also need to override that.

**Comment by lionel-** [comment]
Ah right. About the `str()` method we already have one.

Maybe we want to think in terms of a native R quosure. If we could create `QUOSXP` objects, would it make sense to forward subsetting, length etc to the wrapped expression?

```r
quo <- ^foo(bar)
quo[[2]] <- quote(baz)
```

That's not how formulas work but formulas are `LANGSXP`. For quosures it seems to make more sense.

**Comment by hadley** [comment]
We also need to think pragmatically if this is where it's worth spending a bunch of time.
