### ISSUE TITLE
Do we need enlabel() and entext()?

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#303]
See discussion in #300.

**Comment by lionel-** [comment]
It seems like these should use rlang capture functions in order to support quasiquotation. But if we do so they won't work with forced arguments. Not sure what's best.

**Comment by krlmlr** [comment]
It would be great to have them, because `enquo()` and `enexpr()` don't work e.g. for S3 methods.

**Comment by lionel-** [comment]
Just added to 0.3.0 milestone so we don't forget.

**Comment by krlmlr** [comment]
Thanks. I think I'll use my hack for _tibble_, need to remove it once a better version becomes available in _rlang_.

**Comment by lionel-** [comment]
This should probably wait until 0.4.0 when we have figured out #636.

**Comment by lionel-** [comment]
Interesting, thanks for sharing!

**Comment by lionel-** [comment]
```r
count_top <- function(df, variable, n = 5) {
  name <- enlabel(variable)
  df %>%
    mutate(temp = fct_lump(fct_infreq({{ variable }}), n = n)) %>%
    count(!!name := temp)
}

mtcars %>% count_top(as.factor(cyl))
#> # A tibble: 3 x 2
#>   `as.factor(cyl)`     n
#>   <fct>            <int>
#> 1 8                   14
#> 2 4                   11
#> 3 6                    7
```

**Comment by lionel-** [comment]
Closing this for now.
