### ISSUE TITLE
Error: unable to load rlang.dll on Windows 10

### ISSUE THREAD

**Issue by marcionicolau** [r-lib/rlang#306]
Hi,

I'm trying to install on Windows 10 and 8 machines (R 3.3.0 and 3.3.2) and get this error:

```
An error occurred <Buffer 45 72 72 6f 72 20 69 6e 20 69 6e 44 4c 28 78 2c 20 61 73 2e 6c 6f 67 69 63 61 6c 28 6c 6f 63 61 6c 29 2c 20 61 73 2e 6c 6f 67 69 63 61 6c 28 6e 6f 77 ... >
08:10:57:435 Fail to check Api with message: Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Rlibs/rlang/libs/x64/rlang.dll':
  LoadLibrary failure:  The specified procedure could not be found.
```

How could I solve this?

I try to install with versions 0.1.2 and 0.1.4, the behavior is the same.

**Comment by lionel-** [comment]
Are you trying to install dev or CRAN rlang? Did you install in a completely fresh session? On Windows you should always install packages in fresh sessions because there are issues with packages containing compiled code. Maybe that's the problem?

**Comment by marcionicolau** [comment]
@lionel- I installed from CRAN and from github with ```devtools::install_github```. All in fresh sessions, from both R console and Windows cmd.exe with 
```
"C:\Program Files\R\R-3.3.0\bin\R.exe" -e "install.packages('rlang',dep=TRUE, repos='https://cran.rstudio.com')"
```

**Comment by marcionicolau** [comment]
@lionel- Another thing, the version of Rtools could be a potential issue?

**Comment by lionel-** [comment]
A similar issue is discussed here: https://stackoverflow.com/questions/13497222/the-specified-module-could-not-be-found-in-r

I don't know how to help you because I don't have any experience compiling stuff on Windows.

**Comment by marcionicolau** [comment]
Hi @lionel- !
I read the SO link, and after that, I checked the linkage of rlang.dll on both PC with packages working and not working.

not working
![ldd-rlang-result](https://user-images.githubusercontent.com/1499733/33617965-5ff29258-d9c8-11e7-939d-a15bf0172bf9.jpg)

working
![capturar-ldd-rlang](https://user-images.githubusercontent.com/1499733/33618098-c0dfaf9c-d9c8-11e7-9ca9-d9cb2ce87416.PNG)

I think ```??? => ???``` are ```R.dll``` linkage, Is this correct?

**Comment by lionel-** [comment]
I have no idea what `???` represents there :)

@gaborcsardi @jimhester have you encountered this kind of issue before?

**Comment by marcionicolau** [comment]
I use ldd from Git Bash `ldd /c/Rlibs/rlang/libs/x64/rlang.dll`

**Comment by jimhester** [comment]
You will likely need to use the ldd distributed with the mingw distribution in RTools to get correct results, and will need to use cmd.exe or powershell, not git bash.

Almost certainly the cause is you have modified your `%PATH%` and have incompatible libraries being found instead of the ones distributed with R / RTools.

**Comment by marcionicolau** [comment]
Hi @jimhester you are right! 

But the main question is related to the necessity of rlang to be linked with R.dll? The PC that the installation failed only have R (3.3.X) installed, not Rtools.

**Comment by lionel-** [comment]
Maybe this question is better suited for SO?

**Comment by Raj167** [comment]
I'm also facing same problem, can anyone suggest better solution?
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'E:/Program Files/R/R-3.3.0/library/rlang/libs/x64/rlang.dll':
  LoadLibrary failure:  The specified procedure could not be found.

**Comment by lionel-** [comment]
Perhaps @jeroen knows about this issue?

**Comment by jeroen** [comment]
Sounds indeed like malconfigured compiler. @Raj167 can you show us the full output of installing rlang?

**Comment by jimhester** [comment]
Or possibly the rlang.dll was not correctly installed because an existing one was currently in use. You may want to try installing rlang from a fresh session without any other packages loaded.

**Comment by Raj167** [comment]
@jeroen 
> install.packages("rlang")
Installing package into ‘E:/Program Files/R/R-3.4.1/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/rlang_0.2.0.zip'
Content type 'application/zip' length 819036 bytes (799 KB)
downloaded 799 KB

package ‘rlang’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\t2374rg\AppData\Local\Temp\29\Rtmpo3iFVz\downloaded_packages

This is the output of installing rlang

**Comment by lionel-** [comment]
@Raj167 on a fresh session? I.e. is `install.packages()` the very first thing you did after starting R? If yes, do you perhaps load tidyverse packages or call tidyverse functions in your RProfile? That would also cause the DLL updating issue.

**Comment by Raj167** [comment]
I.e. is install.packages() the very first thing you did after starting R? Yes
no I have load tidyverse packages, and it's working fine while running in rstudio problem when we try to run using batch file using python. Actually I'm creating a pipeline to run sql and rscript together using python wrapper. all SQL code's are running fine but isuue when it reach to rscript

**Comment by chitrak-banerjee** [comment]
Hi I have a similar problem. I am trying perform an R CMD check using shell script...and it shows me:

Error: package or namespace load failed for 'autodiffadolc' in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object....
  LoadLibrary failure:  The specified module could not be found.

Any suggestions whatsoever?

**Comment by chitrak-banerjee** [comment]
Hi @lionel- could you elaborate a little on Suggests: ? and by deps do you mean the Dependencies ?

**Comment by lionel-** [comment]
Suggests are for packages that R will not install automatically but offer optional features. They are needed for R CMD check.

By deps I mean any package that autodiffadolc depends on in the general sense, i.e. any package it might try to use, including suggested packages. The installation process of one of those packages might have silently failed. This Windows bug is really annoying :(

**Comment by chitrak-banerjee** [comment]
Thanks @lionel- I may need some more assistance later.....

**Comment by chitrak-banerjee** [comment]
Hi I think what you suggested may not be the case my package doesn't depend on other packages except for stats. I believe the problem what was happening is probably cross compilation with the Mingw and Rtools. I already removed all Mingw paths from my path variables. Do I need to remove them from environment variables as well?
