### ISSUE TITLE
Shallow copy of environment ancestry

### ISSUE THREAD

**Issue by nfultz** [r-lib/rlang#320]
I currently have this in one of my packages, but rlang might be a better home:

```r
env_deep_copy <- function(e) {
  if(identical(e, emptyenv())) emptyenv() else
  if(identical(e, global_env())) env_clone(e) else # don't clone attached packages
    env_clone(e, Recall(parent.env(e)))
}
```

It's been helpful for fixing some bugs related to laziness.

**Comment by lionel-** [comment]
A deep copy would imply that you're copying the objects within the environments as well. This is more a shallow copy of environment ancestry. Thanks for the suggestion.

**Comment by lionel-** [comment]
We haven't had a need for it since then, so this might be out of scope for rlang.
