### ISSUE TITLE
Should dots_list have .duplicates argument?

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#340]
e.g.

```R
dots_list(x = 1, x = 2)
dots_list(x = 1, x = 2, .duplicates = "keep")
#> list(x = 1, x = 2)

dots_list(x = 1, x = 2, .duplicates = "first")
#> list(x = 1)

dots_list(x = 1, x = 2, .duplicates = "last")
#> list(x = 2)

dots_list(x = 1, x = 2, .duplicates = "error")
#> Argument `x` specified in two locations (1, 2)
```

This would be particularly useful when you're generating a call (or invoking a function) when you are combining user input with a fixed set of attributes. It's convenient to be able to prefer either the users values, the default values, or explicitly throw an error.

This is related to common uses of `modifyList()` (although the recursive nature of `modifyList()` isn't needed here)

**Comment by vspinu** [comment]
`modify` should probably have one as well:

```R
## currently
> x <- list(a = 1, b = 2)
> str(modify(ll(), splice(x), splice(x)))
List of 4
 $ a: num 1
 $ b: num 2
 $ a: num 1
 $ b: num 2

```

**Comment by lionel-** [comment]
hmm I think `modify()` should be marked as experimental. We're not sure yet where we are going with this function. We included it at a time where we were less careful about what was going into the package. WDYT @hadley?

**Comment by vspinu** [comment]
I don't know where you plan to take the package but I am very pleased with the direction taken so far. I love the project! I do see it as a swiss knife. More the better ;)  I finally can use one package for most (not all yet) language manipulation that I need with a concise and consistent semantics. The `modify` grew up on me due to the splice semantics. Hard to imagine using something else already.

**Comment by hadley** [comment]
Yeah, `modify` feels more like a purrr function to me.

**Comment by lionel-** [comment]
@hadley Is it best to table this until we see things more clearly regarding object comparison, in light of the developments in vctrs?

**Comment by hadley** [comment]
I think this is unrelated to vctrs

**Comment by lionel-** [comment]
Ah got it, the argument name made me think of `duplicated()`. Perhaps `.homonyms`?
