### ISSUE TITLE
Mildly suboptimal printing of nested quosures

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#359]
``` r
library(rlang)
make_x <- function(x) quo(x)
quo(!!make_x(10) + !!make_x(20))
#> <quosure>
#>   expr: ^(^x) + (^x)
#>   env:  global
```

It took me a little while to parse the expression - the first `^` has implicit parentheses that surround the whole expression.  But I'm not sure how we can do better here

**Comment by lionel-** [comment]
I don't think we can do much better. The parentheses on the RHS are not needed though. Here is how it looks with formulas and the R deparser: `~(~x) + ~x`

**Comment by lionel-** [comment]
This is less of a problem now that we build expressions with `expr()` instead of `quo()`.
