### ISSUE TITLE
Generic to extract data from objects

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#36]
Which we'd use in base-type conversions.

Related: our own C-level conversion functions, so we can avoid a copy when coercing S3 classes wrapping a vector (changing an attribute implies a copy).

**Comment by hadley** [comment]
Somewhat related is the need for the default `print()` method to have a `no.attr` argument so you can re-use it more easily without having to strip the attributes of an object

**Comment by lionel-** [comment]
See proxy methods in vctrs.
