### ISSUE TITLE
Combine env and child_env

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#363]
I realised that if we had:

```R
child_env <- function(.parent = caller_env(), ...) {}
```

I think we'd only need one of `child_env()` and `env()` since the dots must be named.

**Comment by vspinu** [comment]
I used `child_env` a couple of times now, but I cannot get used to the name. The name rings like an extractor of the child environment from the .parent, but child env is not an inherent property of the .parent. Hence the confusion.

**Comment by vspinu** [comment]
I think `env` is too nice of a name for environment constructor. It better be `new_env` and `get_env` better be `env`. I see three benefits of this:

 - This would parallel base `environment` and `new.env` - the extractor and constructor respectively.   
 - Extraction is a more common operation (at least at the REPL) and deserves a better name.
 - On a mnemonics side, `get_env` is easily confused with `env_get`. I always have to think twice which one to use. Please, please fix!

**Comment by hadley** [comment]
`new_env()` currently takes a list but unquote splicing makes that less necessary. 

I’m not sure about using `env()` to get the current environment - I don’t find myself doing that often. Maybe `current_env()` to parallel `globalenv()` etc?

**Comment by vspinu** [comment]
There is no `new_env` only `new_environment` as far as I can see. 

> I’m not sure about using env() to get the current environment 

I didn't mean current environment. I want `env` to get the environment of its argument. Same thing that `get_env` does now.

**Comment by vspinu** [comment]
Arh, I see what you mean. `get_env()` with no args returns the current environment. IIt feels natural that it should do so. `environment()` does so, and `env_parent()` returns the parent of the current env.

**Comment by lionel-** [comment]
> Maybe current_env() to parallel globalenv() etc?

I like `current_env()`. Perhaps `frame_env()`?

> I want env to get the environment of its argument.

I think this is not possible because it wouldn't be consistent with other variadic constructors in rlang which are all named (where possible) after their abbreviated type name.

**Comment by lionel-** [comment]
I also realise that since `child_env()` takes an environment as first argument in addition to returning one, it should be prefixed with `env_` rather than suffixed (if we keep it).

**Comment by hadley** [comment]
`current_env()` discussion moved to https://github.com/r-lib/rlang/issues/421

**Comment by lionel-** [comment]
> function(.parent = caller_env(), ...)

This signature doesn't work because of partial matching /o\

**Comment by hadley** [comment]
We could make it `` `_parent` ``?

**Comment by lionel-** [comment]
I'm thinking about implementing with this: https://github.com/r-lib/rlang/issues/391

**Comment by hadley** [comment]
Hmm, interesting idea. We can try it out for `env()` and see how it goes.
