### ISSUE TITLE
Should quosures have a str method?

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#371]
Currently:

```R
> str(quo(x))
 language ~x
 - attr(*, ".Environment")=<environment: R_GlobalEnv> 
```

**Comment by kevinushey** [comment]
Looks like there is already a `str()` method:

https://github.com/r-lib/rlang/blob/84deb877d1ce4ba50fbaafea246c1eb918805631/R/quo.R#L514-L517

Do we have a proposal for an alternate presentation? The default R approach seems okay in this scenario.

**Comment by lionel-** [comment]
I think you're right, the current behaviour is probably fine. Thanks for taking a look!
