### ISSUE TITLE
Function constructor?

### ISSUE THREAD

**Issue by vspinu** [r-lib/rlang#380]
`expr_interp` is used internally to create on the fly closures but that doesn't allow for argument splicing due to the R's parser checks: 

```R
> args <- alist(a = 3 + 3)
> expr_interp(function(!!!args) {})
Error: unexpected '!' in "expr_interp(function(!"
```

What do you think about an explicit constructor along the following lines:

```R

fn <- function(fmls, body, env = caller_env()) {
    out <- function() {}
    fn_fmls(out) <- as.pairlist(fmls)
    body(out) <- enexpr(body)
    environment(out) <- env
    out
}

library(rlang)
fn(ll(a = 3 + 3), a + 3)
#> function (a = 6) 
#> a + 3
fn(alist(a = 3 + 3), a + 3)
#> function (a = 3 + 3) 
#> a + 3
```

**Comment by lionel-** [comment]
By the way the general naming rationale is that `new_unabbreviated()` ctors take vectors of components while `abbr()` ctors take variadic dots.

**Comment by vspinu** [comment]
> There is new_function() for this:

Missed that. It does what wanted except that I have to quote the body, which is consistent of course.

> t could have body as first arg and take args with ...:

No room for the env argument then. 

Maybe treat the last argument of ... as body?

```R
fn(a = 1, b = 3, {a + b + 1})
````

Or simply merge all unnamed arguments into body.  Args should be named anyways.

> new_unabbreviated()

Haven't noticed this.  Any reason why it should be "unabreviated"? `new_environment` and `new_function` are rather long for my personal taste.

**Comment by lionel-** [comment]
> No room for the env argument then.

It would be `.env`.

> Maybe treat the last argument of ... as body?

Interesting suggestion. It'd have to be unnamed and we throw an error otherwise. This would make the order consistent with `new_function()`.

> Any reason why it should be "unabreviated"?

For consistency with `is_` predicates and `as_` coercers. I personally don't like when abbrevs are used everywhere because it makes it harder to read. There's some unconsistency in the API though, e.g. `set_env()`. Naming is frustrating.

**Comment by egnha** [comment]
Perhaps the `fn()` constructor from the [nofrills](https://github.com/egnha/nofrills) package already does what you want. It runs on rlang, of course. :-)

- **Quasiquotation**
    ```R
    library(nofrills)
    
    fn(x, y = 1, ... ~ log(x + y, ...))
    #> function (x, y = 1, ...) 
    #> log(x + y, ...)
    
    arg <- "y"; z <- 0
    fn(x, !!arg := !!z ~ x + !!as.name(arg))
    #> function (x, y = 0) 
    #> x + y
    
    args <- alist(x, y = 0)
    fn(!!!args, ~ x + y)  # note the one-sided formula
    #> function (x, y = 0) 
    #> x + y

    lowercase <- x ~ x %in% letters
    is_lowercase <- fn(!!lowercase)
    is_lowercase
    #> function (x) 
    #> x %in% letters
    ```

- **Literal unquoting** (which, for instance, facilitates dplyr programming)

    ```R
    # From dplyr vignette
    library(dplyr)
    
    summariser <- quote(mean)
    
    my_summarise <- fn(df, ... ~ {
      group_by <- quos(...)
      df %>%
        group_by(QUQS(group_by)) %>%
        summarise(a = `!!`(summariser)(a))
    })
    
    my_summarise
    #> function (df, ...) 
    #> {
    #>   group_by <- quos(...)
    #>   df %>% group_by(`!!!`(group_by)) %>% summarise(a = mean(a))
    #> }
    ```

- **Currying** (literal unquoting also handy here)
    ```R
    compare_to <- curry_fn(target, x ~ identical(x, QUQ(target)))
    is_this <- compare_to("this")
    
    is_this
    #> function (x) 
    #> identical(x, "this")
    ```

Additionally, there are functional operators (`make_fn_aware()`, `as_fn()`) that enable higher-order functions (like `Reduce()`) to comprehend the `fn()` syntax.

**Comment by vspinu** [comment]
> It'd have to be unnamed and we throw an error otherwise. 

Here is my try:

```R
fn <- function(..., .env = caller_env()) {
    dots <- exprs(...)
    len <- length(dots)
    args <- dots[1:(len - 1)]
    stopifnot(all(have_name(args)))
    body <- dots[len]
    if(have_name(body))
        stop("Body (last element of `...`) must not be named")
    new_function(args, body[[1]], env = .env)
}

fn(a = 1, b = , c = a + b, {a + b + c})
#> function (a = 1, b, c = a + b) 
#> {
#>     a + b + c
#> }

fn(a = 1, b = , !!!ll(c = quote(a + b)), {a + b + c})
#> function (a = 1, b, c = a + b) 
#> {
#>     a + b + c
#> }

fn(a = 1, b = , c = a + !!(1 + 3), {a + b + c + !!(1 + 1)})
#> function (a = 1, b, c = a + 4) 
#> {
#>     a + b + c + 2
#> }
```

Not really sure how to handle unnamed arguments as `function` would do:

```R
> fn(a = 1, b, {a + b})
Error: all(have_name(args)) is not TRUE
```

> For consistency with is_ predicates and as_ coercers.

If all these are abbreviated then there is no inconsistency. It's a tough call indeed, but consistent naming within each class is probably more important than the meta-consistency across classes. Looks like having both versions of the function is the right approach indeed.

BTW, you have `as_env`, `as_environment`, `is_env` but not `is_environment` or `new_env`. Also, It looks to me that `is_expr` is better than `is_expression` because, well, there is already "expression" class and it's not yours:).  So, you are violating your own convention here . Then you have very similar looking is.expression from base. It all becomes confusing very quickly.

**Comment by lionel-** [comment]
>  but not is_environment

oops I'll add it shortly. `as_env()` is soft-deprecated (and `is_env()` will be as well), you can check out the topic `?lifecycle` to get an overview.

**Comment by vspinu** [comment]
Thanks @egnha! The use of ~ is interesting. Tho, my brain reads all those  `x ~ something`  as arguments. But, I guess, there is nothing one cannot get used to :)

**Comment by egnha** [comment]
@vspinu You're welcome. :-) I like to think of `~` as something like the `.` in lambda-calculus notation.

**Comment by lionel-** [comment]
Let's close this in favour of `new_function()`.
