### ISSUE TITLE
env_bind_quos

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#385]
```R
env_bind_quos <- function(env, ...) {
  quos <- dots_list(...)
  
  for (nm in names(quos)) {
    quo <- quos[[nm]]
    env <- env_bind_exprs(env, 
      !!nm := !!quo_get_expr(quo), 
      .eval_env = quo_get_env(quo)
    )
  }
  env
}
```

Needs more error checking, but I think this seems useful and parallels `env_bind_exprs()`. A real implementation would probably use `delayedAssign()` directly, except that it quotes the `value` argument.

(Note that `env_bind_expr()` should also mention explicitly that it quotes its arguments, and I think we can now simplify/unify the different quoting semantics)

**Comment by lionel-** [comment]
Should also call `eval_tidy()` on the quosure in order to support nested quosures (until we switch to thunk quosures).

**Comment by lionel-** [comment]
Actually once we have thunk quosures we can just use `env_bind_exprs()` with quosures. Do you need that function soon @hadley?

**Comment by hadley** [comment]
No urgency.
