### ISSUE TITLE
env_parents should stop at global_env by default

### ISSUE THREAD

**Issue by vspinu** [r-lib/rlang#386]
As env_parents is mostly useful at the REPL it should stop at `globalenv` by default. Something along these lines:

```R
#' @rdname env_parent
#' @param last Environment at which to end listing. Defaults to
#'   `global_env()`. Use `empty_env()` for the full stack that includes the
#'   search path.
#' @export
env_parents <- function(env = caller_env(), last = global_env()) {
    env <- get_env(env)
    out <- list()

    do <- TRUE
    i <- 1L 
    while (do) {
        nm <- environmentName(env)
        if (is.null(nm))
            nm <- i
        out[[nm]] <- env
        i <- i + 1L
        do <- !(is_reference(env, last) || is_empty_env(env))
        env <- env_parent(env)
    }

    out
}


```

**Comment by vspinu** [comment]
For completeness might be also good to have  `env_parent_names` and `env_parents_names`.

**Comment by lionel-** [comment]
I think I'd rather add a sentinel argument where we'd stop collecting environments, then you can supply `global_env()` as sentinel.

**Comment by vspinu** [comment]
This is what I just did with `last` argument in my version. globenv should be the default. Supplying globalenv each time I want to use it in the shell is hugely annoying, but in programs no-one minds.  The most useful function for interactive use is `env_parents_names` (or `map(env_parents(), env_names)`) and it doesn't make sense to print all names in the search path etc.

Btw, `sentinel` is too poetic and is used to express different meanings in different contexts.  `last` or `stopat`, or `end_with` etc are all better for this context IMO.

**Comment by lionel-** [comment]
Another function where we need to stop at the global env is `env_unbind()` with `inherit = TRUE`.

**Comment by hadley** [comment]
`global_env()` seems like a reasonable default to me. 

Maybe we could have an exception if the first argument is `global_env()`? i.e. `last = if (identical(env, globalenv()) emptyenv() else global_env()`. I think that gets us the best of both worlds (i.e. useful interactively, and to dig into how things work)
