### ISSUE TITLE
Revise `.named` argument of tidy dots

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#390]
- `dots_list()` should gain a `.named` argument (?)
- `.named = FALSE` should be "don't do anything", not "allocate empty names vector".
- deprecate `.named = <int>`. Maybe allow taking a deparsing function instead.

**Comment by hadley** [comment]
We need to make sure this is consistent with tibble, talk to @jennybc for full details.

(And maybe the tibble code should move to rlang)

**Comment by lionel-** [comment]
Needs an option for creating unique names.

**Comment by krlmlr** [comment]
Does this mean that unique name repair should move here?

+1 for a `.named` argument to `dots_list()`, this is my # 1 use case for `tibble::lst()` .
