### ISSUE TITLE
`call_modify` fails on `arg = NULL` when `arg` is not in the call

### ISSUE THREAD

**Issue by vspinu** [r-lib/rlang#393]
On deletion, the lookup of non-existing args is not consistent with `list[["arg"]] <- NULL` or `list$arg <- NULL`:

```R
> call_modify(quote(foo(a = 1)), ... = NULL)
Error in expr[[nm]] <- args[[nm]] : subscript out of bounds
```

This makes using deletion programatically inconvenient, as an extra check for arg presence is required.

**Comment by vspinu** [comment]
Conversely, how would you add `...` to a call consistently?

```R
> call_modify(quote(foo(a = 1)), quote(...)) # OK
foo(a = 1, ...)
> call_modify(quote(foo(a = 1, ...)), quote(...)) # Not OK
foo(a = 1, ..., ...)
```

Thanks.

**Comment by lionel-** [comment]
> Conversely, how would you add ... to a call consistently?

I'm not sure, but I think it wouldn't feel right to special-case `...` here.

**Comment by lionel-** [comment]
Hmm... Thinking more about it, it does make sense to special case it. In a way it is similar to a named argument.
