### ISSUE TITLE
Allow for duplicated arguments to `call_modify`

### ISSUE THREAD

**Issue by vspinu** [r-lib/rlang#398]
Some useful modification patterns are currently disallowed by the arg duplication check:

```R
tc <- quote(foo(a = 1, ..., b = 2))

## move ... towards the end
call_modify(tc, ... = NULL, ... = sym(""))
#> Error: Duplicate arguments

## modification with multiple sources
call_modify(tc, !!!ll(a = 2), !!!ll(a = 3))
#> Error: Duplicate arguments
```

Judging from the code of `call_modify` the modification of named args is incremental; so there is probably little reason to disallow duplication.

**Comment by hadley** [comment]
I agree we should remove it, and when #340 is implemented, we should make sure that `call_modify()`  can also control it (but default to no warning)
