### ISSUE TITLE
Hide `parse_quosures` in docs

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#407]

**Comment by lionel-** [comment]
Do you mean tagging with `internal` keyword? What about `parse_expr()`?

**Comment by lionel-** [comment]
Also maybe `parse_quo()` should not have a default for the `env` argument so that users are forced to think about what kind of environment they want to wrap the expression with.

**Comment by hadley** [comment]
I mean it should be aliased to that page, but not listed in usage
