### ISSUE TITLE
Suspect rlang 0.2.0 is causing an error in dplyr 0.7.4.

### ISSUE THREAD

**Issue by JohnMount** [r-lib/rlang#411]
I can not make a `reprex` out of this as reprex has stopped taking input from my clipboard. 

The code below used to work (with or without names) for `rlang` `0.1.6`.  Upgrading to `0.2.0` causes the error mentioned below.  If found this when warnings appeared on [`seplyr` CRAN checks](https://cran.r-project.org/web/checks/check_results_seplyr.html) and I suspect it may be related to errors appearing on [`dplyr` CRAN checks](https://cran.r-project.org/web/checks/check_results_dplyr.html).  In each case the CRAN architectures are: r-devel-linux-x86_64-debian-gcc, r-devel-linux-x86_64-fedora-clang, r-devel-linux-x86_64-fedora-gcc, and r-patched-linux-x86_64 .  

I myself see the error on OSX R version 3.4.3 (2017-11-30).

```r
library("dplyr")
packageVersion("dplyr")
# [1] ‘0.7.4’
packageVersion("rlang")
# [1] ‘0.2.0’
mp <- c("cyl" = "cylinders", "gear" = "gears")
rename_at(.tbl = datasets::mtcars, 
          .vars = names(mp), 
          .funs = funs(function(si) { mp[si] }))
# Error: All arguments must be named 
```

**Comment by lionel-** [comment]
I think you should have received an email about it one month ago, apologies if you didn't.

I'm not sure why this used to work but `funs()` doesn't take functions but expressions. The right syntax is:

```r
dplyr::rename_at(mtcars, 
  .vars = names(mp), 
  .funs = function(si) { mp[si] }
)
```

The error message could be better though, we should improve it.

**Comment by lionel-** [comment]
Alternatively you can unquote the function:

```r
rename_at(mtcars, 
  .vars = names(mp), 
  .funs = funs(!!function(si) { mp[si] })
)
```

**Comment by JohnMount** [comment]
I am fairly sure I did not get an email.  Also I would have expected`revdep::revdep_check()` should have caught both the `seplyr` and `dplyr` conflicts.

**Comment by lionel-** [comment]
It did, which is why I thought you should have received an email.

**Comment by JohnMount** [comment]
Did you get responses back from other packages you emailed?  The reason I ask is pretty much none of the non-RStudio packages marked as broken by the update incremented their version number.

**Comment by lionel-** [comment]
Yes. I had a problem with the revdepcheck database so I had to send the emails manually, your failure must have slipped through at the time sorry about this.

**Comment by JohnMount** [comment]
Ok, thanks.
