### ISSUE TITLE
Entry point Not Found

### ISSUE THREAD

**Issue by ysm1nz** [r-lib/rlang#416]
I am trying to load the library and get the message "The procedure entry point R_ExternalPtrAddrFn could not be located in the dynamic link library R.dll."
Version rlang_0.2.0 windows binary release.
I'm using R version 3.4.3. I have to download and install all packages manually because of my company's firewall.

**Comment by lionel-** [comment]
It looks like it's trying to link with an old R version?

**Comment by ysm1nz** [comment]
If that is the case, any advice on what to do about it? Thanks

**Comment by lionel-** [comment]
I have very little experience troubleshooting this kind of issue :(

Any idea @jimhester @gaborcsardi?

If you have the development tools installed you can probably fix it by recompiling with `devtools::install_github("cran/rlang")`.

**Comment by gaborcsardi** [comment]
`R_ExternalPtrAddrFn` is new and it is not present in older R versions.

**Comment by lionel-** [comment]
There is a compat in rlang and whether to use it is decided at build-time. Here the rlang library tries to link to the symbol in `R.dll` so it was compiled against a recent R and doesn't use the compat. @ysm1nz is using a recent R so it should work. Maybe there are some other versions of R installed on the system that rlang is trying to link to?

**Comment by gaborcsardi** [comment]
Yeah, sorry, I just read the thread now.

**Comment by gaborcsardi** [comment]
Maybe there is simply an older rlang in the lib path? I would print `.libPaths()` and see if there is an rlang package in there....

**Comment by gaborcsardi** [comment]
Still, maybe it is the wrong binary, since it is clearly a binary incompatibility issue. Can you just try re-downloading and reinstalling rlang?

**Comment by lionel-** [comment]
> Maybe there are some other versions of R installed on the system that rlang is trying to link to?

It seems like this ^ does not make sense either. AFAIK (not much) R is the one loading the DLL and there is no way for rlang to try to link to something else?

**Comment by sandJohnson** [comment]
I had exactly the same problem today, and I also work in a similar setup to ysmnz1. I was able to load packages fine yesterday & today I get this error when trying to load the dplyr package in R Studio. I just installed the latest version of R Studio, and then I checked if I could still load dplyr in R rather than R Studio. This worked fine. What finally worked for me was to go to RStudio and to check the path of the R library (Tools > Global Options...) and it was set to Microsoft\R Client\SERVER, so once I changed that to point instead to C:\Program Files\R\R-3.4.3 all worked fine

**Comment by lionel-** [comment]
Thanks for your input @sandJohnson

**Comment by gregkvas** [comment]
I experienced that the "Entry Point" error message (concerning "rlang.dll", "Rcpp.dll" or other .dll) occures when using/choosing a lower R version in RStudio on packages of a higher built , i.e. using R 3.4 on packages of built 3.5, e.g. after using update.packages(..., checkBuilt = TRUE) on user library of lower R Version 3.4...after getting rid of the packages of the higher built or re-installing them on the lower built in the user library, no "Entry Point" error messages occure anymore when using the lower R Version R 3.4...

**Comment by lionel-** [comment]
Perhaps we should build these compats in separate shared libs installed in `inst/`, and dynamically link to them at runtime.

But in general it's not safe to run packages built for a newer R on older R, so I'm not sure it's worth the effort.

I use this in my `.Renviron` file:

```
R_LIBS_USER= ~/R/library/%v/
```

This creates one package library per major R version.

**Comment by lionel-** [comment]
Maybe worth detecting these situations at load time and point to some documentation about managing different libraries?

**Comment by gaborcsardi** [comment]
Yeah, if we had some self-contained code, that we could just use in all packages with compiled code, that would  be good, I think.

**Comment by gregkvas** [comment]
@lionel- and @gaborcsardi thanks for your comments! It seems to me that the most secure way to prevent .dll-error.messages as mentioned above is to keep R Version and the used packages as homogenous as possible in terms of their built...

**Comment by hakhandan** [comment]
I had the same issue. I noticed that after updating to a newer version of R, I was mistakenly opening R through a shortcut pinned in the Taskbar which was indeed from the older version!!!!
