### ISSUE TITLE
unquoting in for-loops since v0.2.0?

### ISSUE THREAD

**Issue by pkimes** [r-lib/rlang#417]
I recently started using rlang-0.2.0 and realized that unquoting in for-loops is being performed in a way that I didn't expect (and different from rlang-0.1.6). I've included a minimal example.

I can't tell if this is a feature or a bug (since it's different from rlang-0.1.6), so I thought I'd ask.
Thanks!

## Minimal Example

```
addstuff <- function(obj, label, value) {
    obj$stuff[[label]] <- enquo(value)
    obj
}

b <- b2 <- list()
for (i in 1:3) { 
    b <- addstuff(b, paste0("entry-", i), !!i) 
}
for (i in 1:3) { 
    b2 <- addstuff(b2, paste0("entry-", i * 1), !!i)
}

sapply(b$stuff, eval_tidy)
# entry-1 entry-2 entry-3
#       1       2       3

sapply(b2$stuff, eval_tidy)
# entry-1 entry-2 entry-3
#       3       3       3
```
I don't quite understand how adding the `i * 1` suddenly causes the `!!i` values to be re-evaluated at every iteration of the loop.

Also, putting the two together in a single for-loop seems to make things "fine" (or at least returns what I was seeing using rlang-0.1.6).
```
b <- b2 <- list()
for (i in 1:3) {
    b <- addstuff(b, paste0("entry-", i), !!i)
    b2 <- addstuff(b2, paste0("entry-", i * 1), !!i)
}
sapply(b$stuff, eval_tidy)
# entry-1 entry-2 entry-3
#       1       2       3

sapply(b2$stuff, eval_tidy)
# entry-1 entry-2 entry-3
#       1       2       3
```

## Session Info
```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS/LAPACK: /usr/local/Cellar/openblas/0.2.20/lib/libopenblasp-r0.2.20.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] rlang_0.2.0.9000

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.4.2  R6_2.2.2        tools_3.4.2
 [5] withr_2.1.1     curl_3.1        crayon_1.3.4    memoise_1.1.0
 [9] git2r_0.19.0    digest_0.6.14   devtools_1.13.4
```

**Comment by lionel-** [comment]
Interesting, thanks for this report. This looks like a bug, but in the mean time you can `force(i)` at the start of the loop to work around this:

```
x <- new_list(3)

for (i in 1:3) {
  x[[i]] <- quo(!!i)
}

x
#> <quosure>
#>   expr: ^3L
#>   env:  empty
#>
#> [[2]]
#> <quosure>
#>   expr: ^3L
#>   env:  empty
#>
#> [[3]]
#> <quosure>
#>   expr: ^3L
#>   env:  empty

for (i in 1:3) {
  force(i)
  x[[i]] <- quo(!!i)
}

x
#> <quosure>
#>   expr: ^1L
#>   env:  empty
#>
#> [[2]]
#> <quosure>
#>   expr: ^2L
#>   env:  empty
#>
#> [[3]]
#> <quosure>
#>   expr: ^3L
#>   env:  empty
```

**Comment by JohnMount** [comment]
That is related to a trailing reference issue that many programing languages (unfortunately have).  Here are some notes I made on looking into this kind of situation: http://www.win-vector.com/blog/2017/02/iteration-and-closures-in-r/ .

**Comment by lionel-** [comment]
There is no laziness involved here, so it's not related. I'm not sure what's going on.

**Comment by pkimes** [comment]
Thanks for the temporary workaround!

**Comment by JohnMount** [comment]
@lionel- All I meant to do was help. 

Closure references and for-loops has always been a tricky issue for a number of functional languages (often due to re-use of references). The word "lazy" was used in a side discussion of some additional R details that showed why the fix that works in other languages that have the problem (F# and go) needs a bit more care in R.  I did not say the source of the problems was lazy evaluation, and understand this may not match this issue- but that there are known issues in many other languages that may give one a jumping off point to other research and note that help.

So- no I don't think laziness is involved here either.

**Comment by lionel-** [comment]
If you evaluate eagerly (e.g. unquote) there can't be any problem. I think this is a bug, though I don't understand it.

**Comment by lionel-** [comment]
It looks like this has been fixed at some point. I have added a unit test to cover unquoting within for loops.

**Comment by lionel-** [comment]
This was because the refcount of unquoted objects was not bumped. So the for loop code was recycling the same index object.
