### ISSUE TITLE
search_envs()

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#422]
Return a named list of environments, instead of a character vector

**Comment by hadley** [comment]
Definition is just `env_parents(globalenv())`

**Comment by hadley** [comment]
Actually it's slightly different - `search()` includes `globalenv()` but not `emptyenv()`.

**Comment by lionel-** [comment]
@hadley Do you want the empty env in that list? It's currently how `scoped_envs()` (to be renamed to `search_envs()`) is defined.

**Comment by hadley** [comment]
I think ideally it would match `search()` exactly
