### ISSUE TITLE
Function to unlock environments

### ISSUE THREAD

**Issue by jimhester** [r-lib/rlang#423]
I recently needed to add a function to unlock environments to pkgload https://github.com/r-lib/pkgload/blob/0cd9f8d9d455f447a0449513fa27745417289f73/src/unlock.c#L18-L31

Unfortunately requiring compiled code in devtools and its immediate dependencies makes upgrading them more challenging for users on Windows.

Would you consider adding a similar function to rlang? pkgload already has a dependency on rlang, and I could see this being useful (if not generally recommended) in a few other scenarios outside of the pkgload context.

**Comment by lionel-** [comment]
We can add it to rlang and mark it with `@keyword internal`. I think the long term plan is to move all dangerous functions like `node_car()` to a `danger` package so eventually it might be moved there.
