### ISSUE TITLE
Provide infix operators for active and delayed assignment?

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#424]
Like `%<a-%` and `%<d-%` from pryr.

Or are those too specialised?

**Comment by lionel-** [comment]
I think this is too specialised. Also IMO operators should only be added sparingly because they tend to make R code more difficult to read so the payoff has to be important.

**Comment by t-kalinowski** [comment]
I just came across this thread while looking for an active assignment operator. I see that rlang has `%<~%` for delayed assignment. Maybe it makes sense now to add a companion for active bindings? Maybe something like `%<+%`? 

Motivation: in keras, we export `%<-active%` as a convenient way to create the equivalent of python decorated `@property` class methods. I was looking at moving some of the python class generating routines to reticulate, but would rather avoid adding symbols to reticulate that are not strictly python related, like `%<-active%` would be. 

It's just a simple:
```r
`%<-active%` <- function(sym, value) {
  makeActiveBinding(substitute(sym), value, parent.frame())
  invisible(value)
}
```
With intended usage like:
``` r
library(keras)

MyClass %py_class% {
  initialize <- function(x) {
    print("Hi from MyClass$initialize()!")
    self$x <- x
  }
  my_property %<-active% function(x = NULL) {
    if(is.null(x))
      cat("my_property accessed\n")
    else 
      cat("my_property assigned value:", x, "\n")
  }
}

inst <- MyClass("foo")
#> [1] "Hi from MyClass$initialize()!"
inst$x
#> [1] "foo"
inst$my_property
#> my_property accessed
#> NULL
inst$my_property <- "bar"
#> my_property assigned value: bar
```
