### ISSUE TITLE
env_show

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#425]
Something like `str(as.list(e))`, but only one line per element, using `tibble::type_sum()` and what the quosure pretty printer uses for small inline objects.

**Comment by hadley** [comment]
And print the parent environment.

**Comment by hadley** [comment]
And print `environmentName(x)` if it's not `""`

**Comment by hadley** [comment]
Something like this maybe:

```R
e <- env(a = 1)
e$e <- e

env_bind_exprs(e, x = cat("!"))
env_bind_fns(e, y = function(v) runif(1))

env_show(e)
#> Name: 0x10be939c0
#> Parent: R_GlobalEnv
#> Bindings:
#> * a: <dbl>
#> * b: <env>
#> * x: <delayed>
#> * y: <active>
```

**Comment by lionel-** [comment]
@hadley would it better be called `env_print()`?
