### ISSUE TITLE
env_poke should return invisibly

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#426]
Since its called for its side-effects

**Comment by hadley** [comment]
Or should it return the previous value?

**Comment by lionel-** [comment]
Previous discussion: #178

**Comment by lionel-** [comment]
Hmm should it return `NULL` or the missing arg when the binding did not exist yet? Missing arg seems more correct but user will have to test with `is_missing()`.

**Comment by hadley** [comment]
I think `NULL` is probably fine.
