### ISSUE TITLE
Should env_ functions be internally generic

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#427]
Not the parent of that environment.

``` r
library(rlang)

f <- function() {}
env_parent(f)
#> <environment: package:rlang>
#> attr(,"name")
#> [1] "package:rlang"
#> attr(,"path")
#> [1] "/Users/hadley/R/rlang"
```

Created on 2018-02-28 by the [reprex package
(0.1.1.9000)](https://cran.r-project.org/package=reprex).

**Comment by hadley** [comment]
Or should this be `parent_env()` to match `current_env()` etc

**Comment by lionel-** [comment]
Should we deprecate the internal genericity of `env_` functions?

**Comment by hadley** [comment]
I renamed the title of this issue. Another typo that this behaviour makes confusing:

``` r
library(rlang)
env_bind(env, x = 1)
#> Error in base::assign(nm, data[[nm]], envir = env_): cannot add bindings to a locked environment
```

Created on 2018-03-08 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
