### ISSUE TITLE
What is the parent of the empty environment?

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#428]
``` r
library(rlang)
env_parent(empty_env())
#> <environment: R_EmptyEnv>
parent.env(empty_env())
#> Error in parent.env(empty_env()): the empty environment has no parent
```

Created on 2018-02-28 by the [reprex package
(0.1.1.9000)](https://cran.r-project.org/package=reprex).

Returning `empty_env()` seems like a bad idea, as it'll make it easier to get stuck in infinite loops.

**Comment by lionel-** [comment]
The idea was to reproduce lisp idioms where `cdr(nil)` is `nil`, but I agree an error is probably more helpful.
