### ISSUE TITLE
env_label()

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#435]
Something like:

```R
env_label <- function(x)  {
  name <- environmentName(x)
  if (identical(name, "")) {
    pryr::address(x)
  } else {
    name
  }
}
```

**Comment by hadley** [comment]
Note that `search()` special cases the name of the global environment and the base environment. We'll need to decide if we want to copy this, or be consistent with the rest of R.

Or maybe it's better to copy what `print.default()` does? It eventually calls [`encodeEnvironment()`](https://github.com/wch/r-source/blob/fed0444824567e1c4edff234fc5c2fb1c99bbc84/src/main/printutils.c#L148)

**Comment by lionel-** [comment]
I think we should special case but with nicer names than base R provides. We actually have some code for this in the quosure printing method:

```r
quo_env_print <- function(env) {
  if (is_reference(env, global_env())) {
    nm <- "global"
  } else if (is_reference(env, empty_env())) {
    nm <- "empty"
  } else {
    nm <- blue(sexp_address(env))
  }
  meow(nm)
}
```

**Comment by lionel-** [comment]
It might make sense to have `env_name()` in addition to `env_label()`. Only the latter would return the sexp address. This way `env_name()` can be used e.g. to name the list returned by `env_parents()`. It seems appropriate that anonymous environments wouldn't be named.
