### ISSUE TITLE
child_env() doesn't check for duplicate names

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#437]
``` r
library(rlang)
child_env(globalenv(), a = 1, a = 2)
#> <environment: 0x7f908ec09aa0>
```

Created on 2018-03-02 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by lionel-** [comment]
Should this be the behaviour for all env functions? Just overwrite if there are dups.

**Comment by hadley** [comment]
Maybe, but I got the sense from this error message you were trying to throw an error here:

``` r
library(rlang)
child_env(globalenv(),2)
#> Error: Can't bind data because it is not uniquely named
```

And an error seems more helpful.
