### ISSUE TITLE
Wrappers around binding locking?

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#440]
e.g. `lockBinding()`, `unlockBinding()`, `bindingIsLocked()`. Maybe `env_lock(), `env_unlock()`, and `env_is_locked()`?

**Comment by lionel-** [comment]
The challenge is to find a naming scheme consistent with environment locking, cf #423

**Comment by lionel-** [comment]
I'm tempted to use the same functions for both bindings and the environment depending on whether bindings were supplied. But I think the functions should be separate because environment locking should be internal and non-documented as it is using R's non public API.
