### ISSUE TITLE
env_list helper class?

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#441]
To provide a more compact print method, e.g.

```R
env_parents(global_env())
#> [[1]]  <environment: package:rlang>
#> [[2]]  <environment: package:methods>
#> [[3]]  <environment: package:stats>
#> [[4]]  <environment: package:graphics>
#> [[5]]  <environment: package:grDevices>
#> [[6]]  <environment: package:utils>
#> [[7]]  <environment: package:datasets>
#> [[8]]  <environment: 0x7f8fef8b3ff0>
#> [[9]]  <environment: base>
#> [[10]] <environment: R_EmptyEnv>
```

And this should use `env_label()` so you get `<environment: Autoloads>` instead of `<environment: 0x7f8fef8b3ff0>`

**Comment by hadley** [comment]
Well actually this will eventually be a named list, so each line should start with `$` and use the label.

**Comment by lionel-** [comment]
@hadley I wonder if the sentinel for `env_parents()` should always be the empty env, and we'd truncate the print output instead:

```
env_parents(env(env(env(env()))))
#> [[1]]  <env: 0x7f7f4783ed10>
#> [[2]]  <env: 0x7f7f45eb6758>
#> [[3]]  <env: 0x7f7f47c54ae0>
#> [[4]]  <env: global>
#> ... with 11 more environments on the search path
```

cc @vspinu

**Comment by vspinu** [comment]
Would work for me.

I would also want to see a few names of the contained objects: 

```
env_parents(env(env(env(env()))))
##> [[1]] <env: 0x7f7f4783ed10>  # foo, bar, baz ... 10 more
##> [[2]] <env: 0x7f7f45eb6758>  # foo2, bar2, baz2 ... 20 more
##> [[3]] <env: 0x7f7f47c54ae0>  # foo3, bar3, baz3 ... 30 more
##> [[4]] <env: global>          # foo4, bar4, baz4 ... 40 more
##> ... with 11 more environments on the search path
```

**Comment by lionel-** [comment]
That might be nice but it makes it much more complicated to write the printer because you now have to deal with width.

**Comment by lionel-** [comment]
Could be quite useful for debugging, possibly.

**Comment by vspinu** [comment]
I think width could be disregarded here. Names are usually short. Just print top 4 names (like str does), better 6-7; ideally not starting with the special names.

**Comment by lionel-** [comment]
as a stopgap but a print method should take into account width otherwise it causes problems in knitr etc

**Comment by lionel-** [comment]
and I'm fairly certain you'll get line breaks all the time when working on a 13'' with vertical split screen

**Comment by lionel-** [comment]
@hadley could you advise on https://github.com/r-lib/rlang/issues/441#issuecomment-371650910 too please

**Comment by hadley** [comment]
Hmmm, I think the default sentinel env would always be `globalenv()`, and you'd also always terminate on `emptyenv()`. I think that strikes a good balance between correctness and usefulness.
