### ISSUE TITLE
r_push_attribute(x,tag,value) should attach tag to new attribute value before calling SET_ATTRIB.

### ISSUE THREAD

**Issue by BillDunlap** [r-lib/rlang#446]
In rlang/src/lib/attrs.c r_push_attribute(x,tag,value) is used to add an attribute called
'tag' with value 'value' to the object 'x'.  It works by getting the pairlist, attrs, of tagged attributes
of x from ATTRIB(x), adding the new attribute value to the pairlist, calling SET_ATTRIB(x,attrs),
and finally adding the tag.

If it added the tag before calling SET_ATTRIB then SET_ATTRIB could do a bit of error checking
and caching based on the name of the new attribute.  (TERR does some caching for certain
attributes, like names, but R does not yet.)  It also seems wrong to have a nameless attribute,
even for a short time.

Here is a change that doesn't seem to cause any problems, but perhaps you had a good
reason for naming the attribute after it was attached to the object.

-Bill Dunlap

```diff
--- /homes/bill/CRAN/rlang/src/lib/attrs.c      2018-02-19 22:15:49.000000000 -0800
+++ rlang/src/lib/attrs.c       2018-03-07 17:04:16.553244000 -0800
@@ -19,8 +19,8 @@

 sexp* r_push_attribute(sexp* x, sexp* tag, sexp* value) {
   sexp* attrs = r_new_node(value, r_get_attributes(x));
-  r_poke_attributes(x, attrs);
   r_node_poke_tag(attrs, tag);
+  r_poke_attributes(x, attrs);
   return attrs;
 }
```

**Comment by akbertram** [comment]
Fixes the problem with Renjin as well! Thanks!
