### ISSUE TITLE
Flatten a list of quosures?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/rlang#450]
Is there an accepted way to do this?

``` r
library(rlang)

quos_list <- list(quos(x = 4, z = 4), quos(y = 5))

# A list where the elements are quosures
quos_list
#> [[1]]
#> $x
#> <quosure>
#>   expr: ^4
#>   env:  empty
#> 
#> $z
#> <quosure>
#>   expr: ^4
#>   env:  empty
#> 
#> 
#> [[2]]
#> $y
#> <quosure>
#>   expr: ^5
#>   env:  empty

# Flatten doesn't work
flatten(quos_list)
#> [[1]]
#> $x
#> <quosure>
#>   expr: ^4
#>   env:  empty
#> 
#> $z
#> <quosure>
#>   expr: ^4
#>   env:  empty
#> 
#> 
#> [[2]]
#> $y
#> <quosure>
#>   expr: ^5
#>   env:  empty

# I kind of want this
unlist(quos_list)
#> $x
#> <quosure>
#>   expr: ^4
#>   env:  empty
#> 
#> $z
#> <quosure>
#>   expr: ^4
#>   env:  empty
#> 
#> $y
#> <quosure>
#>   expr: ^5
#>   env:  empty

# But the quosures class is lost
class(quos_list[[1]])
#> [1] "quosures"
class(unlist(quos_list))
#> [1] "list"
```

Created on 2018-03-08 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by lionel-** [comment]
That's because of the `quosures` class. You can do this:

```r
flatten_if(quos_list, is_quosures)
```

**Comment by lionel-** [comment]
you will necessarily lose the quosures class.

**Comment by lionel-** [comment]
If you want to flatten any lists no matter the class you can also do `flatten_if(x, is_list)`.

**Comment by DavisVaughan** [comment]
I'm also seeing that I can splice the individual list element beforehand.

```r
flatten(map(quos_list, splice))
```

**Comment by lionel-** [comment]
`splice()` will probably be deprecated.

**Comment by ablack3** [comment]
I think I'm working on a similar problem. I would like to take a list of quosures, combine them into a single expression with the pipe and then evaluate. I can get this idea to work using `expr` but not `quo`. The underlying idea here is programmatically generating dplyr pipelines.

```
library(dplyr)
library(rlang)

(expr_list <- list(expr(mtcars), expr(group_by(cyl)), expr(summarise(count = n()))))
#> [[1]]
#> mtcars
#> 
#> [[2]]
#> group_by(cyl)
#> 
#> [[3]]
#> summarise(count = n())

(final_expr <- purrr::reduce(expr_list, function(arg1, arg2) expr(!!arg1 %>% !!arg2)))
#> mtcars %>% group_by(cyl) %>% summarise(count = n())

eval_tidy(final_expr)
#> # A tibble: 3 x 2
#>     cyl count
#>   <dbl> <int>
#> 1  4.00    11
#> 2  6.00     7
#> 3  8.00    14
```

**Comment by lionel-** [comment]
The magrittr pipe doesn't support quosures as it is using a different kind of NSE.

**Comment by lionel-** [comment]
If all components come from the same context you can use raw expressions and evaluate the pipeline in that environment though (or store the pipeline in a quosure to be evaluated later or in a larger expression).

**Comment by lionel-** [comment]
> If all components come from the same context you can use raw expressions and evaluate the pipeline in that environment though

You may have to add `%>%` to a data mask to make sure it is in scope (but that may be undesirable as `<-` will assign in a wrong context). The alternative is to require the user to attach magrittr to the search path.
