### ISSUE TITLE
env_print tweaks

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#452]
```R
<environment: 0x107aa5588>
  parent: <env: global>
  bindings:
   * a: <dbl>
   * b: <dbl>
```

I think the first environment should also be abbreviated (or the second should be expanded), and I think there's a bit too much indenting. Maybe something more like:

```R
<env: 0x107aa5588>
Parent: <env: global>
Bindings:
*  a: <dbl>
*  b: <dbl>
```

**Comment by hadley** [comment]
I'm also not 100% sure that using `global` instead of `R_GlobalEnv` helps, because you're still going to see `R_GlobalEnv()` when you print the global environment.

**Comment by lionel-** [comment]
About indenting, it should probably be consistent across all print methods. Here is the current quosure printing:

```r
rlang::quo(bim)
#> <quosure>
#>   expr: ^bim
#>   env:  global
```

I think this is less readable:

```r
rlang::quo(bim)
#> <quosure>
#> expr: ^bim
#> env:  global
```

**Comment by hadley** [comment]
What if we bolded `<quosure>`/`<environment: 0x234afe>`?
