### ISSUE TITLE
Feature Request: source() + Time Progress Base

### ISSUE THREAD

**Issue by jtelleriar** [r-lib/rlang#459]
It might prove useful to create an improved source() function which:
a) Includes a Progress Bar, by detecting when each high level Operator Assignation has been called (<-) from within the Total Assignment Operators (<-) in the Source Script.
b) And include a timer, which shows the lapsed time since the source() statement was triggered, by simply calculating time interval difference since the script stated to execute.

**Comment by lionel-** [comment]
This might be a nice project but rlang is probably not the home for this.
