### ISSUE TITLE
Auto-naming and .data

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#468]
Expecting to see `homeworld` or `.data[[my_var]]` as column name here, but not `my_var`:

```
library(tidyverse)
my_var <- "homeworld"

starwars %>%
  group_by(.data[[my_var]]) %>%
  summarise_at(vars(height:mass), mean, na.rm = TRUE)
# # A tibble: 49 x 3
#            my_var   height  mass
#             <chr>    <dbl> <dbl>
#  1       Alderaan 176.3333  64.0
#  2    Aleen Minor  79.0000  15.0
#  3         Bespin 175.0000  79.0
#  4     Bestine IV 180.0000 110.0
#  5 Cato Neimoidia 191.0000  90.0
#  6          Cerea 198.0000  82.0
#  7       Champala 196.0000   NaN
#  8      Chandrila 150.0000   NaN
#  9   Concord Dawn 183.0000  79.0
# 10       Corellia 175.0000  78.5
# # ... with 39 more rows
```

From https://github.com/tidyverse/dplyr/issues/2991, CC @bilydr.

**Comment by lionel-** [comment]
To fix this without double evaluation I think `quos_auto_name()` should expand `.data[[my_var]]` to `string = .data[["string"]]`. This will cause partial evaluation of the expression before `eval_tidy()` is called. This seems ok in that case. cc @hadley

**Comment by hadley** [comment]
I think we should leave as is for now; I want us to think about this more deeply.
