### ISSUE TITLE
Special error class that contains more information

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#481]
For common errors in heavily used tidyverse packages, it would be nice to be able to provide additional information for new users. This could include a longer block of text, and/or a url where more information could be had.

We could then work with the IDE team to provide that information with an expando, and an optional clickable link.

**Comment by lionel-** [comment]
Is this about the idea of generating short unique URLs for warnings and errors that would point to Community threads?

**Comment by hadley** [comment]
Yes, but also potentially a longer paragraph of text that would only be displayed upon request (hence the need for IDE integration)

**Comment by lionel-** [comment]
Closing for now.
