### ISSUE TITLE
quos() and NextMethod() in R 3.1

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#486]
don't work as expected, but only in R 3.1. Related to https://github.com/tidyverse/dplyr/issues/3509. This is with the CRAN version of *rlang*.

``` r
library(rlang)

fn <- function(x, ...) UseMethod("fn")

fn.default <- function(x, ...) quos(...)

fn.numeric <- function(x, ...) NextMethod()

fn("1", a)
#> [[1]]
#> <quosure>
#>   expr: ^a
#>   env:  global
fn(1, a)
#> [[1]]
#> <quosure>
#>   expr: ^..1
#>   env:  0x561933d96490
```

> Created on 2018-04-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Do you see a clean workaround for R 3.1 with current rlang? I could just avoid calling `NextMethod()`.

In the long run this will impede usage of `sloop::reconstruct()`.

**Comment by lionel-** [comment]
I think we are going to drop support for R 3.1 soonish, so probably not worth spending time on this.
