### ISSUE TITLE
is_bare_ predicates should return FALSE with matrices and arrays

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#493]

**Comment by hadley** [comment]
Maybe `bare` should become `vector`?

**Comment by lionel-** [comment]
hmm though we also use `bare` for non vector objects like environments.

**Comment by lionel-** [comment]
Maybe just add a matching argument `dim = NULL` like we have `n = NULL` to vector predicates.

* If `NULL`, dims are not taken into account.
* If `TRUE`, check that dim is defined.
* If `FALSE` check it's a non-dimensional vector.
* If a numeric vector, check that the dims match.

The default could be set to `FALSE` for `_bare_` predicates.

**Comment by lionel-** [comment]
I think because I was using `is_bare_` for checking for bare vectors, and was surprised to get a matrix instead. I can't remember where this occurred though.

In most cases it's not important since matrices and arrays implement the vector interface and shouldn't usually cause unexpected results when you're expecting vectors. The main issue I see is that these matrixes won't dispatch on atomic S3 methods, which you might expect if you've checked for a bare vector.

**Comment by lionel-** [comment]
We could hardcode `is.null(dim(x))` in the bare_ predicates rather than adding dims to the interface.

**Comment by hadley** [comment]
Without a specific motivating example, I'd rather leave the code as is. Dimensions seems to be more the province of vctrs, anyway.
