### ISSUE TITLE
Able to use rlang::UQ() but not rlang::`!!`()

### ISSUE THREAD

**Issue by bschneidr** [r-lib/rlang#496]
For data analysis scripts, I often find that rlang is useful once or twice in the script, so I only want to use the exported functions rather than load the whole package.

One common use case is when I have a variable column name stored as a string and I want to use `!!sym(col_name)` so that I can perform an arbitrary operation such as `count(data, !!sym(col_name))`.

Without loading rlang, it's easy to do this using `rlang::UQ(rlang::sym(col_name))`. But at that moment we can't do the seemingly equivalent `` rlang::`!!`(rlang::sym(col_name)) ``. Here's a simple example:

    library(dplyr)

    col_name <- "Species"

    # This works
    select(iris, rlang::UQ(rlang::sym(col_name)))

    # This doesn't
    select(iris, rlang::`!!`(rlang::sym(col_name)))

Could the `` `!!`() `` function be updated to allow it to work without having to load rlang?

**Comment by lionel-** [comment]
`rlang::UQ()` is going to be deprecated, please use `UQ()` instead. It is not a function call but a syntactic operator. For that reason we're even questioning `UQ()` altogether because it doesn't seem right to overload the function call syntax with unquoting. I would advise using `!!`.

**Comment by lionel-** [comment]
Another reason to deprecate the namespaced syntax is that it is not consistent:

```r
sym <- quote(quux)

expr(foo(rlang::UQ(sym)))
#> foo(quux)

expr(foo(othernamespace::UQ(sym)))
#> foo(othernamespace::quux)
```

**Comment by lionel-** [comment]
(In case it is not clear, you can use both `UQ()` and `!!` without having to attach rlang to the search path.)

**Comment by lionel-** [comment]
Finally (sorry for the cascading emails) writing

```r
rlang::`!!`(foo)
```

is like writing namespaced operators in model formulas:

```r
lm(y ~ stats::`+`(foo, bar))
```

It does not make much sense ;)

**Comment by bschneidr** [comment]
Thanks for the quick replies!

Does all this mean that we can use the `!!` operator without having to load rlang or do something awkward like write `` `!!` <- rlang::`!!` `` at the top of a script?

So the following code would be the standard way of making use of syntax like `!!sym(col_name)` without loading rlang?

    library(dplyr)

    col_name <- "Species"
    select(iris, !!rlang::sym(col_name))

**Comment by roammi** [comment]
sometimes !! or UQ() are not recognized, for some reason I have to restart R and then it works,
