### ISSUE TITLE
abort() should create call component, not .call

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#497]
``` r
library(rlang)
c <- catch_cnd(abort("An error"))
str(c)
#> List of 2
#>  $ message: chr "An error"
#>  $ .call  : NULL
#>  - attr(*, "class")= chr [1:2] "error" "condition"
```

Created on 2018-05-02 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
(To be consistent with the specification of the condition object)

**Comment by lionel-** [comment]
But that will cause the call to be printed out.

**Comment by lionel-** [comment]
Maybe we should just replace `.call` with `.stack` anyway?

**Comment by hadley** [comment]
Isn't printing the call the point of the `call` argument?

**Comment by lionel-** [comment]
Yes but we decided at the time that we would always store the call in the `.call` slot even when it's not printed. But this seems to be superseded by #474

**Comment by lionel-** [comment]
Note that you see `NULL` because the call is recorded one level up and you called abort in the global frame:

```r
fn <- function(...) abort("foo")
err <- catch_cnd(fn(bar))
str(err)
#> List of 2
#>  $ message: chr "foo"
#>  $ .call  : language fn(bar)
#>  - attr(*, "class")= chr [1:2] "error" "condition"
```
