### ISSUE TITLE
Compilation Error rlang

### ISSUE THREAD

**Issue by JonnyPhillips** [r-lib/rlang#513]
I'm experiencing a compilation error installing the development version of rlang. The error has been replicated on four different windows systems (R3.4.3 and R3.4.4), and was initially encountered when trying to install the development version of ggplot2 (which has rlang as a dependency). The error and sessioninfo are below. Apologies if this is not an error in rlang itself, but I'd be grateful for any advice.

> devtools::install_github("r-lib/rlang")
Downloading GitHub repo r-lib/rlang@master
from URL https://api.github.com/repos/r-lib/rlang/zipball/master
Installing rlang
"C:/PROGRA~1/MICROS~1/ROPEN~1/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/Jonny/AppData/Local/Temp/RtmpOcryYW/devtools14485bac3de6/r-lib-rlang-1bd3ebe"  \
  --library="C:/Users/Jonny/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'rlang' ...
** libs
C:/RBuildTools/3.4/mingw_64/bin/gcc -m64 -I"C:/PROGRA~1/MICROS~1/ROPEN~1/R-34~1.4/include" -DNDEBUG -I./lib/    -I"C:/swarm/workspace/External-R-3.4.4/vendor/extsoft/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c capture.c -o capture.o
C:/RBuildTools/3.4/mingw_64/bin/gcc -m64 -I"C:/PROGRA~1/MICROS~1/ROPEN~1/R-34~1.4/include" -DNDEBUG -I./lib/    -I"C:/swarm/workspace/External-R-3.4.4/vendor/extsoft/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c export.c -o export.o
In file included from export.c:1:0:
export/exported.c: In function 'rlang_cnd_type':
export/exported.c:28:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
C:/RBuildTools/3.4/mingw_64/bin/gcc -m64 -I"C:/PROGRA~1/MICROS~1/ROPEN~1/R-34~1.4/include" -DNDEBUG -I./lib/    -I"C:/swarm/workspace/External-R-3.4.4/vendor/extsoft/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c internal.c -o internal.o
C:/RBuildTools/3.4/mingw_64/bin/gcc -m64 -I"C:/PROGRA~1/MICROS~1/ROPEN~1/R-34~1.4/include" -DNDEBUG -I./lib/    -I"C:/swarm/workspace/External-R-3.4.4/vendor/extsoft/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c lib.c -o lib.o
In file included from lib.c:8:0:
lib/cnd.c:142:24: fatal error: Rinterface.h: No such file or directory
 #include <Rinterface.h>
                        ^
compilation terminated.
make: *** [lib.o] Error 1
Warning: running command 'make -f "Makevars" -f "C:/PROGRA~1/MICROS~1/ROPEN~1/R-34~1.4/etc/x64/Makeconf" -f "C:/PROGRA~1/MICROS~1/ROPEN~1/R-34~1.4/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="rlang.dll" WIN=64 TCLBIN=64 OBJECTS="capture.o export.o internal.o lib.o"' had status 2
ERROR: compilation failed for package 'rlang'
* removing 'C:/Users/Jonny/Documents/R/win-library/3.4/rlang'
In R CMD INSTALL
Installation failed: Command failed (1)

> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtils_10.0.9     RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.4.4  R6_2.2.2        tools_3.4.4     withr_2.1.2     curl_3.2       
 [7] yaml_2.1.18     memoise_1.1.0   knitr_1.20      git2r_0.21.0    digest_0.6.15   devtools_1.13.5

**Comment by lionel-** [comment]
See #510
