### ISSUE TITLE
lang_type_of fails on certain formulas

### ISSUE THREAD

**Issue by epatters** [r-lib/rlang#515]
To reproduce:

```
> rlang::lang_type_of(y~x)
[1] "named"

> rlang::lang_type_of(~.)
Error in rlang::lang_type_of(~.) : typeof(x) == "language" is not TRUE

> typeof(~.)
[1] "language"
```

**Comment by lionel-** [comment]
These functions are internally generic and call `get_expr()` on their arguments. So they operate on the RHS of formulas and on the expression wrapped by quosures.

In general the `type_of` functions are experimental and will probably be completely overhauled.
