### ISSUE TITLE
should parse_exprs accept a character vector for .x?

### ISSUE THREAD

**Issue by MilesMcBain** [r-lib/rlang#537]
I was trying to use a list of expressions supplied as text as `dplyr::filter()` expressions and I think this is the best I can do at the moment with `rlang`:

`filter(mtcars, !!!rlang::parse_exprs(textConnection(c("cyl == 4", "gear == 4"))))`

Support for a character vector or list in `.x` would be convenient.

**Comment by lionel-** [comment]
The dev version of rlang supports character vectors.
