### ISSUE TITLE
Possible issue with scoping and `!!!`

### ISSUE THREAD

**Issue by mitchelloharawild** [r-lib/rlang#543]
```r
library(rlang)
my_expr = exprs(FAIL=2)
eval_tidy(
  expr(transform(data, !!!my_expr)),
  env = child_env(global_env(), data = data.frame(x = 1), my_expr = exprs(SUCCESS=1))
)
#>   x FAIL
#> 1 1    2
eval_tidy(
  expr(my_expr),
  env = child_env(global_env(), data = data.frame(x = 1), my_expr = exprs(SUCCESS=1))
)
#> $SUCCESS
#> [1] 1
```

This may be my naivety, but I would have thought that the first code would add a new column named "SUCCESS" with value 1. Instead it appears that it is looking at `my_expr` from the `global_env()` instead of the environment specified in `eval_tidy()`, except only when using `!!!` (see second code).

The usage of `transform` is just a quick way to view the results of `!!!`, it was also tested with `mutate` which gave the same results.

**Comment by lionel-** [comment]
Unquoting with `!!` and `!!!` has uniform semantics: these operators evaluate their arguments *right away*. You can use `qq_show()` to examine the result of unquoting.

**Comment by mitchelloharawild** [comment]
Good to know, thanks.
