### ISSUE TITLE
Document differences between base is.call and rlang::is_call

### ISSUE THREAD

**Issue by md0u80c9** [r-lib/rlang#545]
Hi,

I've been using Rlang to do some code analysis. Obviously many of the RLang functions are modifications upon Base R equivalents.

Rlang::list2 for example has a number of benefits over base::list.

Checking the documentation for Rlang::is_call, I can't see why/where you would use this in preference to base::is.call (either functional benefits or speed differences). It may be that there is no benefit except for having consistent syntax - but that's not clear either!

Any thoughts on what the differences actually are?

There may be other instances of this - is_call was the example which came to mind.

**Comment by lionel-** [comment]
With `is_call()` you can specify the number of expected arguments or an expected namespace. With rlang we're trying to create a consistent base API and we experiment with new syntax and semantics to improve R as a language (tidy eval, tidy dots, errors and backtraces).
