### ISSUE TITLE
enquo and S3 methods

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#553]
``` r
my_enquo <- function(x) UseMethod("my_enquo")

my_enquo.default <- function(x) rlang::enquo(x)

my_enquo(mtcars)
#> <quosure>
#>   expr: ^<data.frame>
#>   env:  empty
my_enquo.default(mtcars)
#> <quosure>
#>   expr: ^mtcars
#>   env:  global
```

> Created on 2018-07-02 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I wanted to auto-assign a title for https://github.com/tidyverse/tibble/issues/373, for this I wanted to use `expr_label()` on the object on which dispatch occurs. Any chance _rlang_ could support this?

**Comment by lionel-** [comment]
The first argument of S3 methods is always evaluated and so cannot be captured.

**Comment by krlmlr** [comment]
Can we help _rlang_ by changing the implementation of the generic?

```r
my_enquo <- function(x) {
  help_rlang(x)
  UseMethod("my_enquo")
}
```

**Comment by lionel-** [comment]
It may be possible but I'm not sure if we should.

**Comment by krlmlr** [comment]
I got a working solution, kind of. Maybe _rlang_ could help do it better? 

``` r
my_enquo <- function(x, title = NULL) {
  UseMethod("my_enquo")
}

my_enquo.default <- function(x, title = NULL) {
  if (is.null(title)) {
    generic_call <- sys.call(-1)
    if (as.character(generic_call[[1]]) == "my_enquo") {
      x_arg <- match.call(my_enquo, generic_call)[["x"]]
    } else {
      x_arg <- rlang::enexpr(x)
    }
    
    title <- rlang::expr_deparse(x_arg)
  }
  
  title
}

my_enquo(mtcars)
#> [1] "mtcars"
my_enquo.default(mtcars)
#> [1] "mtcars"
```

> Created on 2018-07-02 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by lionel-** [comment]
The use case seems similar as in https://github.com/r-lib/rlang/issues/303

**Comment by krlmlr** [comment]
Thanks! Closing, let's continue discussion in #303.
