### ISSUE TITLE
env_print incorrectly labels binding as promise

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#554]
``` r
library(rlang)

power1 <- function(exponent) {
  function(x) {
    x ^ exponent
  }
}

square <- power1(2)
square(2)
#> [1] 4

env <- get_env(square)
env_print(env)
#> <environment: 0x7ff5c3cf7988>
#>   parent: <environment: global>
#>   bindings:
#>    * exponent: <promise>

env$exponent
#> [1] 2
env_print(env)
#> <environment: 0x7ff5c3cf7988>
#>   parent: <environment: global>
#>   bindings:
#>    * exponent: <promise>
```

Created on 2018-07-03 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by lionel-** [comment]
We should probably climb forced promises trails to get the right types.

**Comment by hadley** [comment]
I think there's something slightly more subtle going on:

``` r
library(rlang)

e <- env()
env_bind_exprs(e, x = 1)
env_binding_are_promise(e)
#>    x 
#> TRUE
rlang:::env_binding_type_sum(e)
#>         x 
#> "promise"

e$x
#> [1] 1
env_binding_are_promise(e)
#>     x 
#> FALSE
rlang:::env_binding_type_sum(e)
#>         x 
#> "promise"
```

**Comment by hadley** [comment]
Oh it's because `env_get()` retrieves the promise object:

``` r
library(rlang)

e <- env()
env_bind_exprs(e, x = 1)
e$x
#> [1] 1
env_get(e, "x")
#> <promise: 0x7fae45ac2b50>
```

**Comment by hadley** [comment]
What is the desired behaviour here? Maybe `env_get()` should get an `eval` argument?

**Comment by lionel-** [comment]
I was wondering about that. `base::get()` does evaluate promises, and we should probably too because promises are not meant to be returned on the R side.

**Comment by hadley** [comment]
What about active bindings?

**Comment by lionel-** [comment]
`env_get()` would return the value of the active binding.

**Comment by lionel-** [comment]
(i.e. the result of calling the active function)

**Comment by hadley** [comment]
I can implement this, I think - it just needs a couple of if statements at the end of `rlang_env_get()`, right?

**Comment by lionel-** [comment]
yup a new branch calling `r_eval()` should do it
