### ISSUE TITLE
env_get to evaluate a variable in the env of mutate

### ISSUE THREAD

**Issue by bnicenboim** [r-lib/rlang#555]
I wanted to use env_get to evaluate a variable in the environment of the mutate call, it didn't work, while `get` did work. Example below:

Given a data frame like the following 
```
df <- tibble(n = seq(-10,10), y = rnorm(21), z = runif(21))
```
I want a function that goes inside of mutate and takes a column and uses `n`. Basically, for `y` it would be:
```
mutate(df, a = y - mean(y[n < 0]))
```
With `get`, it works:
```
baseline1 <- function(.x) {
	n <- get('n', envir = parent.frame())
	 .x - mean(.x[n < 0])
}
 mutate(df, a = baseline1(y))
```
But not with env_get:

```
baseline2 <- function(.x) {
n <-  rlang::env_get( parent.frame(), 'n')
   .x - mean(.x[n < 0])
}

mutate(df, a = baseline2(y))
```
I get a `Error in mutate_impl(.data, dots) :   Evaluation error: object 'n' not found.`

**Comment by lionel-** [comment]
You need `inherit = TRUE`, it's FALSE by default in `env_get()` whereas it's TRUE in `get()`.
