### ISSUE TITLE
rlang:::new_lines makes illegal pairlist, not terminated by NULL

### ISSUE THREAD

**Issue by BillDunlap** [r-lib/rlang#563]
rlang:::new_lines maintains a linked list, indent_status, whose elements are made with new_node(FALSE, 0L).  The second argument to new_node (eventually to Rf_cons) should be a linked list (pairlist), not 0L.  I noticed this because TERR complains about the illegal second argument to Rf_cons, but when I used R to trace the calls to new_node, with trace(rlang::new_node, quote({str(car),str(cdr)})), R crashed.  E.g.,
  > library(rlang)
  > str(new_node(FALSE, 0L))  
  
   *** caught segfault ***
  address 0x21006009, cause 'memory not mapped'

I believe the following patch will keep things legal without changing the logic of your code much.  All the testthat tests pass after the change.

```
--- /homes/bill/CRAN/rlang/R/deparse.R  2018-02-14 23:32:56.000000000 -0800
+++ ./rlang/R/deparse.R 2018-07-27 12:03:28.463628000 -0700
@@ -159,10 +159,10 @@
       status <- node_car(self$indent_status)

       if (self$next_indent_sticky) {
-        node_poke_cdr(status, inc(node_cdr(status)))
+        node_poke_cadr(status, inc(node_cadr(status)))
       } else {
         self$indent <- self$indent + 2L
-        self$indent_status <- new_node(new_node(FALSE, 0L), self$indent_status)
+        self$indent_status <- new_node(pairlist(FALSE, 0L), self$indent_status)
         self$next_indent_sticky <- TRUE
       }

@@ -176,7 +176,7 @@
       }

       reset <- node_car(status)
-      n_sticky <- node_cdr(status)
+      n_sticky <- node_cadr(status)

       # Decrease indent level only once for all the openers that were
       # on a single line
@@ -187,7 +187,7 @@
       }

       if (n_sticky >= 1L) {
-        node_poke_cdr(status, dec(n_sticky))
+        node_poke_cadr(status, dec(n_sticky))
       } else {
         self$indent_status <- node_cdr(self$indent_status)
         self$next_indent_sticky <- FALSE


```

**Comment by lionel-** [comment]
This is an experiment in using cons cells as data structures. These cells do crash with `str()` but they have basic `print()` support:

```r
print(rlang::new_node(1, 2))
#> [[1]]
#> [1] 1
#> 
#> . 
#> 
#> [1] 2
```

Cons cell support in R is admittedly poor but I don't think a non-pairlist CDR should be considered illegal. It is fine to make this assumption in calls though. Is this highly problematic for TERR?

**Comment by lionel-** [comment]
There is indeed something wrong, but this is a bug in `str()` in my opinion. Since R is unlikely to move in the direction of greater support for cons cells, I'll look into applying your patch.

**Comment by BillDunlap** [comment]
There is a fair bit of code in packages (and perhaps in R itself) that
detects the end of a pairlist with CRD(pairlist)==R_NilValue or
isNUll(CDR(pairlist)).  With non-NULLs allowed at the end of
a pairlist this would faill.

**Comment by lionel-** [comment]
I use this idiom all the time as well, it's just an assumption about the data structure at hand for a particular bit of code.

This is the same situation as creating a circling environment ancestry. If you do this you're going to freeze R, but there is no point in runtime checking for this. It is fine to assume the code is correct.

**Comment by lionel-** [comment]
To be clear, I don't think it is a bad idea to runtime-check here, but it would make more sense in CAR/CDR accessors and setters than in `Rf_cons()`. As mentioned above I'll just remove usage of cons cells in rlang since that's not a canonical usage of pairlist structures.

**Comment by lionel-** [comment]
@BillDunlap I think you should reconsider that runtime check. It's going to make TERR incompatible with the new unwind protection API that will be used by default in Rcpp soonish.

See https://github.com/wch/r-source/blob/c1d5ccc7e2fcc1040eaa3de06c57c1105c52c243/src/main/context.c#L881

The proper place for runtime checks is in the pairlist accessors and getters, if you can afford the cost.

**Comment by lionel-** [comment]
Though I may have wrong assumptions about how TERR interfaces with the R API?
