### ISSUE TITLE
Documentation strategy for packages that import then re-export functions from rlang

### ISSUE THREAD

**Issue by jennybc** [r-lib/rlang#564]
`usethis::use_tidy_eval()` provides a template file [inst/templates/tidy-eval.R](https://github.com/r-lib/usethis/blob/master/inst/templates/tidy-eval.R) for use in packages that want to use tidy eval.

Currently, this will result in a sub-optimal situation re: help for the rlang functions that are imported and re-exported, as pointed out by @lionel- https://github.com/r-lib/usethis/pull/377#issuecomment-410937968

> Would it be possible to make ?dplyr::quo and ?rlang::quo point to the same documentation page? From discussions on Twitter, it may be likely that people don't notice or follow links and miss out on the documentation.

I merged that PR, which means the next usethis release will have a substantially improved template, but this concern remains.

**Comment by lionel-** [comment]
Here is how I do it in purrr: https://github.com/tidyverse/purrr/blob/master/R/reexport-rlang.R

With this approach, each alias has a dedicated page. It's then easier to follow the link to the rlang documentation:

```
zap                   package:purrr                    R Documentation

Zap an element

Description:

     These objects are imported from other packages. Follow the links
     below to see their documentation.

     rlang ‘zap’
```

**Comment by lionel-** [comment]
Closing since this seems to be more of a roxygen issue than an rlang issue.
