### ISSUE TITLE
Using eval_tidy() with environments is not straightforward / well documented

### ISSUE THREAD

**Issue by privefl** [r-lib/rlang#571]
library(rlang)
    myquo <- quo((Temp - 32) / 1.8)
    eval_tidy(myquo, data = as_data_mask(datasets::airquality)) # works
    e <- as_env(datasets::airquality, parent = global_env())
    eval_tidy(myquo, data = as_data_mask(list(), parent = e))   # error

I expected `Temp` to be found in `e`.

I have R version 3.5.0 and tested this with both latest CRAN and GitHub versions of {rlang}.

***
PS: I've posted this on SO: https://stackoverflow.com/q/51830920/6103040

**Comment by lionel-** [comment]
From `?rlang::as_data_mask`

```
#' * `as_data_mask()` transforms a data frame, named vector or
#'   environment to a data mask. If an environment, its ancestry is
#'   ignored. It automatically installs a data pronoun.
```

I.e. for environments it only creates the  bottom. I think we should issue a warning instead.

By the way, `as_env()` is soft-deprecated, please use `as_environment()` or `base::list2env()`.

**Comment by privefl** [comment]
I don't understand. If there is an argument `parent`, why is it ignored?

**Comment by lionel-** [comment]
It's for lists and data frames.

**Comment by privefl** [comment]
OK, thanks. I think there is also the same "problem" with `as_environment()` then:
`env_parent(as_env(new_environment(), parent = global_env()))`

**Comment by lionel-** [comment]
I'm not sure what the semantics should be. If we do use the new parent, then the environment should be cloned to avoid side effects.

But then this makes it harder to use `as_environment()` for normalising inputs in functions that expect an environment. I think this is the reason for the current behaviour.

**Comment by privefl** [comment]
OK, no problem.
Yet, a warning for {rlang} newbies like me would be useful.
Thanks.

**Comment by privefl** [comment]
`eval_tidy(myquo, data = as_data_mask(data.frame(), parent = e))` should work, right? Because the first argument is a data frame.

**Comment by privefl** [comment]
`eval_tidy(myquo, data.frame(), e)` doesn't work either.

**Comment by privefl** [comment]
The context: https://github.com/privefl/bigdfr/blob/master/R/mutate.R#L22-L28
The workaround I use it to always put the environment with the quosure.

**Comment by lionel-** [comment]
> eval_tidy(myquo, data.frame(), e) doesn't work either.

Right your data mask is an environment and the `env` argument is for the lexical scope, i.e. it won't mask the quosure envs, only `data` will.

> The context: https://github.com/privefl/bigdfr/blob/master/R/mutate.R#L22-L28

I don't understand what's going on there. Let's try to take a step back. There are two scopes in a data-masked evaluation:

- The data mask, which can be a single environment or an ancestry of several environments. This mask comes in first under evaluation.

- The lexical scope, whose default is given by the `env` argument, and is overridden by the quosure environment when a quosure is evaluated. This is a scope that goes up to the empty environment.

If your data mask is several environments deep, you have to use `new_data_mask()` and specify the top and bottom. In that case you need to add a pronoun manually to the bottom of the mask with `bottom$.data <- as_data_proun(bottom)`.

**Comment by privefl** [comment]
My approach of having an ancestry of several environments that I set to my quosure before using `eval_tidy()` is wrong?

**Comment by lionel-** [comment]
I guess it works but it's doing too much work that should be done by rlang. I would create a data mask with `new_data_mask()` once and then `eval_tidy()` each quosure with it.

I wonder if supplying a bare environment to `eval_tidy()` and `as_data_mask()` should be an error?

**Comment by lionel-** [comment]
Hi Florian. Just checked your mutate implementation again. I don't really understand what's going on, but it looks like you're using `eval_tidy()` with bare environments? This is deprecated and will stop working in the future. You need to construct a real data mask. The documentation for `new_data_mask()` has been updated. Is it now clearer?
