### ISSUE TITLE
Is there a reason there is an is_quosures but not an is_expressions?

### ISSUE THREAD

**Issue by md0u80c9** [r-lib/rlang#574]
Hi,

Just writing some sanity checks in my code at present and realised that there is an is_quosure and is_quosures but no equivalent for expressions, even though this is an exprs() to match quos(). Given it seems obvious- is this a deliberate omission?

**Comment by lionel-** [comment]
Then you'd pass the result of `map()` to `new_quosures()`. It checks that each element is indeed a quosure and creates a list with the right class. This makes me think the class should probably be expanded with methods like `[<-`.

**Comment by md0u80c9** [comment]
Ah - awesome, thank you 👍
