### ISSUE TITLE
Using purrr on quos or exprs generates plain lists

### ISSUE THREAD

**Issue by md0u80c9** [r-lib/rlang#575]
If you use purrr to create expressions you get a list rather than an exprs object (and indeed if you use purrr to generate quosures you get a list, even though you've actually generated a quosures list). However I can't see a language feature which allows you to convert that list into a list of quos, so as_quosures will be FALSE (presumably unless you go and set the class attribute by hand - which sounds dangerous...)

Purrr is clearly behaving as intended - wonder whether there is scope to introduce map_quos / map_exprs objects to purrr, or whether there is benefit in an as_quosures / as_exprs in rlang which validates that all items in a list can be valid quosures / expressions and subclasses the list accordingly.

```
test <- rlang::exprs(a - b, a + b)
test2 <- purrr::map(test, ~ rlang::quo(!!.x + c))
rlang::is_quosures(test2)
rlang::is_quosure(test2[[1]])
rlang::is_quosure(test2[[2]])
```

**Comment by lionel-** [comment]
Discussed in #574
