### ISSUE TITLE
dots_list() fails when called via lapply()

### ISSUE THREAD

**Issue by mikmart** [r-lib/rlang#580]
It seems `dots_list()` fails when called via `lapply()`:

``` r
lapply(list(quote(a)), rlang::dots_list)
#> Error in FUN(X[[i]], ...): object 'a' not found
```

I would expect the above to be equivalent to:

``` r
list(rlang::dots_list(quote(a)))
#> [[1]]
#> [[1]][[1]]
#> a
```

This came up when I tried to construct several calls from expressions:

``` r
lapply(rlang::exprs(a, b), rlang::call2, .fn = quote(f))
#> Error in dots_list(...): object 'a' not found
```

I was hoping to get:

``` r
rlang::exprs(f(a), f(b))
#> [[1]]
#> f(a)
#> 
#> [[2]]
#> f(b)
```

Created on 2018-08-21 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0.9000).

(Originally accidentally posted in [tidyverse/purrr#534](https://github.com/tidyverse/purrr/issues/534#issue-352499866))

**Comment by egnha** [comment]
@mikmart, an aside: although this doesn't fix the root problem you've identified, if you just want to construct lists of calls, you can do this succinctly with base R (though I suppose you already knew that), e.g., `lapply(alist(a, b), function(arg) call("f", arg))`.

**Comment by mikmart** [comment]
@egnha thanks, I actually hadn't thought of that alternative. Turns out that doesn't quite work for what I wanted to do though. More generally, I was looking to replace this anonymous function pattern that I found myself using in `map()` functions: `function(x) rlang::expr((!!f)(!!x, !!!dots))`; where `f` and `dots` come as arguments to the enclosing function, and `f` can for example be an anonymous function, too.

**Comment by egnha** [comment]
In this case, where you're mapping over `x` for given a `f` and `dots`, you might want to consider using `as.call()` instead, e.g.,
```R
make_fns <- function(f, args, dots) {
  lapply(args, function(arg) as.call(c(f, arg, dots)))
}
```
(`f` may be anything which could be the head of a call, i.e., a name like `quote(f)` or a function literal.)
