### ISSUE TITLE
Printing quosures with calls sometimes lacks required parentheses

### ISSUE THREAD

**Issue by mikmart** [r-lib/rlang#581]
Printing quosures does not always have parentheses around the CAR of a call when it's necessary. For example, if an anonymous function expression is unquoted into the CAR slot of a call, the required parentheses are missing and produce a strange print result for the expression:

``` r
f <- quote(function(x) x + 1)
rlang::quo((!!f)(x))
#> <quosure>
#>   expr: ^function(x) x + 1(x)
#>   env:  global
```

Extracting the expression shows that it's only the printing that's incorrect:

``` r
q <- rlang::quo((!!f)(x))
rlang::quo_get_expr(q) # correct expression
#> (function(x) x + 1)(x)
```

Another example with the same issue:

``` r
g <- quote(f + g)
rlang::quo((!!g)(x))
#> <quosure>
#>   expr: ^f + g(x)
#>   env:  global
as.call(c(g, quote(x))) # expected
#> (f + g)(x)
```

I think this could be fixed by adding a check to `call_deparse()` before deparsing the CAR to see if parentheses are needed, and insert them if so.

https://github.com/r-lib/rlang/blob/2cf70c8f41513831a02878384421e417169719a8/R/deparse.R#L432-L435

I have a local branch implementing this, and could submit a PR if that sounds OK.

**Comment by lionel-** [comment]
Hmm I'm not sure. Could you give me the name of your branch please? Then when I have time to look into this I can start from it if this is the right approach.

**Comment by lionel-** [comment]
Or send a PR, that might be best.

**Comment by mikmart** [comment]
Okay, sent the PR! My terminology might not be spot on, but I hope the message gets through.
