### ISSUE TITLE
Feature Request: Appropriately Signal Any Condition

### ISSUE THREAD

**Issue by billdenney** [r-lib/rlang#583]
I have recently learned about the new signal handling code in rlang, and I'm loving it!

Using `with_handlers()`, I have generated a list of multiple conditions that I'm wanting to modify and then re-signal.  It would help to have a function that will appropriately signal any condition provided.  What would you think about adding something like the following to signal any condition?  (The function name could likely be better.)

``` r
#' @rdname cnd_signal
#' @export
cnd_signal_general <- function(.cnd, ...) {
  if (inherits_all(.cnd, class = c("error", "condition"))) {
    cnd_abort(.cnd = .cnd, ...)
  } else if (inherits_all(.cnd, class = c("warning", "condition"))) {
    cnd_warn(.cnd = .cnd, ...)
  } else if (inherits_all(.cnd, class = c("message", "condition"))) {
    cnd_inform(.cnd = .cnd, ...)
  } else if (inherits_any(.cnd, class = "condition")) {
    cnd_signal(.cnd = .cnd, ...)
  } else {
    stop("`x` must be a condition, not a ", paste0(class(x), collapse = ", "))
  }
}
```

**Comment by lionel-** [comment]
The development version has `cnd_signal()` for exactly this purpose :)

**Comment by billdenney** [comment]
Great!  I am currently using 0.2.2, so I guess the behavior of `cnd_signal()` has changed since then.

Thanks!
