### ISSUE TITLE
Any API for gathering the variables from an expr (or list of exprs)?

### ISSUE THREAD

**Issue by md0u80c9** [r-lib/rlang#586]
Hi,

This is really an extension on a question from https://stackoverflow.com/questions/50563895/using-rlang-find-the-data-pronoun-in-a-set-of-quosures/51955427#51955427

In a nutshell I have a large (400 item) list of expressions (not quosures - I have since established they can be safely expressions). I'm using them to operate on a larger CSV file, and I want to check the variables from the expressions to do a selective import of the dataset.

The code proposal in the example works, but takes about 5 seconds to execute, mainly because of having to convert each expression in the AST into a list and then recursively act on the list. I can optimise the code somewhat but unless it is pre-executed it surprisingly will be slower than just importing the entire dataset. It also relies upon variables being identified by the .data pronoun (which I can do within the code but is not an ideal generic solution).

I wondered though whether there is a better approach to the problem - or whether Rlang itself exposes a way of gathering a list of variables from a parsed expression. Or indeed whether a function to gather a list of variables from an expression is indeed a valuable consideration for the API.

**Comment by lionel-** [comment]
Haven't looked in details but one source of slowness is having to convert the language lists to vector lists. You can walk the AST with the node accessors instead but they are tricky to work with because they don't perform any type checking: if your code is wrong, R crashes.

Why are you working with expressions?

**Comment by md0u80c9** [comment]
Basically we have a large dataset (250,000 rows and rapidly expanding, and a variable number of columns but usually >400) which we use to run a national clinical audit of stroke care.

Each of the list expressions is an aggregation calculation which we pass to dplyr.

We run a number of different reports for each hospital team, and each team may need different columns from that depending upon their service capabilities. Different reports may need different levels of detail so for example we can use a base expression to produce just a median for one report but a set of quartiles for another, or just a percentage of patients from one report and a denominator, numerator and number of grouped values in another report.

In general this process is working really well and is beautiful and flexible - but obviously pushes the use of rlang quite a bit!

Currently I can only access the data from CSV using readr though hopefully soon we'll be able to do it directly from the live (SQL Server) database. What I'm trying to do with the variable reading is to work out which columns I need and then do a selective import. You can of course make such lists by hand, but it's error-prone and tedious hence a quick way of producing the list directly from the expression would be awesome.

**Comment by lionel-** [comment]
It sounds like a lazy readr backend for dplyr would be useful for your case.

**Comment by md0u80c9** [comment]
Immensely useful yes! I can’t imagine it is an unusual use case.

RLang is awesome though for making that code design possible.

**Comment by david-jankoski** [comment]
hi, maybe you've considered these already, but in case not - i thought to mention, maybe helpful in your situation
https://github.com/edwindj/chunked 
https://github.com/edwindj/ffbase2

**Comment by md0u80c9** [comment]
Thanks Lionel.

David - yeah I had seen these: I would still like to limit the number of columns wherever possible, rather than chunk the number of rows. Ideally I'd like to just move to direct data access using SQL Server, but that is an Information Governance issue rather than a technical one.

One workaround I have is to use my code as a unit test against pre-made column lists for the expression lists which are built in (and to generate those lists in the first place). Doesn't solve the problem for user-customised expression lists (we plan to have a Shiny dashboard where you might want to plot things not set up in the predefined lists).

Just wanted to explore that there weren't quicker ways of generating the variable lists before settling for 'mitigation' options.

**Comment by lionel-** [comment]
We don't plan on providing an API for this at the moment. Perhaps if you profvis your code you will find slow parts in the rlang API? If you do, please file a new issue.
