### ISSUE TITLE
Should names2() return NA instead of ""

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#588]
Missing is a bit match to the absence of a name

**Comment by lionel-** [comment]
That would introduce more edge cases whereas the goal of `names2()` is to reduce the edge cases. E.g. `list(1, 2)` vs `list(1, foo = 2)`. With the current behaviour the name of component 1 is `""` in both cases.

**Comment by hadley** [comment]
I think it's too late to change our minds on this even if it might be slightly better.
