### ISSUE TITLE
Variant of as_function() and other coercers without aborting or with a custom error message

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#589]
In _tibble_ we're implementing an argument that can be either a string or a function. I'd like to support the "anonymous function" notation of _purrr_ so that we can use e.g. `as_tibble(..., .name_repair = ~make.names(., unique = TRUE))` .

We could do

```r
if (is_character(x)) {
  ...
} else {
  x <- as_function(x)
  ...
}
```

but that would give a rather unhelpful error message. To fix this, we'd use

```r
} else {
  tryCatch(
    x <- as_function(x),
    error = function(e) abort(...)
  )
  ...
}
```

I wonder if we could provide a better API, e.g. one of:
but that would give a rather unhelpful error message. To fix this, we'd use

```r
} else {
  x <- try_as_function(x)
  if (!is_function(x)) abort(...)
  ...
}
```
but that would give a rather unhelpful error message. To fix this, we'd use

```r
} else {
  x <- as_function(x, msg = "Must be either string or function")
  ...
}
```

**Comment by lionel-** [comment]
I think it should be:

```r
if (is_formula(x)) {
  x <- as_function(x)
} else if (!is_function(x)) {
  abort("informative")
}
```

If you do use the tryCatch, make sure to force the input outside of it otherwise you'll swallow errors such as "object not found".

**Comment by krlmlr** [comment]
Thanks. This duplicates some the logic of `as_function()` in my code, though. What if the semantics of `as_function()` change later?

**Comment by lionel-** [comment]
It will always accept formulas.

**Comment by lionel-** [comment]
We can throw a typed error in `as_function()` if you'd like to catch it. We can't do much better. Taking additional parameters for custom error messages is not a scalable approach. Nor is having versions that return instead of throw errors.

**Comment by krlmlr** [comment]
Agree that the added complexity isn't worth the effort for this use case. A `tryCatch()` with a typed error message may be the least of all evils here.

Btw, do we have a lighter-weight variant of `tryCatch()` that doesn't cripple the stack trace?

**Comment by lionel-** [comment]
I think one fundamental issue is that we include parameter names in error messages and they are not necessarily relevant for the user.

> do we have a lighter-weight variant of tryCatch() that doesn't cripple the stack trace?

Not at the moment, but that's something we'd like to explore.

**Comment by krlmlr** [comment]
Maybe we could use an "error context" that is picked up by `abort()`? _tibble_ would set the context, and `abort()` would add it to the error message:

```r
with_context("processing the `.name_repair` argument",
  as_function(x)
)
#> Error processing the `.name_repair` argument: Can't convert double vector to a function
```

These contexts could be nested too, sort of a high-level stack trace. But then it might be easier to just teach the users to read call trees (and to make them available when the error is printed).
