### ISSUE TITLE
Warn when UQ() is called with rlang:: prefix

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#599]
The first expression with a namespace prefix should give a warning, use the second instead:

```
# Bad
rlang::expr(rlang::UQ("foo"))

# Good
rlang::expr(UQ("foo"))
```
The UQ/UQS operators are soft-deprecated as of rlang 0.2.0 but seem popular. Do we want to keep them around @hadley?

**Comment by hadley** [comment]
I think they're a crutch, but I don't know if we want to actively remove them.

**Comment by lionel-** [comment]
Done in https://github.com/r-lib/rlang/pull/601
