### ISSUE TITLE
Invalid formula when using !! on right hand side of formula

### ISSUE THREAD

**Issue by NikNakk** [r-lib/rlang#606]
I've run into an issue with unquoting a quosure on the right-hand-side of a formula. Is this known? Is there a workaround?

```
library(rlang)
x <- sample(LETTERS[1:2], 100, replace = TRUE)
y <- 1:100
xq <- quo(x)
yq <- quo(y)
wilcox.test(y ~ x) # works
eval_tidy(quo(wilcox.test(y ~ x))) # works
eval_tidy(quo(wilcox.test(!!yq ~ x))) # works
eval_tidy(quo(wilcox.test(y ~ !!xq))) # fails with error 'invalid model formula'
```

**Comment by yutannihilation** [comment]
In formula, you have to use symbols, not quosures. If you investigate the unquoted expression with `expr()`, you'll find the formulas have extra `~`.

``` r
library(rlang)

xq <- quo(x)
yq <- quo(y)

expr(
  eval_tidy(quo(wilcox.test(!!yq ~ x)))
)
#> eval_tidy(quo(wilcox.test(~y ~ x)))

expr(
  eval_tidy(quo(wilcox.test(y ~ !!xq)))
)
#> eval_tidy(quo(wilcox.test(y ~ ~x)))
```

In this case, I think you can use `expr()` instead of `quo()` to get symbols.

```r
xq <- expr(x)
yq <- expr(y)
```

**Comment by lionel-** [comment]
Thanks @yutannihilation. As a general rule it's better to use `expr()` and only create quosures with `enquo()`, i.e. for stuff that doesn't belong to you. That's the approach we are taking in https://tidyeval.tidyverse.org which will replace the dplyr vignette.
