### ISSUE TITLE
Consolidate vector coercions

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#61]
e.g. `as_character()` should handle factors.

Also we need to distinguish between implicit and explicit coercions. Currently `as_character()` etc are used for implicit coercions as well. But we'd want explicit coercion support serialisation of e.g. numeric vectors, but that should be forbidden in implicit coercions.

**Comment by hadley** [comment]
This will need to use S3, and is hence outside the scope of rlang, right?
