### ISSUE TITLE
`env_clone()`ed env's objects no longer have copy-on-modify semantics

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/rlang#621]
I believe this change is introduced by 395cf4aacb1b3542ce49fdd54d4c7b5c3f0cc05b. For example, I expect `x` in `env` below is preserved:

``` r
library(rlang)

env <- env(x = 1:3)
clone <- env_clone(env)

clone$x[1] <- NA

clone$x
#> [1] NA  2  3
env$x
#> [1] NA  2  3
```

Created on 2018-09-21 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Is this behaviour intended and supposed? Since `env_clone()` is soft-deprecated, I know I have to get rid of this function sooner or later. So, it's OK if this is intended change, but I just want to know what's happening behind this mystery...

**Comment by lionel-** [comment]
oops, that is not intended. I thought I had checked for this.

`env_clone()` is not soft-deprecated though. Only passing an environment wrapper instead of an environment is deprecated.

**Comment by yutannihilation** [comment]
> `env_clone()` is not soft-deprecated though.

Oh, thanks for the good news! I misread the NEWS, sorry.
