### ISSUE TITLE
.data pronoun using the data mask environment ancestry

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/rlang#629]
Initially discussed here: https://github.com/tidyverse/dplyr/pull/3858 and also related to https://github.com/tidyverse/dplyr/issues/3734

The idea would be to construct the data pronoun from the data mask so that it would look up for bindings navigating up the ancestry between `.top_env` and (not including) `.env`.

**Comment by lionel-** [comment]
There should be some kind of flag to disable lookup. For instance we'd set the flag in the tidyselect environment that masks `c()`, `:` and `-`, so `.data$c` fails instead of returning the function.

**Comment by romainfrancois** [comment]
Should it fail or attempt to look for `c` further ?

**Comment by lionel-** [comment]
It should keep walking the mask and only fail at the end, I think.

**Comment by lionel-** [comment]
Read-only is now hard-coded to `TRUE` except in the compatibility alias `as_dictionary()` that was soft-deprecated in rlang 0.2.0. The only CRAN package where `as_dictionary()` is used is valr, in old embedded dplyr files: https://github.com/cran/valr/blob/ffb9fc012b43faaca1e04c5705b47aedb12c2527/inst/include/dplyr/Result/GroupedHybridCall.h. Not sure what this embedding is about? I'm going to bump the retirement status to deprecated for these functions.

I think we can ignore read-write pronouns and just fail in `$<-`.
