### ISSUE TITLE
missing KEEP_N for rlang_as_data_mask:data_pronoun?

### ISSUE THREAD

**Issue by BillDunlap** [r-lib/rlang#640]
If I run the following code in TERR with gctorture(TRUE) and with all internal checks turned on, TERR crashes in garbage collection after rlang_as_data_mask() creates data_pronoun and while it is creating the next object.  If I modify the code to call gc() right after creating data_pronoun then it crashes R as well.  There must be some difference between gctorture(TRUE) in R and TERR, but shouldn't data_pronoun be protected from garbage collection?

> df <- data.frame(X=c(11, 17), Y=c(23,29))
> f <- function(mydata) {
>   cat("Entering 'f'\n")
>   mydata
> }
> library(dplyr)
> gctorture(TRUE)
> dplyr:::do.data.frame(df, f(.))

The following patch protects data_pronoun with the KEEP_N macro, just as all the objects in that function are protected.

```diff
diff -ru /homes/bill/CRAN/rlang/src/internal/eval-tidy.c rlang/src/internal/eval-tidy.c
--- /homes/bill/CRAN/rlang/src/internal/eval-tidy.c     2018-08-14 10:56:07.000000000 -0700
+++ rlang/src/internal/eval-tidy.c      2018-10-02 12:21:23.124333000 -0700
@@ -134,10 +134,9 @@
   if (data == r_null) {
     return rlang_new_data_mask(r_null, r_null, parent);
   }
-  sexp* data_pronoun = rlang_as_data_pronoun(data);
-  sexp* bottom = NULL;
-
   int n_protect = 0;
+  sexp* data_pronoun = KEEP_N(rlang_as_data_pronoun(data), n_protect);
+  sexp* bottom = NULL;

   switch (r_typeof(data)) {
   case r_type_environment:
```

**Comment by lionel-** [comment]
It totally should, thanks!

**Comment by lionel-** [comment]
I'll run the tests with gctorture and check with Tomas's rchk package before release.
