### ISSUE TITLE
Pre-pull request: Two-sided formula to function

### ISSUE THREAD

**Issue by cfhammill** [r-lib/rlang#645]
Hi rlang devs,

For a [package I'm working on](https://github.com/cfhammill/lenses) I recently implemented a two-sided formula variant of `as_function` that I'm calling `as_lambda`, this gives users the ability to specify what the arguments to their anonymous function are.

example use would be:

```r
as_lambda(x ~ x + 5)(x = 7)
```

multiple arguments can be passed via enclosing the args on the LHS in a function call

```r
as_lambda(c(x,y) ~ x + y + 5)(x = 7, y = 2)
```

if the LHS is omitted the function is constructed identically to `as_function`. To use in place of e.g. `purrr:::as_mapper.default`, I extended `as_closure` to optionally use `as_lambda` instead of `as_function`.

Is this a feature you would consider adding to `rlang`? 

Source for the two functions are available below. If it is more convenient to view this as a diff, I'll open a PR.

```r
as_lambda <- function(x, env = rlang::caller_env()){
  rlang::coerce_type(x, friendly_type("function"), primitive = , closure = {
        x
    }, formula = {
        if (length(x) == 2) {
          args <- list(... = missing_arg(), .x = quote(..1), .y = quote(..2), 
                           . = quote(..1))
        } else {
          lhs <- rlang::f_lhs(x)
          if(length(lhs) > 1){
            if(any(vapply(lhs, length, numeric(1)) > 1))
               stop("LHS of a lambda must be a single symbol, or a single expression "
                  , "of symbols, it appears your expression is nested.")
            lhs <- lhs[-1]
          }

          args <- rep(list(rlang::missing_arg()), length(lhs))
          names(args) <- vapply(lhs, deparse, character(1))
        }

        rlang::new_function(args, rlang::f_rhs(x), rlang::f_env(x))
    }, string = {
        get(x, envir = env, mode = "function")
    })
}

as_closure <-
  function (x, env = caller_env(), lambda = FALSE) {
    to_fun <- `if`(lambda, as_lambda, rlang::as_function)
    x <- to_fun(x, env = env)
    rlang::coerce_type(x, "a closure", closure = x, primitive = {
        fn_name <- prim_name(x)
        fn <- op_as_closure(fn_name)
        if (!is_null(fn)) {
            return(fn)
        }
        if (fn_name == "eval") {
            fmls <- formals(base::eval)
        }
        else {
            fmls <- formals(.ArgsEnv[[fn_name]] %||% .GenericArgsEnv[[fn_name]])
        }
        args <- syms(names(fmls))
        args <- set_names(args)
        names(args)[(names(args) == "...")] <- ""
        prim_call <- call2(fn_name, splice(args))
        new_function(fmls, prim_call, base_env())
    })
}
```

**Comment by egnha** [comment]
Looks like #380 is also pertinent.

**Comment by cfhammill** [comment]
@lionel-, that's the plan, just thought I'd offer. 

@egnha, `nofrills` looks pretty cool, but if I need anything more elaborate than name binding I'd probably just type `function`, I frequently do when using `purrr`. I plan on using this rarely, it's more for my coauthor.

**Comment by cfhammill** [comment]
@lionel-, would it be possible to export `op_as_closure`? That is the only `rlang` internal function I would need to CRAN check.

**Comment by lionel-** [comment]
`as_closure()` is experimental and I'm not happy with its current state, so I'd rather not expose more of its internals. I think it would be better if you copied it in your package, this way you're not dependent on potential changes (deprecation, different approach).

**Comment by lionel-** [comment]
The most likely change is that it'll use the documented argument names of primitive functions when applicable, e.g. `e1, e2` instead of `.x, .y`.

**Comment by cfhammill** [comment]
understood. It's a bit unfortunate, the code of `op_as_closure` is pretty rlang dependent and is going to be... not beautiful, when namespaced. But c'est la vie. 

Thanks!

**Comment by lionel-** [comment]
You can evaluate it in a child of `pkg_env("rlang")` to avoid the namespacing ;)

Unexported compats can also be defined in that environment so they don't pollute your namespace.

**Comment by cfhammill** [comment]
Brilliant, thank you!

**Comment by lionel-** [comment]
oops, `pkg_env()` is not right, it would need rlang to be attached... We really need to export a way of constructing artificial package environments.

`ns_env("rlang")` is an alternative but much riskier because you might involuntarily depend on internals.

**Comment by cfhammill** [comment]
hmm, too bad, it's alright, I'll just bite the bullet and namespace all the functions. It would be very cool if artificial package environments could be created.
