### ISSUE TITLE
Erron on installing the dev version on Windows

### ISSUE THREAD

**Issue by grayskripko** [r-lib/rlang#661]
```{r}
>> devtools::install_github("r-lib/rlang", build_vignettes = TRUE)

Downloading GitHub repo r-lib/rlang@master
from URL https://api.github.com/repos/r-lib/rlang/zipball/master
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.5.1 was found. (Only the following incompatible version(s) of Rtools were found:3.5)

Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/.
Installing rlang
"C:/PROGRA~1/MICROS~1/ROPEN~1/R-35~1.1/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/srskr/AppData/Local/Temp/Rtmpmie1he/devtools1bd4b0513e2/r-lib-rlang-c448185"  \
  --library="C:/Users/srskr/Documents/R/win-library/3.5" --install-tests 

* installing *source* package 'rlang' ...
Warning in system("sh ./configure.win") : 'sh' not found
ERROR: configuration failed for package 'rlang'
* removing 'C:/Users/srskr/Documents/R/win-library/3.5/rlang'
In R CMD INSTALL
Installation failed: Command failed (1)
```

**Comment by lionel-** [comment]
Have you tried reinstalling Rtools?

**Comment by grayskripko** [comment]
I tried to fix it many times. I will try one more time tomorrow. Anyway, I don't think this is the reason. Looks like ```system("sh ...``` can be a problem.

**Comment by lionel-** [comment]
I think `sh` should be available as part of the mingw32 suite that is part of Rtools, but I don't know much about the Windows toolchain.

**Comment by lionel-** [comment]
Perhaps try installing https://www.cygwin.com/

**Comment by lionel-** [comment]
oops sorry, I see that cygwin is not used in Rtools anymore: https://cran.r-project.org/bin/windows/Rtools/Rtools.txt

It says that it is replaced by msys2.

**Comment by lionel-** [comment]
So perhaps try: https://www.msys2.org/

**Comment by grayskripko** [comment]
I've found what was the problem with Rtools. There is no 3.5.1 version at all https://cran.r-project.org/bin/windows/Rtools/

**Comment by lionel-** [comment]
Rtools35 is compatible with R 3.3 and later, so it should work on R 3.5.1.

**Comment by grayskripko** [comment]
working on applying it. Thanks @yutannihilation 

I'm not sure but maybe it's in ```rlang``` installation problem. I have ```mingw``` in my PATH but ```rlang``` tried to find it in other directory

![image](https://user-images.githubusercontent.com/10427026/47014033-51344d00-d149-11e8-9655-3c78ab045ef2.png)

**Comment by lionel-** [comment]
rlang has nothing to do with the way it is installed, it's the development tools that are responsible for installing packages.

**Comment by grayskripko** [comment]
```remotes::install_github``` works. Thanks @lionel for your help
