### ISSUE TITLE
call_name behavior with qualified functions

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/rlang#670]
I found the behavior of `call_name` on qualified functions a little surprising. Is this a bug?

``` r
library(rlang)

call_name(~ func())
#> [1] "func"
call_name(~ func)
#> Error: `call` must be a call or must wrap a call (e.g. in a quosure)

call_name(~ pkg::func())
#> [1] "func"
# I would expect an error here, not `::`
call_name(~ pkg::func)
#> [1] "::"
```

<sup>Created on 2018-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by egnha** [comment]
While this does indeed seem strange, it is not inconsistent: `::` is a function, so `pkg::func` is not a symbol but rather a call, `` `::`(pkg, func) ``.

**Comment by lionel-** [comment]
`call_name()` is a high level accessor so perhaps should error in this case.

**Comment by hadley** [comment]
Yeah, I think it should error since the RHS of `::` is a symbol, not a call.

**Comment by lionel-** [comment]
@hadley I wonder if we need `call_ns()`? It seems `call_name()` is incomplete without it. And `call_ns<-` / `call_name<-`?

**Comment by hadley** [comment]
Yeah that makes sense to me (although I wouldn't worry about the setters for now)

**Comment by lionel-** [comment]
I have reverted this because `if (is_call(x)) call_name(x)` should never be an error. Not sure that `is_call()` can be this high-level though. Needs more thinking.
