### ISSUE TITLE
Pre-pull request: with_data

### ISSUE THREAD

**Issue by cfhammill** [r-lib/rlang#672]
I recently had occasion to augment a function with extra data. It's for `map` style anonymous functions that can view data.frame elements - cfhammill/lenses#29 for context. 

The solution was pretty simple:

```r
with_data <- function(f, d){
  body(f) <- bquote(eval_tidy(quote(.(body(f))), data = .(d)))

f
}
```

Is this something you'd consider adding to rlang? There's probably a cleaner non-bquote version possible too

**Comment by lionel-** [comment]
Hmm I don't think we need this in rlang, but thanks for the suggestion!

By the way `expr()` and `!!` are how you do quasiquotation with the rlang API:

```r
expr(eval_tidy(quote(!!body(f)), data = !!d))
```

Also you need to call `eval_tidy` with `rlang::` prefix because it might not be in scope in the closure environment.

**Comment by cfhammill** [comment]
Thanks @lionel-, understood. I figured the rlang way would be about that simple but my brain wasn't working at top gear when I wrote it.

Good point re scoping rlang, thanks.
