### ISSUE TITLE
Operator precedence issue with !! and ^

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#677]
``` r
library(rlang)
x <- expr(X)
y <- expr(Y)

expr(!!x ^ !!y)
#> Error in !y: invalid argument type
expr((!!x) ^ !!y)
#> X^Y
```

<sup>Created on 2018-10-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by lionel-** [comment]
This is https://github.com/r-lib/rlang/issues/530 again ;)

**Comment by hadley** [comment]
Hmmmmm, I think I do expect that `!!` to be the tightest binding operator of them all.

**Comment by hadley** [comment]
I expect it to be equivalent to operators that don't have spaces around them, which is [turns out](http://style.tidyverse.org/syntax.html#spacing) to include `^`
