### ISSUE TITLE
Feature suggestion: Logging eval_tidy

### ISSUE THREAD

**Issue by cfhammill** [r-lib/rlang#678]
I recently had need to figure out which symbols were coming from my data_mask in eval_tidy. My intended solution is to map over the mask replacing the data with a thunk that reports the symbol to a logging environment then evals the code.

This seems like a somewhat handy function. Although perhaps belongs in pryr. 

Any thoughts?

**Comment by lionel-** [comment]
Thanks for the suggestion. Sounds like this could be useful in some cases, but there is no plan to add this in rlang. Also pryr is no longer under development, we're trying to move stuff to lobstr and rlang.

Also check out the objectable package, it might be useful for logging environment info.

In what debugging scenario did you need this information?

**Comment by cfhammill** [comment]
It's actually not for debugging (evil, yes, I know). In our lens library (cfhammill/lenses) we implement a bidirectional version of `dplyr::filter`, meaning you can update a subset as though independent. To satisfy the lens laws, any columns used in the filter condition should be excluded from the result. Which columns are used can't be known statically, so I came up with this logging idea.

We have an unlawful version too, but this one is more interesting + desirable.

Thanks for the tip re lobstr. Should I open this issue there?

Also let me know if these are getting irritating.

**Comment by lionel-** [comment]
No worries, it's just that we're being a bit more conservative wrt what we include in rlang, in an effort to make the package more focused. Perhaps logging environments might be useful for lobstr. Would probably need to be implemented with objectables then, but that's still a github-only package. We're really waiting for ALTENV for this kind of stuff.

**Comment by cfhammill** [comment]
Totally makes sense. Thanks @lionel- !

I'll check out objectables and see what I can do.
