### ISSUE TITLE
Unknown local variable not throwing exception

### ISSUE THREAD

**Issue by akubisch** [r-lib/rlang#680]
Hi everyone,

I hope I'm in the right place - if not, please tell me!

We've discovered some concerning behavior in R when accessing a local variable in a function that has not been given to the function when calling:
```
test <- function(a) {
  b <- c(1, 2, 3)
  d <- b[a]
  return(d)
}
test()
```
I would have expected to get an error when calling `test()`, but instead I get `[1] 1 2 3`. Suppose this is a bug?

**Comment by lionel-** [comment]
It's not a bug, that's because it is equivalent to this:

```
letters[]
```

Subsetting without argument returns the full vector.

By the way, rlang is just a package. If you want to report bugs for R core, see their bugzilla: http://bugs.r-project.org/
