### ISSUE TITLE
Do we need try2()?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#684]
With tidy eval, something like:

``` r
my_catch_cnd <- function(expr) {
  quos <- rlang::enquos(expr)
  rlang::eval_tidy(
    rlang::quo(tryCatch(!!!quos, error = identity))
  )
}
my_catch_cnd(stop("test"))
#> <simpleError in ~stop("test"): test>
```

<sup>Created on 2018-11-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

I wonder if we can get rid of the tilde too.

**Comment by lionel-** [comment]
Perhaps `bang()` should use `eval_tidy()`, then it'd be just:

```r
catch_cnd <- function(expr) {
  bang(
    tryCatch(condition = identity, {
      force(!!enquo(expr))
      return(NULL)
    })
  )
}
```

> I wonder if we can get rid of the tilde too.

We'd need support for quosures in the R deparser. However we can inline every symbol in the call and evaluate it in the caller env, then we don't need the quosure:

```r
catch_cnd <- function(expr) {
  expr <- call2(tryCatch, condition = identity, expr({
    force(!!enexpr(expr))
    return(NULL)
  }))
  eval_bare(expr, caller_env())
}
catch_cnd(stop("test"))
#> Error in list2(...) : test
```

Note that `catch_cnd()` catches all conditions and is not suitable for capturing errors. Perhaps we need `try2()`.

**Comment by krlmlr** [comment]
May I suggest `dare()` instead of `try2()`?

Why does `catch_cnd()` return `NULL` anyway?

**Comment by krlmlr** [comment]
Does it mean we'll get a `stop2()`, `warning2()` and `message2()`? :upside_down_face:

If not in _rlang_, I'm not sure where this function would belong.

Thanks for looking into it!

**Comment by lionel-** [comment]
No but you've got `list2()`, `call2()` and `names2()`.

**Comment by lionel-** [comment]
There's also the issue of rlang backtraces. If the purpose of this function is to capture errors in knitr settings (cf your downstream issue in pkgdown), then it should probably set a trace top env as well. But is printing the error object rather than the error message the right thing to do in these settings?

**Comment by krlmlr** [comment]
I wanted similar behavior in the console (in particular with `example()`) and on a _pkgdown_ website, in situations where code raises an error. Printing the error object or the message will do, but the error mustn't leak.

**Comment by lionel-** [comment]
Probably out of scope for rlang.
