### ISSUE TITLE
Unquoting argument names with := fails in expr and quo

### ISSUE THREAD

**Issue by klmr** [r-lib/rlang#687]
I’ve noticed that unquoting argument names in a call via `:=` does not work inside `expr` and `quo`. Is this intentional? If so, how am I supposed to achieve the equivalent?

## MWE

```r
library(rlang)

x = sym('y')

(e = expr(list(!! x := 1)))
eval_bare(e)

(q = quo(list(!! x := 1)))
eval_tidy(q)
```

## Expected output

```
list(y = 1)
$y
[1]

<quosure>
expr: ^list(y = 1)
env:  global
$y
[1]
```

## Actual output

```
list(`:=`(y, 1))
Error: `:=` can only be used within a quasiquoted argument

<quosure>
expr: ^list(y := 1)
env:  global
Error: `:=` can only be used within a quasiquoted argument
```

Analogously with e.g. `tibble::tibble(!!x := 1)` I would expect the above to work. From what I understand of rlang from the documentation, it *should* work.

**Comment by lionel-** [comment]
Yes it is intentional. `:=` unquoting is a feature of functions taking dots like `exprs()` or `list2()`.

**Comment by lionel-** [comment]
The reason is that it makes it possible to use rlang to meta-program for APIs like data.table. Also it's always possible to deep-unquote names with `!!!set_names(list(x), nm)`, though it's more verbose.

**Comment by klmr** [comment]
> `:=` unquoting is a feature of functions taking dots like `exprs()` or `list2()`

It fails with `exprs`, too:

```r
exprs(list(y := 1 + 1))
```

… of course you probably mean that it works only when not nested inside a complex expression but this isn’t clear from the documentation and resources like the cheat sheet (they all imply that `!!`, `!!!` and `:=` are essentially on equal footing). I suggest adding a clarifying note.

For the suggested workaround I ended up having to nest `expr`(s) calls to avoid evaluating the parameters:

```r
expr(list(!!! set_names(exprs(1 + 2), x)))
```

**Comment by lionel-** [comment]
I have added a note in https://github.com/r-lib/rlang/commit/31b80d447ebbe3b1264d9924660f261280e7e23e

**Comment by egnha** [comment]
Would it help to add a remark in the docs that one can also do something like this?:
```R
call2("foo", !!nm := quote(x))
```
