### ISSUE TITLE
Syntactic sugar for !!sym(.)?

### ISSUE THREAD

**Issue by kendonB** [r-lib/rlang#694]
I use `!!sym(my_expr)` a lot in `filter` calls when I want to reference a column using a string. See below for an example of some uglyish code:

``` r
library(tidyverse)
this_variable <- "Sepal.Width"

iris %>% 
  filter(!!rlang::sym(this_variable) > 3.0) %>% 
  as_tibble()
#> # A tibble: 67 x 5
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl> <fct>  
#>  1          5.1         3.5          1.4         0.2 setosa 
#>  2          4.7         3.2          1.3         0.2 setosa 
#>  3          4.6         3.1          1.5         0.2 setosa 
#>  4          5           3.6          1.4         0.2 setosa 
#>  5          5.4         3.9          1.7         0.4 setosa 
#>  6          4.6         3.4          1.4         0.3 setosa 
#>  7          5           3.4          1.5         0.2 setosa 
#>  8          4.9         3.1          1.5         0.1 setosa 
#>  9          5.4         3.7          1.5         0.2 setosa 
#> 10          4.8         3.4          1.6         0.2 setosa 
#> # ... with 57 more rows
```

<sup>Created on 2018-12-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

It would be nice to be able to do something like:

```r
iris %>% 
  filter(!?this_variable > 3.0) 
```

**Comment by egnha** [comment]
@kendonB, you're right, that is indeed quite noisy. Some of that is due to the fact that `this_variable` ought to be a symbol, not a string, i.e., `this_variable <- quote(Sepal.Width)`. Then your filter is more simply `filter(!!this_variable > 3.0)`.

**Comment by kendonB** [comment]
In the real example, `this_variable` is generated by `paste0` and is dependent on a function input. What would one do in that case?

**Comment by lionel-** [comment]
You can transform it to a symbol outside the pipeline, to make the code clearer and easier to read:

```r
this_variable <- sym(paste0("Sepal.", "Width"))

iris %>% 
  filter(!!this_variable > 3.0) %>% 
  as_tibble()
```

You can also implement a `paste_sym()` or `paste0_sym()` wrapper if you'd like.

We have pondered whether to add this type of syntax in the early stages of tidy eval. We're unlikely to add it because syntax is best kept minimal.
