### ISSUE TITLE
Shortcut for `eval_bare(expr(!!...))`

### ISSUE THREAD

**Issue by vspinu** [r-lib/rlang#697]
Would it make sense to have a function `e` which would quasiquote and eval at once? 

Something like `e(lm(!!fmla, data))` instead of `eval(expr(lm(!!fmla, data))`. Somewhat similar to the purpose of #384.

**Comment by lionel-** [comment]
This is https://github.com/r-lib/rlang/pull/591, we've been trying to find a name for that function for like a year ;)
