### ISSUE TITLE
rlangy way to do assignment?

### ISSUE THREAD

**Issue by kendonB** [r-lib/rlang#698]
I'd like to be able to create and evaluate a variable assignment expression using rlang where the lhs of the assignment is made up on the fly. Is this possible? I tried the below:

``` r
library(rlang)
a <- expr(b)
eval_tidy(quo(!!a <- 1))
#> [1] 1
b
#> Error in eval(expr, envir, enclos): object 'b' not found
assign(x = as_string(a), value = 1)
b
#> [1] 1
```

<sup>Created on 2018-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by yutannihilation** [comment]
The environment for evaluation has the quosure's environment (in this case, the global environment) as its parent, so "in its original context" is correct in this sense. You can see the differences below:

``` r
library(rlang)

q <- quo({
  print(current_env())
  env_parents()
})

eval_tidy(q)
#> <environment: 0x7ff3a22402b0>
#> [[1]] $ <env: global>

eval_bare(quo_get_expr(q))
#> <environment: R_GlobalEnv>
#>  [[1]] $ <env: package:rlang>
#>  [[2]] $ <env: package:stats>
#>  [[3]] $ <env: package:graphics>
#>  [[4]] $ <env: package:grDevices>
#>  [[5]] $ <env: package:utils>
#>  [[6]] $ <env: package:datasets>
#>  [[7]] $ <env: package:methods>
#>  [[8]] $ <env: Autoloads>
#>  [[9]] $ <env: package:base>
#> [[10]] $ <env: empty>
```

You may wonder why `eval_tidy()` doesn't use the environment directly. In my understanding, this is because it allows you to insert a data mask.

``` r
eval_tidy(q, data = iris)
#> <environment: 0x7ff3a3ea9590>
#> [[1]]   <env: 0x7ff3a3ea9e50>
#> [[2]] $ <env: global>
```

<sup>Created on 2018-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by lionel-** [comment]
Why don't you use `assign()` or `env_bind()`?

**Comment by yutannihilation** [comment]
I forgot about `env_bind()`, thanks!

**Comment by lionel-** [comment]
oh and `env_poke()` which is a bit more convenient if the variable name is in a string. You can also use it with `map2()`

```r
map2(nms, values, env_poke, env = env)
```

Quosured symbols are automatically unwrapped when unquoted on the LHS of `:=`, so `env_bind()` might be convenient in that case:

```r
x <- quo(foo)
env_bind(current_env(), !!x := "bar")
foo
#> [1] "bar"
```

However I think quosured symbols are often indicative of a design issue. If you have a quosure, you shouldn't assume the type of expression inside it (at least that's my current thinking).

Finally, your analysis is correct, `eval_tidy()` will cause assignment to be performed in a data mask, even when you don't supply one (the minimal mask contains `~` binding to make quosures work).

**Comment by yutannihilation** [comment]
> However I think quosured symbols are often indicative of a design issue. If you have a quosure, you shouldn't assume the type of expression inside it

Totally agreed. Still, I slightly feel we might eventually find it useful to assign and refer to the variable in a seperated environment with quosures, though I don't have any paticular idea in my mind. e.g. can this be rewritten nicely if there's something like `tidy_assign()`?

``` r
get_counter <- function() {
  i <- 0
  function() {
    i <<- i + 1
    i
  }
}

counter <- get_counter()
counter()
```
