### ISSUE TITLE
`cnd_muffle`doesn't muffle conditions with different "abnormal" restarts

### ISSUE THREAD

**Issue by burchill** [r-lib/rlang#707]
This was mentioned in @hadley's comment in #224 : 

> I think it's reasonable to say that the signalling is always determined by the class of the condition

But see the following issue:

```r
library(rlang)
m_cond <- catch_cnd(inform("This is a message"))
with_handlers(warning(m_cond), message = calling(function(x) cnd_muffle(x)))
# Error in invokeRestart("muffleMessage") : 
#  no 'restart' 'muffleMessage' found
```

The problem is that the stock signaling functions (`stop`, `warning`, and `message`) all can take in a condition as an argument and signal that condition (without changing it), while throwing the restart methods of their "canonical" condition.

If the point of `cnd_muffle` is to muffle the conditions, shouldn't it be looking at the available restarts, rather than the class of the condition?  If you're already having to pray that restarts and condition classes have a 1-to-1 correspondence, isn't it a safer prayer that the first restart with "muffle" in its name will muffle the condition? 

The only downside I can see from doing the latter is if a user starts adding custom restarts with "muffle" in the name that **DON'T** muffle the condition. But what's more likely: that a user does something as simple as `warning(m_cond)`, or that a user is advanced enough to add custom restarts but would still rely on `cnd_muffle`?

I think the following would work just as well, but perhaps `computeRestarts` is very costly?

```r
cnd_muffle <- function (cnd) {
  possibleRestarts <- computeRestarts(cond)
  muffleRestarts <- possibleRestarts[grepl("muffle", Map(function(x) x$name, possibleRestarts))]
  resumeRestarts <- possibleRestarts[grepl("resume", Map(function(x) x$name, possibleRestarts))]
  if (length(muffleRestarts)) {
    invokeRestart(muffleRestarts[[1]])
  } else if (length(muffleRestarts)) {
    invokeRestart(resumeRestarts[[1]])
  } else {
    abort("Can't find a muffling restart")
  }
}

```

**Comment by lionel-** [comment]
Isn't it ok to just let these conditions unhandled? What is your use case?

**Comment by lionel-** [comment]
I wonder if `base::warning()`, `message()`, and `stop()` should add the relevant class to the condition, if not already there.

**Comment by burchill** [comment]
I honestly don't have a "use case" per se--I'm working on making a package that will make certain condition handling even simpler, and I want to make code that is robust as I possibly can.

The closest thing I have to a use case would be my desire to make something that catches, say, messages, and turns them into warnings and raises that. I theoretically wanted users to just pass functions like `warn` in as arguments, which could be directly applied to the captured conditions.

I'm relatively new to the whole R condition handling thing, so I don't really know how other packages and users do when raising conditions, etc.

**Comment by lionel-** [comment]
I think it's better to ensure that the class matches the signaller. I don't think we need to worry too much about these special cases though.

**Comment by lionel-** [comment]
We'll let these conditions go unhandled for now because I don't see a definite advantage to work around this.
