### ISSUE TITLE
expr() within a tibble is messy

### ISSUE THREAD

**Issue by md0u80c9** [r-lib/rlang#711]
Hi,

I've been experimenting with ways of doing selective data import of a very large CSV dataset (300-500 columns; 250,000 rows) by calculating which columns are needed for particular cohorts of data, skipping the ones which aren't needed and ergo skipping the post-import processing of those columns.

This led to me experimenting with having a tibble of the post-processing instructions - allowing the meta of being able to manipulate the instructions for building the data in much the same way as I'm manipulating the data.

Below is a table of two trivial sample rows of instructions - in this case simple conversions of a factor which is 'Y', 'N', NA to logical variables:

```
transforms_table <-
  tibble::tribble(
    ~transform_type, ~input_column, ~output_column, ~true_value, ~false_value, ~transform_function,
    "csv_factor_to_yn_logical", "S1ArriveByAmbulance", "S1ArriveByAmbulance", "Y", "N",
    rlang::exprs("S1ArriveByAmbulance" = factor_to_new_islogical_tf(
                .data[["S1ArriveByAmbulance"]], "Y", "N")
                ),
    "csv_factor_to_yn_logical", "S1OnsetInHospital", "S1OnsetInHospital", "Y", "N",
    rlang::exprs("S1OnsetInHospital" = factor_to_new_islogical_tf(
                .data[["S1OnsetInHospital"]], "Y", "N")
                )
)

```

The first problem is you can't form the expression using expr (unless you have a second column for the LHS) - otherwise you get unused argument errors).

You can however use exprs() where the LHS is treated as a named list of expressions.

I had expected at this point to do a simple splice and mutate:

```
  if (length(transforms_table[[1]] > 0)) {
    imported_data <- dplyr::mutate(imported_data,
      !!! transforms_table[["transform_function"]])
  }
```

However, because you've used exprs() in each row you're now dealing with a list of exprs() and not a column which you can treat as exprs().

You can unlist the column after creation which works.

I think the root cause of this problem is that
`list(expr("A" = my_fun(b), expr("C" = my_fun(d)) 
`

is invalid syntax, whereas:

```
my_exprs <- list(exprs("A" = my_fun(b)), exprs("C" = my_fun(d))) 
unlist(my_exprs)
```

Generates exprs without problems.

Any thoughts? Have I missed something here? Is there a better way to do this?

**Comment by lionel-** [comment]
I'm not sure I understand what you're trying to do. By the way, have you seen Jim's new package vroom?

**Comment by lionel-** [comment]
Why are you generating expressions for each row?

**Comment by md0u80c9** [comment]
Sorry if that wasn't clear: so in my workflow we have a (very large) tibble of raw data and different operations will produce different output cohorts of data using different columns dependent upon purpose. These combinations need to be easily extendible to cope with new columns being added to the data etc.

So to get around that I'm trying to build a tibble of post-processing instructions which will be applied to the raw data tibble. The rationale for that is we can subset which instructions are performed based upon filter criteria to the other columns. Imagine instead of the simple factor-to-boolean conversion in the opening example that they are potentially much more complex / time-consuming functions.

So if my data is in a tibble called data_table, and my expressions are in a tibble called my_exprs_table, I want to decide based upon what my end results need to contain which exprs I'll need to apply; filter my_exprs_table to end up with a column of expr objects which can be spliced into dplyr:

`dplyr::mutate(my_data_table, !!! my_exprs_table$my_exprs)
`

The intended benefit is that you can then subset the exprs being used based upon a set of filter criteria for the tibble (ie. use dplyr on dplyr...)


Yes I have seen vroom - it looks amazing (reminds me to offer Jim any help I can)! To be honest vroom is partly the motivation here: selective CSV column import using readr already helps improve my process by a factor of 2-3x (I've already optimised so once you know the list you use cols_skip on any column you don't need); it should be even more super-speedy with vroom; but that will only be effective if I then am selective about the post-import processing of the data. If I have a load of columns I don't need, but I then perform a full set of post-processing on them I end up loading them into memory after all.

**Comment by lionel-** [comment]
I'm still not sure what you're implementing and how, but would it help to store the expressions in a list-column in your tibble? You'd have a list of list of expressions of length `nrow()`.

**Comment by lionel-** [comment]
> isn't exprs() by definition a list-column

Any list can be a list-column, but it sounds like here you need a list of `exprs()`, so a list of lists. You need one list of expressions per row right? Or only one expression per row?

> Is there a reason expr doesn't allow anything on the left hand side

Because `expr()` returns an expression and an expression doesn't have a name. This is similar to how `1:5` can have internal names, but not external ones. The external name is a property of the container (a data frame, a list, ...), not the containee.

>  but then fails if spliced into dplyr

`:=` is meant as replacement for `=`, and can only be used in such contexts. Also splicing single expressions such as a `:=` call has been soft-deprecated and should issue a warning with recent rlang.

**Comment by lionel-** [comment]
I've read the discussion again and I think I'm starting to understand where you're going. You don't need a list-column of list of expressions, but a list-column of expressions that you can then filter.

```r
```

**Comment by md0u80c9** [comment]
Yes - exactly! I'll test that out this evening, but I think your suggestion makes sense to me - thank you!
