### ISSUE TITLE
Uninformative error when subsetting an NA quosure

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#715]
``` r
rlang::quo(NA)[-1]
#> Error in if (length(ans) == 0L || as.character(ans[[1L]])[1L] == "~") {: missing value where TRUE/FALSE needed
```

<sup>Created on 2019-01-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment]
Similarly for `quo(NULL)[-1]`

**Comment by lionel-** [comment]
Do we want to forward `[` to the contained object? Will this cause trouble for dbplyr?

**Comment by lionel-** [comment]
I think these options make sense:

* Failing with an error suggesting to use `quo_get_expr()` before subsetting.
* Forward `[` to the contained object.
* Implement the normal language subsetting with `~` in the head node which acts as a placeholder to be ignored, as in formulas.

This is related to the notion of scalars. Is a quosure a scalar? Probably depends on the task at hand, if you're parsing/reinterpreting language, it's recursive.

It seems like the least surprising semantics is to let quosures be subsettable as any other calls. Fixing the error message will require overriding `[.formula`. This should probably be fixed upstream as well.

**Comment by hadley** [comment]
Ah yeah, it should probably be:

```R
`[.quosure` <- function(x, ...) {
  new_quosure(NextMethod(), quo_get_env(x))
}
```

**Comment by lionel-** [comment]
I think I'd prefer an error suggesting to use `call_modify()`.
