### ISSUE TITLE
Allow `enquo` to accept string arguments?

### ISSUE THREAD

**Issue by zachary-foster** [r-lib/rlang#716]
Thanks for the great package! I am just starting to understand all this, so forgive me if I missed something.

I have a function with about 50 parameters (I know that's not ideal) and I want do the same custom evaluation for them all with a function called `obj$eval_one` or `obj$eval_many`, and I am trying to avoid having 50 statements like this:

```r
param <- obj$eval_one(!! rlang::enquo(param))
```
After much pain, I managed to get it to work like this:

```r
raw_arguments <- as.list(match.call()[-1])
arguments <- obj$eval_many(!!! rlang::eval_tidy(rlang::call2(rlang::enquos, !!! rlang::syms(names(raw_arguments)))))
names(arguments) <- names(raw_arguments)
for (i in seq_along(arguments)) {
  assign(names(arguments)[i], arguments[[i]])
}
```
I originally hoped I could do this:

```r
raw_arguments <- as.list(match.call()[-1])
arguments <- obj$eval_many(!!! rlang::eval_tidy(rlang::enquos(names(raw_arguments))))
names(arguments) <- names(raw_arguments)
for (i in seq_along(arguments)) {
  assign(names(arguments)[i], arguments[[i]])
}
```
 
But `enquo`/`enquos` cannot accept strings. Would this be a useful/possible addition, or is there a better way to approach this?

Thanks!

**Comment by lionel-** [comment]
I would probably use something like this:

```r
enquos_ <- function(args) {
  enquos_call <- expr(enquos(!!!syms(args)))
  eval_bare(enquos_call, caller_env())
}

f <- function(foo, bar) {
  enquos_(c("foo", "bar"))
}
```

But I don't think it would be useful enough to include in rlang. Thanks for the suggestion though.
