### ISSUE TITLE
is_na(NaN)

### ISSUE THREAD

**Issue by grayskripko** [r-lib/rlang#717]
why is it TRUE?

**Comment by lionel-** [comment]
`NaN` are considered missing values in R.

**Comment by grayskripko** [comment]
as well as NA. What if I'm interested in treating them separately?
As for now, 

```{r}
> is.nan(c(NA, NaN))
[1] FALSE  TRUE
> is.na(c(NA, NaN))
[1] TRUE TRUE
```

I thought ```rlang``` and the whole family of ```tidyverse``` packages tend to be explicit as much as possible. That's why I was forced to know different typed versions of NA (NA_real_ and so on) . Because of usage of ```if_else()```
So, I would rather expect

```{r}
c(NA, NaN) %>% map_lgl(is_na)  # T, F
c(NA, NaN) %>% map_lgl(is_nan)  # F, T
```

**Comment by grayskripko** [comment]
for the missing values it's possible to combine them in something like ```is_missing```. But there are ```Inf``` and ```-Inf``` values too.

**Comment by lionel-** [comment]
Once we integrate vctrs in dplyr, you won't be forced to know about the typed NAs anymore.

We could in principle differentiate, but I'm not sure we need to, and I'm not sure of the implications.

**Comment by lionel-** [comment]
Of relevance

```r
identical(NA_real_, NaN)
#> [1] FALSE
```

**Comment by grayskripko** [comment]
wow. I've found the ```vctrs``` package. Why don't you just write the whole new language? :) Something like a hybrid of R and Haskell.
Anyway, I like and believe in everything the ```tidyverse``` team produces.

**Comment by grayskripko** [comment]
thanks for ```identical()``` solution. I haven't known.

As far as I see how the biggest concepts are revised in R it's hard to accept the answer 

> NaN are considered missing values in R.

**Comment by lionel-** [comment]
Right, but at the same time we should not change things lightly. I agree that on the surface it seems missing values and NaN are two different concepts, and so shouldn't be considered the same. However there most certainly is a reason behind this, and I do not know what it is. The compositional implications have to be considered before making the change.

**Comment by grayskripko** [comment]
ok, this is clear to me, thanks
