### ISSUE TITLE
`with_handlers` doesn't preserve handler order

### ISSUE THREAD

**Issue by burchill** [r-lib/rlang#718]
For `withCallingHandlers` and `tryCatch`, conditions are checked by the applicable handlers *in the order in which they were specified*.  E.g., with the following handlers, a warning message would be be checked by both handlers: 

```r
# prints "CONDITION", then "WARNING"
withCallingHandlers(warning("woops!"),
              condition = function(x) print("CONDITION"),
              warning = function(x) {print("WARNING"); cnd_muffle(x)})
```

However, `with_handlers` only respects order *within* exiting/calling classes.  The following only checks the warning handler:

```r
# prints only "WARNING"
with_handlers(warning("woops!"),
              condition = calling(function(x) print("CONDITION")),
              warning = exiting(function(x) { print("WARNING")}))
```

Would it not make sense to change this arguably unintuitive arrangement? Letting users specify the order the handlers are checked would give them more control and make input more consistent with other base condition-handling code. It seems like the following code could do the same thing but would preserve order:

```r
with_handlers <- function(.expr, ...) {
  handlers <- list2(...)
  is_calling <- map_lgl(handlers, inherits, "rlang_box_calling_handler")
  handlers <- map_if(handlers, is_calling, unbox)
  handlers <- map(handlers, as_function)
  expr <- quote(.expr)
  
  for (i in 1:length(handlers)) {
    handler <- handlers[i]
    if (is_calling[[i]]) 
      expr <- expr(withCallingHandlers(!!expr, !!!handler))
    else
      expr <- expr(tryCatch(!!expr, !!!handler))
  }
  .Call(rlang_eval, expr, environment())
}
```

Are there any downsides to doing it this way?

**Comment by lionel-** [comment]
I think the calling handlers should all come first. But it looks like they currently come last!

**Comment by burchill** [comment]
That does make _more_ sense I'll admit, but I still feel like letting the users control the order makes the most. (But this ain't my package, in the end)

**Comment by lionel-** [comment]
Adding calling handlers outside of exiting handlers doesn't make sense because they will never be called.

**Comment by burchill** [comment]
That's only true _within_ a particular condition class.  Let's say you wanted to muffle everything that wasn't a `simpleWarning`, which you would want to exit for, using an "all callers first" approach. 

First, as far as I know, you actually _couldn't_ do that without a bunch of janky workarounds / having two handlers with the same name. But second, even if you _could_, it would require code something like this:

```r
with_handlers(expr,
  interrupt = calling(cnd_muffle), 
  message = calling(cnd_muffle), 
  warning = calling(cnd_muffle), # Technically would block `simpleWarning`, making it impossible
  simpleWarning = exiting(...)
)
```

Checking handlers in order (regardless of calling/exiting type) would 1) actually let you _do_ it and 2) use much less code:

```r
with_handlers(expr,
  simpleWarning = exiting(...),
  condition = calling(cnd_muffle)
)
```

Now that I think about it, one actually faces similar hard limitations with the _current_ "all exiting handlers first" approach.  Imagine the inverse of the above--that you wanted to exit for every condition that _wasn't_ a `simpleWarning`, but muffle those.  I don't think you could do it with the current set-up without major hacks.

Given these scenarios, I actually believe _more_ strongly that evaluating them in order is the right way to go. It's consistent with previous code, gives more control to the user (in an intuitive way), and avoids the hard limitations of the alternatives, all with having no discernible downsides!

**Comment by lionel-** [comment]
> you actually couldn't do that without a bunch of janky workarounds

Handlers are ordinary functions. Just write a new handler that conditionally calls `cnd_muffle()`.

> all with having no discernible downsides

You're forgetting complexity of the implementation. You don't want to rewrap in withCallingHandlers / tryCatch if not necessary, for performance and cleanliness of backtraces. I would consider an implementation that avoids unnecessary wrappings.

>  gives more control to the user (in an intuitive way),

I wouldn't say that the evaluation timing of handlers is intuitive. It's easy to forget/overlook that calling handlers have to be on the inside to be able to recover an error. Your proposed UI might be more flexible for expert users, but less usable for casual users.

**Comment by burchill** [comment]
> Handlers are ordinary functions. Just write a new handler that conditionally calls cnd_muffle().

Yeah, that's fair. Good point.

> You're forgetting complexity of the implementation. You don't want to rewrap in withCallingHandlers / tryCatch if not necessary, for performance and cleanliness of backtraces. I would consider an implementation that avoids unnecessary wrappings.

Yeah, that's what I was asking about when I was wondering about downsides. Theoretically, it could be wrapped a _lot_ (if there were a lot of handlers), and I had the feeling it might do something screwy in that regard. Thanks!
