### ISSUE TITLE
FR: C equivalent of a closure

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#722]
For https://github.com/r-lib/vctrs/issues/124#issuecomment-458462076.

Implementation along the lines of:

```r
new_native_closure <- function(c_callable, data) {
  list(c_callable = c_callable, data = data)
}

call_native_closure <- function(x, ...) {
  call_c_callable(x$c_callable, x$data, list2(...))
}
```

With a corresponding C interface:

```c
SEXP rlang_call_native_closure(SEXP x, SEXP aux) {
  c_callable = VECTOR(x)[0];
  data = VECTOR(x)[1];
  return rlang_call_c_callable(c_callable, data, aux);
}
```

Is this something we could support in _rlang_?

**Comment by krlmlr** [comment]
`c_callable` is a pointer to a function, yes. I think we need two arguments, which can be pairlists. Type checking will be up to the callable.

**Comment by lionel-** [comment]
Currently out of scope, let's revisit in the future.
