### ISSUE TITLE
is_integerish with bit64::integer64

### ISSUE THREAD

**Issue by mmuurr** [r-lib/rlang#723]
`rlang::is_integerish` gives different results for `bit64::integer64` objects between rlang versions 0.2.2 and 0.3.1 (sorry, I don't have the in-between build installed to find the exact release of the change).

Previously:
```R
> rlang::is_integerish(bit64::as.integer64(1))
[1] TRUE
> packageVersion("bit64")
[1] ‘0.9.7’
> packageVersion("rlang")
[1] ‘0.2.2’
```

Now:
```R
> rlang::is_integerish(bit64::as.integer64(1))
[1] FALSE
> packageVersion("bit64")
[1] ‘0.9.7’
> packageVersion("rlang")
[1] ‘0.3.1’
```

In my usage this doesn't cause a problem as I've added a specific test for integer64 objects, but figured it'd be worth documenting here for others. :-)

**Comment by mmuurr** [comment]
Just a thought to add to this, I notice the current `is_integerish` implementation is a `.Call` ... is there any plan to implement some of rlang's basic functions as generics so other packages (e.g. bit64) can write the implementations to allow for easy use with rlang?

**Comment by lionel-** [comment]
This is probably out of scope for rlang because this would make `is_integerish()` a conceptual predicate rather than a base type predicate. Might be relevant in vctrs or funs though.
