### ISSUE TITLE
Add appendLF flag to rlang::inform

### ISSUE THREAD

**Issue by x1o** [r-lib/rlang#729]
Please consider adding an analogue of `base::message()`'s `appendLF` flag to `rlang::inform`.

**Comment by lionel-** [comment]
We always append a newline by design, consistenly with other signaller functions.

**Comment by x1o** [comment]
What's the right way to implement "Doing X... done" kind of logging then?

**Comment by lionel-** [comment]
I would probably use a variant of `cat()`:

```r
is_suppressed <- function() {
  withRestarts(
    muffleMessage = function(...) TRUE,
    {
      signalCondition(message_cnd())
      FALSE
    }
  )
}
cat_log <- function(..., file = stderr()) {
  if (!is_suppressed()) {
    cat(..., file = file)
  }
}

cat_log("foo\n")
#> foo

suppressMessages(cat_log("foo\n"))
#>
```

**Comment by x1o** [comment]
@lionel- that's alright, but why not include *an optional* switch to do just that?

**Comment by lionel-** [comment]
Then you'd still be missing the `cat()` features such as ability to pipe to a log file rather than stderr.

**Comment by x1o** [comment]
IMHO printing to the console is a much more frequent task than logging to a file (in which case I'd rather use another package or write my own wrapper indeed). As a user, I don't need all of `cat()`'s functionality. If `inform`, `warn` and `abort` are drop in replacements for the corresponding base R functions, wouldn't that be wrong to *sometimes* use `inform` and *sometimes* `message`?

**Comment by lionel-** [comment]
The other issue is that if the thing that's being done fails for some reason, then a new line is missing. I'm not sure it's good practice to output incomplete strings to the REPL.

**Comment by lionel-** [comment]
For this reason, perhaps signalling progress is a job for the cli package rather than rlang. The signalling function would take both pre- and post- messages and ensure newline termination with an exit handler.

**Comment by x1o** [comment]
> The other issue is that if the thing that's being done fails for some reason, then a new line is missing.

Perhaps wrapping with `tryCatch` might help.

> For this reason, perhaps signalling progress is a job for the cli package rather than rlang. The signalling function would take both pre- and post- messages and ensure newline termination with an exit handler.

That makes sense, thank you.

`cli` doesn't seem to support this functionality right now though, so probably I should go to their repo and open another annoying ticked... :)
