### ISSUE TITLE
Should has_name() work with an environment?

### ISSUE THREAD

**Issue by jennybc** [r-lib/rlang#737]
From `has_name()` help:

> This function returns a logical value that indicates if a data frame or another named object contains an element with a specific name.

I had hopes that `has_name()` would work for an environment, yet it does not. Are we supposed to use `env_has()` directly in this case?

``` r
e <- new.env(parent = emptyenv())

rlang::has_name(e, "yo")
#> Error: Use env_names() for environments.
#> Backtrace:
#>     █
#>  1. └─rlang::has_name(e, "yo")
#>  2.   ├─name %in% names2(x)
#>  3.   └─rlang::names2(x)

rlang::env_has(e, "yo")
#>    yo 
#> FALSE
```

<sup>Created on 2019-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by lionel-** [comment]
Good question. The conservative approach is for `has_name()` and `names2()` to only work with vectors. The bold approach is to let it work with all containers implementing `names()`. cc @hadley

**Comment by hadley** [comment]
I think `names`-functions should only work with real vectors, i.e. things that support `[` (not just `[[` like environments)

**Comment by lionel-** [comment]
Should we rename `env_names()` to `env_bindings()`?
