### ISSUE TITLE
Unquoting base operators in prefix notation

### ISSUE THREAD

**Issue by juangomezduaso** [r-lib/rlang#739]
I am trying to learn about tidy evaluation and unqoting, and I am surprised to see that  these two get different results:

```
> qq_show(!!`&&`(T,F))
FALSE
> qq_show(!!`+`(1,2))
1 + 2
```

It seems that in the second case the bang bang operates on the first argument instead of the whole call.

```
> a <- 3
> qq_show(!!`+`(a,a))
3 + a
```

Which is what both do in infix notation.
Some binary operators are of the first kind and some are of the other.
I am sorry if this is a know/discused/solved issue that i wasn't able to find.

**Comment by lionel-** [comment]
That's because we reorder the AST to change the precedence, so that `!!a + b` works the expected way. It is not possible to distinguish between `!!a + b` and `` !!`+`(a, b) ``, so we reorder the AST in both cases.

Just use parentheses to specify the precedence: `!!(a + b)`.

**Comment by juangomezduaso** [comment]
I suposed this was the reasonable behavior for +, but was confused whit the difference behavior of other operators. My concern had more to do with the logic operators. &&, shows diffrent results :
 qq_show(!! T && F)
TRUE && F
> qq_show(!! `&&`(T, F))
FALSE
Here the infix notation gives the reasonable result but the prefix doesnt (acts like a call?)

**Comment by lionel-** [comment]
Yes exactly. Ideally you'd be able to control the precedence by using the prefix form. It's just that there's no way to know the prefix form was used in the case of `+`:

```r
> lobstr::ast(!`+`(a, b))
█─`!` 
└─█─`+` 
  ├─a 
  └─b 

> lobstr::ast(!a + b)
█─`!` 
└─█─`+` 
  ├─a 
  └─b 
```

Compare to `&`:

```r
> lobstr::ast(!a & b)
█─`&` 
├─█─`!` 
│ └─a 
└─b 

> lobstr::ast(!`&`(a, b))
█─`!` 
└─█─`&` 
  ├─a 
  └─b 
```

I'm afraid we need to live with this inconsistency.

**Comment by juangomezduaso** [comment]
Not really a problem in practice. And as you said, one can be safe with a few defensive parentheses here and there. It seems a cheap price for what we get with this awesome package.
Thank you very much for your detailed response!
