### ISSUE TITLE
exec doesn’t work in pipes

### ISSUE THREAD

**Issue by flying-sheep** [r-lib/rlang#740]
```r
> library(rlang)
> `%>%` <- magrittr::`%>%`
> list(LETTERS[1:3], collapse = '.') %>% exec(paste, !!!.)      
```
```                                                                                                    
Error in do.call(.fn, args, envir = .env): 'what' must be a function or character string
Traceback:

1. list(LETTERS[1:3], collapse = ".") %>% exec(paste, !!!.)
2. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
3. eval(quote(`_fseq`(`_lhs`)), env, env)
4. eval(quote(`_fseq`(`_lhs`)), env, env)
5. `_fseq`(`_lhs`)
6. freduce(value, `_function_list`)
7. withVisible(function_list[[k]](value))
8. function_list[[k]](value)
9. exec(., paste, !!!.)
10. do.call(.fn, args, envir = .env)
```

**Comment by lionel-** [comment]
See https://github.com/tidyverse/magrittr/issues/191

**Comment by choisy** [comment]
`purrr::invoke()` worked in pipes. Now, if `purrr::invoke()` is supposed to be replaced by `rlang::exec()` that doesn't work in pipes, how do we do with our pipes???

**Comment by lionel-** [comment]
* `invoke()` is retired but not deprecated. You can keep using it.

* You can wait for magrittr to fix it.

* You can use this workaround if you like: `list(na.rm = TRUE) %>% { exec(mean, 1:5, !!!.) }`

* You can use `do.call()`.

**Comment by choisy** [comment]
Thanks a lot. Very useful.
"Wait for `magrittr` to fix it": what's the plan in that respect?
