### ISSUE TITLE
Can name a variable in mutate_at according to the name of the function called

### ISSUE THREAD

**Issue by jazzmoe** [r-lib/rlang#741]
I want to create a function that mutates all variables specified in ... with a particular metric specified by the metric argument. I use mutate_at in the function and want it to rename the variable with "var.functionname". The function is as follows:

```
seasonAggregator <- function(.data, ..., metric = "sum") {
  # all variables in ... will be accumulated
  metric <- sym(metric)
  name <- ensym(metric)
  print(paste0("Metric for accumulation was: ", metric))
  .data <- .data %>% mutate_at(vars(...), .funs = list(!!name := metric)) # HERE IS THE ISSUE
  return(.data)
}
```

How can I specify the function in the metric argument as such, that the mutate_at uses the name of the function to rename the variables?

Best Moritz!

**Comment by lionel-** [comment]
Hello,

This is an issue tracker for bugs and feature requests. Could you post your question on stackoverflow or community.rstudio.com please? Thanks!
