### ISSUE TITLE
Can't update from 0.3.1 to 0.3.2

### ISSUE THREAD

**Issue by Marieag** [r-lib/rlang#743]
Hi! 

I keep getting this issue 

```
These packages have more recent versions available.
Which would you like to update?

1:   rlang (0.3.1 -> 0.3.2) [CRAN]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 1
rlang (0.3.1 -> 0.3.2) [CRAN]
Installing 1 packages: rlang

  There is a binary version available but the source version is later:
      binary source needs_compilation
rlang  0.3.1  0.3.2              TRUE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/rlang_0.3.1.zip'
Content type 'application/zip' length 1081821 bytes (1.0 MB)
downloaded 1.0 MB

package ‘rlang’ successfully unpacked and MD5 sums checked
Error: (converted from warning) cannot remove prior installation of package ‘rlang’
```
I've tried downloading from various sources, deleting the folder and reinstalling and all that, but it doesn't seem to work. 
Any idea what I can do to make it behave? 

Thanks!

**Comment by lionel-** [comment]
Looks like the installer depends on rlang and this prevents it from updating it. This should be solved by the pak package in the future I think (cc @gaborcsardi).

Can you try `install.packages("rlang", type = "source")` in a fresh session please?

**Comment by Marieag** [comment]
Yay, a catch-22. Typical. 
When I run installation with source, I get this error:

```
> install.packages("rlang", type = "source"); packageVersion("rlang")
trying URL 'https://cran.rstudio.com/src/contrib/rlang_0.3.2.tar.gz'
Content type 'application/x-gzip' length 858244 bytes (838 KB)
downloaded 838 KB

* installing *source* package 'rlang' ...
** package 'rlang' successfully unpacked and MD5 sums checked
** libs

*** arch - i386
Advarsel i system(cmd) : 'make' not found
ERROR: compilation failed for package 'rlang'
* removing 'D:/Program Files/R/R-3.5.3/library/rlang'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘rlang’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\Marie\AppData\Local\Temp\RtmpETwexE\downloaded_packages’
Error in packageVersion("rlang") : package ‘rlang’ was not found
```
I can't remember having gotten that error before...

**Comment by lionel-** [comment]
Maybe you need to install Rtools to compile packages from source? Another solution is to wait a bit, the Windows binaries for 0.3.2 will likely appear today or tomorrow.

**Comment by Marieag** [comment]
Didn't work either. Guess I'll just have to wait for a little while until the binaries update. Thanks for your help, though :)

**Comment by jlzrgs** [comment]
Hi, 
I have the exact same issue, did you find a way to fix it or is it still not working ?

**Comment by lionel-** [comment]
The Windows binaries are now available.

**Comment by jlzrgs** [comment]
Problem solved, my version of R was just too old.

**Comment by lionel-** [comment]
Ah yes binaries are only provided for 2 versions of R.
