### ISSUE TITLE
Broken NEWS link in RStudio

### ISSUE THREAD

**Issue by siddharthprabhu** [r-lib/rlang#745]
Hello,

The NEWS link for rlang in RStudio's Update Packages window is broken. I'm not sure whether this is something that package developers define or whether it's handled by RStudio itself.

![image](https://user-images.githubusercontent.com/39954383/54862416-6056a100-4d60-11e9-8f96-6e2b90a72ef5.png)
![image](https://user-images.githubusercontent.com/39954383/54862426-a6ac0000-4d60-11e9-93fd-7ab28e4683bb.png)

The link must instead point to [https://cran.rstudio.com/web/packages/rlang/news/news.html](https://cran.rstudio.com/web/packages/rlang/news/news.html). Is this something that can be fixed by the rlang team?

**Comment by lionel-** [comment]
Does this happen only with rlang? This is probably an RStudio IDE issue. Maybe CRAN changed the URL?

**Comment by siddharthprabhu** [comment]
@lionel- No, it's not exclusive to rlang. I've encountered the issue with many tidyverse packages too (among others). However, not all packages have broken links. zoo for example correctly directs the user to [https://cran.rstudio.com/web/packages/zoo/NEWS](https://cran.rstudio.com/web/packages/zoo/NEWS).

It's clear that CRAN did change the URL at some point in the past (the additional **/news/** in the path). However, since the NEWS link works correctly with some packages and not with others, I suspect the issue might be something package-specific rather than the RStudio IDE overall.

**Comment by lionel-** [comment]
CRAN probably changed the URL for packages with `NEWS.md` files. Could you post the issue on the RStudio tracker please?
