### ISSUE TITLE
issues with gcc 7.2  in the new version of R

### ISSUE THREAD

**Issue by GaGaMan1101** [r-lib/rlang#754]
When I upgraded the R, I installed `rlang`, however, I had below errors, and I could not downgrade my gcc to 7.2

/usr/local/Cellar/gcc/7.2.0/bin/gcc-7 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./lib/  -I/usr/local/include   -fPIC  -Wall -g -O2  -c capture.c -o capture.o
/bin/sh: /usr/local/Cellar/gcc/7.2.0/bin/gcc-7: No such file or directory
make: *** [capture.o] Error 127
ERROR: compilation failed for package ‘rlang’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rlang’
Warning in install.packages :
  installation of package ‘rlang’ had non-zero exit status

**Comment by lionel-** [comment]
It looks like R can't find your compiler:

```
/bin/sh: /usr/local/Cellar/gcc/7.2.0/bin/gcc-7: No such file or directory
```

What does `echo $CC` yield? Did you set `CC` to a particular value in your `~/.R/Makevars` file?

**Comment by GaGaMan1101** [comment]
thanks 

> It looks like R can't find your compiler:
> 
> ```
> /bin/sh: /usr/local/Cellar/gcc/7.2.0/bin/gcc-7: No such file or directory
> ```
> What does `echo $CC` yield? Did you set `CC` to a particular value in your `~/.R/Makevars` file?

`echo $CC` returns null,

here is what in `~/.R/Makevars`:
CC=/usr/local/Cellar/gcc/7.2.0/bin/gcc-7
CXX=/usr/local/Cellar/gcc/7.2.0/bin/g++-7
CXX11=/usr/local/Cellar/gcc/7.2.0/bin/g++-7
CXX14=/usr/local/Cellar/gcc/7.2.0/bin/g++-7
cxx17=/usr/local/cellar/gcc/7.2.0/bin/g++-7
cxx1X=/usr/local/cellar/gcc/7.2.0/bin/g++-7
LDFLAGS=-L/usr/local/Cellar/gcc/7.2.0/lib%

**Comment by lionel-** [comment]
ah then you need to change your Makevars to an existing compiler. Look where brew installed gcc-8 and update the variables.

You can discover the files with:

```
brew list gcc
```

**Comment by GaGaMan1101** [comment]
/usr/local/Cellar/gcc/8.3.0/bin/c++-8
/usr/local/Cellar/gcc/8.3.0/bin/cpp-8
/usr/local/Cellar/gcc/8.3.0/bin/g++-8
/usr/local/Cellar/gcc/8.3.0/bin/gcc-8
/usr/local/Cellar/gcc/8.3.0/bin/gcc-ar-8
/usr/local/Cellar/gcc/8.3.0/bin/gcc-nm-8
/usr/local/Cellar/gcc/8.3.0/bin/gcc-ranlib-8
/usr/local/Cellar/gcc/8.3.0/bin/gcov-8
/usr/local/Cellar/gcc/8.3.0/bin/gcov-dump-8
/usr/local/Cellar/gcc/8.3.0/bin/gcov-tool-8
/usr/local/Cellar/gcc/8.3.0/bin/gfortran
/usr/local/Cellar/gcc/8.3.0/bin/gfortran-8
/usr/local/Cellar/gcc/8.3.0/bin/x86_64-apple-darwin17.7.0-c++-8
/usr/local/Cellar/gcc/8.3.0/bin/x86_64-apple-darwin17.7.0-g++-8
/usr/local/Cellar/gcc/8.3.0/bin/x86_64-apple-darwin17.7.0-gcc-8
/usr/local/Cellar/gcc/8.3.0/bin/x86_64-apple-darwin17.7.0-gcc-8.3.0
/usr/local/Cellar/gcc/8.3.0/bin/x86_64-apple-darwin17.7.0-gcc-ar-8
/usr/local/Cellar/gcc/8.3.0/bin/x86_64-apple-darwin17.7.0-gcc-nm-8
/usr/local/Cellar/gcc/8.3.0/bin/x86_64-apple-darwin17.7.0-gcc-ranlib-8
/usr/local/Cellar/gcc/8.3.0/bin/x86_64-apple-darwin17.7.0-gfortran-8
/usr/local/Cellar/gcc/8.3.0/include/c++/ (752 files)
/usr/local/Cellar/gcc/8.3.0/lib/gcc/ (608 files)
/usr/local/Cellar/gcc/8.3.0/libexec/gcc/ (13 files)
/usr/local/Cellar/gcc/8.3.0/share/gcc-8.3.0/ (4 files)
/usr/local/Cellar/gcc/8.3.0/share/man/ (10 files)

**Comment by lionel-** [comment]
yup that's it, just update the Makevars variables to point to `g++-8` and `gcc-8` and you're done :)

**Comment by GaGaMan1101** [comment]
@lionel- 
I have updated to this 
CC=/usr/local/Cellar/gcc/8.3.0/bin/gcc-8
CXX=/usr/local/Cellar/gcc/8.3.0/bin/g++-8
CXX11=/usr/local/Cellar/gcc/8.3.0/bin/g++-8
CXX14=/usr/local/Cellar/gcc/8.3.0/bin/g++-8
cxx17=/usr/local/cellar/gcc/8.3.0/bin/g++-8
cxx1X=/usr/local/cellar/gcc/8.3.0/bin/g++-8
LDFLAGS=-L/usr/local/Cellar/gcc/8.3.0/lib

however had a new error
`/usr/local/Cellar/gcc/8.3.0/lib/gcc/8/gcc/x86_64-apple-darwin17.7.0/8.3.0/include-fixed/stdio.h:78:10: fatal error: _stdio.h: No such file or directory`

**Comment by GaGaMan1101** [comment]
@lionel- sorry mate, new error

**Comment by lionel-** [comment]
At https://github.com/Microsoft/LightGBM/issues/1420#issuecomment-394652782 they suggest to reinstall XCode cli tools.

**Comment by lessig7** [comment]
> 

How does one "update the Makevars variables to point to g++-8 and gcc-8"? I'm having the same problem and can't figure out how to do as you recommended.

**Comment by lionel-** [comment]
Find the paths to gcc and g++ (not necessarily versions 8) and inline them in the Makevars file.
Alternatively, add your homebrew/bin directory to your PATH (I'm assuming you have a mac) and just refer to the program names.

In my Makevars I have:

```
CC = gcc-11
CXX = g++-11
CXX11 = g++-11
```

And the corresponding bin folder in my path so that these commands can be found:

```sh
command -v gcc-11
#> /opt/homebrew/bin/gcc-11
```

Note this is just an example, I'm using the arm64 distribution of homebrew on M1. On your computer this might be somewhere else. You might need to call `brew link` on the GCC package.

Overall it's probably easier to use clang which should be installed by default with XCode.

```
CC = clang
CXX = clang++
CXX11 = clang++
```
