### ISSUE TITLE
Include package::function information

### ISSUE THREAD

**Issue by wetlandscapes** [r-lib/rlang#763]
I was thinking it would make profiling/error identification a lot easier if there was an argument/option for `abort`, `warn`, etc. to include information about the package and function where the signal was raised.

This is my "manual" version of the kind of behavior I am thinking about; the `windower` function is just a dummy function used to raise an exception:
```
windower <- function(x) {
  if(!is.numeric(x)) {
    pf <- environmentName(parent.frame())
    func <- match.call()[[1]]
    pf_func <- paste0("`", pf, "::", func, "`")
    rlang::abort(paste0(pf_func, " was expecting a numeric value."))
  }
}
windower(letters)
```
This would be the error:
```
Error: `R_GlobalEnv::windower` was expecting a numeric value.
```
I'm guessing my example is a lot easier to implement because I'm in the actual environment raising the exception.

**Comment by lionel-** [comment]
In general we opt not to display call information in error messages, unlike `stop()`. To get information about both the call and the namespace, users can call `rlang::last_error()` to get a simplified trace with namespace prefixes.
