### ISSUE TITLE
"ggpubr" problem wuth rlang

### ISSUE THREAD

**Issue by XWeiZhou** [r-lib/rlang#767]
Hi All！
when I run the code something the wrong will occurs. My code  as follows:
##
> library("ggpubr")
> data("ToothGrowth")
> head(ToothGrowth)
   len supp dose
1  4.2   VC  0.5
2 11.5   VC  0.5
3  7.3   VC  0.5
4  5.8   VC  0.5
5  6.4   VC  0.5
6 10.0   VC  0.5
> compare_means(len~supp, data=ToothGrowth)
Error in filter_impl(.data, quo) : Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0.
Please use `as_data_pronoun()` instead.

##
> traceback()
18: stop(list(message = "Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0.\nPlease use `as_data_pronoun()` instead.", 
        call = filter_impl(.data, quo), cppstack = NULL))
17: .Call(`_dplyr_filter_impl`, df, quo)
16: filter_impl(.data, quo)
15: filter.tbl_df(tbl_df(.data), ...)
14: filter(tbl_df(.data), ...)
13: as.data.frame(filter(tbl_df(.data), ...))
12: filter.data.frame(., !is.na(p))
11: dplyr::filter(., !is.na(p))
10: function_list[[k]](value)
9: withVisible(function_list[[k]](value))
8: freduce(value, `_function_list`)
7: `_fseq`(`_lhs`)
6: eval(quote(`_fseq`(`_lhs`)), env, env)
5: eval(quote(`_fseq`(`_lhs`)), env, env)
4: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
3: pvalues %>% tidyr::gather(key = "group1", value = "p", -group2) %>% 
       dplyr::select(group1, group2, p) %>% dplyr::filter(!is.na(p))
2: test.func(formula = formula, data = data, method = method, paired = paired, 
       p.adjust.method = "none", ...)
1: compare_means(len ~ supp, data = ToothGrowth)

I don't know why always occurs! Thank you very much!

Wei

**Comment by lionel-** [comment]
You are probably using Windows. On this platform, installation of packages with DLLs can fail silently. There was likely an issue when you updated dplyr. Please close all your instances of R and RStdio, and reinstall dplyr in a fresh session.

**Comment by XWeiZhou** [comment]
Dear Lionel 

Thank you so much for your attention and suggestions. It works well and my problem has been solved under your suggestions. First, I closed all instances in RStudio and delete the dplyr package(V 0.7), then reinstall a new dplyr package (V 0.8.0.1). Finally, it works.
Thank you so much.

Best
Wei
