### ISSUE TITLE
r_init_library

### ISSUE THREAD

**Issue by gaelledoucet** [r-lib/rlang#768]
I am trying to install rlang but keep having the same error (tried multiple times in different ways/ versions/...):
> devtools::install_github("cran/rlang")
Error: .onLoad failed in loadNamespace() for 'rlang', details:
  call: fun(libname, pkgname)
  error: object 'r_init_library' not found 

I would really appreciate any help or advice on how to fix it. 
PS: I have R version 3.5.1

**Comment by lionel-** [comment]
Are you on Windows?

**Comment by gaelledoucet** [comment]
yes

**Comment by lionel-** [comment]
Installation of packages with DLL silently fail on Windows when the package's DLL is already loaded in R. Since devtools depends on rlang, you can't use it to install rlang on that platform.

Please close all sessions of R and RStudio, and reinstall rlang on a fresh session with the `remotes` package, which doesn't depend on rlang:

```r
remotes::install_github("cran/rlang")
```

**Comment by gaelledoucet** [comment]
Thank you. It helped but it's still not working: 

Downloading GitHub repo cran/rlang@master
   checking for file 'C:\Users\douceg01\AppData\Local\Temp\RtmpQLCgjL\remotes33e5049e86b07\cran-rlang-e14cdef/DESCRIPTION' ...
   checking for file 'C:\Users\douceg01\AppData\Local\Temp\RtmpQLCgjL\remotes33e5049e86b07\cran-rlang-e14cdef/DESCRIPTION' ... 
√  checking for file 'C:\Users\douceg01\AppData\Local\Temp\RtmpQLCgjL\remotes33e5049e86b07\cran-rlang-e14cdef/DESCRIPTION' (22.6s)
-  preparing 'rlang': (911ms)
   checking DESCRIPTION meta-information ...
   checking DESCRIPTION meta-information ... 
√  checking DESCRIPTION meta-information
-  cleaning src
-  installing the package to process help pages (371ms)
         -----------------------------------
-  installing *source* package 'rlang' ...
   file 'build/rlang.pdf' is missing
   Warning in system("sh ./configure.win") : 'sh' not found
   ERROR: configuration failed for package 'rlang'
-  removing 'C:/Users/douceg01/AppData/Local/Temp/Rtmp2T1ZQf/Rinst33918648d3b31/rlang'
   In R CMD INSTALL
         -----------------------------------
   ERROR: package installation failed

**Comment by lionel-** [comment]
You may need to install Rtools. Why are you not using `install.packages()` to install the CRAN binary by the way? This way you don't need to compile rlang.

**Comment by gaelledoucet** [comment]
Yes, I tried but it was not working at the time. I also installed Rtools.  
Anyway, thanks to you, I think I fixed the problem after reinstalling R in a different place (It was in Program files and I think the space messed up everything).
Anyway, thanks a lot!

**Comment by lionel-** [comment]
No worries.

**Comment by stevacca** [comment]
In my case, it worked uninstalling all the packages except the basics installations.
According to this [source](https://www.r-bloggers.com/how-to-remove-all-user-installed-packages-in-r/)

```
# CLEAN UP THE WORKSPACE WITH ALL THE INSTALLATIONS
# create a list of all installed packages
 ip <- as.data.frame(installed.packages())
 head(ip)
# if you use MRO, make sure that no packages in this library will be removed
 ip <- subset(ip, !grepl("MRO", ip$LibPath))
# we don't want to remove base or recommended packages either\
 ip <- ip[!(ip[,"Priority"] %in% c("base", "recommended")),]
# determine the library where the packages are installed
 path.lib <- unique(ip$LibPath)
# create a vector with all the names of the packages you want to remove
 pkgs.to.remove <- ip[,1]
 head(pkgs.to.remove)
# remove the packages
 sapply(pkgs.to.remove, remove.packages, lib = path.lib)
```

Then reinstall all the packages you need.

**Comment by lionel-** [comment]
For the error message cited here, it should be enough to just reinstall rlang.

**Comment by lionel-** [comment]
Though other update failures for other packages might have less verbose symptoms, so I guess reinstalling the whole library is the safe course of action.

**Comment by stevacca** [comment]
I agree but, in my case, it didn't work reinstalling the libraries. If you don't have anything to lose, the last option is to reinstall everything.

**Comment by d-kahvecioglu** [comment]
Unfortunately, I am still unable to load ggplot2. See below. I have asked CMS IT to uninstall R and RStudio and reinstall them to local drive. Does anyone else have a similar problem?

library(ggplot2)
Error: package or namespace load failed for ‘ggplot2’:
 .onLoad failed in loadNamespace() for 'rlang', details:
  call: fun(libname, pkgname)

**Comment by lionel-** [comment]
Please open a new issue with the results for `library(rlang)`, `sessionInfo()`, `.libPaths()`, `getOption("repos")`.
