### ISSUE TITLE
Ownership of data mask

### ISSUE THREAD

**Issue by asardaes** [r-lib/rlang#774]
This weird behavior showed up in one package I'm working on:

```r
library(rlang)

data_mask <- new_data_mask(current_env())
a <- eval_tidy(quo("a"), data_mask)

if (a == "a") {
  print(a)
}
Error in if (a == "a") { : could not find function "if"
```

Afterwards, no other calls work, although syntactic literals do get evaluated. It's almost as if after the call to `eval_tidy`, everything is executed in the empty environment. My Linux machine even froze entirely. The problem does not occur if I use `c("a")` inside `quo`.

EDIT: scratch that last part, it actually freezes even harder if I use `c("a")`, also on my Windows machine.

Session info:

```
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Antergos Linux

Matrix products: default
BLAS:   /usr/lib/libblas.so.3.8.0
LAPACK: /usr/lib/liblapack.so.3.8.0     

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0
```

**Comment by lionel-** [comment]
You should only create data masks from environments you have created. If you pass an environment that you don't own, this is undefined behaviour because the parent of the environment will be rechained by the tidyeval engine. For the same reason, you shouldn't make any assumption about the parent of `top` (or `bottom` if you don't supply top).

To solve this you could create a data mask from a child of the current env: `new_data_mask(env(current_env()))`.

**Comment by asardaes** [comment]
Got it, thanks. Since I wanted to capture variables from the current environment, I had to do

```r
data_mask <- new_environment(list(...))
data_mask <- new_data_mask(data_mask)
```

I guess it would be good to have the above statement in the documentation, I see it says

> Note that the parent of the top environment is completely undetermined, you shouldn't expect it to remain the same at all times. This parent is replaced during evaluation by eval_tidy()...

But I didn't immediately make the correct deduction and realized that I should only use environments I create.

**Comment by lionel-** [comment]
Agreed this should be mentioned in the documentation.
