### ISSUE TITLE
Allow setting last error externally

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/rlang#778]
To let other packages set the last error, without imposing a dependency on rlang, we could have a simple protocol about this.

Another package could then just put the error object to the proper place, in the proper format, and then `rlang::last_error()` and `rlang::last_trace()` would pick it up from there.

One option would be to put it into `.Last.error` in `baseenv()`.

**Comment by gaborcsardi** [comment]
So, actually, considering that the pretty printing only needs the print methods, one can just set `base::.Last.error` and it will be pretty printed if rlang is loaded.

**Comment by lionel-** [comment]
I don't think we should modify the base env for this though.

**Comment by gaborcsardi** [comment]
Well, if you have a better idea where we could put it, don't keep it. :)

**Comment by gaborcsardi** [comment]
Considering that `.Last.value` is there, it would make sense to put `Last.error` there as well. Ideally base R would do this, but we can also help ourselves.

**Comment by gaborcsardi** [comment]
Also strictly speaking, it is not against the CRAN policies.

**Comment by lionel-** [comment]
Right but CRAN policies are not the alpha and omega of good practices ;)

**Comment by gaborcsardi** [comment]
OK, so an alternative is to put it in a custom env on the search path. I'll do that.

**Comment by lionel-** [comment]
Shouldn't rlang do the same on its side? I thought the goal was for `rlang::last_error()` to work with errors saved with this protocol.

**Comment by gaborcsardi** [comment]
OTOH, creating a nice `rlang_error` object is not trivial, so we should encourage people to use rlang to throw errors instead of putting together an error object. I think we can close this.
