### ISSUE TITLE
`new_bytes` is mentioned but doesn't exist

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/rlang#783]
in `help("new-vector")` : 

> Except for `new_list()` and `new_bytes()`, the empty vectors are filled with typed missing values.

I assume it would be an alias to `new_raw`, which exists

**Comment by lionel-** [comment]
Thanks. Note that these ctors are likely to be deprecated in favour of `vctrs::vec_init()` (it might be a different name), see https://github.com/r-lib/vctrs/issues/372
