### ISSUE TITLE
Please use `quo_text` intead

### ISSUE THREAD

**Issue by harrysouthworth** [r-lib/rlang#793]
wh <- function(bleargh){
      nnng <- enquo(bleargh)
      as.character(nnng)[2]
    }

    wh(cakeyhorse)

That gives output 
[1] "cakeyhorse"
Warning message:
Using `as.character()` on a quosure is soft-deprecated as of rlang 0.3.0.
Please use `quo_text()` intead.
This warning is displayed once per session. 

in which "intead" should be "instead" with an "s" in it.

    wh <- function(bleargh){
      nnng <- enquo(bleargh)
      quo_text(nnng)
    }

    wh(cakeyhorse)

That gives output:

Error in quo_text(nnng) : could not find function "quo_text"

    quo_text <- quo_name

    wh(cakeyhorse)

which works. So presumably "quo_text()" in the error message should be "quo_name()"

**Comment by lionel-** [comment]
This has been fixed in the devel version, this is now:

```r
Warning message:
Using `as.character()` on a quosure is deprecated as of rlang 0.3.0.
Please use `as_label()` or `as_name()` instead.
```
