### ISSUE TITLE
Suggest candidate in case of small fuzzy match in `arg_match()`

### ISSUE THREAD

**Issue by echasnovski** [r-lib/rlang#798]
Currently `arg_match()` suggest candidate value only if there is a partial match. However, if values are quite long, input mismatch can occur because of a typo inside a word. For example:

``` r
input <- "continuuos"
rlang::arg_match(input, c("discrete", "continuous"))
#> `input` must be one of "discrete" or "continuous"
```

<sup>Created on 2019-07-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think it would be helpful in this case to have 'Did you mean "continuous"?' suggestion.

This can be achieved by first checking for partial matching with `pmatch()` (as is currently done), and in case of a failure check fuzzy matching with `agrep()`.

**Comment by lionel-** [comment]
Good idea!
