### ISSUE TITLE
Error: `into` must be a character vector

### ISSUE THREAD

**Issue by nantekoto** [r-lib/rlang#799]
im trying to use the function read_inp to read my project file, but it failed and showed the error below 

Error: `into` must be a character vector
Call `rlang::last_error()` to see a backtrace

it works with the example file , what should i do
im not good at programming

**Comment by nantekoto** [comment]
and then

> rlang::last_error()
<error>
message: `into` must be a character vector
class:   `rlang_error`
backtrace:
  1. swmmr::read_inp(x = inp_path)
  5. purrr::imap(...)
  6. purrr::map2(.x, vec_index(.x), .f, ...)
  7. swmmr:::.f(.x[[i]], .y[[i]], ...)
  8. swmmr:::section_to_tbl(.x, .y, rm.comment = rm.comment, options = options)
 10. swmmr:::parse_section.infiltration(x, inf_model = tolower(options$INFILTRATION))
 11. swmmr:::separate_into(x, header)
 13. tidyr:::separate.data.frame(...)
Call `rlang::last_trace()` to see the full backtrace

**Comment by nantekoto** [comment]
> rlang::last_trace()
     x
  1. \-swmmr::read_inp(x = inp_path)
  2.   +-`%>%`(...)
  3.   | \-base::eval(lhs, parent, parent)
  4.   |   \-base::eval(lhs, parent, parent)
  5.   \-purrr::imap(...)
  6.     \-purrr::map2(.x, vec_index(.x), .f, ...)
  7.       \-swmmr:::.f(.x[[i]], .y[[i]], ...)
  8.         \-swmmr:::section_to_tbl(.x, .y, rm.comment = rm.comment, options = options)
  9.           +-swmmr:::parse_section(x, inf_model = tolower(options$INFILTRATION))
 10.           \-swmmr:::parse_section.infiltration(x, inf_model = tolower(options$INFILTRATION))
 11.             \-swmmr:::separate_into(x, header)
 12.               +-tidyr::separate(...)
 13.               \-tidyr:::separate.data.frame(...)

**Comment by lionel-** [comment]
Hi, this looks like a problem with the way you're using `swmmr` functions, it's probably not a bug in rlang.

I recommend learning about doing reproducible examples, see https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html.

Also I wouldn't post on the development pages of the packages you're using unless you can't find help anywhere else. A great place to start is https://community.rstudio.com. Good luck!

**Comment by nantekoto** [comment]
thank a lot!
it havs been solved. i read and rewrote the inp file line by line and, fortunately and unfortunately, found the modified Horton infiltration model cannot be identified. after changing it to horton or GreenAmpt，function works.
moreover,  the function read_inp may not read chinese characters in inp file, it will lead to a coding error.
