### ISSUE TITLE
Allow .data pronoun subsetting with name

### ISSUE THREAD

**Issue by klmr** [r-lib/rlang#807]
rlang encourages interfaces that handle unevaluated expressions and names.

Yet rlang’s `.data` pronoun can only be subset with strings, not names. This is inconsistent, and [leads people to perform metaprogramming with strings, rather than with quosures](https://www.reddit.com/r/rstats/comments/ca90nk/why_i_love_datatable/et8y42i/).

Unfortunately metaprogramming still scares people (see linked discussion thread), and I believe that making `.data` subsetting work with names would simplify many common use-cases (this is only partially alleviated by the new `{{…}}` interpolation syntax, which only works with unevaluated function arguments), and would encourage use of R language objects over strings for metaprogramming.

(The next logical step would be for the documentation to *discourage* using `.data` with strings, but here I’m getting ahead of myself.)

To clarify what I’m talking about, this is a request to make the following code legal:

```r
var1 = quote(weight)
dplyr::summarize(ChickWeight, mean(.data[[var1]]))

var2 = quo(weight)
dplyr::summarize(ChickWeight, mean(.data[[var2]]))
```

**Comment by lionel-** [comment]
We've added support for symbols in `.data[[x]]` some time ago.

@hadley any objections regarding automatically unwrapping quosures? I think it makes sense, it it consistent with what we do for the LHS of `:=`

```r
exprs(!!quo(foo) := 1)
#> $foo
#> [1] 1
```

**Comment by hadley** [comment]
I don't have any objections
