### ISSUE TITLE
Offer a shortcut for eval_tidy(enquo(x))?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#812]
For new users test-driving tidy evaluation (e.g. the `{{}}` mustaches), it would help to have a shortcut that operates like a quoting function. What would be a good name for `eval_tidy_quo()`?

``` r
library(rlang)

eval_tidy_quo <- function(expr, data = NULL, env = caller_env()) {
  eval_tidy(enquo(expr), data = data, env = env)
}

b <- 5
a <- sym("b")

# This is not tidy evaluation, a is unquoted eagerly?
eval_tidy({{a}})
#> [1] 5
eval_tidy(a)
#> [1] 5
eval_tidy({{a}}, data = list(b = 3))
#> [1] 3
eval_tidy(a, data = list(b = 3))
#> [1] 3

# Tidy evaluation without mustache:
eval_tidy_quo(a)
#> b

# Not picking up b from .GlobalEnv here
try(eval_tidy_quo({{a}}))
#> Error in eval_tidy(enquo(expr), data = data, env = env) : 
#>   object 'b' not found

# ...but works with the data mask
eval_tidy_quo({{a}}, data = list(b = 3))
#> [1] 3

# A quosure works
a <- quo(b)
eval_tidy_quo({{a}})
#> [1] 5

# Mustaches implement quote-unquote in a function:
quoting_fun <- function(expr) {
  eval_tidy_quo({{expr}})
}

quoting_fun(a)
#> <quosure>
#> expr: ^b
#> env:  global
quoting_fun({{a}})
#> [1] 5
```

<sup>Created on 2019-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
This is `with_data()` ;)

**Comment by krlmlr** [comment]
It looks like this function only lives in the examples?

Would it be too bad to introduce `quo_eval()` and `expr_eval()` as safer and less ambiguous alternatives to `eval_tidy()`? We still need to think of a name that also works in situations when we test-drive tidy evaluation without a data mask.

Forgot to mention the motivation for this question: https://community.rstudio.com/t/how-to-pass-optional-quosures-to-a-tibble/34371/9. CC @courtiol.

**Comment by lionel-** [comment]
I think we need `expand()` as eval + enexpr and `with_data()` as eval_tidy + enquo.

**Comment by krlmlr** [comment]
`expand()` is already a tidyr verb. IMO, `with_data(data = NULL)` looks weird.

**Comment by lionel-** [comment]
It's not necessarily a concern for rlang that `expand()` is a tidyverse verb.

I think it looks fine:

```r
mtcars %>% with_data(cyl + am)
```

**Comment by krlmlr** [comment]
Also discussed in #591.

**Comment by lionel-** [comment]
Useful case for `with_data()`: https://stackoverflow.com/questions/61229332/function-to-run-over-selected-columns-with-dplyr-tidyeval/61230024#61230024

**Comment by lionel-** [comment]
Let's keep thinking about this.
