### ISSUE TITLE
Error in switch_lang

### ISSUE THREAD

**Issue by Yvaine19** [r-lib/rlang#814]
While using dplyr package version 0.8.3, which is dependent on rlang 0.4.0 I get the following error: 
Error in switch_lang(call, inlined = , namespaced = , recursive = eval_bare(call,  : 
  could not find function "switch_lang"

I need to use dplyr function "in:schema" and "join" and it seems it is calling switch_lang function. Is there any workaround?

the code is like this:
table_out = dplyr::tbl(SQLcon, dbplyr::in_schema(schema = "s1", table = "s1_output")) %>%
    dplyr::filter(StatusID == '1') %>%
    dplyr::inner_join(constraints, by = "ProductID")

**Comment by lionel-** [comment]
Can you update dbplyr and see if that fixes it please?

**Comment by Yvaine19** [comment]
It helped, thanks! Updating dbplyr to 1.4.2 seems to be working :-)

**Comment by lionel-** [comment]
Great! The problem is that both dplyr and dbplyr depend on the latest rlang, but if you only update dplyr you'll get new rlang and dplyr but dbplyr will remain at the old version. That is why it is better to update all packages rather than a subset.
