### ISSUE TITLE
{{ }} doesn't seem to work with map

### ISSUE THREAD

**Issue by Jesse-Kerr** [r-lib/rlang#815]
I'm trying to write a function to use map2 together with pull and {{ }}. 

Pull and {{ }} work together just fine, but when I add in map2, it fails.

```
#Reprex

dat <- tribble(
  ~A, ~B,
  1, 3, 
  4, 6 
)

#this function works.
p <- function(df, col) {
  df %>% pull({{col}})
}

p(dat, A)
#1 4

#but this doesn't work
p_map <- function(df, col) {
  map2(df, col, function(x, y) x %>% pull({{ y }}))
}

p_map(dat, A)

`Error during wrapup: object 'A' not found`

```

**Comment by lionel-** [comment]
`{{` *must* be used throughout the whole pipeline. It allows composing data-masking functions, but doesn't work with normal functions. `map2()` is a normal function so you can't do e.g. `map2(df, {{ col }}, f)`.

**Comment by lionel-** [comment]
I'm not sure I understand what you're trying to achieve with this `pull()` and `map2()` combination.

**Comment by Jesse-Kerr** [comment]
I have a list of dataframes. From each df, I have a list of columns that I need to pull the data from, do some analysis on it, and save it in a list of lists.

Here's how I had it work before:
```
#I passed the list of columns to pull to the function in ...
enq_col_to_pull <- enquos(...)

map(dat_split, function(x)
        map(enq_col_to_pull, function(y)
            list(x %>% pull(quo_name(y)) %>% #do stuff)
```

**Comment by lionel-** [comment]
I suggest:

```r
do_stuff_at <- function(data, ...) {
  data %>%
    select(...) %>%
    map(do_stuff)
}

map(dfs_list, do_stuff_at, starts_with("prefix"))
```

**Comment by Jesse-Kerr** [comment]
Thank you @lionel- for the advice
