### ISSUE TITLE
easier way to create formulas using `rlang`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/rlang#816]
I am completely revamping my package codebase using the `{{` operator and so far it has been a wonderful experience. But the one domain in which I have found using `rlang` to be difficult is in creating a formula.

For example, the following code (from [SO](https://stackoverflow.com/questions/57209284/creating-a-new-formula-of-type-x-y-using-rlang/57210448#57210448)) is needed to create expression of type `~x + y`
```r
# correlation analysis
tryfn <- function(data, x, y) {
  stats::cor.test(
    formula = rlang::new_formula(NULL, rlang::expr(!!rlang::enexpr(x) + !!rlang::enexpr(y))),
    data = data,
    method = "pearson"
  )
}
```

As can be seen, this is a very complicated way to create a formula and I was wondering if there is a simpler way to do the same. This will also be helpful for me to create other kinds of formula (e.g., `y ~ x | z `).

**Comment by lionel-** [comment]
Unquoting is still generally useful. To simplify things a bit, I would use:

```r
expand <- function(expr) eval_bare(enexpr(expr), caller_env())

f <- expand(!!enexpr(lhs) ~ !!enexpr(rhs))
```

`{{` is not appropriate here because it uses `enquo()` rather than `enexpr()`, so you'll get quosures inlined in the formula. This won't work because modelling tools don't use tidy eval.

**Comment by lionel-** [comment]
Or you could use `{{` but squash all quosures inside:

```r
f <- quo_squash(expand({{ lhs }} ~ {{ rhs }})
```

**Comment by IndrajeetPatil** [comment]
Thanks a lot! That's really helpful :)
