### ISSUE TITLE
Feature request: f_rhs additional argumen to locate in relation to |

### ISSUE THREAD

**Issue by JanaJarecki** [r-lib/rlang#825]
Hi there,
Many formulas use `|` in their RHS. It is often useful to extract the part before a "|" or after. It would be a nice enhancement to add an argument to `f_rhs` like `n = 1` to return only the RHS before the first "|", or `n = 2` to return the next part of the RHS.

The [Formula package](https://cran.r-project.org/web/packages/Formula/Formula.pdf) accomplishes this, for example

    fml <- y ~ a + b | c + s
    library(Formula)
    fancyfml <- as.Formula(fml)
    formula(fancyfml, rhs = 1, lhs = 0) # ~a + b
    formula(fancyfml, rhs = 2, lhs = 0) # ~c + s

It would be a nice enhancement of `f_rhs` could also get this capability!
Cheers
Jana

**Comment by lionel-** [comment]
Unfortunately this sort of formula parsing is out of scope for rlang.
