### ISSUE TITLE
failed to install 'rlang' from GitHub

### ISSUE THREAD

**Issue by chrisrfu** [r-lib/rlang#829]
Prior to running devtools::install_github("r-lib/rlang") I did the following:

- deleted '00LOCK-rlang' folder from my '../R-3.6.1/library' directory
- restarted R session
- rm(list=ls())
- install.packages("rlang")
- library(reprex)
- library(devtools)

Reprex: 

``` r
devtools::install_github("r-lib/rlang")
#> Downloading GitHub repo r-lib/rlang@master
#>   
  
  
   checking for file 'C:\Users\bh48819\AppData\Local\Temp\RtmpIbvVaG\remotes453c174b160f\r-lib-rlang-15e799c/DESCRIPTION' ...
  
   checking for file 'C:\Users\bh48819\AppData\Local\Temp\RtmpIbvVaG\remotes453c174b160f\r-lib-rlang-15e799c/DESCRIPTION' ... 
  
v  checking for file 'C:\Users\bh48819\AppData\Local\Temp\RtmpIbvVaG\remotes453c174b160f\r-lib-rlang-15e799c/DESCRIPTION' (1.1s)
#> 
  
  
  
   
  
-  preparing 'rlang': (2s)
#> 
  
   checking DESCRIPTION meta-information ...
  
   checking DESCRIPTION meta-information ... 
  
v  checking DESCRIPTION meta-information
#> 
  
-  cleaning src
#> 
  
  
  
-  installing the package to process help pages (1.7s)
#> 
  
  
  
-  cleaning src (25.7s)
#> 
  
  
  
-  checking for LF line-endings in source and make files and shell scripts
#> 
  
  
  
-  checking for empty or unneeded directories (451ms)
#> 
  
  
  
-  building 'rlang_0.4.0.9002.tar.gz'
#> 
  
   
#> 
#> Error: Failed to install 'rlang' from GitHub:
#>   (converted from warning) installation of package 'C:/Users/bh48819/AppData/Local/Temp/RtmpIbvVaG/file453c450c55cc/rlang_0.4.0.9002.tar.gz' had non-zero exit status
```

Session Info:

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.1 (2019-07-05)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/Chicago             
#>  date     2019-08-30                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.1)
#>  backports     1.1.4   2019-04-10 [1] CRAN (R 3.6.0)
#>  callr         3.3.1   2019-07-18 [1] CRAN (R 3.6.1)
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.6.1)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.1)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.1)
#>  devtools      2.1.0   2019-07-06 [1] CRAN (R 3.6.1)
#>  digest        0.6.20  2019-07-04 [1] CRAN (R 3.6.1)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.1)
#>  fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.1)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.1)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.6.1)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.6.1)
#>  knitr         1.24    2019-08-08 [1] CRAN (R 3.6.1)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.1)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.1)
#>  pkgbuild      1.0.5   2019-08-26 [1] CRAN (R 3.6.1)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.1)
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.6.1)
#>  processx      3.4.1   2019-07-18 [1] CRAN (R 3.6.1)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.1)
#>  R6            2.4.0   2019-02-14 [1] CRAN (R 3.6.1)
#>  Rcpp          1.0.2   2019-07-25 [1] CRAN (R 3.6.1)
#>  remotes       2.1.0   2019-06-24 [1] CRAN (R 3.6.1)
#>  rlang         0.4.0   2019-06-25 [1] CRAN (R 3.6.1)
#>  rmarkdown     1.15    2019-08-21 [1] CRAN (R 3.6.1)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.1)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.1)
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.6.0)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.6.1)
#>  testthat      2.2.1   2019-07-25 [1] CRAN (R 3.6.1)
#>  usethis       1.5.1   2019-07-04 [1] CRAN (R 3.6.1)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.1)
#>  xfun          0.9     2019-08-21 [1] CRAN (R 3.6.1)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.6.0)
#> 
#> [1] C:/Users/bh48819/Documents/R/R-3.6.1/library
```

``` r
Sys.getenv()['PATH']
#> PATH                  C:\Users\bh48819\Documents\R\R-3.6.1\bin\x64;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program
#>                       Files\1E\NomadBranch\;C:\Program Files
#>                       (x86)\Microsoft SQL Server\Client
#>                       SDK\ODBC\130\Tools\Binn\;C:\Program Files
#>                       (x86)\Microsoft SQL
#>                       Server\140\Tools\Binn\;C:\Program Files
#>                       (x86)\Microsoft SQL
#>                       Server\140\DTS\Binn\;C:\Program Files
#>                       (x86)\Microsoft SQL
#>                       Server\140\Tools\Binn\ManagementStudio\;C:\Program
#>                       Files\Microsoft SQL
#>                       Server\130\Tools\Binn\;C:\Program Files
#>                       (x86)\Microsoft SQL
#>                       Server\150\DTS\Binn\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program
#>                       Files\1E\NomadBranch\;C:\Program Files
#>                       (x86)\Microsoft SQL Server\Client
#>                       SDK\ODBC\130\Tools\Binn\;C:\Program Files
#>                       (x86)\Microsoft SQL
#>                       Server\140\Tools\Binn\;C:\Program Files
#>                       (x86)\Microsoft SQL
#>                       Server\140\DTS\Binn\;C:\Program Files
#>                       (x86)\Microsoft SQL
#>                       Server\140\Tools\Binn\ManagementStudio\;C:\Program
#>                       Files\Microsoft SQL
#>                       Server\130\Tools\Binn\;C:\Program Files
#>                       (x86)\Microsoft SQL
#>                       Server\150\DTS\Binn\;C:\Users\bh48819\AppData\Local\Microsoft\WindowsApps;C:\Users\bh48819\AppData\Local\Programs\MiKTeX
#>                       2.9\miktex\bin\x64\;C:\Users\bh48819\AppData\Local\Programs\Microsoft
#>                       VS
#>                       Code\bin;C:\Python34\Scripts;C:\Users\bh48819\AppData\Local\Continuum\anaconda3;C:\Users\bh48819\AppData\Roaming\Python\Python37\Scripts;
```

<sup>Created on 2019-08-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
What happens if you use `remotes::install_github()` instead?

**Comment by chrisrfu** [comment]
``` r
remotes::install_github("r-lib/rlang")
#> Downloading GitHub repo r-lib/rlang@master
#>   
  
  
   checking for file 'C:\Users\bh48819\AppData\Local\Temp\Rtmp6FHoq1\remotes15f029bfeed\r-lib-rlang-15e799c/DESCRIPTION' ...
  
   checking for file 'C:\Users\bh48819\AppData\Local\Temp\Rtmp6FHoq1\remotes15f029bfeed\r-lib-rlang-15e799c/DESCRIPTION' ... 
  
v  checking for file 'C:\Users\bh48819\AppData\Local\Temp\Rtmp6FHoq1\remotes15f029bfeed\r-lib-rlang-15e799c/DESCRIPTION' (1.1s)
#> 
  
  
  
   
  
-  preparing 'rlang': (2.1s)
#> 
  
   checking DESCRIPTION meta-information ...
  
   checking DESCRIPTION meta-information ... 
  
v  checking DESCRIPTION meta-information
#> -  cleaning src
#> 
  
  
  
-  installing the package to process help pages (2.2s)
#> 
  
  
  
-  cleaning src (33.6s)
#> 
  
  
  
-  checking for LF line-endings in source and make files and shell scripts (436ms)
#> 
  
  
  
-  checking for empty or unneeded directories (586ms)
#> 
  
  
  
-  building 'rlang_0.4.0.9002.tar.gz' (399ms)
#> 
  
   
#> 
#> Error: Failed to install 'rlang' from GitHub:
#>   (converted from warning) installation of package 'C:/Users/bh48819/AppData/Local/Temp/Rtmp6FHoq1/file15f039c158c9/rlang_0.4.0.9002.tar.gz' had non-zero exit status
```

<sup>Created on 2019-08-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
The problem is that the output doesn't contain any indication of what went wrong. In any case that this is most likely not an rlang issue but a tooling issue.

Can you install from source other packages that need compilation?

**Comment by chrisrfu** [comment]
I used tidyverse as my package of choice and installed it from R source. This is what the output looks like. 

> install.packages("tidyverse")
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cran.revolutionanalytics.com/bin/windows/contrib/3.6/tidyverse_1.2.1.zip'
Content type 'application/zip' length 93076 bytes (90 KB)
downloaded 90 KB

package ‘tidyverse’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\bh48819\AppData\Local\Temp\Rtmp4KQs1X\downloaded_packages

**Comment by lionel-** [comment]
This is installing from binary. When you install from github, it installs from source. You might need to install Rtools.

**Comment by chrisrfu** [comment]
I ran this the first time and it worked no problem. 

> devtools::install_github("rstudio/ggvis")
Downloading GitHub repo rstudio/ggvis@master
√  checking for file 'C:\Users\bh48819\AppData\Local\Temp\RtmpgP6iWa\remotes4c5c36363969\rstudio-ggvis-435ca19/DESCRIPTION' ... 
-  preparing 'ggvis': (2.7s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (1.6s)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'ggvis_0.4.4.tar.gz'
   
* installing *source* package 'ggvis' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'ggvis'
    finding HTML links ... done
    add_axis                                html  
    add_data                                html  
    add_guide_axis                          html  
    add_guide_legend                        html  
    add_legend                              html  
    add_props                               html  
    add_relative_scales                     html  
    add_scale                               html  
    add_tooltip                             html  
    as.vega                                 html  
    auto_group                              html  
    axis_props                              html  
    band                                    html  
    bin_vector                              html  
    cocaine                                 html  
    compute_align                           html  
    compute_bin                             html  
    compute_boxplot                         html  
    compute_count                           html  
    compute_density                         html  
    compute_model_prediction                html  
    compute_stack                           html  
    compute_tabulate                        html  
    create_broker                           html  
    create_input                            html  
    default_options                         html  
    dplyr-ggvis                             html  
    explain                                 html  
    explain.ggvis                           html  
    export_png                              html  
    fullseq                                 html  
    get_data                                html  
    ggvis                                   html  
    ggvisControlOutput                      html  
Rd warning: C:/Users/bh48819/AppData/Local/Temp/RtmpeIBurW/R.INSTALL299c53d741cb/ggvis/man/ggvisControlOutput.Rd:16: file link 'uiOutput' in package 'shiny' does not exist and so has been treated as a topic
    ggvisOutputElements                     html  
    ggvis_message                           html  
    ggvis_scale                             html  
    group_by                                html  
    handle_brush                            html  
    handle_click                            html  
    handle_resize                           html  
    input_checkbox                          html  
    input_select                            html  
    input_slider                            html  
    finding level-2 HTML links ... done

    input_text                              html  
    is.axis_props                           html  
    is.broker                               html  
    is.dynamic                              html  
    is.ggvis                                html  
    is.legend_props                         html  
    is.scaled_value                         html  
    knit_print.ggvis                        html  
    layer_bars                              html  
    layer_boxplots                          html  
    layer_densities                         html  
    layer_f                                 html  
    layer_guess                             html  
    layer_histograms                        html  
    layer_lines                             html  
    layer_model_predictions                 html  
    left_right                              html  
    legend_props                            html  
    linked_brush                            html  
    mark                                    html  
    marks                                   html  
    new_prop                                html  
    padding                                 html  
    pipe                                    html  
    print.ggvis                             html  
    prop                                    html  
    prop_domain                             html  
    propname_to_scale                       html  
    props                                   html  
    resolution                              html  
    save_spec                               html  
    scale_datetime                          html  
    scale_numeric                           html  
    scale_ordinal                           html  
    scaled_value                            html  
    scales                                  html  
    scaletype_to_vega_scaletype             html  
    set_options                             html  
    set_scale_label                         html  
    shiny-ggvis                             html  
    show_spec                               html  
    show_tooltip                            html  
    sidebarBottomPage                       html  
    singular                                html  
    subvis                                  html  
    vector_type                             html  
    vega_data_parser                        html  
    waggle                                  html  
    zero_range                              html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (ggvis)

I ran it again with reprex and this is the result. 

``` r
devtools::install_github("rstudio/ggvis", force = TRUE)
#> Downloading GitHub repo rstudio/ggvis@master
#> 
#>   
  
  
   checking for file 'C:\Users\bh48819\AppData\Local\Temp\RtmpqKT0FY\remotes2d0c189d340d\rstudio-ggvis-435ca19/DESCRIPTION' ...
  
   checking for file 'C:\Users\bh48819\AppData\Local\Temp\RtmpqKT0FY\remotes2d0c189d340d\rstudio-ggvis-435ca19/DESCRIPTION' ... 
  
   checking for file 'C:\Users\bh48819\AppData\Local\Temp\RtmpqKT0FY\remotes2d0c189d340d\rstudio-ggvis-435ca19/DESCRIPTION' ... OK
  
v  checking for file 'C:\Users\bh48819\AppData\Local\Temp\RtmpqKT0FY\remotes2d0c189d340d\rstudio-ggvis-435ca19/DESCRIPTION' (1.2s)
#> 
  
  
  
-  preparing 'ggvis': (2.1s)
#> 
  
   checking DESCRIPTION meta-information ...
  
   checking DESCRIPTION meta-information ... 
  
   checking DESCRIPTION meta-information ... OK
  
v  checking DESCRIPTION meta-information
#> 
  
  
  
-  checking for LF line-endings in source and make files and shell scripts (1.5s)
#> 
  
  
  
-  checking for empty or unneeded directories
#> 
  
  
  
-  looking to see if a 'data/datalist' file should be added
#> 
  
  
  
-  building 'ggvis_0.4.4.tar.gz'
#> 
  
   
#> 
#> Error: Failed to install 'ggvis' from GitHub:
#>   (converted from warning) installation of package 'C:/Users/bh48819/AppData/Local/Temp/RtmpqKT0FY/file2d0c41b55e12/ggvis_0.4.4.tar.gz' had non-zero exit status
```

<sup>Created on 2019-08-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
If you're on Windows you need to install packages with DLLs from a fresh session.

Please close all your RStudio and R versions, open a new one, check that no packages are loaded (`sessionInfo()` should not have the package you're trying to install).

Then, use `remotes::install_github()` to install the package.

**Comment by chrisrfu** [comment]
``` r
sessionInfo()
#> R version 3.6.1 (2019-07-05)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 17134)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.6.1  magrittr_1.5    tools_3.6.1     htmltools_0.3.6
#>  [5] yaml_2.2.0      Rcpp_1.0.2      stringi_1.4.3   rmarkdown_1.15 
#>  [9] highr_0.8       knitr_1.24      stringr_1.4.0   xfun_0.9       
#> [13] digest_0.6.20   evaluate_0.14
```

installing ggvis again
``` r
remotes::install_github("rstudio/ggvis")
#> Downloading GitHub repo rstudio/ggvis@master
#> 
#>   
  
  
   checking for file 'C:\Users\bh48819\AppData\Local\Temp\Rtmp8uhpQ2\remotes34d8f4c5cdb\rstudio-ggvis-435ca19/DESCRIPTION' ...
  
   checking for file 'C:\Users\bh48819\AppData\Local\Temp\Rtmp8uhpQ2\remotes34d8f4c5cdb\rstudio-ggvis-435ca19/DESCRIPTION' ... 
  
v  checking for file 'C:\Users\bh48819\AppData\Local\Temp\Rtmp8uhpQ2\remotes34d8f4c5cdb\rstudio-ggvis-435ca19/DESCRIPTION' (1.2s)
#> 
  
  
  
   
  
   preparing 
  
   preparing 'ggvis'
  
   preparing 'ggvis':
  
-  preparing 'ggvis': (2.7s)
#> 
  
   checking DESCRIPTION meta-information ...
  
   checking DESCRIPTION meta-information ... 
  
   checking DESCRIPTION meta-information ... OK
  
v  checking DESCRIPTION meta-information
#> 
  
  
  
-  checking for LF line-endings in source and make files and shell scripts (1.3s)
#> 
  
  
  
-  checking for empty or unneeded directories
#> 
  
  
  
-  looking to see if a 'data/datalist' file should be added
#> 
  
  
  
-  building 'ggvis_0.4.4.tar.gz'
#> 
  
   
#> 
#> Error: Failed to install 'ggvis' from GitHub:
#>   (converted from warning) installation of package 'C:/Users/bh48819/AppData/Local/Temp/Rtmp8uhpQ2/file34d873db167b/ggvis_0.4.4.tar.gz' had non-zero exit status
```

<sup>Created on 2019-08-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Maybe post your issues on StackOverflow or Community? I don't know how to help with this issue.

**Comment by chrisrfu** [comment]
Will do. Thank you for your help!

**Comment by chrisrfu** [comment]
The following is what worked for 'rlang':

1. Close out RStudio
2. install.packages("rlang")
3. remotes::install_github("r-lib/rlang")

**Comment by lionel-** [comment]
hmm, that's strange. Glad that worked out though!
