### ISSUE TITLE
`{{` missing from function reference

### ISSUE THREAD

**Issue by batpigandme** [r-lib/rlang#830]
You can get to a small explanation through accessing the quasiquotation reference page by clicking on [`qq_show()`](https://rlang.r-lib.org/reference/quasiquotation.html), but it's pretty hard to find. 

See my attempt at consolidating `{{` documentation is in response to [this thread](https://community.rstudio.com/t/documentation-for/38727) on community.

**Comment by lionel-** [comment]
The issue is that `{{` doesn't play well with pkgdown / roxygen (I can't remember which). We should at least add an alias for curly-curly though.
