### ISSUE TITLE
Some exceptions to the parse_expr() function

### ISSUE THREAD

**Issue by AlohaSen** [r-lib/rlang#832]
I'm using the rlang package，I found some problems with the function parse_expr()，The expression generated with parse_expr() can be run by pasting it into the console, but adding "!!! "Will report an error.What's the reason, please

**Comment by lionel-** [comment]
The result of `parse_expr()` should be run using `eval()`.

**Comment by AlohaSen** [comment]
Maybe I didn't describe it clearly, my problem is that parse_expr() is used in mutate(), batch operation of each value in the data frame, I used qq_show() to check the code, the code is correct, but it can't be used "!!! " in mutate()

**Comment by lionel-** [comment]
Please describe your problem with a reproducible example.

**Comment by AlohaSen** [comment]
library(rlang)
library(tidyverse)

df = tibble(
  regcanal1 = c(NaN,NaN),
  regcanal2 = c(-999,-999),
  regcanal3 = c(-999,-999),
  regcanal4 =	c(1,1),
  regcanal5 = c(-999 ,-999),
  regcanal6 = c(NaN,1),
  regcanal7 = c(0,0),
  regcanal8 = c(-999 ,-999),
  regcanal9 = c(-999 ,-999),
  regcanal10 = c(NaN ,NaN),
)
tmp_nm <- (df %>% colnames)
tmp_expr <- str_glue('{tmp_nm} = nvl({tmp_nm},-1)') %>% as.list %>% map(parse_expr)
qq_show(df %>% mutate(
  !!! tmp_expr
))

df %>% mutate(
  !!! tmp_expr
)

This is an example，attachment is the error log.

**Comment by AlohaSen** [comment]
Sorry, the attachment is too big to send out, intercepting the key information

**Comment by lionel-** [comment]
I get this when I run your code, which seems like an expected error:

```
Error in nvl(regcanal1, -1) : could not find function "nvl"
```

**Comment by AlohaSen** [comment]
Oh, sorry, nvl () is hive function, we need to connect spark,You need to add：

library(sparklyr)
sc <- spark_connect(master = "local")
df = copy_to(sc,df_,name = ‘sdf',overwrite = T)

**Comment by lionel-** [comment]
Are you sure you can't reduce your example to something that doesn't use spark?

Making your example super simple makes it a lot easier for us to help you, and the process of simplifying your use case usually reveals the source of the error by itself.

**Comment by AlohaSen** [comment]
Haha, my problem is solved，thank you for your help. tmp_expr  too long will cause error ，and need to set_names() for the list. But qq_show () returns an error result. Here is a simple example.

library(rlang)
library(tidyverse)
library(tidyr)
df = tibble(
  regcanal1 = c(NaN,NaN),
  regcanal2 = c(-999,-999),
  regcanal3 = c(-999,-999),
  regcanal4 =	c(1,1),
  regcanal5 = c(-999 ,-999),
  regcanal6 = c(NaN,1),
  regcanal7 = c(0,0),
  regcanal8 = c(-999 ,-999),
  regcanal9 = c(-999 ,-999),
  regcanal10 = c(NaN ,NaN),
)
tmp_nm <- (df %>% colnames)
tmp_expr <- str_glue('replace_na({tmp_nm},-1)') %>% as.list %>% map(parse_expr) %>% set_names(tmp_nm) 
qq_show(df %>% mutate(
  !!! tmp_expr 
))

df %>% mutate(
  !!! tmp_expr
)



set_names()

**Comment by lionel-** [comment]
oh of course, I should have spotted that! By the way, here is a more programmatic way of creating this list of expressions:

```r
tmp_nm %>% set_names() %>% map(~ expr(nvl(!!sym(.), -1)))
```

**Comment by AlohaSen** [comment]
I have one more question，qq_show() returns an error result.

**Comment by lionel-** [comment]
I don't see any error result.... Please use the github UI to post, not email.

**Comment by AlohaSen** [comment]
Oh, sorry, I didn't know you couldn't see it by email，Before, I sent the screenshot, but you can't see it, now I send out the code, you can run it and have a look.The code is the same as before，`qq_show()` returns the same result,but the result should be different.
`tmp_expr <- str_glue('replace_na({tmp_nm},-1)') %>% as.list %>% map(parse_expr)
qq_show(df %>% mutate(
  !!! tmp_expr
))
df %>% mutate(
  !!! tmp_expr
)`
`tmp_expr <- str_glue('replace_na({tmp_nm},-1)') %>% as.list %>% map(parse_expr) %>% set_names(tmp_nm)
qq_show(df %>% mutate(
  !!! tmp_expr
))
df %>% mutate(
  !!! tmp_expr
)`
