### ISSUE TITLE
Corner case: ensym() with dot-dot argument ..1 from ellipsis

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#833]
Do we expect `ensym(..1)` to return the same as `ensyms(...)[[1]]`, similarly for `enquo()` and `enexpr()` ? (Should we update `as_function()` to use mustaches?)

``` r
library(rlang)

f <- function(...) ensym(..1)
f(a)
#> Error in (function (x) : object '..1' not found

f <- function(...) ensyms(...)[[1]]
f(a)
#> a

f <- function(x, .x = {{ x }}) ensym(.x)
f(a)
#> a

f <- function(..., .x = {{ ..1 }}) ensym(.x)
f(a)
#> Error in (function (x) : object '..1' not found
```

<sup>Created on 2019-09-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
As a consequence, tidy evaluation doesn't work with purrr-style lambdas, but this can be worked around easily by supplying a proper function. Where's the best place to document this?

**Comment by lionel-** [comment]
Maybe in `?as_function`.

**Comment by krlmlr** [comment]
Would it be too bad to soft-deprecate `..1` etc. in lambdas, since this isn't even documented? Or should we bite the bullet and document, perhaps marking as "questioning"?

**Comment by lionel-** [comment]
hmm I don't think we need to take action yet.
