### ISSUE TITLE
Mechanism for inhibiting unquoting? 

### ISSUE THREAD

**Issue by vspinu** [r-lib/rlang#835]
I wasn't able to find a way to inhibit unquoting within an expression:

```R
new_function(NULL, body = expr({bb <- 1; dbl(!!!bb)}))
#> Error in enexpr(expr) : object 'bb' not found
```

Is there a provision for such things? Let's say if `.(...)` is used to for such inhibiting, then  `expr({bb <- 1; dbl(.(!!!bb))}))` would simply expand into `expr({bb <- 1; dbl(!!!bb)}`. 

related #264

**Comment by lionel-** [comment]
You can do it like in lisp:

```r
expr({bb <- 1; dbl(!!quote(!!!bb))})
```

We prefer not adding syntax for this at the moment. Maybe we'll add it if it proves a common occurrence, it might be more important for shinymeta users.

**Comment by vspinu** [comment]
Ok, this is good enough. Didn't expect nested quoting to work :) Thanks.
