### ISSUE TITLE
printing argument of a function changes the result of enquo

### ISSUE THREAD

**Issue by danilinares** [r-lib/rlang#837]
I found that printing the argument of a function changes the result of enquo

example_function <- function(x) x^2

my_function <- function(fun) {
  quo_name(enquo(fun))
}
my_function(example_function)

my_function <- function(fun) {
  print(is.function(fun))
  quo_name(enquo(fun))
}
my_function(example_function)

**Comment by lionel-** [comment]
This is expected behaviour, once a promise is forced it can't be `enquo()`. This should be documented somewhere.

**Comment by lionel-** [comment]
Duplicate of #884.
