### ISSUE TITLE
using the pipe in enquo changes behaviour

### ISSUE THREAD

**Issue by danilinares** [r-lib/rlang#838]
I found that enquo(x) does not do the same that x %>% enquo()

example_function <- function(x) x^2

my_function <- function(fun) {
  enquo_fun <- enquo(fun)
  print(quo_name(enquo_fun))
}
my_function(example_function)

my_function <- function(fun) {
  enquo_fun <- fun %>% enquo()
  print(quo_name(enquo_fun))
}
my_function(example_function)

**Comment by lionel-** [comment]
You shouldn't expect `enquo()` to be pipable.
