### ISSUE TITLE
Unquoting/unquote splicing inside purrr::map inside dplyr::mutate calls

### ISSUE THREAD

**Issue by srnnkls** [r-lib/rlang#839]
I'd like to be able to construct calls from columns of a dataframe. Background: I collect my model ingredients tidyly in a dataframe and expand this dataframe to hold all possible combinations, which I map over. However, sometimes I want call different functions with, again, different sets of parameters to calculate i.e. SEs. Unquote splicing doesn't seems to be straightforward when applied to such nested structures. Possibly related to the timing of evaluations and available environments.

Here is a simple reprex:

``` r
library(tidyverse)
library(rlang)

x <- tibble(a = letters[1:3],
            b = 1:3)

y <- tibble(args = list(list(NULL), list(sep = "->")),
       names = list("paste0", "paste"))

xy <- expand_grid(x, y)

xy <- xy %>%
  mutate(call = pmap(list(a, b, names, args), ~call2(..3, ..1, ..2, !!!..4)))
#> Error in splice(dot_call(capture_dots, frame_env = frame_env, named = named, : ..4 used in an incorrect context, no ... to look in
```

<sup>Created on 2019-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
This is a dplyr issue, it works in rlang:

```r
fn <- function(...) {
  list2(!!!..1)
}
fn(1:3)
#> [[1]]
#> [1] 1
#>
#> [[2]]
#> [1] 2
#>
#> [[3]]
#> [1] 3


fn <- function(...) {
  call2("foo", !!!..1)
}
fn(1:3)
#> foo(1L, 2L, 3L)
```

Can you post the issue in dplyr please?

**Comment by srnnkls** [comment]
Of course, thank you.
