### ISSUE TITLE
Provide catch_cnds()

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#848]
That captures all conditions, always returning a list.

**Comment by lionel-** [comment]
Are these the desired properties?

* Unknown conditions are recorded.
* Suppressable conditions like `message` and `warning` are recorded and suppressed.
* Errors are caught and interrupt the control flow.

**Comment by hadley** [comment]
I was thinking that it would catch and suppress all conditions, but I think idea is better.

**Comment by hadley** [comment]
No longer think this is important; better to implement specific parts as needed in individual packages.
