### ISSUE TITLE
Improve display of chained errors

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#851]
```r
a <- function() b()
b <- function() c()
c <- function() abort("low-level")

f <- function() g()
g <- function() h()
h <- function() tryCatch(a(), error = function(err) abort("high-level", parent = err))

f()
#> Error: high-level
#> Call `rlang::last_error()` to see a backtrace.

last_error()
#> <error/rlang_error>
#> high-level
#> Backtrace:
#>  1. global::f()
#>  2. global::g()
#>  3. global::h()
#> Call `rlang::last_trace()` to see the full backtrace.

last_trace()
#> <error/rlang_error>
#> high-level
#> Backtrace:
#>     █
#>  1. └─global::f()
#>  2.   └─global::g()
#>  3.     └─global::h()
#> <parent: error/rlang_error>
#> low-level
#> Backtrace:
#>     █
#>  1. └─global::a()
#>  2.   └─global::b()
#>  3.     └─global::c()

last_error()$parent
#> <error/rlang_error>
#> low-level
#> Backtrace:
#>   1. global::f()
#>   2. global::g()
#>   3. global::h()
#>   8. global::a()
#>   9. global::b()
#>  10. global::c()

last_error()$parent$trace
#>      █
#>   1. └─global::f()
#>   2.   └─global::g()
#>   3.     └─global::h()
#>   4.       ├─base::tryCatch(...)
#>   5.       │ └─base:::tryCatchList(expr, classes, parentenv, handlers)
#>   6.       │   └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>   7.       │     └─base:::doTryCatch(return(expr), name, parentenv, handler)
#>   8.       └─global::a()
#>   9.         └─global::b()
#>  10.           └─global::c()
```

Comments from @gaborcsardi 

1. It would make sense to indicate in the default output that there is another level. Even the last_error() output does not indicate that, actually. You probably end up staring at the error for a bit and then calling last_error() as suggested, and then after some more staring last_trace(), as suggested. And you'd better not mistype either one, because then the last error object will be gone.

2. Having to call $parent to get a complete stack is not great, especially if you have more than two levels, i.e. last_error()$parent$parent, etc. The same with last_error()$parent$parent$trace, etc.

3. Having different numbers for the parent frames in last_trace() might be confusing. Personally I would prefer if the numbers were not mangled, and they referred to the real frame numbers.

4. There is no way to see all error messages and a full stack, in the same output. Personally, this is my preferred output, as above, as it shows all information, and the levels are clearly separated by whitespace, and they are easy to parse. I can decide how deep I need to dig into the output, without issuing additional commands.

5. Relatedly, I am not sure that having all these different kinds of output is great. People need to learn to parse all of them, and think about whether the information they are looking for is missing in general, or they need the other kind of output, etc.

**Comment by lionel-** [comment]
Also need to support errors rethrown with `withCallingHandlers()`.

**Comment by hadley** [comment]
Yeah, that sounds fine to me.

I assume this:

```
#> <error/dplyr_error>
#> Problem with `mutate()` input `..1`.
#> ✖ Can't subset columns that don't exist.
#> ✖ Column `foo` doesn't exist.
#> ℹ Input `..1` is `dplyr::select(mtcars, foo)`.
#> Lower level error: <error/vctrs_error_subscript_oob>
#> Can't subset columns that don't exist.
```

will become something more like

```
#> <error/dplyr_error>
#> Problem with `mutate()` input `..1`.
#> ✖ Can't subset columns that don't exist.
#> ✖ Column `foo` doesn't exist.
#> ℹ Input `..1` is `dplyr::select(mtcars, foo)`.
#> ----------------------------------------------
#> <error/vctrs_error_subscript_oob>
#> Can't subset columns that don't exist.
```

?
