### ISSUE TITLE
Should `rlang::inform()` use `stdout()` by default?

### ISSUE THREAD

**Issue by jimhester** [r-lib/rlang#852]
One issue with `base::message()` is that it outputs to `stderr()`, which while it works great for terminal usage, in RStudio and in the Windows GUI causes the output to be in red.

I just did a [workaround for this in vroom](https://github.com/r-lib/vroom/commit/55a94bb9dfd18eac30c4771f3c48dc6af6c55f86#diff-90a167c269c93fd663f1c3c690147343R460-R472). Maybe we should do this by default in `rlang::inform()`? 

Currently some packages (such as usethis) use `cat()` for user messaging to avoid the red text issue, but they really should use message conditions, so users can use `suppressMessages()` to suppress the messages.

**Comment by lionel-** [comment]
We could send to stdout if the session is interactive, and stderr otherwise. This way the output of messages can be filtered out when piping.
