### ISSUE TITLE
`cnd_message()` tweaks

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#854]
* Add `cnd_details()` generic. Then we have header (issue) + body (bullets) + footer (details).

* Add `rlang_condition` class and move `cnd_message()` invokation from `rlang_error.conditionMessage` to `rlang_condition.conditionMessage` method.

**Comment by krlmlr** [comment]
Should we limit the number of bullets printed, and automatically add a footer like "... and x more"?

**Comment by lionel-** [comment]
Consider adding `cnd_header()` / `cnd_body()` / `cnd_footer()` aliases, or switching to non-functional names altogether.

**Comment by lionel-** [comment]
Was fixed in rlang 0.4.2. Let's think a bit more about truncating error bullets, also it's likely the code for this (which is now independent from `cnd_body()`) will move to cli.
