### ISSUE TITLE
`0.4.1` source installation failure with `Error in strptime(xx, f, tz = tz)` error message

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/rlang#857]
My GitHub CI installations for `rlang 0.4.1` are failing (e.g., https://github.com/IndrajeetPatil/broomExtra/commit/301fae5bf92db4d7d35efa082ced31b8743e6bb4/checks?check_suite_id=282680790) with the following error. 

```r
trying URL 'https://cloud.r-project.org/src/contrib/rlang_0.4.1.tar.gz'
Content type 'application/x-gzip' length 797012 bytes (778 KB)
==================================================
downloaded 778 KB

Error in strptime(xx, f, tz = tz) : 
  (converted from warning) unable to identify current timezone 'C':
please set environment variable 'TZ'
Error in i.p(...) : 
  (converted from warning) installation of package 'rlang' had non-zero exit status
Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
Execution halted
```

Of course, when binaries built, I am guessing this issue will go away. But I just wanted to raise it nonetheless in case you thought this was relevant. If not, feel free to close the issue.

**Comment by lionel-** [comment]
hmm, maybe this is an issue in your setup? I'm not sure if timezones (or the TZ envvar) can be set to "C", from a quick google it doesn't look like it.

**Comment by IndrajeetPatil** [comment]
Hmm, this seems to have been a spurious issue. The builds are failing for a different reason now.
