### ISSUE TITLE
Forward to cnd_signal() from abort()?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#861]
Do we want to make `abort(error_cnd(...))` behave the same as `cnd_signal(error_cnd(...))` ? 

In {tibble}, condition messages are created separately and thrown with `abort()`. I'm upgrading to condition objects and need to replace or wrap all `abort()` calls. I'm wondering if supporting `abort(error_cnd(...))` would lower the entry bar to use classed conditions.

**Comment by lionel-** [comment]
I don't think so at the moment, because it makes the function signature weird and the parameters (e.g. subclass) redundant.
