### ISSUE TITLE
error: unable to locate xcodebuild when installing rlang and digest packages via install of ggplot2

### ISSUE THREAD

**Issue by algotr8der** [r-lib/rlang#863]
error: unable to locate xcodebuild when installing rlang and digest packages via install of ggplot2

Also see here: https://stackoverflow.com/questions/58685537/error-unable-to-locate-xcodebuild-when-installing-rlang-and-digest-packages-via

On my Macbook 10.15 in RStudio I attempted to install ggplot2, however I get errors for dependencies related to digest and rlang. I did perform a xcode-select --install to install that and also rebooted my Mac.

However it seems R can't locate xcode.

I notice that the error messages complain about the xcode path. Is this a red herring or is that the root of the problem?

Metroids-MacBook-Air:~ metroid$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
What should the path be set to and why isn't it set by default?

Any thoughts?

Please see below:

> install.packages("ggplot2")
also installing the dependencies ‘digest’, ‘rlang’

  There are binary versions available but the source versions are later:
       binary source needs_compilation
digest 0.6.21 0.6.22              TRUE
rlang   0.4.0  0.4.1              TRUE

Do you want to install from sources the packages which need compilation? (Yes/no/cancel) Yes
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/ggplot2_3.2.1.tgz'
Content type 'application/x-gzip' length 3973186 bytes (3.8 MB)
==================================================
downloaded 3.8 MB

The downloaded binary packages are in
    /var/folders/q5/pqd495t95fq3tjtbxbdsvv_00000gn/T//Rtmp8aJzND/downloaded_packages
installing the source packages ‘digest’, ‘rlang’

trying URL 'https://cran.rstudio.com/src/contrib/digest_0.6.22.tar.gz'
Content type 'application/x-gzip' length 141968 bytes (138 KB)
==================================================
downloaded 138 KB

trying URL 'https://cran.rstudio.com/src/contrib/rlang_0.4.1.tar.gz'
Content type 'application/x-gzip' length 797012 bytes (778 KB)
==================================================
downloaded 778 KB

* installing *source* package ‘digest’ ...
** package ‘digest’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
dyld: Symbol not found: _kConditionalConnectionRequirementTimeWindowStartTime
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/bin/../../../SharedFrameworks/DVTFoundation.framework/Versions/A/DVTFoundation
  Expected in: /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
 in /Applications/Xcode.app/Contents/Developer/usr/bin/../../../SharedFrameworks/DVTFoundation.framework/Versions/A/DVTFoundation
make: error: unable to locate xcodebuild, please make sure the path to the Xcode folder is set correctly!
make: error: You can set the path to the Xcode folder using /usr/bin/xcode-select -switch
ERROR: compilation failed for package ‘digest’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/digest’
Warning in install.packages :
  installation of package ‘digest’ had non-zero exit status
* installing *source* package ‘rlang’ ...
** package ‘rlang’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
dyld: Symbol not found: _kConditionalConnectionRequirementTimeWindowStartTime
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/bin/../../../SharedFrameworks/DVTFoundation.framework/Versions/A/DVTFoundation
  Expected in: /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
 in /Applications/Xcode.app/Contents/Developer/usr/bin/../../../SharedFrameworks/DVTFoundation.framework/Versions/A/DVTFoundation
make: error: unable to locate xcodebuild, please make sure the path to the Xcode folder is set correctly!
make: error: You can set the path to the Xcode folder using /usr/bin/xcode-select -switch
ERROR: compilation failed for package ‘rlang’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rlang’
Warning in install.packages :
  installation of package ‘rlang’ had non-zero exit status

The downloaded source packages are in
    ‘/private/var/folders/q5/pqd495t95fq3tjtbxbdsvv_00000gn/T/Rtmp8aJzND/downloaded_packages’
>

**Comment by lionel-** [comment]
This is not an rlang issue. If you can't figure out how to fix your setup, you have two options:

- Wait for the mac binaries to come out
- You could force installation of the latest binary available with `install.packages("rlang", type = "binary")`.

**Comment by lionel-** [comment]
Reopening until the macOS binaries are distributed.

It is strange that they have not shown up yet.

**Comment by lionel-** [comment]
macOS binaries are now on CRAN.
