### ISSUE TITLE
Named arguments in lambda functions

### ISSUE THREAD

**Issue by Christopher-Peterson** [r-lib/rlang#864]
One limitation of rlang's lambda functions is the inability to specify argument names.  While this isn't a problem in most cases that anonymous functions are helpful, it makes lambdas less useful for `purrr::pmap()` and relatives.  I'm proposing an expansion of the lambda syntax that could allow argument names.

To specify arguments, `as_function()` should be passed a two-sided formula; the RHS is converted into the function body as usual, but the LHS is interpreted as the arguments with the following rules:

- Arguments can be declared directly with the pseudo-function f(), e.g. `f(a, b) ~ a + b`; this accepts forcing and splicing arguments.
- Arguments can be passed as a character vector, e.g., `c("d", "e") ~ d - e`
- Arguments can be taken from the names of a list or dataframe, e.g., `iris ~ Sepal.Length / Sepal.Width`

Multiple forms could be combined with the `+` operator (which could be useful if there are different 

The last option would be the easiest to use with `purrr::pmap()`:
```r
iris %>% pmap_chr(.l ~ Sepal.Length/Sepal.Width)
```
If the community is interested in this or has comments, I'd be happy to contribute the code and tests.

**Comment by lionel-** [comment]
Thanks for the suggestions, however this aspect of the design is deliberate. We do not plan to revisit at the moment. Perhaps open a Community thread if you'd like to discuss this more broadly?
