### ISSUE TITLE
Allow set_names(NULL) ?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#867]
Currently:

``` r
rlang::set_names(NULL, character())
#> Error: `x` must be a vector
```

<sup>Created on 2019-11-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Would it be safe to return `NULL` here?

**Comment by lionel-** [comment]
I don't know, but it's probably better to keep the conservative status quo.

If you'd like to change the rules, you'll need to provide a full motivation + likely consequences for generic composition of code using `set_names()`. Probably the motivation would be in terms of nil-punning here? (Note that vctrs doesn't use nil punning, it treats `NULL` as an absent argument, which should be an error here.)
