### ISSUE TITLE
Should infinity be integerish?

### ISSUE THREAD

**Issue by jimhester** [r-lib/rlang#872]
This is really a philosophical question, but I was expecting this to be `FALSE`

``` r
rlang::is_integerish(Inf)
#> [1] TRUE
```

<sup>Created on 2019-11-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
You can specify `finite = TRUE` to get `FALSE` with infinity. However this will also be false for missing values then.

I think `is_integerish()` is most useful for input validation in functions, and `Inf` may be a valid sentinel for round number inputs.

**Comment by jimhester** [comment]
Ok I guess!
