### ISSUE TITLE
rlang 0.4.2 windows binary

### ISSUE THREAD

**Issue by enoshliang** [r-lib/rlang#873]
Hello, when I tried to install devtools, the following message showed up

 There is a binary version available but the source version is later:
      binary source needs_compilation
rlang  0.4.1  0.4.2              TRUE

  Binaries will be installed

Then when I tried to install another package "phenor" that is dependent on it, the following error message showed up

package ‘rlang’ successfully unpacked and MD5 sums checked
Error: Failed to install 'phenor' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang’

Can anyone help me with updating rlang to its latest version?

**Comment by enoshliang** [comment]
thank you, but the same message showed up

There is a binary version available (and will be installed) but the source version is later:
      binary source
rlang  0.4.1  0.4.2

I also tried 

install.packages("rlang", type = "source") 

and got the following error

Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'rlang'
* removing '\\ad.uky.edu/AS/Geography/LLI225/Documents/R/win-library/3.6/rlang'
Warning in install.packages :
  installation of package ‘rlang’ had non-zero exit status

**Comment by lionel-** [comment]
Are you sure it didn't work? The message above says the binary version "will be installed".

By the way, check https://github.com/rstats-wtf/what-they-forgot/issues/62#issuecomment-545038970

**Comment by lionel-** [comment]
oops sorry I didn't read your initial post properly. Check the link above for how to properly install binary packages on Windows. Following the advice there should fix your issue. In particular, all sessions must be closed.
