### ISSUE TITLE
`arg_match()` should not allow inputs to be length >1

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/rlang#874]
I feel like if the argument is "not missing" it should check that the input is a string, not a character vector? I think I wanted an error here

``` r
my_fn <- function(x = c("a", "b", "c")) {
  rlang::arg_match(x)
}

my_fn(c("a", "c"))
#> [1] "a"

my_fn(c("a", "d"))
#> [1] "a"
```

<sup>Created on 2019-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by yutannihilation** [comment]
I think it's a common practice to list all options on the default value and use `match.args()` to choose the first one if user doesn't specify the argument. But, I agree we need an error in some cases.
