### ISSUE TITLE
`as_closure` should be able to de-reference a symbol

### ISSUE THREAD

**Issue by vspinu** [r-lib/rlang#876]
```R
> as_closure(as.symbol("plot"))
Error: Can't convert a symbol to function
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by lionel-** [comment]
I don't think so. I'd rather use a conditional `env_get()` with control on object type and reach of scope.

**Comment by vspinu** [comment]
Why not,  ore concretely? I am baffled.  You can dereference the string - a lower quality symbol. Symbols should have the same right, even more so.

**Comment by lionel-** [comment]
That's from early versions of purrr. It's probably too late to change, but a conversion function should not do a lookup action.

As for strings vs symbols, I think you're mixing up lisp and R idioms. Symbols are for evaluation, strings are for programmatic lookup. But, as I said, `as_function()` and `as_closure()` should not do any lookup, and I wouldn't rely on it in your code.

**Comment by vspinu** [comment]
Ok. no-lookup-during-the-conversions sounds reasonable indeed.

>  I think you're mixing up lisp and R idioms. Symbols are for evaluation, strings are for programmatic lookup.

Well, symbols are looked up (aka de-referenced) by R itself during the evaluation. So the fact that I cannot do `get(as.symbol("plot"))` is an oversight of the language IMO, but ok. You are right, lisp is sticking sticks here :)

> should not do any lookup, and I wouldn't rely on it in your code.

Will do. Thanks!
