### ISSUE TITLE
Creating spliced object with custom class duplicates the custom class

### ISSUE THREAD

**Issue by nteetor** [r-lib/rlang#877]
In some work I am making use of `rlang::splice()`. I am creating a spliced object with a custom class. The custom class is necessary for s3 methods. This appears to work fine at first. However, repeated calls to the object constructor function appear to stash(?) the custom class. Each time the constructor is called the custom class appears 1 extra time, see below.

``` r
custom_splice <- function(obj) {
  this <- rlang::splice(list(value = obj))
  class(this) <- c("custom_splice", class(this))
  this
}

x <- custom_splice("peach")
str(x)
#> List of 1
#>  $ :List of 1
#>   ..$ value: chr "peach"
#>  - attr(*, "class")= chr [1:3] "custom_splice" "rlang_box_splice" "rlang_box"

x <- custom_splice("pear")
str(x)
#> List of 1
#>  $ :List of 1
#>   ..$ value: chr "pear"
#>  - attr(*, "class")= chr [1:4] "custom_splice" "custom_splice" "rlang_box_splice" "rlang_box"

y <- custom_splice("honeydew")
str(y)
#> List of 1
#>  $ :List of 1
#>   ..$ value: chr "honeydew"
#>  - attr(*, "class")= chr [1:5] "custom_splice" "custom_splice" "custom_splice" "rlang_box_splice" ...

y <- list()
str(y)
#>  list()

y <- custom_splice("orange")
str(y)
#> List of 1
#>  $ :List of 1
#>   ..$ value: chr "orange"
#>  - attr(*, "class")= chr [1:6] "custom_splice" "custom_splice" "custom_splice" "custom_splice" ...
```

<sup>Created on 2019-12-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by nteetor** [comment]
I should also add that subsequent calls to `rlang::splice()` include the custom class.

``` r
custom_splice <- function(obj) {
  this <- rlang::splice(list(value = obj))
  class(this) <- c("custom_splice", class(this))
  this
}

x <- custom_splice("peach")
str(x)
#> List of 1
#>  $ :List of 1
#>   ..$ value: chr "peach"
#>  - attr(*, "class")= chr [1:3] "custom_splice" "rlang_box_splice" "rlang_box"

class(rlang::splice(list()))
#> [1] "custom_splice"    "rlang_box_splice" "rlang_box"
```

<sup>Created on 2019-12-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by nteetor** [comment]
I have another strange piece of the puzzle. To adjust the s3 class of an object I created a helper function. I discovered using this helper function interferes with the expected behaviour of a spliced object. Whereas, if I add a custom class without using the helper the spliced object acts as expected. See below,

``` r
s3_class_add <- function(x, new) {
  class(x) <- unique(c(new, class(x)))
  x
}

style_splice_with_helper <- function(x) {
  s3_class_add(rlang::splice(x), "yonder_style_accumulator")
}

style_splice_no_helper <- function(x) {
  s <- rlang::splice(x)
  class(s) <- unique(c("yonder_style_accumulator", class(s)))
  s
}

print(
  rlang::list2(style_splice_with_helper(list(class = "btn")))
)
#> [[1]]
#> <spliced>
#> $class
#> [1] "btn"

print(
  rlang::list2(style_splice_no_helper(list(class = "btn")))
)
#> $class
#> [1] "btn"
```

<sup>Created on 2019-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by lionel-** [comment]
Our position is that if a constructor doesn't explicitly allow subclassing via a `class` argument and `...` passed down to `structure()`, it is Undefined Behaviour to try and subclass it by other means.

**Comment by nteetor** [comment]
Okay, thank you, I will keep that in mind.
