### ISSUE TITLE
A wrong example on catch_cnd()

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/rlang#887]
Just happened to see this on https://rlang.r-lib.org/reference/catch_cnd.html. Maybe this should be something like `catch_cnd(signal(message = "a condition", class = "my_condition"))`?

```r
catch_cnd(cnd_signal("my_condition", .msg = "a condition"))
#> <simpleError in cnd_signal("my_condition", .msg = "a condition"): unused argument (.msg = "a condition")>
```

**Comment by lionel-** [comment]
oops thanks! Due to the nature `catch_cnd()`, this is the kind of thing that could go unnoticed for years :)

**Comment by yutannihilation** [comment]
Yeah, I guess no one noticed so far...
