### ISSUE TITLE
Centralized documentation for options that affect rlang behaviour

### ISSUE THREAD

**Issue by jennybc** [r-lib/rlang#899]
Is there a central place to find all of rlang's options and what they do?

This is motivated by my recent journey into options that affect back traces (re: knitr, reprex, etc.).

If not, can there be? And would it be a good issue for Tidyverse dev day?

I made a [help topic like this for gargle](https://gargle.r-lib.org/reference/gargle_options.html). I realize options might play a different role here in rlang, but maybe the basic idea is still sound.

**Comment by jennybc** [comment]
Specifically, right now I'm staring at `rlang_force_unhandled_error` and `rlang_backtrace_on_error` and wondering ... are there related options I should know about? What values can these options take on?

I happen to know that `rlang_force_unhandled_error` takes logical, so that narrows things down. But I'm not sure how to learn more.

`rlang_backtrace_on_error` is more of an enum and the values are described in the [docs for `abort()`](https://rlang.r-lib.org/reference/abort.html#backtrace). I just discovered this by searching here for "rlang_backtrace_on_error".

**Comment by lionel-** [comment]
A centralised help topic for all rlang options is a good idea.

I should rename `rlang_force_unhandled_error` to `rlang:::force_unhandled_error` to make it clear it's internal.

**Comment by lionel-** [comment]
I like the idea of making this a TDD topic. The options to document in a single topic would be:

- `rlang_interactive`
- `rlang_backtrace_on_error`
- `rlang_trace_format_srcrefs`
- `rlang_trace_top_env`
