### ISSUE TITLE
fail to install into  R 3.6.2 (windows). 

### ISSUE THREAD

**Issue by amenokoyushi** [r-lib/rlang#903]
Dear author,
I am trying to install rlang 0.4.3 into R 3.6.2. But failed, any help?
nevertheless, the former rlang 0.4.2 can be installed correctly.

> install.packages("rlang")

  There is a binary version available but the source version is later:
      binary source needs_compilation
rlang  0.4.2  0.4.3              TRUE

installing the source package ‘rlang’

 URL 'https://cran.rstudio.com/src/contrib/rlang_0.4.3.tar.gz' を試しています 
Content type 'application/x-gzip' length 813395 bytes (794 KB)
downloaded 794 KB

ERROR: failed to lock directory 'D:/Program Files/R/R-3.6.2/library' for modifying
Try removing 'D:/Program Files/R/R-3.6.2/library/00LOCK-rlang'
Warning in install.packages :
  installation of package ‘rlang’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\Public\Documents\Wondershare\CreatorTemp\Rtmpkf4tg3\downloaded_packages’

**Comment by yutannihilation** [comment]
> Try removing 'D:/Program Files/R/R-3.6.2/library/00LOCK-rlang'

Have you tried this? 

Note that this probably indicates some prior attempt of installation failed for another reason. This comment might be helpful. https://github.com/rstats-wtf/what-they-forgot/issues/62#issuecomment-545038970

**Comment by amenokoyushi** [comment]
thank you for your reply.
I have removed the package, restarted the system, even reinstall R studio and R, and change computers.
Then, I found that if I use R-3.6.1 or below, the install works well without any problem.
 I am not very familiar with codes, however, what I wonder is whether this rlang 0.4.3 supports R-3.6.2.

> > Try removing 'D:/Program Files/R/R-3.6.2/library/00LOCK-rlang'
> 
> Have you tried this?
> 
> Note that this probably indicates some prior attempt of installation failed for another reason. This comment might be helpful. [rstats-wtf/what-they-forgot#62 (comment)](https://github.com/rstats-wtf/what-they-forgot/issues/62#issuecomment-545038970)

**Comment by lionel-** [comment]
It is very unlikely that R-3.6.2 would be incompatible. Have you removed the `LOCK` folder prior to reinstalling? This lock folder will prevent any further installation. Also make sure no R session is running, and make sure with `sessionInfo()` rlang is not loaded before installing. See the link that Hiroaki posted.

**Comment by amenokoyushi** [comment]
Now i have removed 0000LOCK-rlang folder as below.![image](https://user-images.githubusercontent.com/18525398/73319819-da10c280-4280-11ea-844a-20b22d9d9e22.png)
