### ISSUE TITLE
Build pkgdown site by GitHub Actions

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/rlang#907]
It seems [gh-pages branch](https://github.com/r-lib/rlang/tree/gh-pages) has not been rebuilt since last November. Probably `pkgdown.yaml` needs to be added?

**Comment by lionel-** [comment]
Now fixed, thanks for letting me know! Also added some missing topics.

**Comment by yutannihilation** [comment]
Thanks, confirmed the pkgdown site is up to date with the master!
