### ISSUE TITLE
rlang zero sum exit (failure) 

### ISSUE THREAD

**Issue by nmacknight** [r-lib/rlang#912]
Hi,

I recently updated R to 3.6.2 and R studio to the latest software and restarted it all. I am getting an issue trying to load in PCAtools and ggplot2, where it tells me that rlang had an issue and therefore cannot load the packages I need to run the functions I was previously working with. Any resolutions to get rlang to cooperate with R 3.6.2? 

Thank you for your time and suggestions.

**Comment by lionel-** [comment]
Please provide the error message, this is essential for figuring out what is wrong. Also try to reinstall rlang, if you're on Windows it can be tricky, please see the advice at https://github.com/rstats-wtf/what-they-forgot/issues/62#issuecomment-545038970
