### ISSUE TITLE
driveupdate issue with new rlang release!

### ISSUE THREAD

**Issue by raavirss** [r-lib/rlang#919]
Code:

library(sqldf)
library(dplyr)
library(RMySQL)
library(tcltk2)
library(stringr)
#Google Libraries
library(gsheet)
library(googledrive)
library(googlesheets)
#SQL Libraries
library(httr)
library(xlsx)
library(janitor)

require(googlesheets)
id = '[google sheet id]'
drive_update(file = as_id(id) ,media = "foo.xlsx") //foo.xlsx : excel file with 2 tabs, with dummy data 

--------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------

Error: Predicate functions must return a single `TRUE` or `FALSE`, not a missing value
Backtrace:
     █
  1. └─googledrive::drive_update(file = as_id(id), media = "foo.xlsx")
  2.   ├─googledrive::as_dribble(file)
  3.   └─googledrive:::as_dribble.drive_id(file)
  4.     └─googledrive::drive_get(id = x)
  5.       ├─googledrive::as_dribble(purrr::map(as_id(id), get_one_id))
  6.       └─purrr::map(as_id(id), get_one_id)
  7.         └─googledrive:::.f(.x[[i]], ...)
  8.           └─googledrive::generate_request(...)
  9.             └─googledrive:::match_params(params, ept$parameters)
 10.               └─spec %>% purrr::keep("required") %>% names()
 11.                 ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
 12.                 └─base::eval(quote(`_fseq`(`_lhs`)), env, env

--------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------

Session info ------------------------------------------------------------------
 setting  value
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, linux-gnu
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 tz       Asia/Dubai
 date     2020-02-04

Packages ----------------------------------------------------------------------
 package      * version date       source
 assertthat     0.2.0   2017-04-11 CRAN (R 3.5.0)
 base         * 3.5.0   2018-05-19 local
 bit            1.1-14  2018-05-29 CRAN (R 3.5.0)
 bit64          0.9-7   2017-05-08 CRAN (R 3.5.0)
 blob           1.1.1   2018-03-25 CRAN (R 3.5.0)
 cellranger     1.1.0   2016-07-27 CRAN (R 3.5.0)
 chron          2.3-53  2018-09-09 CRAN (R 3.5.0)
 compiler       3.5.0   2018-05-19 local
 crayon         1.3.4   2017-09-16 CRAN (R 3.5.0)
 datasets     * 3.5.0   2018-05-19 local
 DBI          * 1.0.0   2018-05-02 CRAN (R 3.5.0)
 devtools       1.13.6  2018-06-27 CRAN (R 3.5.0)
 digest         0.6.17  2018-09-12 CRAN (R 3.5.0)
 dplyr        * 0.8.4   2020-01-31 CRAN (R 3.5.0)
 glue           1.3.1   2019-03-12 cran (@1.3.1)
 googledrive  * 0.1.1   2017-08-28 CRAN (R 3.4.4)
 googlesheets * 0.3.0   2018-06-29 CRAN (R 3.5.0)
 graphics     * 3.5.0   2018-05-19 local
 grDevices    * 3.5.0   2018-05-19 local
 gsheet       * 0.4.2   2016-12-30 CRAN (R 3.5.0)
 gsubfn       * 0.7     2018-03-16 CRAN (R 3.5.0)
 httr         * 1.4.1   2019-08-05 CRAN (R 3.5.0)
 janitor      * 1.1.1   2018-07-31 CRAN (R 3.5.0)
 magrittr       1.5     2014-11-22 CRAN (R 3.5.0)
 memoise        1.1.0   2017-04-21 CRAN (R 3.5.0)
 methods      * 3.5.0   2018-05-19 local
 pillar         1.4.3   2019-12-20 CRAN (R 3.5.0)
 pkgconfig      2.0.2   2018-08-16 CRAN (R 3.5.0)
 proto        * 1.0.0   2016-10-29 CRAN (R 3.5.0)
 purrr          0.3.3   2019-10-18 CRAN (R 3.5.0)
 R6             2.3.0   2018-10-04 CRAN (R 3.5.0)
 Rcpp           1.0.3   2019-11-08 CRAN (R 3.5.0)
 rJava          0.9-10  2018-05-29 CRAN (R 3.5.0)
 rlang          0.4.4   2020-01-28 cran (@0.4.4)
 RMySQL       * 0.10.15 2018-05-13 CRAN (R 3.5.0)
 RSQLite      * 2.1.1   2018-05-06 CRAN (R 3.5.0)
 sqldf        * 0.4-11  2017-06-28 CRAN (R 3.5.0)
 stats        * 3.5.0   2018-05-19 local
 stringi        1.2.4   2018-07-20 CRAN (R 3.5.0)
 stringr      * 1.3.1   2018-05-10 CRAN (R 3.5.0)
 tcltk        * 3.5.0   2018-05-19 local
 tcltk2       * 1.2-11  2014-12-20 CRAN (R 3.5.0)
 tibble         2.1.3   2019-06-06 CRAN (R 3.5.0)
 tidyselect     1.0.0   2020-01-27 CRAN (R 3.5.0)
 tools          3.5.0   2018-05-19 local
 utils        * 3.5.0   2018-05-19 local
 withr          2.1.2   2018-03-15 CRAN (R 3.5.0)
 xlsx         * 0.6.1   2018-06-11 CRAN (R 3.5.0)
 xlsxjars       0.6.1   2014-08-22 CRAN (R 3.5.0)

**Comment by lionel-** [comment]
This doesn't seem like an rlang issue. purrr has gotten stricter like a year ago. I recommend updating all your packages, or at least those involved in googledrive.
