### ISSUE TITLE
set_names doesn't update group indices

### ISSUE THREAD

**Issue by sfirke** [r-lib/rlang#925]
Here the group is still "a" but the variable name is "A":
```
dat <- data.frame(
  a = 1:5,
  b = letters[1:5]
) %>%
  dplyr::group_by(a)

dat %>% purrr::set_names(toupper)
#> # A tibble: 5 x 2
#> # Groups:   a [5]
#>       A B    
#>   <int> <fct>
#> 1     1 a    
#> 2     2 b    
#> 3     3 c    
#> 4     4 d    
#> 5     5 e
```

background: https://github.com/sfirke/janitor/issues/260#issuecomment-589250443 is the underlying problem I want to solve and here's where I got the idea from Lionel to use `set_names`: https://github.com/r-lib/tidyselect/issues/93#issuecomment-561688384

**Comment by lionel-** [comment]
This is a dplyr issue, which is already fixed in the development version. This will have to wait for dplyr 1.0.

**Comment by sfirke** [comment]
Okay, thanks Lionel!
