### ISSUE TITLE
"Error during wrapup" with entrace and %>%

### ISSUE THREAD

**Issue by willcrichton** [r-lib/rlang#936]
Example:

```
> library(tidyverse)
...
> a %>% b
Error in b(.) : could not find function "b"
> options(error = rlang::entrace)
> a %>% b
Error in b(.) : could not find function "b"
Error during wrapup: object 'b' of mode 'function' was not found
```

Seems like `entrace` has some kind of bug in handling this `could not find function` error. I haven't seen this behavior with other function not found errors, only with tidyverse pipe.

**Comment by lionel-** [comment]
I can't reproduce on R 4.0, hopefully it's been fixed.
