### ISSUE TITLE
Offer tools for pairlists and attributes

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#940]
- [ ] Combine two pairlists like `modifyList()`
- [ ] Remove nodes with specific tags, similar to `setdiff()` on the names
- [ ] Iterate over pairlists
- [ ] Extract attributes as pairlist

**Comment by lionel-** [comment]
I have some tools scattered in different packages. For example https://github.com/lionel-/flowery/blob/master/R/node-utils.R

**Comment by lionel-** [comment]
Currently out of scope for rlang.
