### ISSUE TITLE
Summarise backtraces with error trajectory across packages

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#946]
E.g.

```
dplyr -> tidyselect -> vctrs -> <error_names_must_be_unique>
```

Before showing simplified or full backtraces.

**Comment by hadley** [comment]
Could also embolden the package name in the full tree whenever it changes.

**Comment by lionel-** [comment]
Can you try this out and see if that is helpful @hadley?

<img width="652" alt="Screenshot 2021-09-16 at 12 22 09" src="https://user-images.githubusercontent.com/4465050/133596070-03d6393c-05a2-48d9-abb9-a09132c921e5.png">
