### ISSUE TITLE
problem with version number

### ISSUE THREAD

**Issue by wraff** [r-lib/rlang#948]
Dear developers,

thank you for providing all these wonderful tools to the R-comunity.
Unfortunately I have a problem related to version-numbering :

I tried installing your package rlang from CRAN and from Github, but I always have the same problem :
After loading the package (eg rlang_0.4.5.zip) sessionInfo says it's 0.4.2 and other packages (like broom, ggeffects, svrepmisc ...) won't load ...

> install.packages("finalfit")
trying URL 'https://pbil.univ-lyon1.fr/CRAN/bin/windows/contrib/3.6/rlang_0.4.5.zip'
Content type 'application/zip' length 1130303 bytes (1.1 MB)
downloaded 1.1 MB

package ‘rlang’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\wraffadm\AppData\Local\Temp\RtmpwzDiXl\downloaded_packages

> library(rlang)
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
[3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rlang_0.4.2

loaded via a namespace (and not attached):
[1] compiler_3.6.3

Yes, I tried restarting R and rebooting the PC. Unfortunately the problem persists.

Then I tried the following : 
Close R,  (manually) removing the package (from C:\Program Files\R\R-3.6.3\library) and install a previous version (downloaded from CRAN): 

install.packages("rlang_0.4.4.tar.gz", repos=localCRAN)

Then R tells me again version rlang_0.4.2, see below :

> library(rlang)
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
[3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rlang_0.4.2

loaded via a namespace (and not attached):
[1] compiler_3.6.3

Any hints ?

thank's in advance,
Wolfgang Raffelsberger

**Comment by lionel-** [comment]
Can you look at the directories listed in `.libPaths()` and see if an old installation of rlang is present in any of these please?

**Comment by wraff** [comment]
Thank you so much !

Great thinking, there was an old version in another location of .libPaths() ...
So I removed it and the problem is solved, now sessionInfo says  rlang_0.4.5
I confirm, the issue is solved.

Wolfgang
