### ISSUE TITLE
Unquoting missing arguments

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#952]
Should `!!` make an effort to make missing arguments explicit, so that we can give a better error message?

``` r
library(rlang)

foo <- function(a) {
  a <- enquo(a)
  quos(a = !!a)
}

# Error message unclear
eval_tidy(foo()$a)
#> Error in eval_tidy(foo()$a): object '' not found

# Should this have stop_missing_arg("a") in an expression?
foo()$a
#> <quosure>
#> expr: ^
#> env:  empty

# Implementation sketch
stop_missing_arg <- function(name) {
  abort(paste0("Missing argument `", name, "`"))
}

better_enquo <- function(a) {
  if (missing(a)) {
    quo(stop_missing_arg("a"))
  } else {
    enquo(a)
  }
}

foo <- function(a) {
  a <- better_enquo(a)
  quos(a = !!a)
}

eval_tidy(foo()$a)
#> Error: Missing argument `a`
```

<sup>Created on 2020-03-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Interesting idea, but I think it would get in the way of metaprogramming.

Another thing we could do is bind the missing arg in tidy eval masks to an active binding that throws an error, I just tried to bind it to a value and it works.

**Comment by lionel-** [comment]
hmm, if we bind the missing arg to itself, we get:

```r
eval_tidy(quo(), mtcars)
#> Error: argument is missing, with no default
```

How does this look @krlmlr and @hadley? I think it'd be difficult to get the error to mention the variable name without doing it at the `enquo()` level, which I think we should avoid.

**Comment by krlmlr** [comment]
The new error message looks much nicer, it's still not possible to understand what argument it refers to. Maybe if `enquo()` had an `.ignore_empty` or `.allow_empty` argument?

**Comment by lionel-** [comment]
It wouldn't help in the general case, e.g. with `{{`. For specific cases the function can check arguments explicitly. Let's revisit if it causes more confusion.

**Comment by lionel-** [comment]
Sorry I had to revert this change because binding the missing arg in the mask causes issues with environment cloning.
