### ISSUE TITLE
Side effect bug when using quosures

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/rlang#953]
I'm writing a function where I need to check if my enquoted first argument is a lambda function (it could be pretty much anything else).

Therefore, I ended using this piece of code to test this condition:

```r
library(rlang)
foo = function(.vars=NULL) {
    x = enquo(.vars) #this line is mandatory, due to other code in the function
    is_lambda(as_function(quo_squash(x)))
}
foo(~mean(.x)>3.5)
```
Unfortunately, `as_function` throws the following error:

> Error: `env` must be an environment

I tried a lot of things, using `set_env` on almost all objects, but the only thing that could prevent this error was to use `try`:

```r
bar = function(.vars=NULL) {
    dummy_variable_ill_never_ever_use = try(.vars, silent = T)
    x = enquo(.vars)
    is_lambda(as_function(quo_squash(x)))
}
bar(~mean(.x)>3.5)
```

Actually, the assignment is optional, but the point is that the `try` call has a side-effect that somehow prevents the error.

I thought it could be due to my computer, but testing on https://rdrr.io/snippets/ gave the exact same behavior.

Here is some more info on the error:

> ```
> > rlang::last_error()
> <error/rlang_error>
> `env` must be an environment
> Backtrace:
>  1. global::foo(~mean(.x) > 3.5)
>  3. rlang::as_function(quo_squash(x))
>  4. rlang::new_function(args, f_rhs(x), f_env(x))
> Run `rlang::last_trace()` to see the full context.
> 
> > rlang::last_trace()
> <error/rlang_error>
> `env` must be an environment
> Backtrace:
>     x
>  1. \-global::foo(~mean(.x) > 3.5)
>  2.   +-rlang::is_lambda(as_function(quo_squash(x)))
>  3.   \-rlang::as_function(quo_squash(x))
>  4.     \-rlang::new_function(args, f_rhs(x), f_env(x))
> ```
 
Hope I could be any help.

**Comment by lionel-** [comment]
The side effect is that `.vars` is evaluated, and thus can longer be defused by `enquo()`. There is nothing we can do about this because of technical reasons.

The problem is that you're defusing the `~` call. A defused `~` call does not carry an environment, because the environment is recorded when `~` is evaluated. The error message could be clearer.

```r
as_function(quote(~foo))
#> Error: `env` must be an environment
```

**Comment by DanChaltiel** [comment]
I'm afraid my comprehension of meta-programming with R and `rlang` is not good enough for this matter.

In the end, if there is nothing to be done, should I stick with my solution of dummy-evaluating `.vars` in `try` or is there a "cleaner" way to do it?

**Comment by lionel-** [comment]
I'm not sure what you're trying to achieve.

**Comment by DanChaltiel** [comment]
I have to test if the object inside `enquo(.vars)` is a `lambda-function`. 
For now, it fails in `as_function` if I don't call `try` beforehand, as in my first example.

**Comment by lionel-** [comment]
> I have to test if the object inside enquo(.vars) is a lambda-function.

In some ways there is no "object" inside `enquo(.vars)`. It's a defused expression.

You can test whether the expression is a call to `~` with:

```r
.vars <- enquo(.vars)
quo_is_call(.vars, "~")
```

Be careful with what you do with this information. The tilde call hasn't been evaluated and doesn't carry a fully-formed formula, it doesn't have an environment. You'll need to post-process the tilde call in some way. For instance you can evaluate it manually in the quosure environment:

```r
formula <- eval(quo_get_expr(.vars), quo_get_env(.vars))
```

**Comment by DanChaltiel** [comment]
What you are suggesting does not appear significantly less complicated than evaluating `.vars` in `try`, which still allows me to check on the class of the result of the evaluation of the defused expression of `enquo(.vars)`.
Do you think using `quo_is_call` would be less bug-prone or error-prone?
Otherwise, I think I'd stick with the dummy `try` call, for which my code is working as I want it to.
Thank you very much for your patience on this issue.

**Comment by lionel-** [comment]
> evaluating .vars in try, which still allows me to check on the class of the result of the evaluation of the defused expression of enquo(.vars).

Off-track evaluation of the sort has side effects. This really should be avoided.

**Comment by DanChaltiel** [comment]
With extensive use of `debugonce`, I finally figured this out. 

The point was that `as_function` uses the `.Environment` attribute of the formula, which is dumped by `quo_squash`:
```r
x=~mean(.x)>3.5
x %>% enquo %>% quo_squash %>% attr(".Environment")
#NULL
x %>% attr(".Environment")
#<environment: R_GlobalEnv>
```

In the end, this function works fine and does not need off-track evaluation.

```r
foo = function(.vars=NULL) {
    x = enquo(.vars) 
    xx = quo_squash(x)
    attr(xx, ".Environment") = caller_env()
    is_lambda(as_function(xx))
}
foo(~mean(.x)>3.5)
```

Still, off-track evaluation did not magically cause `.Environment` attribute to be kept, so why it was preventing the error to be thrown is still a deep mystery to me.

**Comment by lionel-** [comment]
1. I would never use `quo_squash()` except for printing stuff. Any other use of `quo_squash()` is a source of bugs.

2. The formula never had an environment because it was never evaluated. You're confusing the formula environment (which never existed) and the quosure environment (which you squashed).

3. Evaluating the formula is cleaner than adding the attribute manually.

**Comment by DanChaltiel** [comment]
OK, it seems there is no clean way to do what I unfortunately need to do, so I will not bother you with this anymore.

Just so you know, adding the attribute manually prevented some errors to be thrown when using `devtools::check` (they were not with `devtools::test`) so I think I will stick with this last method, despite its downsides. If there are bugs in future releases, I will see this at that time.

Thanks again for your help, I learned a lot during this discussion.

**Comment by lionel-** [comment]
Still need to improve the error message.
