### ISSUE TITLE
Support defusion in as_function() or a variant?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#955]
This is for creating optimized lambda functions:

``` r
x <- 1
rlang::as_function_bang(~ .x + !!x)
#> <lambda>
#> function (..., .x = ..1, .y = ..2, . = ..1) 
#> .x + 1
#> attr(,"class")
#> [1] "rlang_lambda_function" "function"
```

<sup>Created on 2020-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Thanks for the suggestion, but it's probably not in scope for rlang.
