### ISSUE TITLE
Add .named argument to dots_list()?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#957]
To shorten code like this:

```r
map(enquos(..., .named = TRUE), eval_tidy)
```

**Comment by lionel-** [comment]
Note that you shouldn't generally use `eval_tidy()` without masks because the expressions are not evaluated in the quosure environment but in a child (in order to mask `~` with a quosure evaluator).

A safer approach is:

```r
nms <- map_chr(exprs(...), as_label)
set_names(list2(...), nms)
```
