### ISSUE TITLE
Change regex in prim_name to support TERR

### ISSUE THREAD

**Issue by BillDunlap** [r-lib/rlang#958]
rlang::prim_name() uses regular expressions to get the name of .Primitive.  In TERR (TIBCO's version of R) the equivalent of a .Primitve is .Native.  Would you consider changing the regex "^.Primitive\\(\"" to "^.(Primitive|Native)\\("" to support that?
While you are at it, the initial dot could also be backslashed.
-Bill

**Comment by lionel-** [comment]
Sounds good.
