### ISSUE TITLE
pkgdown reference index doesn't make it easy to see where !! and !!! are documented

### ISSUE THREAD

**Issue by jennybc** [r-lib/rlang#959]
When looking at the reference index:

https://rlang.r-lib.org/reference/index.html

it's very hard to figure out where to read more about `!!` and `!!!`.

The correct answer is "click on `qq_show()`", but that's very non obvious.

Can that be improved?

**Comment by lionel-** [comment]
It seems that pkgdown chooses to display `qq_show()` even though it's only one of the aliases for the `nse-force` topic. Is there any way to force a displayed name @hadley?

**Comment by hadley** [comment]
I don't know 😞  This might be a pkgdown bug.

**Comment by jennybc** [comment]
> ... it's only one of the aliases for the nse-force topic. Is there any way to force a displayed name ?

This is definitely a wish I've had in other contexts, but `!!` and `!!!` is a very compelling illustration of the problem.

**Comment by lionel-** [comment]
@hadley It seems that pkgdown always prefers to use objects included in the Usage section as topic name. In this case I just removed `qq_show()`'s usage which is no big deal, but in general this behaviour seems a bit confusing and inflexible. Should I file a pkgdown bug?

**Comment by hadley** [comment]
@lionel- yeah it's worth filing an issue.
