### ISSUE TITLE
Document caveats of inlining functions with `call2()`

### ISSUE THREAD

**Issue by lgautier** [r-lib/rlang#960]
I am looking that working out how to keep the functionality of `dplyr::filter_()` as it is being deprecated.

In the example below I can reproduce `filter_(mtcars, "gear == 3")` using `filter()`, `parse_expr()`, and `call2()`:

```r
library(dplyr)
library(rlang)

x <- "gear == 3"
x_p <- parse_expr(x)
mycall <- rlang::call2(dplyr::filter, quote(mtcars), x_p)
eval(mycall)
## works.
```

However, when trying to compose / nest calls (here trying to mimic `mtcars %>% filter(gear == 3)`) I get errors:

```
mynestedcall <- rlang::call2(dplyr::filter, x_p)
myothercall <- call2(`%>%`, quote(mtcars), mynestedcall)
eval(myothercall)
## Error in pipes[[i]] : subscript out of bounds
```

Should it be possible to build calls by composition ? (Or am I missing something ?).

**Comment by lionel-** [comment]
This is not a `call2()` issue actually. Apparently the magrittr operator doesn't support being inlined in a call. Use the symbol instead of the function object and it works:

```r
myothercall <- call2(quote(`%>%`), quote(mtcars), mynestedcall)
```

I highly recommend learning quasiquotation though, your code will be much simpler:

```r
mtcars %>% dplyr::filter(!!x_p)
```

**Comment by lionel-** [comment]
For completeness, you can also use strings instead of symbols, they are automatically converted to symbols:

```r
call2(quote(`%>%`), 1, 2)
#> 1 %>% 2

call2("%>%", 1, 2)
#> 1 %>% 2
```

If the symbol is namespaced, the `.ns` argument is useful:

```r
call2(quote(dplyr::filter), 1, 2)
#> dplyr::filter(1, 2)

call2("filter", 1, 2, .ns = "dplyr")
#> dplyr::filter(1, 2)
```

Note that inlining the function objects in the call causes weirdness in stacktraces and captured calls (e.g. the calls captured by modelling functions like `lm()`).

**Comment by lgautier** [comment]
> This is not a call2() issue actually. Apparently the magrittr operator doesn't support being inlined in a call. Use the symbol instead of the function object and it works:

Ok. Thanks. I'll bump that as an issue for `magrittr` then.

> I highly recommend learning quasiquotation though, your code will be much simpler:

I would have thought implicit that anyone dedicated enough to figure out how to keep the useful `dplyr::filter_()` going is at least somewhat acquainted with quasiquotations. ;-) Here this is not an option for me, as I need to be able to construct calls from expressions specified as strings.

May be the doc for `call2` should reflect the need to quote the function object depending on the function (or always quote as a safe default ?), for example here:

>         • The function to call can be a string or a callable object: a
          symbol, another call (e.g. a ‘$’ or ‘[[’ call), or a function
          to inline. ‘base::call()’ only supports strings and you need
          to use ‘base::as.call()’ to construct a call with a callable
          object.
          
          call2(list, 1, 2)
 

Both of the examples below will work, but I am understanding that only the second one will work with all functions.

```r
> eval(call2(sum, call2(c, 1, 2)))
[1] 3
> eval(call2(quote(sum), call2(quote(c), 1, 2)))
[1] 3
```

**Comment by lionel-** [comment]
> Here this is not an option for me, as I need to be able to construct calls from expressions specified as strings.

I'm not sure what you mean. The expressions parsed from strings can be unquoted. `call2()` and quasiquotation are two equivalent methods for constructing calls.

> but I am understanding that only the second one will work with all functions.

There are trade offs. If `sum` is binded to a different function in that environment, it won't work well. Inlining the function may solve the issue.

**Comment by lgautier** [comment]
>> Here this is not an option for me, as I need to be able to construct calls from expressions specified as strings.

> I'm not sure what you mean. The expressions parsed from strings can be unquoted. call2() and quasiquotation are two equivalent methods for constructing calls.

I mean that I need to be able to create the complete call dynamically (from the C API). My experience has been that unquoting (`UQ()`) cannot be used for this because it will only work if in a language-level construct (at which point using `call2()` appears the simplest/most readable way to proceed).

> There are trade offs. If sum is binded to a different function in the evaluation environment, it won't work well. Inlining the function may solve the issue.

The point here is that the some function may not work inlined (e.g., `%>%`), and this create rather unexplained errors while the doc says it should work.

**Comment by lionel-** [comment]
But `call2()` is not used at the C level? I'm not sure what you mean.

> The point here is that the some function may not work inlined

Mentioning magrittr would be a distraction but a general comment about the effect of inlining (on the call stack in particular) would be useful.

**Comment by lgautier** [comment]
> But call2() is not used at the C level? I'm not sure what you mean.

I mentioned: "I mean that I need to be able to create the complete call dynamically (from the C API)."
Literally.

I am calling R through its C API, which means that I will have to build the call from there. May be a concrete example will help. In the link below, `dplyr::filter_()` is used from Python with R as DSL in strings: https://rpy2.github.io/doc/v3.3.x/html/lib_dplyr.html

`dplyr::filter_()` is being deprecated, so I will have to emulate that functionality.

**Comment by lionel-** [comment]
I don't understand because you're using call2 which is a function at the R level, not C level. Therefore quasiquotation still seems relevant. Besides, you can create calls and symbols with the C API so I'm not sure why strings are involved. But no worries, I'm just curious ;)

**Comment by lgautier** [comment]
I might be "holding it wrong", so may be going over what I am doing in details will lead to a better solution. I first thought about using `UQ()` but my attempts lead me to believe that it was not the simplest route.

The unconventional part here is that as far as R is concerned this is starting from its C-API, and this is where a lot of the reasoning that apply to R code in an R source do not necessarily apply.

In fact this is starting from Python (this is a bridge to call R from Python). In the R-exts terminology, this is considered having an embedded R (in a Python process). On the Python side, this is like having a C-extension module. That C extension as a state, which is the state of the embedded R.

Skipping the details of initialization, what a user of the Python library will have is a way to manipulate R objects. For example, to fetch the object `letters`, and the function `paste()` in the base R namespace, it will look like:

```python
r_letters = baseenv['letters']
r_paste = baseenv['paste']
```

The result of the snippet above is that the corresponding R objects are now bound to Python object wrappers associated with the symbols `r_letters` and `r_paste` in Python (the embedded R does not know anything about this) .

Python object wrappers for R functions are "callable" (in the Python lingo - meaning that they can be called and behave like functions). For example, the following will just work:
```python
res = r_paste(r_letters)
```
When coming from R programming, there are few distinctive points here though:
- `res` is "anonymous"  for R (R has no symbol associated with the result object)
-  The R function `paste()` will not know that the R symbol associated with the object was `letters`. This is sort of like writing in R `do.call(structure(paste), list(structure(letters)))`.

Now back to our example with `dplyr::filter()`. At the moment I manage to have the following working nicely with `dplyr::fitler_()` (but remember, `filter_()` is being deprecated so I have to work out how to keep the functionality).  The Python string `gear == 3` is essentially like having R as a DSL (Domain Specific Language):

```python
dplyr.filter(mtcars, 'gear == 3')
```

Now how would one go about using `UQ()` / `!!`? Trying something like the following will not work:
```python
dplyr.filter(mtcars, rlang.UQ(baseenv['str2lang']('gear == 3')))
```
It does not because, unlike R, Python does not defer the evaluation of expressions in call arguments. That is it will first try to evaluate `rlang.UQ(baseenv['str2lang']('gear == 3')` before proceeding to the body of the function. You certainly already know what will be the error, but I am adding it here for general readability:
```r
> UQ(str2lang("gear == 3"))
Error: `UQ()` can only be used within a quasiquoted argument
```

The current solution I am seeing is to explicitly build an R call object, and evaluate it at the end (therefore the use of `call2()`).

**Comment by lionel-** [comment]
Interesting thanks for the wrap-up!

So from your last examples `call2()` is actually meant as a metaprogramming solution for the user side, not for your internal implementation?

If this is about the internal implementation receiving these strings and having to plug them back in dplyr, you could do this on the R side (assuming you can call R functions implemented in an internal package from your C state):

```r
input <- parse_expr(input)
dplyr::filter(df, !!input)
```

For simple stuff like this, going back to R won't be worth it. So from the C side, constructing a call to filter along these lines should work:

```c
SEXP input = PROTECT(Rf_parse(input_string));
SEXP call = PROTECT(Rf_lang2(df, input));
Rf_eval(call)
```

**Comment by lgautier** [comment]
> So from your last examples call2() is actually meant as a metaprogramming solution for the user side, not for your internal implementation?

I am not distinguishing myself from any other user of that Python-R bridge here. The module wrapping `dplyr` is merely using that bridge. 

I had not considered this with the perspective of metaprogramming, but this is a good way to look at it when considering deferred evaluation of expressions.

> If this is about the internal implementation receiving these strings and having to plug them back in dplyr, you could do this on the R side (assuming you can call R functions implemented in an internal package from your C state):
>
> ```r
> input <- parse_expr(input)
> dplyr::filter(df, !!input)
> ```

I have made calling R using strings relatively easy. In fact a general solution using this
may just look like:

```python
myfilter_ <- rinterface.evalr("""
  function(dataf, ...) {
    dplyr::filter(dataf, !!!(parse_exprs(...))) 
  }
""")
```

> For simple stuff like this, going back to R won't be worth it. So from the C side, constructing a call to filter along these lines should work:
>
> ```c
> SEXP input = PROTECT(Rf_parse(input_string)); // this step might be a little more complex
> SEXP call = PROTECT(Rf_lang3(Rf_install("filter"), df, input));
> Rf_eval(call, env)
> ```

Since I have made utilities such as `evalr()` above, typing out a custom sequence of C code is actually what is often not worth it. (I tend to prefer `R_ParseVector()` because of the ability to better handle errors - https://github.com/rpy2/rpy2/blob/master/rpy2/rinterface_lib/_rinterface_capi.py#L551)

> It's a good idea to avoid inlining objects (like the data frame) in the calls, which you can do by binding the objects to symbols in (a child of) the evaluation env, e.g. something like _data.

I have considered doing something like this for quite a while, but a nagging presentiment of opening a Pandora's Box kept me from doing it so far. I should certainly try to revisit the idea. Thanks for the suggestion.
