### ISSUE TITLE
rlang installation issue

### ISSUE THREAD

**Issue by nandyal** [r-lib/rlang#962]
Hi,

I recently updated R to version 3.6.3 and since then I am having problems with several libraries as rlang has not been updated. 

package ‘rlang’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot remove prior installation of package ‘rlang’
Warning in install.packages :
  problem copying C:\Users\nandy\Documents\R\win-library\3.6\00LOCK\rlang\libs\x64\rlang.dll to C:\Users\nandy\Documents\R\win-library\3.6\rlang\libs\x64\rlang.dll: Permission denied
Warning in install.packages :
  restored ‘rlang’
package ‘usethis’ successfully unpacked and MD5 sums checked

**Comment by lionel-** [comment]
Maybe update the permissions of `C:\Users\nandy\Documents\R\win-library\3.6\rlang`? I am not really familiar with Windows or OS / R administration. Stackoverflow or community.rstudio.com are better venues for this kind of question.
