### ISSUE TITLE
Can't compile rlang on Windows

### ISSUE THREAD

**Issue by sumana86543** [r-lib/rlang#966]
installing *source* package 'rlang' ...
** package 'rlang' successfully unpacked and MD5 sums checked
** using staged installation
** libs

*** arch - i386
MAKE Version 5.0  Copyright (c) 1987, 1997 Borland International
Error C:/PROGRA~1/R/R-40~1.0/share/make/winshlib.mk 27: Colon expected
*** 1 errors during make ***
ERROR: compilation failed for package 'rlang'
Warning in install.packages :
  installation of package ‘rlang’ had non-zero exit status

not able to solve this problem of rlang using the latest version of R studio and R.

**Comment by lionel-** [comment]
Maybe reinstall Rtools?

**Comment by sumana86543** [comment]
> Maybe reinstall Rtools?

I have tried that and reinstalling all the other packages as well but it doesnt work

**Comment by lionel-** [comment]
Does this look familiar @jeroen?

In the meantime I would just install the previous binary version of rlang rather than the latest from source, until the binaries have been published.

To do this, supply `type = "binary"` argument to `install.packages()`.

**Comment by jeroen** [comment]
@sumana86543 you have the wrong `make` on the path. You need to put rtools on the path, see https://cran.r-project.org/bin/windows/Rtools/

**Comment by sumana86543** [comment]
Thank you @jeroen , @lionel- , i solved it
(https://cran.r-project.org/bin/windows/Rtools/ )----this helped
