### ISSUE TITLE
Installation of rlang on Windows 10 looks for old Rtools instead of Rtools40

### ISSUE THREAD

**Issue by s-mckay-curtis** [r-lib/rlang#968]
Posting in case others are having this issue. 

I upgraded to R 4.0.0 this weekend. The new version of R also requires a new version of Rtools. Previously, Rtools was installed in c:/Rtools. The new Rtools is now installed in c:/rtools40. Most of my packages, including ones that needed to be installed from source, updated just fine, except rlang (and a couple other minor ones).

The error indicated that when trying to install "rlang" the install script was trying to look for the old version of Rtools in the c:/Rtools folder, which i had removed. (I wish I had copied the exact error, but it was something like "c:/Rtools/mingw_64/bin/gcc no such file or directory.") 

So reinstalled the old version of Rtools, but I still kept the new version too. Since they are in different folders it's not a problem (yet?!). I have the additional line in my .Renviron file that prepends the location of the new Rtools40 to the path, but I also added back the path to the old Rtools in my system settings (so not in .Renviron). Anyway, that worked: I was able to install rlang. 

I'm posting here in case other people run into the same problem and are looking for a (somewhat hackish) solution. Also, I was wondering if you might have any ideas why the install script might be looking for the old Rtools?

Thanks.

**Comment by s-mckay-curtis** [comment]
Ok.... Just poked around my home folder and found this rogue line in a ".Rprofile" file: Sys.setenv(BINPREF = "C:/Rtools/mingw_$(WIN)/bin/")

So mystery solved, I guess. I wanna say that was added a long time ago when I installed Stan.

**Comment by lionel-** [comment]
Thanks for reporting!
