### ISSUE TITLE
Tidy eval and NextMethod

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#971]
What should you do if a generic uses tidy evaluation and you want to call the parent method? (e.g. https://github.com/tidyverse/tidyr/issues/948)

**Comment by lionel-** [comment]
We could fix it in base R, but it is possibly not trivial to fix this in a fully backward compatible way.

Probably the better approach is to offer `s3_next_method()` that would return the next method to invoke. Then it can be called in the normal way, using `{{` to tunnel NSE arguments.

**Comment by hadley** [comment]
Or we could just wait on R7 to solve this.
