### ISSUE TITLE
splice enexpr(arg) as list into downstream call

### ISSUE THREAD

**Issue by thackl** [r-lib/rlang#975]
Suppose I want to capture multiple arguments (e.g. with `enexpr`) that themselves are argument lists for downstream calls, is there a good way to do that?

This dummy snippet kinda works, but feels hackish, and bound to break...

```r
hack <- function(x, f1_args, f2_args){
  f1_exprs <- as.list(enexpr(f1_args))[-1]
  f2_exprs <- as.list(enexpr(f2_args))[-1]

  filter(x, !!! f1_exprs) %>%
    select(!!! f2_exprs)
}

df <- tibble(x=1:3, y=4)
hack(df, c(x>1), c(y, z=x))
```

**Comment by thackl** [comment]
OK, scratch that - I think this is how it should be done. But apparently I had to first submit this issue before my brain really woke up :)
```r
sane <- function(x, f1_args, f2_args){
  f1_exprs <- enexprs(f1_args)
  f2_exprs <- enexprs(f2_args)

  filter(x, !!! f1_exprs) %>%
    select(!!! f2_exprs)
}
sane(df, c(x>1), c(y, z=x))
sane(df, c(x>1), y)
```

**Comment by lionel-** [comment]
Just a note to never use `enexpr()` or `enexprs()`. Use `enquo()` or `enquos()` instead.

**Comment by thackl** [comment]
Ok, thanks!

**Comment by thackl** [comment]
OK, sorry, but I need to reopen. This is actually not really the solution I was looking for. It works with `select()` and `filter()`. However, I'd like to use this approach more generally. Is there a way to make something like the following work.

```
df <- tibble(x=1:4, y=c(5,5,6,6))

foo <- function(x, f1_args, f2_args){
  f1_quos <- enquos(f1_args)
  f2_quos <- enquos(f2_args)

  print(f1_quos)
  
  group_by(x, !!! f1_quos) %>%
    summarize(!!! f2_quos)
}
```

`enquos()` captures the arguments as a single quosure with `list(` as part of the expression. And that construct does not get spliced by the big bang operator. That is why I initially came up with the poor `as.list(enexpr(args))` hack. That produces a list of expressions that then can be spliced.

Is there a way to make this example work?

**Comment by lionel-** [comment]
Yes, you need to use external quoting:

```r
df <- tibble(x=1:4, y=c(5,5,6,6))

foo <- function(x, f1_args, f2_args){
  print(f1_quos)
  
  group_by(x, !!! f1_quos) %>%
    summarize(!!! f2_quos)
}

foo(df, vars(x), vars(mean = mean(y)))
```

**Comment by thackl** [comment]
Ahhh, yes, that makes sense! Thanks!
