### ISSUE TITLE
Add raw_to_string() helper?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#978]
Creating a string from a `raw` vector is very slow in R, required to write BLOBs to the database. Extrapolating gives an upper limit of 4 MB/s for writing BLOB data to the database.

Can we add a suitable helper to rlang or elsewhere, dbplyr doesn't have compiled code yet?

We really need to write the whole string at once for best performance.
``` r
data <- raw(1e5)

format_raw <- Rcpp::cppFunction("
  SEXP format_raw(Rcpp::RawVector x) {
    SEXP out = PROTECT(Rf_allocVector(STRSXP, x.length()));
    SEXP dummy = PROTECT(Rf_mkChar(\"00\"));
    for (R_xlen_t i = 0; i < x.length(); ++i) {
      SET_STRING_ELT(out, i, dummy);
    }
    UNPROTECT(2);
    return out;
  }
")

raw_to_string <- Rcpp::cppFunction("
  Rcpp::CharacterVector raw_to_string(Rcpp::RawVector x) {
    char buf[2 * x.length() + 3];
    char* p = buf;

    const char* lookup = \"0123456789abcdef\";

    *p++ = '0';
    *p++ = 'x';

    for (R_xlen_t i = 0; i < x.length(); ++i) {
      *p++ = lookup[x[i] / 16];
      *p++ = lookup[x[i] % 16];
    }

    *p = 0;
    return Rcpp::CharacterVector(buf);
  }
")

bench::mark(
  paste0("0x", paste(format(data), collapse = "")),
  paste(c("0x", format(data)), collapse = ""),
  sprintf("0x%s", paste(format(data), collapse = "")),
  paste(c("0x", format_raw(data)), collapse = ""),
  raw_to_string(data)
)
#> # A tibble: 5 x 6
#>   expression                                              min  median `itr/sec`
#>   <bch:expr>                                          <bch:t> <bch:t>     <dbl>
#> 1 paste0("0x", paste(format(data), collapse = ""))     24.4ms  25.5ms      38.7
#> 2 paste(c("0x", format(data)), collapse = "")          23.4ms  24.7ms      40.3
#> 3 sprintf("0x%s", paste(format(data), collapse = ""))  25.1ms  28.4ms      31.7
#> 4 paste(c("0x", format_raw(data)), collapse = "")      10.8ms  12.4ms      77.1
#> 5 raw_to_string(data)                                 522.2µs 619.9µs    1503. 
#> # … with 2 more variables: mem_alloc <bch:byt>, `gc/sec` <dbl>
```

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
This is a sort of deparsing function, so maybe `raw_deparse()`? What are the size invariants of this function?

**Comment by krlmlr** [comment]
`nchar(out) == nchar(prefix) + 2 * length(x) + nchar(suffix)`

**Comment by lionel-** [comment]
A `raw_deparse()` function should also have vector size invariants. Should we have some sort of `stride` parameter? If set to `Inf`, the size would 1? Then `raw_deparse_str()` would be an alias for `stride = Inf`?

**Comment by krlmlr** [comment]
I think that would complicate matters for the use given case. For `stride = 1` there's `base::format()` that works well enough and fast enough.

Maybe `raw_deparse()` isn't the right name after all?

**Comment by lionel-** [comment]
I think `raw_deparse()` and `raw_deparse_str()` both make sense.
