### ISSUE TITLE
Abort listed under lifecycle defunct

### ISSUE THREAD

**Issue by jeffwong-nflx** [r-lib/rlang#982]
I just noticed that `abort` is listed as a `defunct` function. I love the abort, warn, and inform family of functions, and they are much nicer than stop, warn, etc. Is there an alternative to `abort` that is recommended?

https://rlang.r-lib.org/reference/lifecycle.html

**Comment by mitchelloharawild** [comment]
This listing is referring to the arguments of `abort()` and not the function itself.
The `msg` argument has been renamed to `message`, and `type` argument is now `.subclass` as of rlang v0.4.0.
However it looks like the lifecycle doc needs updating as the new names have changed.

**Comment by lionel-** [comment]
Yes `abort()` is stable. I'll update the doc, thanks!
