### ISSUE TITLE
Pronouns in Package development

### ISSUE THREAD

**Issue by MyKo101** [r-lib/rlang#983]
The following function
```
dot_func <- function(x)
{
  x %>%
    paste0("hello ",.)
}
```
outputs as you would expect:
```
> dot_func("world")
[1] "hello world"
```

However, it gives a Note when `devtools::check()` is ran:
```
> checking R code for possible problems ... NOTE
  dot_func: no visible binding for global variable '.'
  Undefined global functions or variables:
    .
```

The [documentation ](https://rlang.r-lib.org/reference/tidyeval-data.html) for data pronouns suggests replacing `.` with `.data`, doing this stops the Note:
```
dot_func2 <- function(x)
{
  x %>%
    paste0("hello ",.data)
}
```
```
0 errors √ | 0 warnings √ | 0 notes √
```
however, the output is incorrect:
```
> dot_func2("world")
[1] "worldhello "
```
This is because the `.data` pronoun is designed for extracting elements of `data.frames` and `magrittr` doesn't substitute the `.data` in the same way it does with `.`. It is essentially running `paste0(x,"hello ",.data)`, rather than the desired `paste0("hello ",x)`.

A solution I have found is to define `.` as a fake pronoun in the same way that `.data` (and `.env`) are defined.
```
. <-  structure(list(), class = "rlang_fake_data_pronoun")
```

However, I'd like some advice as to whether others think this could potentially cause problems as I'm not 100% sure of the ramifications. In theory, any use of `.` within a function or pipeline should be replaced appropriately, but would this cover up error alerts if `.` is missing? 

Is there a better solution that would be recommended and would eliminate this `devtools::check()` Note? I find it difficult to understand why I've found it so hard to find this solution if it is fine.

Is there a reason this *wasn't* done in `rlang`? If not, would it make a reasonable PR to add this to `eval_tidy()`?

**Comment by lionel-** [comment]
`.data` is a tidy eval pronoun, it is distinct from the magrittr pronoun.

Maybe magrittr should export a `.` object you could import in your package. However I think the ideal solution is to simply call `utils::globalVariables(".")` somewhere in your package.
