### ISSUE TITLE
Capturing !! and !!!

### ISSUE THREAD

**Issue by TylerGrantSmith** [r-lib/rlang#986]
Is there any operator that could protect `!!` and `!!!` from being evaluated by `rlang::expr` to produce output like `substitute(!!x)`?

**Comment by lionel-** [comment]
You can protect with `quote()`:

```r
expr(foo(!!quote(!!bar)))
```

**Comment by TylerGrantSmith** [comment]
Sorry, @lionel- Perhaps I didn't provide an accurate example.  

````

f <- function(expr) {
  rlang::enexpr(expr)
}
f(!!x)
# desired output:
# > !!x
```

**Comment by lionel-** [comment]
I think this is `substitute()`? Why do you want to use `enexpr()` if not for the quasiquoting?

**Comment by TylerGrantSmith** [comment]
The idea is that I am building a function in which the quasiquoting will happen.  But thank you, I tried `substitute` again and got what I wanted.  I think I got off that idea because of how `substitute` behaves differently when called from the global environment.

``` r
make_unquote_expr_from_symbol <- function(x) {
  x <- rlang::enexpr(x)
  substitute(!!x)
}
make_unquote_expr_from_symbol((a+b))
#> !!(a + b)
purrr::map(list(as.symbol("a"), as.symbol("b")), ~make_unquote_expr_from_symbol(!!.))
#> [[1]]
#> !!a
#> 
#> [[2]]
#> !!b
```

**Comment by lionel-** [comment]
Ah I see. Another way is:

```r
make_unquote <- function(x) {
  call("!", call("!", x))
}

make_unquote_expr_from_symbol <- function(x) {
  make_unquote(rlang::enexpr(x))
}
```

**Comment by TylerGrantSmith** [comment]
Ah yes, that's good too.  Thank you!
