### ISSUE TITLE
`is_true` (and `is_false`) defined too strictly?

### ISSUE THREAD

**Issue by mmuurr** [r-lib/rlang#987]
rlang's [`is_true`](https://github.com/r-lib/rlang/blob/e7500d4c5ca38c07607855a726961d8cf635bb9c/R/types.R#L294) (and `is_false`) are defined how base R's _previous_ `isTRUE` and `isFALSE` were defined.

In more recent R versions, `isTRUE` has been modified to not fail in certain situations (e.g. a _named_ logical scalar of length one with `TRUE` as the value) ... should rlang's version be changed to this less-strict (and, I'd argue, more intuitive, _especially_ for new programmers) definition?

Here's base R's current definition of `isTRUE` and the corresponding documentation for the change:
```R
isTRUE <- function (x) {
  is.logical(x) && length(x) == 1L && !is.na(x) && x
}
```
> In earlier R versions, ‘isTRUE <- function(x) identical(x, TRUE)’, had the drawback to be false e.g., for ‘x <- c(val = TRUE)’.

**Comment by lionel-** [comment]
There is currently no plan to change this.
