### ISSUE TITLE
sys.parent Stymied by Mask Environment

### ISSUE THREAD

**Issue by brodieG** [r-lib/rlang#988]
The mask environment used to store the tilde is not placed on the context stack.  This prevents `sys.parent` from functioning correctly.  When nested inside a closure, `sys.parent` will get stuck at the closure frame evaluated in the mask environment.  This is because that closure runs with `cptr->sysparent` as the mask environment, and when that doesn't exist on the stack [`R_sysparent` gets stuck at that context][1]:

```
eval_tidy(quo((function() sys.parent(10))()))
## [1] 2
eval(quote((function() sys.parent(10))()))
## [1] 0
```

This also appears affects `call_frame`.

When there is no intervening closure then, the [logic that tries to unwind the `sys.*`][2] frame prior to looking for parents causes those functions to blow past all the frames because it's looking for the mask environment on the call stack:

```
eval_tidy(
  quo(
    (function()
      (function()
        (function() !!quo(sys.parent(1)))()
      )()
    )()
  )
)
## [1] 0
eval(
  quote(
    (function()
      (function()
        (function() eval(quote(sys.parent(1))))()
      )()
    )()
  )
)
## [1] 6
```
[1]: https://github.com/wch/r-source/blob/tags/R-4-0-0/src/main/context.c#L432
[2]: https://github.com/wch/r-source/blob/tags/R-4-0-0/src/main/context.c#L632

**Comment by lionel-** [comment]
Interesting. But unless this affects rlang backtraces in important use cases, there is probably no need for action here.

**Comment by brodieG** [comment]
Maybe document that `sys.parent` (and possibly other `sys.*`) cannot be relied on within quosures?   That would have been helpful to know (took me a little while to figure out what was going on).  Note it does affect `call_frame`, not sure what it means for the rlang backtraces.

Also, are you sure it's okay to have a `sysparent` set in the context stack that breaks the underlying `sys.*` and possibly other function assumptions?  It's fine here because the result isn't horrendous, but if internal C code is working under the assumption that there will be a `sysparent` because the only way something gets on the stack requires this be true, it feels a little living on the edge.  I'm not as familiar as I would like to be with this stuff, but if this is either documented or is there other precedent for setting a sysparent without having the sysparent on the stack?  It may be more common than I realize.

**Comment by lionel-** [comment]
I'm not sure I follow. With e.g. `do.call()` you can put any environment on the stack.

In general I'm not too concerned about sys.parent, the important primitive for real code is `parent.frame()`. The `sys.foo` functions are only for IDE and devtools introspection, and they currently have problematic semantics as discussed on that r-bugzilla issue. I don't think it's a problem to break the chain of dynamic inheritance, it's just creating a new trailing branch in the tree representation of the call stack, a representation that is only useful for debugging.

**Comment by brodieG** [comment]
Interesting point about `do.call`; I had not looked at its implementation.  Worth noting in the usual use case (i.e. not specifying `envir`) it will reference an environment on the stack (maybe it's worse that it will then be particularly surprising when someone does supply an `envir` not on the stack).

I think what you say makes sense if you're willing to state that `eval_tidy` establishes a new calling chain that is independent of the existing one (and maybe that's what your saying).  Either way, it seems worth documenting, IMO.

And I think you're fully aware of this, but just to be clear, the second issue applies equally to `parent.frame` (and "issue" could be restated to "manifestation of the call-chain reset"):

```
f <- function() g()
g <- function() h()
h <- function() list(
  rlang=eval_tidy(quo(parent.frame(2))),
  base=eval(quote(parent.frame(4))),
  docall=do.call(parent.frame, list(2))
)
f()
# $rlang
# <environment: R_GlobalEnv>
# 
# $base
# <environment: 0x7fe670f254b0>
# 
# $docall
# <environment: 0x7fe670f254b0>
```

**Comment by lionel-** [comment]
You're right, the parent of a foreign environment is the global env. Ideally `eval_tidy()` would evaluate in a frame whose identity is the same as that of the quosure environment, even though that frame environment is maskable.

The behaviour you point out could be documented with the other consequences of not using `base::eval()`, i.e. quosure-masked evaluation can't use `return()`. (Note that in my ideal semantics, `return()` would have the same reach as from within a promise, it would not return from the "target" `eval()` frame).

**Comment by lionel-** [comment]
Does this note make sense @brodieG? https://github.com/r-lib/rlang/commit/7be72f8eb9f66ab06791bfebf5052b375c8283b9

**Comment by brodieG** [comment]
Looks good.

I would add to the opening sentence:

> This only affects the behavior of functions like `parent.frame` and `sys.parent` that inspect the call stack.

This is what I would write for the second paragraph, but obviously that's just me:

> Expressions evaluated in `eval_tidy` establish a new call tree, so the `parent.frame()` of the topmost expression in an `eval_tidy` is the Global Environment.  Due to an implementation detail, `sys.parent()` will not return any frames past the mask environment so its behavior differs from that of `parent.frame()`.

I think the main point to make clear is that `eval_tidy()` establishes a new tree, not just a new branch.  At least in my interpretation every call in a closure establishes a new branch.  Maybe the term "branch" has a more formal definition than the one I'm informally giving it here.

`sys.parent` has that special issue that it can't get past the mask, so you get the weirdness of it never getting to the Global Environment, which complicates the documentation but should probably be mentioned.  This is further complicated by the differences in semantics discussed over at bugzilla.  Another option is just mention that `sys.parent`, and other function that don't have the fallback to the global env when they can't find a frame on the context stack should not be expected to work normally.

**Comment by lionel-** [comment]
The way I see it is that the tree is the whole stack, and each node descending from global is a branch (even if they have multiple children).

I'd prefer to avoid providing too much detail about sys.parent though, I suspect they would only confuse things. Also they are not too important. The call structure should mostly be considered undefined and can change at any point in time after a refactoring.

**Comment by brodieG** [comment]
Makes sense.  Obviously I think of branches differently than you, but I could well be the only person that does so.  In re `sys.parent`, I understand the reluctance to get into it.
