### ISSUE TITLE
rlanglibtest has installed itself into my system library

### ISSUE THREAD

**Issue by jennybc** [r-lib/rlang#989]
I reserve my main system library for base and recommended packages and use a user library for add-on packages.

But I notice that rlanglibtest has been installed into my system library. This seems a bit presumptuous. But I also gather that it's intentional?

https://github.com/r-lib/rlang/blob/6eb14bd63ef46f6f7bd7a03b8a6d41776dd9cf87/tests/testthat/test-c-api.R#L202

 Can this be avoided or, at least, cleaned up?

**Comment by lionel-** [comment]
I remember having lots of trouble with temporary libraries, and the behaviour didn't really make sense to me (perhaps on remotes, or CRAN?). The current setup isn't ideal but worked. Maybe I was missing something obvious.
